9689 modify pi local vars
camunda/camunda pull request #10217
Opened 2022-08-30 08:57 UTC by remcowesterhoud

## Description

Using a callback create the variables during activation of of the element and flow scopes

## Related issues

closes #9689 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-08-31 07:30 UTC, saig0 requested changes
@remcowesterhoud looks nice :+1: 

I have a few minor comments regarding the tests. Especially for event subprocesses, I'm not sure if this is already working as expected. Please have a look.

2022-08-31 07:30 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/util/client/ProcessInstanceClient.java
> +    public ActivationInstructionBuilder activateElement(final String elementId) {
:+1: I like the new builder.

2022-08-31 07:30 UTC, saig0 commented on engine/src/main/java/io/camunda/zeebe/engine/processing/common/ElementActivationBehavior.java
> +      final BiConsumer<DirectBuffer, Long> createVariablesCallback) {
:+1: The new callback fits well. The code is easy to understand.

2022-08-31 08:36 UTC, remcowesterhoud commented on engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/ModifyProcessInstanceVariablesTest.java
> +  public void shouldCreateLocalVariablesInNonExistingFlowscope() {
Wow, good catch, this was a bug 👍

2022-09-01 08:26 UTC, saig0 requested changes
@remcowesterhoud thank you for applying the hints :+1: 

I have one major point about the variable creation and a few minor suggestions. Please have another look. :cake:

2022-09-01 11:44 UTC, saig0 approved these changes
@remcowesterhoud super. Looks all good :+1:

2022-09-01 11:45 UTC, saig0 commented
bors merge

2022-09-01 12:01 UTC, merged