feat(broker): request created topics over the management api
camunda/camunda pull request #1031
Opened 2018-07-09 09:50 UTC by saig0

* a broker can request the partition ids of a topic via management api

closes #1005

2018-07-09 09:50 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 305f1f7d7b391acffb6cdaafc7cd5fe39292dc42
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci**

Guidelines are available at https://github.com/zeebe-io/zeebe/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-07-10 15:01 UTC, ThorbenLindhauer requested changes
* see notes at change set
* There are no tests. With the goal of a stable `develop` branch, we should not have untested (and without tests also unused) code. If you disagree, we should probably discuss this in the team.

2018-07-10 15:01 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/system/management/topics/FetchCreatedTopicsRequest.java
> +public class FetchCreatedTopicsRequest
This class is never used.

2018-07-10 15:01 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/system/management/topics/FetchCreatedTopicsRequestHandlerService.java
> +public class FetchCreatedTopicsRequestHandlerService
This looks unnecessarily complex. Why have an extra service and not just merge it with `LeaderManagementRequestHandler`?

2018-07-10 15:07 UTC, ThorbenLindhauer commented
In addition, commit https://github.com/zeebe-io/zeebe/pull/1031/commits/81537188c4de9d2dca3f3be8983bb3e0c99d4750 should be squashed into the previous commit.

2018-07-11 08:45 UTC, saig0 commented
@ThorbenLindhauer , I added a test case. I'll squash the commits after the review is done.

2018-07-12 12:38 UTC, ThorbenLindhauer approved these changes

2018-07-13 06:45 UTC, saig0 commented
bors r+

2018-07-13 07:02 UTC, merged