feat: support terminate end events
camunda/camunda pull request #10442
Opened 2022-09-22 08:19 UTC by saig0

## Description

Add support for BPMN terminate end events. See https://github.com/camunda/zeebe/issues/8789#issuecomment-1253338375 on how the BPMN element should work.

Side note: I implemented the major parts during a [Live Hacking session](https://www.twitch.tv/videos/1584245006).

## Related issues

closes #8789

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-09-22 10:39 UTC, saig0 commented
Note that the failing test case is not related to the changes. I can reproduce the failure also on `main`. I created an issue for further analysis: https://github.com/camunda/zeebe/issues/10445.

2022-09-22 11:14 UTC, saig0 commented
:heavy_check_mark: I tested the terminate end event manually in Operate.

![image](https://user-images.githubusercontent.com/4305769/191732411-0044228e-3dfc-4787-b530-e48da4600885.png)

2022-09-23 11:21 UTC, remcowesterhoud requested changes
Whew that was big one 😄 Nice work @saig0 🚀

I have a few questions and comments. But my main thing is what you mentioned in the PR.

>The implementation doesn't follow the BPMN spec in one point: the flow scope that contains the terminate end event is not terminated but completed.

❌ I think we should reconsider this. In my opinion the downsides don't outweigh the positives by terminating instead of completing.

1. You mention that this decision doesn't influence the core behavior. While this is true, it does cause a strange behavior for users willing to test their process using zeebe-process-test. For example, we have an assertion verifying if a process is terminated. For users it would be natural to verify this in the case of a terminate end event. However, this assertion will fail, because in reality Zeebe will complete the process.
2. You mention it fits better with the existing implementation. I have no doubts that this is true and you will definitely know better than me 😄. The code will become more complex, but the behavior of the code would do what feels natural and is expected. I noticed I had a bit of trouble reviewing this PR already, because sometimes an element would be terminated, other times it would be completed. I understand how it works after the review, but it feels unpredictable, which is again something that consumers of the exported records may have trouble with.
3. You mention it aligns better with C7. So let's improve it 😄 

Please reconsider this approach.


❌ It would be cool if we can support this terminate end event in our randomised tests. This can be a separate issue which we can work on later.

2022-09-23 11:21 UTC, remcowesterhoud commented on engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/TerminateEndEventTest.java
> +                        .parallel()
🔧 I think we should also test the sequential multi instance.

2022-09-23 12:06 UTC, remcowesterhoud approved these changes
🍪

2022-09-23 13:11 UTC, saig0 commented
We discussed if the flow scope should be `completed` or `terminated`. Besides the spec, we have different options about the user's (or our) expectations. From the code side, we agreed that the completion behavior fits better and avoids more complex logic for the particular case of the terminate end event. 

We decided to `complete` the flow scope for now. We could change the behavior later if we see a strong need for it. Or, if it aligns with further implementation of other BPMN elements. From a user point-of-view, it's mainly a change of the icon in Operate.

2022-09-23 17:48 UTC, saig0 commented
Bors merge

2022-09-26 03:29 UTC, saig0 commented
bors merge

2022-09-26 03:57 UTC, saig0 commented
bors merge

2022-09-26 04:24 UTC, saig0 commented
bors merge

2022-09-26 04:52 UTC, saig0 commented
bors merge

2022-09-26 05:24 UTC, saig0 commented
bors merge

2022-09-26 08:08 UTC, saig0 commented
bors merge

2022-09-26 10:18 UTC, merged