Support user task candidate users
camunda/camunda pull request #10459
Opened 2022-09-22 18:25 UTC by lzgabel

## Description
As a user I would like to specify task candidate-users for user tasks.

* candidate users are defined as a string containing a comma-separated list of values (e.g. x,y,z), or a Zeebe-formatted FEEL expression (i.e. prefixed by = ) where the expression should evaluate to a list of strings.

##### Example
```xml

<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <zeebe:assignmentDefinition candidateUsers="jack,rose" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 

<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   
  <zeebe:assignmentDefinition candidateUsers="= distinct values(fellowship.belongsTo)"/>
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 

<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
  <zeebe:assignmentDefinition
      assignee="= userId" 
      candidateUsers="jack"
      candidateGroups="admin,developer" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
```

## Related issues

closes #10346

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-09-22 18:26 UTC, lzgabel commented
Hi @korthout. Please take a moment to review this code. 🙇

2022-09-27 03:59 UTC, saig0 commented
@lzgabel thank you for your contribution. :tada: 

Currently, Nico is on vacation and we are busy. We try to have a look at your PR in the next two weeks. Stay tuned. :rocket:

2022-10-07 12:26 UTC, korthout commented
Thanks for the wait @lzgabel, I'll have a look at it :)

2022-10-07 14:32 UTC, korthout requested changes
👏 Bravo @lzgabel and ❤️ thanks for this great contribution!

👍 The code LGTM!
👍 The tests LGTM!
👍 I really like the `rose and jack` examples

❌ Revapi (which also runs on our CI) complains that the zeebe-bpmn-model API has changed. That's correct because you've added two new methods to it: `zeebeCandidateUsers(String)` and `zeebeCandidateUsersExpression(String)`. We can accept that, because this would become part of the following minor release (which is allowed to have new methods). So we need to tell revapi that we're okay with this change. Please have a look at the output of `mvn install -DskipTest -pl :zeebe-bpmn-model`, for instructions on how to tell revapi that it can ignore these changes.

```
[INFO] --- revapi-maven-plugin:0.14.7:check (check) @ zeebe-bpmn-model ---
[INFO] Comparing [io.camunda:zeebe-bpmn-model:jar:8.0.0] against [io.camunda:zeebe-bpmn-model:jar:8.1.0-SNAPSHOT] (including their transitive dependencies).
[INFO] API problems found.
[INFO] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore these changes or provide justifications for them, add the json snippets to your Revapi configuration for the "revapi.differences" extension.

{
  "ignore": true,
  "code": "java.method.addedToInterface",
  "new": "method B io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder<B extends io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder<B>>::zeebeCandidateUsers(java.lang.String)",
  "justification": "ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE"
  /*  "classSimpleName": "ZeebeUserTaskPropertiesBuilder",
  "methodName": "zeebeCandidateUsers",
  "exampleUseChainInNewApi": "interface io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder<B extends io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder<B>> is part of the API",
  "package": "io.camunda.zeebe.model.bpmn.builder",
  "classQualifiedName": "io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder",
  "elementKind": "method",
  "newArchive": "io.camunda:zeebe-bpmn-model:jar:8.1.0-SNAPSHOT",
  "newArchiveRole": "primary",
  "breaksVersioningRules": "false",
  */

},
{
  "ignore": true,
  "code": "java.method.addedToInterface",
  "new": "method B io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder<B extends io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder<B>>::zeebeCandidateUsersExpression(java.lang.String)",
  "justification": "ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE"
  /*  "classSimpleName": "ZeebeUserTaskPropertiesBuilder",
  "methodName": "zeebeCandidateUsersExpression",
  "exampleUseChainInNewApi": "interface io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder<B extends io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder<B>> is part of the API",
  "package": "io.camunda.zeebe.model.bpmn.builder",
  "classQualifiedName": "io.camunda.zeebe.model.bpmn.builder.ZeebeUserTaskPropertiesBuilder",
  "elementKind": "method",
  "newArchive": "io.camunda:zeebe-bpmn-model:jar:8.1.0-SNAPSHOT",
  "newArchiveRole": "primary",
  "breaksVersioningRules": "false",
  */
},
```

Please let me know if you have any questions about this 🙇

2022-10-07 15:12 UTC, lzgabel commented
Hi @korthout. Please checkout this out. :bow:

2022-10-10 14:30 UTC, korthout commented
👍 I've successfully tested it manually!

## As static value
- deploy a simple process with a user task with a task assignment specifying:
  - `assignee`: `korthout`
  - `candidateGroups`: `devs`
  - `candidateUsers`: `korthout,lzgabel`
- create an instance of this process
- verify the record in kibana:
```json
{
  "partitionId": 1,
  "value": {
    "type": "io.camunda.zeebe:userTask",
    "errorMessage": "",
    "retries": 1,
    "retryBackoff": 0,
    "bpmnProcessId": "user-task-candidate-users",
    "processInstanceKey": 2251799813685251,
    "variables": {},
    "processDefinitionKey": 2251799813685249,
    "elementInstanceKey": 2251799813685255,
    "recurringTime": -1,
    "processDefinitionVersion": 1,
    "elementId": "Activity_1sh8ixb",
    "customHeaders": {
      "io.camunda.zeebe:candidateUsers": "[\"korthout\",\"lzgabel\"]",
      "io.camunda.zeebe:assignee": "korthout",
      "io.camunda.zeebe:candidateGroups": "[\"devs\"]"
    },
    "deadline": -1,
    "errorCode": "",
    "worker": ""
  },
  "key": 2251799813685256,
  "timestamp": 1665411608214,
  "valueType": "JOB",
  "brokerVersion": "8.1.0",
  "recordType": "EVENT",
  "sourceRecordPosition": 17,
  "intent": "CREATED",
  "rejectionType": "NULL_VAL",
  "rejectionReason": "",
  "position": 19
}
```

## As an expression
- deploy a simple process with a user task with a task assignment specifying:
  - `assignee`: `=user.name`
  - `candidateGroups`: `=user.roles`
  - `candidateUsers`: `=users`
- create an instance of this process with a context:
```json
{
  "user": {
    "name": "korthout",
    "roles": ["dev"]
  },
  "users: ["lzgabel", "korthout"]
}
```
- verify the record in kibana:
```json
{
  "partitionId": 1,
  "value": {
    "type": "io.camunda.zeebe:userTask",
    "errorMessage": "",
    "retries": 1,
    "retryBackoff": 0,
    "bpmnProcessId": "user-task-candidate-users-expr",
    "processInstanceKey": 2251799813685275,
    "variables": {},
    "processDefinitionKey": 2251799813685273,
    "elementInstanceKey": 2251799813685281,
    "recurringTime": -1,
    "processDefinitionVersion": 2,
    "elementId": "Activity_1sh8ixb",
    "customHeaders": {
      "io.camunda.zeebe:candidateUsers": "[\"lzgabel\",\"korthout\"]",
      "io.camunda.zeebe:assignee": "korthout",
      "io.camunda.zeebe:candidateGroups": "[\"dev\"]"
    },
    "deadline": -1,
    "errorCode": "",
    "worker": ""
  },
  "key": 2251799813685282,
  "timestamp": 1665412156392,
  "valueType": "JOB",
  "brokerVersion": "8.1.0",
  "recordType": "EVENT",
  "sourceRecordPosition": 75,
  "intent": "CREATED",
  "rejectionType": "NULL_VAL",
  "rejectionReason": "",
  "position": 77
}
```

2022-10-10 14:32 UTC, korthout approved these changes
Thanks @lzgabel LGTM 🏆 

bors merge

2022-10-10 15:03 UTC, merged