refactor(bpmn-model) Improve error message of BPMN features
camunda/camunda pull request #10646
Opened 2022-10-09 17:43 UTC by sccalabr

## Description

Improve error message in case of uncovered BPMN features by linking error message to documentation. 

## Related issues

closes #7282

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-10-11 04:52 UTC, saig0 commented
@sccalabr thank you for your contribution. :tada:  I'll have a look at your PR in the next few days. :eyes:

2022-10-12 11:25 UTC, remcowesterhoud requested changes
Thanks for your contribution @sccalabr! 🚀 Sorry I took a little while to look at it.

I have a suggestion about rephrasing the message. Please let me know what you think of it!

2022-10-13 08:04 UTC, remcowesterhoud requested changes
I'm sorry I wasn't clear enough with my previous comment. I have left another one that should clear things up.

2022-10-13 08:04 UTC, remcowesterhoud commented on bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/FlowElementValidator.java
> +              + "https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage");
❌ Maybe I should have clarified myself better 😄 We don't want to actually return `elementType.getSimpleName()` in the message. We want to be executed.

```suggestion
          String.format(
              "Elements of type '%s' are currently not supported. Please refer "
                  + "to the documentation for a list of supported elements: "
                  + "https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage",
              elementType.getSimpleName()));
```

2022-10-14 07:46 UTC, remcowesterhoud approved these changes
Thanks @sccalabr! 🚀 

This pull request counts toward the Hacktoberfest challenge. If you contributed four pull requests then you can complete your Camunda Hacktoberfest challenge [here](https://camunda.com/hacktoberfest2022/).

bors merge

2022-10-14 08:02 UTC, merged