Export missing records to ES
camunda/camunda pull request #10697
Opened 2022-10-13 06:04 UTC by lzgabel

## Description

Currently, the Zeebe Elasticsearch exporter doesn't allow to export all records. The following records are missing:

* `timer`
* `message_start_event_subscription`
* `process_event`
* `deployment_distribution`

## Related issues

closes #8337

## Definition of Done

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-10-13 06:06 UTC, lzgabel commented
Hi @remcowesterhoud. Please take a moment to check this out. :bow:

2022-10-13 12:02 UTC, remcowesterhoud commented
@saig0 We had [an issue ](https://github.com/camunda/zeebe/issues/8338)before to export these records by default. We never got around to doing it for these records since they were more work that flipping a boolean. Do we still want to export these by default?

2022-10-13 12:26 UTC, saig0 commented
@remcowesterhoud good point. :+1: 

Yes, let's export these records by default. :rocket: Except, the `process_event` records. Reasoning:

- we write a lot of `process_event` records, at least one for each completed job  
- I'm not sure how useful these records are for analyzing

2022-10-13 14:10 UTC, remcowesterhoud requested changes
Thanks for another contribution @lzgabel 🏅 

The indexes themselves look good. There is a few other things that require some attention though.

1. This wasn't in the issue so you couldn't have known, but please change exporting of the `timer`, `message_start_event_subscription` and `deployment_distribution` to `true` by default.
2. We'll have to add these records to the [ElasticSearchExporter](https://github.com/camunda/zeebe/blob/main/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java#L143-L206)
3. We should modify the [toString() method](https://github.com/camunda/zeebe/blob/main/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporterConfiguration.java#L164-L213) of the `ElasticSearchExporterConfiguration`.
4. We have some [parametrised tests](https://github.com/camunda/zeebe/blob/main/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/ElasticsearchExporterIT.java#L47) these tests use this [TestSupport](https://github.com/camunda/zeebe/blob/main/exporters/elasticsearch-exporter/src/test/java/io/camunda/zeebe/exporter/TestSupport.java#L20) class. We will have to add the value types of these records to the `setIndexingForValueType()` method and remove them from the `provideValueTypes()` method.

2022-10-13 14:45 UTC, lzgabel commented
Hi @remcowesterhoud. Please check this out. 🙇

2022-10-14 07:29 UTC, remcowesterhoud approved these changes
Awesome! 🏆 

The issue is not marked as hacktoberfest, but I reckon it still deserves it so I'll add the `hacktoberfest-accepted` label to this PR. If you have 4 PRs within Camunda labelled with `hacktoberfest-accepted` you have completed the hacktoberfest challenge. In this case please submit the [entry form here](https://camunda.com/hacktoberfest2022/) 🙂 

bors merge

2022-10-14 08:49 UTC, lzgabel commented
Hi @remcowesterhoud. Seems like `bors` is not working again? Do I need to rebase this PR on main again?

2022-10-14 08:50 UTC, remcowesterhoud commented
@lzgabel Yes, please do a rebase

2022-10-14 08:51 UTC, remcowesterhoud commented
bors cancel

2022-10-14 08:51 UTC, lzgabel commented
Done.

2022-10-14 09:08 UTC, merged