feat(engine): set the variables locally when failling a job with variables
camunda/camunda pull request #10701
Opened 2022-10-13 07:19 UTC by skayliu

## Description

If a failling job has variables, then the variables will be set locally.

## Related issues

closes #10698 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-10-14 04:32 UTC, saig0 commented
@skayliu thank you for your contribution. :tada: We'll have a look at your PR in the next few days. :eyes:

2022-10-14 16:12 UTC, korthout requested changes
Thanks for this @skayliu 🏆 This will be another great contribution!

👍 I really like that you've split up the commits

There are still a few things that need to be addressed, but the main parts are there already. Nice work!

2022-10-14 16:12 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobFailProcessor.java
> +
❌ This code block in which this code is placed is executed only when the retries is 0 (or negative). The rest of this code block is aimed at creating an incident at the associated task. We should create the variables regardless of the number of retries.

2022-10-14 16:12 UTC, korthout commented on engine/src/test/java/io/camunda/zeebe/engine/processing/job/FailJobTest.java
> +    assertThat(failRecord.getValue().getVariables()).containsExactly(entry("foo", "bar"));
❌ This test should also verify that the Variable `foo` is `CREATED` with value `bar` at the variable scope (`failRecord.getValue().getElementInstanceKey()`).

💡 Tip: You can use the `RecordingExporting.variableRecords()` to find the exported variable records.

2022-10-17 09:17 UTC, korthout approved these changes
Nice job @skayliu 👏 

I have just one last suggestion. Please let me know if you'd like to apply it. Otherwise, we can just merge this PR.

2022-10-17 10:08 UTC, skayliu commented on engine/src/test/java/io/camunda/zeebe/engine/processing/job/FailJobTest.java
> +        .isEqualTo("\"bar\"");
@korthout, Done.

2022-10-17 10:59 UTC, korthout commented
bors merge

2022-10-17 12:06 UTC, korthout commented
@skayliu We had a problem with our automated merge tooling (bors). It should be fixed after rebasing your changes on top of `main`.

2022-10-17 13:17 UTC, merged