feat(broker): open message subscription
camunda/camunda pull request #1071
Opened 2018-07-20 12:54 UTC by saig0

* new SBE message to open a message subscription
* new record for message subscriptions
* send a command over the subscription endpoint when a message catch
event is entered
* write a message subscription record when a command is received

closes #1014

2018-07-24 10:58 UTC, ThorbenLindhauer reviewed
Test coverage:

* Two subscriptions with the same correlation key should go to the same partition
* This should work with and without a broker restart in between

I think these tests make particularly sense, because the current implementation assumes that the fetch topic response returns partition IDs in a consistent order. This dependency is not obvious and could lead to a regression in the future.

2018-07-24 10:58 UTC, ThorbenLindhauer commented on protocol/src/main/resources/protocol.xml
> +        <validValue name="WORKFLOW_INSTANCE_SUBSCRIPTION">12</validValue>
This is not used.

2018-07-24 11:00 UTC, ThorbenLindhauer requested changes
See comments above

2018-07-24 14:04 UTC, saig0 commented
I created a follow-up issue for the partition assignment test #1083 .

2018-07-25 07:27 UTC, ThorbenLindhauer approved these changes

2018-07-25 07:31 UTC, saig0 commented
bors r+

2018-07-25 07:53 UTC, merged