fix(engine): use link events in different flow scopes
camunda/camunda pull request #10855
Opened 2022-10-28 17:07 UTC by lzgabel

## Description

I can use link events in different flow scopes.

## Related issues
closes #10854 

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-10-28 17:11 UTC, lzgabel commented
Hi @saig0. Please take a moment to check this out. :bow:

2022-11-01 09:36 UTC, saig0 commented
@lzgabel thank you for your contribution. :tada: We'll have a look at your PR in the next few days. :eyes:

2022-11-17 12:24 UTC, saig0 requested changes
@lzgabel thank you for fixing the issue. :cookie: 

Your changes fix the issue. :+1: But they also allow one case that I would like to reject. Please have a look at my comments. :cake:

2022-11-21 06:10 UTC, lzgabel commented
Hi @saig0. I've fixed all review comments. Please check this out. 🙇

2022-11-22 09:51 UTC, saig0 approved these changes
@lzgabel super. :+1: The changes are ready to merge. :tada:  

Thank you for applying the hints. :cake:

2022-11-22 10:31 UTC, saig0 commented
bors merge

2022-11-22 10:45 UTC, merged