Support throw error with variables
camunda/camunda pull request #10882
Opened 2022-11-01 16:30 UTC by skayliu

## Description

Support throw error with variables.

![image](https://user-images.githubusercontent.com/26370117/199285371-c30696cc-7468-4691-ae28-390408f812cd.png)

## Related issues

closes #4337
closes #4080 
closes #9473 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-11-01 16:37 UTC, skayliu commented
Hi, @saig0, @korthout. Please take a moment to review this feature when you have time. Thanks. ❤️

2022-11-02 17:27 UTC, korthout commented
Thanks @skayliu 

I quickly noticed that your PR states:

>closes https://github.com/camunda/zeebe/issues/4337
closes https://github.com/camunda/zeebe/issues/4080
closes https://github.com/camunda/zeebe/issues/9473

Both #4337 and #9473 differ from #4080 (and your PR) in that they refer explicitly to the error message and error code properties and somehow extract them into variables, while your PR is about passing along variables in the thrown error.

🔧 Let's only close #4080.
🔧 Let's add a reference `relates to #4337`

I'll make sure to provide a full review of this PR in the coming days.

2022-11-03 01:12 UTC, skayliu commented
Hi

![2022-11-03_090852](https://user-images.githubusercontent.com/26370117/199630309-7e7d35b0-fee8-49b8-ad2f-acf95db83e27.png)

2022-11-04 15:03 UTC, korthout requested changes
Thanks for this amazing contribution @skayliu 🚀 

There are a few things we need to adjust, but you've done a wonderful job!

Please have a look at my requests. 🙇

2022-11-04 15:03 UTC, korthout commented on engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobThrowErrorTest.java
> +            JobThrowErrorTest.class.getResourceAsStream("/processes/error_event_exclusive.bpmn"));
❓ What is this test verifying? Please clarify

2022-11-04 15:03 UTC, korthout commented on gateway-protocol/src/main/proto/gateway.proto
> +  // job's associated task, and will propagate to upper scopes; it must be a JSON object, as variables will be mapped in a
>// job's associated task, and will propagate to upper scopes;

❌ The variables should only be merged on the error catch event that catches the thrown error. It should not be propagated, unless output mappings are used to achieve this.

2022-11-09 07:53 UTC, skayliu commented on engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobThrowErrorTest.java
> +            tuple("foo", "\"bar\"", processInstanceKey, VariableIntent.CREATED));
And what about this one, right row the variable is created at the  process instance, not at the `event sub process`, or the `error start event`.
![error-event-process](https://user-images.githubusercontent.com/26370117/200765137-815c2307-6fde-4881-b3ec-02e8fd9c0a46.png)

2022-11-10 17:16 UTC, korthout commented on engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobThrowErrorTest.java
> +            tuple("foo", "\"bar\"", processInstanceKey, VariableIntent.CREATED));
Thanks for investigating @skayliu. It sounds related to #9061, but it's likely a separate bug. I've started investigating this in some more detail and will follow-up on this.

2022-11-11 12:57 UTC, korthout commented on engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/error/ErrorCatchEventTest.java
> +            .throwError();
@skayliu Please remove the variable assignment.
```suggestion
    ENGINE
        .job()
        .ofInstance(processInstanceKey)
        .withType(JOB_TYPE)
        .withErrorCode(ERROR_CODE)
        .withVariables("{'foo':'bar'}")
        .throwError();
```

2022-11-11 13:00 UTC, korthout requested changes
Thanks @skayliu I have one last request and then this can be merged 🥇 

👍 About the variable scopes, it seems that I was wrong. The way you've implemented/tested it is correct. I'll discuss it once more with the team next week, but that doesn't have to block this PR.

2022-11-11 13:08 UTC, skayliu commented on engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnVariableMappingBehavior.java
> +  }
what name should be?

2022-11-11 13:35 UTC, skayliu commented
Hi, @korthout , It's done, please check this out. Thanks.

2022-11-11 16:18 UTC, korthout commented
@oleschoenburg Recently you made [changes to the caching](https://github.com/camunda/zeebe/pull/10662). The test [run](https://github.com/camunda/zeebe/actions/runs/3445383381/jobs/5750593349) on this PR fails because after the Zeebe Gateway has been built, the used cache is replaced by another cache. Do you agree that we should disable the cache [when switching the java version to 8](https://github.com/camunda/zeebe/actions/runs/3445383381/workflow#L292)?

- Cache before building: `Linux-maven-java-client-e9dbd284a3699116d5717077527466fe949957b550bcb2bbd77278ecafe4a747`
- Cache after builder, before starting the test: `setup-java-Linux-maven-e9dbd284a3699116d5717077527466fe949957b550bcb2bbd77278ecafe4a747`

<img width="1311" alt="Screen Shot 2022-11-11 at 17 10 23" src="https://user-images.githubusercontent.com/3511026/201382706-fa270ab5-a2d3-467e-8fe5-ada60d6caa7a.png">

@skayliu Caching is turned off by default, so I believe we can try to fix this by removing [this line](https://github.com/skayliu/zeebe/blob/4337-set-variables-for-throw-error/.github/workflows/ci.yml#L292). Can you please remove that line in another commit to this PR?

2022-11-11 16:33 UTC, skayliu commented
> Caching is turned off by default, so I believe we can try to fix this by removing [this line](https://github.com/skayliu/zeebe/blob/4337-set-variables-for-throw-error/.github/workflows/ci.yml#L292). Can you please remove that line in another commit to this PR?

Hi, @korthout, It's been removed. Please try again.

2022-11-11 16:37 UTC, korthout commented
@skayliu Thanks for the quick change. It worked! 💯 

🔧 Please also squash your commits into ones with more meaningful descriptions. Both our [Contributing Guide](https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md#commit-message-guidelines) and our Wiki entry on [Pull Requests](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#ive-written-a-clear-changelist-description) push for more explanation in commit messages. This can help us understand why certain changes are made during the review. But it can also help us when we're trying to understand code in the future because the choices are written close the code (in the version control). It will help us if you try to provide a bit more info in the commit messages about the changes. 🙇  Thanks a lot

2022-11-11 17:44 UTC, lzgabel commented
Done.

Hi @korthout. Please check this out. 🙇

2022-11-14 07:49 UTC, oleschoenburg commented
@korthout Yes, sounds reasonable :+1: No cache needed for Java 8, Zeebe should be built already, we are just switching to Java 8 to run tests. Nice catch!

2022-11-15 10:16 UTC, korthout approved these changes
Thanks @skayliu 🚀 

Let's get this merged!

bors merge

PS: Sorry for the delay in my review 🙇

2022-11-15 14:29 UTC, korthout commented
It seems Bors got stuck

>Resource not accessible by integration

It seems to be related to the changes to the workflow. Bors is not allowed to merge PRs from forks with workflow changes due to permissions.

@skayliu Do you mind if I extract that commit into another PR?

2022-11-15 14:37 UTC, skayliu commented
> @skayliu Do you mind if I extract that commit into another PR?

@korthout, never mind, just go ahead.

2022-11-15 15:21 UTC, korthout commented
@skayliu https://github.com/camunda/zeebe/pull/10995 has been merged. Please remove the commit [695bc95](https://github.com/camunda/zeebe/pull/10882/commits/695bc954533b645c1152cad6e8d3a1aa692dea3f) and rebase on top of `main`. Then we should be able to get this merged.

2022-11-15 15:43 UTC, lzgabel commented
Done.

Hi @korthout. Please check this out. 🙇

2022-11-15 15:47 UTC, korthout approved these changes
LGTM 🚀 

bors merge

2022-11-15 15:48 UTC, korthout commented
bors cancel

2022-11-15 15:52 UTC, lzgabel commented
Sorry.  @korthout. Please try it again. 🙇

2022-11-15 16:58 UTC, korthout commented
@skayliu Seems there's a failing test now.

```
JobThrowErrorTest.shouldThrowErrorWithVariablesWithEventSubProcess:388 [With event sub process the variables are created at the process instance] 
Expecting actual:
  [("foo", ""bar"", 2251799813685273L, CREATED),
    ("foo", ""bar"", 2251799813685269L, CREATED)]
to contain exactly (and in same order):
  [("foo", ""bar"", 2251799813685269L, CREATED)]
but some elements were not expected:
  [("foo", ""bar"", 2251799813685273L, CREATED)]
```

2022-11-15 17:16 UTC, lzgabel commented
Sorry @korthout. :bow: It was caused by the conflict resolution during the rebase on `main`, and I've resolved it. Wait a few minutes. 🙇

2022-11-15 17:44 UTC, korthout commented
Looks good to me! Thanks @lzgabel and @skayliu 

bors merge

2022-11-15 17:59 UTC, merged

2022-11-16 14:20 UTC, skayliu commented
Hi, @korthout The Go client is not include, Please open an issue for it.

2022-11-16 14:35 UTC, korthout commented
Thanks for noting that @skayliu, I've opened an issue:
- #11019