Add feel expressions for error events
camunda/camunda pull request #10972
Opened 2022-11-10 18:45 UTC by lzgabel

## Description

This PR adds feel expression support to all error events.

Supported error events:

* start event
* end event
* boundary event

## Related issues

closes #3801

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-11-10 18:45 UTC, lzgabel commented
Hi @saig0. Please take a moment to review this feature when you have time. ❤️

2022-11-22 15:10 UTC, remcowesterhoud requested changes
Hey @lzgabel, I'm sorry this took so long to review. The throwing part looks good! Great work on that 🚀 

❌ The catching part is more complex than it seems. I know it is mentioned as part of the issue, but I want to propose taking it out. Similar to with the escalation event.
The current changes won't work fully since you are modifying the model during processing. This is something we should avoid doing. It could result in some unexpected behaviour since the `Error` part of the model can be reused by multiple events.

Please take out the expression support for the catch events. Let me know if you need further help with this!

2022-11-22 15:41 UTC, lzgabel commented on engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/ErrorTransformer.java
> +              }
> So we don't need both the expression and the error code in the ExecutableError. Instead we can change the type of the errorCode in here to an Expression.

https://github.com/camunda/zeebe/blob/93839abcc216f5b4ebaf4983228fc89691ca9211/engine/src/main/java/io/camunda/zeebe/engine/state/analyzers/CatchEventAnalyzer.java#L123-L126
❓  So we need to evaluate the expression here?

2022-11-22 15:55 UTC, remcowesterhoud commented on engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/ErrorTransformer.java
> +              }
Hmm you raise a good point. I need to discuss within the team how we will handle this. It seems supporting throw events without catch events is not as straightforward as we thought.

2022-11-24 12:41 UTC, lzgabel commented
Hi @remcowesterhoud. Please check this out. 🙇

2022-11-25 11:01 UTC, remcowesterhoud requested changes
Very nice @lzgabel. We're almost to the point of merging it. I have some small comments left!

2022-11-25 12:08 UTC, lzgabel commented
Hi @remcowesterhoud. I've fixed all review comments. I'll squash all commits when you're done checking this out. 🙇

2022-11-25 12:29 UTC, remcowesterhoud approved these changes
Thanks @lzgabel!

Some small stuff left, a typo and I think you missed copying one of the test cases to the different class.

Feel free to rebase it already with these fixes. If you let me know when you're done I'll merge it!

2022-11-25 12:29 UTC, remcowesterhoud commented on engine/src/main/java/io/camunda/zeebe/engine/state/analyzers/CatchEventAnalyzer.java
> +        // Because a catch event can ot contain an expression, we ignore it if not set.
🙃 You made a typo here

2022-11-25 12:29 UTC, remcowesterhoud commented on bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/validation/ZeebeErrorEventValidationTest.java
> +      },
🔧 Let's also add the scenario of the error start event, like you had in the previous test class.

2022-11-25 12:47 UTC, lzgabel commented
Done.

Hi @remcowesterhoud. Please check this out. 🙇

2022-11-25 13:31 UTC, remcowesterhoud approved these changes
Thanks for your changes 🚀

2022-11-25 13:31 UTC, remcowesterhoud commented
bors merge

2022-11-25 13:48 UTC, merged