Change zeebe ports
camunda/camunda pull request #1108
Opened 2018-07-30 13:15 UTC by Zelldon

* changed 51015 to 26500: Client API (Gateway)
 * changed 51016 to 26502: Management API
 * changed 51017 to 26503: Replication API
 * changed 51018 to 26504: Subscription API

 also ports which started with 41*, 31*, etc are use now the port offset
 (+10 to the default port)

 closes zeebe-io/zeebe#1074

2018-07-31 13:20 UTC, menski requested changes
In general that looks good. I think there was a misunderstanding what client/broker API nowadays means. The old port 51015 (client API) should now be 26501 (broker API). And 26500 will be used by the gateway later on.

@Zelldon I will adjust this by myself before merging, so you can focus on the next topic. I have one questions, I assume you did not touch the get started guides as far as I can see? Which is no problem I would just create a new issue for them so we adjust this before doing the next release.

2018-07-31 13:54 UTC, Zelldon commented
Yep, sorry this was a thing I wanted to ask you today (I forgot it :see_no_evil: ) Thank you :) 

Hm yeah I only changed the docs and quickstart guide.

2018-08-01 12:29 UTC, menski approved these changes

2018-08-01 13:51 UTC, menski commented
bors r+

2018-08-01 14:11 UTC, merged