feat(engine): add escalation block builder
camunda/camunda pull request #11116
Opened 2022-11-28 16:07 UTC by koevskinikola

## Description

Adds an Escalation event BlockBuilder for the BPMN randomized tests. The Escalation Event BlockBuilder generates a sub-process or a call activity. There is a child process that throws and escalation event, and there is a boundary escalation catch event (interupting or non-interrupting) that catches the escalation and joins in an appropriate gateway (exclusive or parallel).

The escalation code is unique to the generated block. At the moment, this might be redundant, as the escalation event will always be caught by the encapsulating boundary escalation catch event.

## Related issues

closes #10768

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-11-29 11:06 UTC, remcowesterhoud requested changes
@koevskinikola Nice work 🚀 You missed the part of actually using this block 😄

I ran the test with this block a bunch of times and it failed a few times. I don't think it is related to your changes, so we might've found our first bug with it already. I'll retry it when you've made the changes.

2022-11-29 15:34 UTC, koevskinikola commented on test-util/src/main/java/io/camunda/zeebe/test/util/bpmn/random/blocks/EscalationEventBuilder.java
> +  static class Factory implements BlockBuilderFactory {
Oh no. I actually added it, commented out the rest of the factories for testing, and I guess I removed it when I reverted the Factory comments. :smile: 

However, I didn't get any failures. Maybe I didn't test correctly.

2022-11-30 12:44 UTC, koevskinikola commented
@remcowesterhoud all done with implementing the review hints. Have a look when you can.

2022-12-01 09:00 UTC, remcowesterhoud approved these changes
LGTM 👍 

bors merge

2022-12-01 09:15 UTC, merged