feat(client): Added automatic generation of Golang proto code
camunda/camunda pull request #1121
Opened 2018-08-01 12:07 UTC by jsam

Using maven proto compiler plugin we can generate Golang code needed for implementation of Go client.

closes #1082

2018-08-01 12:07 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: e75a570078dd5c4ad28350254ec17c5ea80ba3ae
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-08-02 11:42 UTC, menski requested changes
Looks good. I rebased the branch against the latest `1081-gateway`. I would like to have a `README.md` in the `gateway-protocol` which describes how to manually generate the go stubs:
- Go >= 1.7 required
- `go get -u github.com/golang/protobuf/protoc-gen-go`
- `mvn generate-sources -P golang`

Also could you update your local version of `protoc-gen-go` and regenerate the stub. Let's start with the latest version.

2018-08-03 11:50 UTC, menski approved these changes

2018-08-03 11:50 UTC, menski commented
bors r+

2018-08-03 12:06 UTC, merged