feat(engine): support catch-all and code-specific escalation catch events
camunda/camunda pull request #11276
Opened 2022-12-15 09:55 UTC by lzgabel

## Description
As a user, in a given scope, I can define:

* A single Escalation catch event with no escalation code defined (a catch-all Escalation event).
* Multiple Escalation catch events with a defined escalation code.

## Related issues
closes #11265

## Definition of Done
Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-12-15 09:56 UTC, lzgabel commented
Hi @koevskinikola. Please take a moment to check this out. :bow:

2022-12-15 10:44 UTC, koevskinikola commented
Hey @lzgabel, thank you for contributing this. :rocket: 

Me or another team member will have a look at the PR in the following days.

2022-12-19 14:21 UTC, koevskinikola requested changes
Hey @lzgabel, the changes look good. Thanks for implementing this so fast!

I have some minor change suggestions, but otherwise the code is ready to be merged.

2022-12-19 14:21 UTC, koevskinikola commented on engine/src/main/java/io/camunda/zeebe/engine/state/analyzers/CatchEventAnalyzer.java
> +    final Optional<ExecutableCatchEvent> escalstionCatchEvent =
:wrench: There's a typo here:
```suggestion
    final Optional<ExecutableCatchEvent> escalationCatchEvent =
```

2022-12-19 14:21 UTC, koevskinikola commented on engine/src/main/java/io/camunda/zeebe/engine/state/analyzers/CatchEventAnalyzer.java
> +            .sorted(ESCALATION_CODE_COMPARATOR)
:+1: Nice!

2022-12-19 14:21 UTC, koevskinikola commented on engine/src/main/java/io/camunda/zeebe/engine/state/analyzers/CatchEventAnalyzer.java
> +    if (escalstionCatchEvent.isPresent()) {
:wrench: Typo here as well:

```suggestion
    if (escalationCatchEvent.isPresent()) {
```

2022-12-19 14:21 UTC, koevskinikola commented on engine/src/main/java/io/camunda/zeebe/engine/state/analyzers/CatchEventAnalyzer.java
> +      catchEventTuple.catchEvent = escalstionCatchEvent.get();
:wrench: Same here:
```suggestion
      catchEventTuple.catchEvent = escalationCatchEvent.get();
```

2022-12-19 14:28 UTC, lzgabel commented
Done. 

Hi @koevskinikola. Please check this out. ❤️

2022-12-19 15:26 UTC, koevskinikola approved these changes
LGTM! :rocket: 

bors merge

2022-12-19 15:40 UTC, merged