Always activate the correct start event upon a create command
camunda/camunda pull request #11279
Opened 2022-12-15 14:48 UTC by remcowesterhoud

## Description

A process could contain multiple start events. Depending on whether we can find an EventTrigger we activate the triggered start event, or the none start event. If we want to activate the none start event, but we already have an EventTrigger in the state we will trigger the wrong one.

By using the process instance key in the EventTrigger we can determine whether this activation relates to the EventTrigger in the state. If this is the case we should activate this triggered start event. Otherwise we should activate the none start event.

For backwards compatibility's sake, if the process instance key is not available in the EventTrigger, we should still activate the triggered start event. This way behavior does not change.

## Related issues

closes #10536 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-12-15 14:49 UTC, remcowesterhoud commented
@saig0 Feel free to leave this review for a couple of weeks, since I won't be fixing comment before I'm back from my holidays anyway 😄

2022-12-21 05:56 UTC, saig0 requested changes
@remcowesterhoud the changes look good. :+1: 

But some tests are failing. I have also a few minor suggestions. Please have a look. :cookie:

2022-12-21 05:56 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java
> +  public void shouldActivateNoneStartEventWhenEventTriggerIsAvailableInState() {
:wrench: We could add a comment with a link to the issue (e.g. "This is a regression test of ..."). 

The issue can give more context than the test case itself.

2022-12-21 05:56 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java
> +            .getProcessInstanceKey();
:x: Getting the first process instance creation record with a class rule is flaky.

If the test case is not executed first then the first record is written by a different test case. If I run the whole test class locally then the test case fails. 

We could use a unique process id (e.g. `BrokerClassRuleHelper.getBpmnProcessId()`) and use it to filter the records.

2022-12-21 05:56 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/util/client/ProcessInstanceClient.java
> +    public ProcessInstanceCreationClient withoutExpectation() {
:wrench: The new method is not used. Can it be removed?

2022-12-21 05:56 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/state/instance/EventScopeInstanceStateTest.java
> +    triggerStartEvent(SCOPE_KEY, 456, eventTrigger, -1L);
:wrench: We should verify in a test case that the process instance key of the event trigger is stored in the state.

2022-12-21 05:56 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceTest.java
> +                BpmnElementType.START_EVENT, "msgStart", ProcessInstanceIntent.ELEMENT_ACTIVATED));
:wrench: Additionally, we could verify that the message start event is activated later but with a different process instance key.

2022-12-21 05:56 UTC, saig0 commented on bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/builder/ProcessBuilder.java
> +    bounds.setY(100 + getLowestHeight());
:x: The `CoordinatesGenerationTest` doesn't like your changes. 

This test fails because the coordinated doesn't match the expectations anymore.

2023-01-16 09:58 UTC, saig0 approved these changes
@remcowesterhoud looks good. :+1:

2023-01-16 09:58 UTC, remcowesterhoud commented
bors merge

2023-01-16 13:51 UTC, remcowesterhoud commented
bors retry

2023-01-16 14:08 UTC, merged

2023-01-16 14:08 UTC, backport-action commented
Backport failed for `stable/8.0`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally.
```bash
git fetch origin stable/8.0
git worktree add -d .worktree/backport-11279-to-stable/8.0 origin/stable/8.0
cd .worktree/backport-11279-to-stable/8.0
git checkout -b backport-11279-to-stable/8.0
ancref=$(git merge-base 0f88bc59a86a994e30533a20e4ff0f0fdb179935 fea7e1611688f7c3f08bcd0d2b4880ea0bd37852)
git cherry-pick -x $ancref..fea7e1611688f7c3f08bcd0d2b4880ea0bd37852
```

2023-01-16 14:08 UTC, backport-action commented
Backport failed for `stable/8.1`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally.
```bash
git fetch origin stable/8.1
git worktree add -d .worktree/backport-11279-to-stable/8.1 origin/stable/8.1
cd .worktree/backport-11279-to-stable/8.1
git checkout -b backport-11279-to-stable/8.1
ancref=$(git merge-base 0f88bc59a86a994e30533a20e4ff0f0fdb179935 fea7e1611688f7c3f08bcd0d2b4880ea0bd37852)
git cherry-pick -x $ancref..fea7e1611688f7c3f08bcd0d2b4880ea0bd37852
```