Add record and intent for signal
camunda/camunda pull request #11296
Opened 2022-12-19 15:08 UTC by skayliu

## Description

Add record, intent, stream and export to es for signal.

## Related issues

closes #11295 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-12-19 15:09 UTC, skayliu commented
Hi, @korthout, Please take a look at this feat. Thank you. :heart:

2022-12-20 16:39 UTC, korthout requested changes
Nicely done @skayliu 👏 

🔧 We want `Signal:Broadcast` commands to be sent from the client to the gateway, and from the gateway to the broker. To support the broker receiving this command from the gateway, we'll need to add the `Signal` record to the `records_by_type` mapping in `CommandApiRequestReader`. We could add it later, but it's easy to miss and complicates efforts once you start work on the gateway. So, I suggest making that change now.

❌ There's one small change required before merging this pull request (i.e. the order of the compact record logger's entries). Please have a look at my comment below.

👍 Awesome job on splitting up the commits. The changes were easy to follow.

2022-12-20 16:39 UTC, korthout commented on test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java
>            entry("SIGNAL_SUBSCRIPTION", "SIG_SUB"));
❌ Please swap these. The order matters. In the current order, records of type `SIGNAL_SUBSCRIPTION` would be abbreviated to `SIG_SUBSCRIPTION`  instead `SIG_SUB`.

2022-12-20 16:39 UTC, korthout commented on test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java
> +    return result.toString();
🔧 There's no need for the local variable result

```java
return new StringBuilder()
    .append("\"")
    .append(value.getSignalName())
    .append("\"")
    .append(summarizeVariables(value.getVariables()))
    .toString();
```

2022-12-21 01:46 UTC, skayliu commented
@korthout Done, Please check this out. Thank you.

2022-12-22 15:03 UTC, korthout approved these changes
Awesome 🚀 

LGTM 💯 

🙇 Sorry for the slow review @skayliu, let's get this merged

bors merge

2022-12-22 21:02 UTC, korthout commented
bors retry

2022-12-23 10:14 UTC, korthout commented
Sorry about that @skayliu, we're experiencing some difficulties with out Github Actions Self-Hosted Runners. I'll retry when I think it should be resolved

2022-12-23 10:56 UTC, skayliu commented
> Sorry about that @skayliu, we're experiencing some difficulties with out Github Actions Self-Hosted Runners. I'll retry when I think it should be resolved

Take your time& there is no rush.

2022-12-23 15:01 UTC, Zelldon commented
bors r+

2022-12-23 15:17 UTC, merged