feat(engine): add retry backoff support in BPMN
camunda/camunda pull request #11339
Opened 2022-12-26 05:58 UTC by aivinog1

## Description

I've added retry backoff support in BPMNs for service tasks.

## Related issues

closes #11101 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-12-27 09:06 UTC, Zelldon commented
Hey @aivinog1 thanks for your contribution, please be aware that most of the team is on holiday so it might take a while until we can review your PR (likely until the end of next week). Sorry for the inconvenience:bow:

2023-01-09 06:51 UTC, aivinog1 commented
Hi @Zelldon! 
Can we speed up the review a little bit in terms of BPMN API (I mean the XML structure)? We could settle down the API and I could create a PR in the Modeler. Thanks 🙂

2023-01-09 06:54 UTC, Zelldon commented
This week @remcowesterhoud and @saig0 are back

2023-01-10 09:09 UTC, korthout commented
Sorry for the long wait @aivinog1 I'll have a look at it now.

2023-01-10 14:52 UTC, korthout requested changes
Thanks for this awesome contribution @aivinog1 🚀 Great stuff!

>We could settle down the API and I could create a PR in the Modeler

👍 Both the BPMN API (XML) as well as the bpmn-model API (Java) look good to me.

❌ I found a few things that must be changed before this can be accepted.

Please have a look at my comments, suggestions and questions.

2023-01-10 14:52 UTC, korthout commented on bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/util/time/Interval.java
> +    return Math.addExact(durationMillis, periodMillis);
👍 Nice work coming up with a solution here

I thought about this code for some time, and I understand its need. Periods and Durations don't combine well, and Java's standard time library doesn't allow easily converting the two to milliseconds. The problem is that Periods may be mapped to different Durations depending on the TimeZone. With this in mind, I worried that this implementation might be incorrect in some situations. But does it matter for the current use case? It is useful to tell the engine to backoff a job for several days, but this does not have to be precise. So, in my opinion, it's fine to keep it this way. Let me know how you feel about this.

🔧 In any case, let's document this, so the method is not used for cases where this precision is required for Intervals containing Periods.

2023-01-10 14:52 UTC, korthout commented on bpmn-model/pom.xml
> +    </dependency>
❌ We should not add this dependency. The Zeebe Util is not built for Java 8 and would push a lot of new transitive dependencies to consumers of the bpmn-model library. 

>**Note** it seems only to be needed for the Tuple class. Perhaps you can find a different solution without this class.

2023-01-31 13:01 UTC, nikku commented
[Which direction](https://github.com/camunda/zeebe/issues/11101#issuecomment-1410297770) to you go with this PR?

* Back-off as an additional property?
* Back-off encoded in retries (be able to define a repeating interval), i.e. via ISO date 8601?

2023-01-31 19:48 UTC, aivinog1 commented
> [Which direction](https://github.com/camunda/zeebe/issues/11101#issuecomment-1410297770) to you go with this PR?
> 
> * Back-off as an additional property?
> * Back-off encoded in retries (be able to define a repeating interval), i.e. via ISO date 8601?

Hey @nikku!
Right now it is two separate attributes

2023-02-14 17:14 UTC, korthout commented
> > [Which direction](https://github.com/camunda/zeebe/issues/11101#issuecomment-1410297770) to you go with this PR?
> > 
> > * Back-off as an additional property?
> > * Back-off encoded in retries (be able to define a repeating interval), i.e. via ISO date 8601?
> 
> Right now it is two separate attributes

For completeness, we made a decision about this in https://github.com/camunda/zeebe/issues/11101#issuecomment-1412328461:
> 📝 Let's decide to introduce the retriesBackoff as a secondary field next to retries.

2023-05-22 14:16 UTC, korthout commented
Hi @aivinog1 👋 Just checking in with you to see if you're still interested in continuing this pull request. If you are, is there anything I can do to unblock you?

2023-05-22 14:20 UTC, aivinog1 commented
Hi @korthout 👋
Sure, I'm interested 🙂 But our team's priorities changed a bit and I'll come back to it in a couple of weeks 🙂

2023-05-22 14:24 UTC, korthout commented
Thanks for the update @aivinog1. Looking forward to it, and let me know if I can assist in any way 🏗️

2023-11-15 19:35 UTC, npepinpe commented
What's the status here? Lots of changes were done in the meantime to jobs.

2023-12-12 13:17 UTC, Zelldon commented
This PR is open since a year. I will close it. Feel free to reopen or create another PR if you want to contribute this change.

2023-12-12 13:17 UTC, closed without merging