feat(broker): publish message with TTL
camunda/camunda pull request #1155
Opened 2018-08-07 12:09 UTC by saig0

* new property of message record
* correlate message only within the TTL
* delete message after TTL
* extend gateway client

closes #1026

2018-08-08 14:17 UTC, ThorbenLindhauer requested changes
Looks good in general, see code comments.

2018-08-08 14:17 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java
> +        batchWriter.addFollowUpCommand(key, MessageIntent.DELETE, messageRecord);
This is a bit inconsistent in my opinion. The message is never added to the store, so it is not required to delete it in a separate step. Also, having the extra asynchronous command suggests that the message can be correlated to subscriptions that are opened between `PUBLISH` and `DELETE`. I think it's cleaner if we either directly write the `DELETED` event or omit this record entirely.

2018-08-08 14:17 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/MessageTimeToLiveChecker.java
> +    writer.flush();
Should maybe yield or break out of the message store iteration on backpressure.

2018-08-09 13:34 UTC, saig0 commented
@ThorbenLindhauer , I applied the review hints. Please review the changes :)

2018-08-10 07:14 UTC, ThorbenLindhauer approved these changes

2018-08-10 10:01 UTC, saig0 commented
bors r+

2018-08-10 10:18 UTC, merged