Process Signal BROADCASTED events
camunda/camunda pull request #11778
Opened 2023-02-21 17:28 UTC by lzgabel

## Description

This PR adds introduce new `Signal:Broadcast` command processor.

## Related issues
closes #11777

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-02-21 17:28 UTC, lzgabel commented
Hi @korthout. Please take a moment to check this out. 🙇

2023-02-22 13:20 UTC, korthout commented
Thanks @lzgabel 🙇 I don't think I'll find any time for this anymore in this week. I'll have a closer look next week. Sorry for the delay.

2023-03-01 16:04 UTC, korthout requested changes
Wow, awesome work @lzgabel 👏 

I'm very sorry to make you wait for my review so long 🙇 

👍 Great to see that this already functions correctly! 🎉 

❌ I have a few change requests and some suggestions. Please have a look.

🔧 Please also add the following test case to `SignalStartEventTest`:
```java
@Test
public void shouldNotCreateInstanceDirectly() {
  // given
  engine
      .deployment()
      .withXmlResource(
          Bpmn.createExecutableProcess("SignalStartEventOnly")
              .startEvent("signal-start")
              .signal("start")
              .endEvent()
              .done())
      .deploy();

  // when
engine.processInstance().ofBpmnProcessId("SignalStartEventOnly").expectRejection().create();

  // then
  Assertions.assertThat(
          RecordingExporter.processInstanceCreationRecords()
              .onlyCommandRejections()
              .withBpmnProcessId("SignalStartEventOnly")
              .getFirst())
      .hasRejectionType(RejectionType.INVALID_STATE)
      .hasRejectionReason(
          "Expected to create instance of process with none start event, but there is no such event");
}
```

2023-03-01 17:37 UTC, lzgabel commented
Hi @korthout.  I've rebased on top of `main` and fixed all review comments. Please have another look! :bow:

2023-03-01 19:00 UTC, korthout approved these changes
Awesome 🚀 You're so fast 🏎️ 

🔧 Now that the processes are inlined in the test, I noticed something we could improve. Other than that, it is perfect 🏅 Let me know if you want to apply this suggestion or leave it. I'm okay with both.

LGTM 👍

2023-03-01 19:11 UTC, lzgabel commented on engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalStartEventTest.java
> +            .serviceTask("task", t -> t.zeebeJobType("test"))
Hi @korthout. I have applied your suggestions. Please check this out. :heart:

2023-03-01 19:33 UTC, korthout commented
bors merge

🎉

2023-03-01 19:48 UTC, merged