feat(bpmn-model): add dueDate and followUpDate as user task properties
camunda/camunda pull request #11811
Opened 2023-02-24 13:48 UTC by koevskinikola

## Description

As a user, I can use the Zeebe BPMN Model API to define the following properties on user tasks:

* `dueDate`
* `followUpDate`

The properties accept static values and expressions. The properties are encapsulated by the new `ZeebeTaskSchedule` extension element.

## Related issues

closes #11795 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-02-28 11:19 UTC, berkaycanbc requested changes
:+1: Nice and clean! I only asked clarifying questions and requested a minor change.

:question: One clarifying question for the overall PR: this PR will not affect current behavior because data will not be transformed and run yet, right? Therefore, we do not need to introduce a feature flag.

2023-02-28 11:34 UTC, koevskinikola commented on bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/instance/zeebe/ZeebeTaskSchedule.java
> +public interface ZeebeTaskSchedule extends BpmnModelElementInstance {
The reason was that the majority of the interfaces in the `io.camunda.zeebe.model.bpmn.instance.zeebe` package, where we define the extension interfaces, don't contain the `Definition` suffix. 

There are only four interfaces there with the `Definition` suffix, and @korthout gave me feedback that in retrospect, he wouldn't have added the `Definition` suffix to them.

So I decided to drop it, and keep with the majority pattern.

2023-02-28 11:34 UTC, koevskinikola commented on bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/instance/zeebe/ZeebeTaskSchedule.java
> + * Copyright © 2017 camunda services GmbH (info@camunda.com)
I don't think so. The license header is auto-generated by our IDE from the project configuration. So we shouldn't change it. If there was an issue with it, the CI would have complained.

2023-02-28 11:34 UTC, koevskinikola commented on bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/builder/UserTaskBuilderTest.java
> +  void shouldSetAssigneeAndCandidateGroupsAndCandidateUsersAndDueDateAndFollowUpDateOnUserTask() {
Yup, I agree. I'll update it. :+1:

2023-02-28 11:38 UTC, koevskinikola commented
@berkaycanbc, regarding your question about a feature flag, we won't need to add a feature flag anywhere in the epic about due and follow-up dates in user tasks.

The support for these dates in user tasks is a completely new feature, and as such it will be supported by default with the next minor version of Zeebe (`8.2.0`). We are also not backporting new features, so we don't need to add a feature flag.

Another reason is that the changes made by this epic won't impact any existing behavior, they just expand the properties provided by user tasks in Camunda Platform 8.

2023-02-28 11:38 UTC, berkaycanbc commented on bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/instance/zeebe/ZeebeTaskSchedule.java
> +public interface ZeebeTaskSchedule extends BpmnModelElementInstance {
Alright, makes sense. Then, what do you think about refactoring `ELEMENT_SCHEDULE_DEFINITION` in constant definitions to only `ELEMENT_SCHEDULE` ?

2023-02-28 11:39 UTC, berkaycanbc commented on bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/instance/zeebe/ZeebeTaskSchedule.java
> + * Copyright © 2017 camunda services GmbH (info@camunda.com)
Ahh, okay, thanks!

2023-02-28 12:01 UTC, koevskinikola commented
@berkaycanbc all done with resolving the review hints. Have a look. :smile:

2023-02-28 14:54 UTC, berkaycanbc approved these changes
Thanks for the responses and applying the suggestion, approved! :rocket:

2023-03-01 07:47 UTC, koevskinikola commented
Thanks @berkaycanbc!

BTW, if everything looks good with the PR (e.g. no review hints, all commits are correctly formatted) you can trigger a PR merge yourself like so:

bors merge

2023-03-01 08:12 UTC, merged