added region property to client properties
camunda/camunda pull request #11870
Opened 2023-03-01 13:25 UTC by ogkunald

## Description

added `region` property to  the client configuration properties

## Related issues

closes #11846 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-03-01 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/zeebe?pullRequest=11870) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/zeebe?pullRequest=11870) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/zeebe?pullRequest=11870) it.</sub>

2023-03-03 08:15 UTC, korthout requested changes
Thanks @ogkunald. This looks great! 🚀 

👍 Code and tests are perfect

❌ Please rebase and squash your commits into one or more commits with meaningful messages that follow our [commit message guidelines](https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md#commit-message-guidelines). By writing meaningful commit messages, future code readers may be better equipped to understand why these changes were made.

2023-03-03 08:35 UTC, korthout commented
Seems that checkstyle detected a minor code style issue (just some training whitespace):
>[INFO] --- maven-checkstyle-plugin:3.2.0:check (validate-java) @ zeebe-client-java ---
[INFO] There are 2 errors reported by Checkstyle 10.8.0 with check/.checkstyle.xml ruleset.
Error:  src/main/java/io/camunda/zeebe/client/ClientProperties.java:[104] (regexp) Regexp: Line matches the illegal pattern 'Trailing whitespace'.
Error:  src/main/java/io/camunda/zeebe/client/ClientProperties.java:[109] (regexp) Regexp: Line matches the illegal pattern 'Trailing whitespace'.

2023-03-03 11:34 UTC, ogkunald commented
Hi @korthout  As per your suggestion.
I have made following changes-
1. Removed unwanted trailing whitespaces
2.  Single commit with meaningful message.

Please review and let me know. 
Thanks.

2023-03-03 13:45 UTC, korthout approved these changes
Awesome! Thanks for the changes @ogkunald 🙇 

LGTM 👍 

bors merge

2023-03-03 14:02 UTC, merged

2023-03-03 14:17 UTC, korthout commented
/backport

2023-03-03 14:18 UTC, backport-action commented
Successfully created backport PR for `stable/8.0`:
- #11915

2023-03-03 14:18 UTC, backport-action commented
Successfully created backport PR for `stable/8.1`:
- #11916