Add Opensearch exporter
camunda/camunda pull request #12045
Opened 2023-03-15 16:13 UTC by remcowesterhoud

## Description

The `OpensearchExporter` is almost the same as the `ElasticsearchExporter`. This PR creates copy of the `ElasticsearchExporter` and migrates it to `Opensearch`. This involves a few things:

- Update all the dependencies from elasticsearch to opensearch
- Make the code compatible with the opensearch dependencies
- Making sure we can build the opensearch artifact
- Switch the tests to use the opensearch testcontainer as opposed to the elasticsearch one

## Related issues

closes #12011 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-03-16 14:57 UTC, koevskinikola requested changes
@remcowesterhoud, the changes look good to me.

I found some files that still reference or use ElasticSearch components that we should update. Let me know if you were planning to adjust them in a later PR.

2023-03-16 14:57 UTC, koevskinikola commented on exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/RestClientFactory.java
> +   * @param allowAllSelfSignedCertificates if set to true ALL self-signed certificates will be
:upside_down_face: Just nitpicking, we can add a comma here, but my English grammar knowledge might be wrong.

```suggestion
   * @param allowAllSelfSignedCertificates if set to true, ALL self-signed certificates will be
```

2023-03-16 14:57 UTC, koevskinikola commented on exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/RestClientFactory.java
> +        final var sslcontext =
:upside_down_face: Same here, we can use camelCase:

```suggestion
        final var sslContext =
```

2023-03-16 14:57 UTC, koevskinikola commented on exporters/opensearch-exporter/README.md
:x: The README still mentions Elasticsearch, and provides several links to it. Should we update it within this PR?

2023-03-16 14:57 UTC, koevskinikola commented on exporters/opensearch-exporter/docker-compose.yml
:x: Same as the README, we're defining an ElasticSearch instead of an OpenSearch service in the Docker Compose file. We should update it to OpenSearch.

2023-03-16 14:57 UTC, koevskinikola commented on exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/dto/Template.java
> + * href="https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html">here</a>.
:wrench: We should update to an OpenSearch link here, if it is available.

2023-03-17 08:12 UTC, koevskinikola commented on exporters/opensearch-exporter/README.md
I just saw that there's a separate issue about the README [here](https://github.com/camunda/zeebe/issues/12016). You can ignore this comment.

2023-03-17 09:43 UTC, remcowesterhoud commented on exporters/opensearch-exporter/docker-compose.yml
Good catch 👍

2023-03-17 10:11 UTC, koevskinikola approved these changes
LGTM :rocket: 

bors merge

2023-03-17 10:11 UTC, koevskinikola commented on exporters/opensearch-exporter/docker-compose.yml
:+1: Wow, nice find regarding the OpenSearch Dashboards project. I wasn't aware of it, although I should have expected it. :smile:

2023-03-17 10:29 UTC, merged