feat(broker): correlate message resilient
camunda/camunda pull request #1206
Opened 2018-08-22 13:44 UTC by saig0

* store pending subscriptions in state
* check pending subscriptions and retry after timeout
* reject duplicated subscription commands

closes #1079

2018-08-23 12:07 UTC, ChrisKujawa requested changes

2018-08-24 06:31 UTC, saig0 commented
@Zelldon , please have a look at my last commit :)

2018-08-24 06:48 UTC, ChrisKujawa approved these changes

2018-08-24 06:53 UTC, saig0 commented
bors r+

2018-08-24 07:11 UTC, merged