Add node id to configuration and use it instead of endpoint for communicating with brokers
camunda/camunda pull request #1209
Opened 2018-08-23 22:11 UTC by menski

The node id should identify a node uniquely in the cluster. It should be between 0 to cluster nodes (exclusive). This allows us to already know on startup all node ids if we are aware of the cluster size.

Transport now contains a component called `EndpointRegistry` which is used to handle the lookup between node id and current endpoint. Endpoint registration and deactivating is happening based on state discovered through gossip. All requests are now send to a node by id instead of a specific endpoint.

There are two special cases where the node id is not known. First on broker bootstrap only the contact points are known without the node id, therefore gossip registers the current tested contact point with a special node id `UNKNOWN_NODE_ID`. After the initial sync request the node ids are known. The same is true for the gateway client which also only has an initial contact point. After the first topology refresh the node ids are known.

Removes as many as possible `host` and `port` fields from the SBE protocol and replaces them with node ids instead. This allows to replace a node by joining a new node with the same id even with different endpoints.

closes #1046 
closes #1066

2018-08-27 07:17 UTC, ChrisKujawa requested changes

2018-08-27 07:17 UTC, Zelldon commented on raft/src/test/java/io/zeebe/raft/util/RaftRule.java
> +    clientTransport.deactivateEndpoint(other.getNodeId());
Awesome :)

2018-08-27 09:30 UTC, menski commented on broker-core/src/test/java/io/zeebe/broker/util/BufferingClientOutput.java
> +    private final Integer destination;
This is a test class and the destination is provided by a `Supplier<Integer>` so could return null. I didn't changed it. Hope that is okay.

2018-08-28 05:32 UTC, Zelldon commented
Looks good can we change the other List<Integer> as well to IntArrayList?

2018-08-28 06:42 UTC, menski commented
Which list did I missed?

2018-08-28 08:41 UTC, menski commented
I squashed and rebased on develop. Waiting for Jenkins build to pass. @Zelldon can I get an approve of the changes to the PR so I can merge it?

2018-08-28 08:44 UTC, ChrisKujawa approved these changes

2018-08-28 09:51 UTC, menski commented
bors r+

2018-08-28 10:00 UTC, merged