Add deployment intermediate states
camunda/camunda pull request #1215
Opened 2018-08-28 09:27 UTC by Zelldon

* create - transforms, validates deployment and generates key
 * distribute - distributes the deployment to remaining partitions
 * creating - verifies whether the deployment was already added or not,
   if it exist already then it will be rejected otherwise the created event is written
 * created - adds the deployment to the state
 * creating and created processor runs on each partition
 * create and distribute runs only on partition 1

closes #1208

2018-08-28 14:56 UTC, menski requested changes
Please merge `DeploymentDistributeProcessor` and `DeploymentRejectedProcessor` into `DeploymentCreateProcessor`. Also merge `DeploymentCreatedProcessor` into `DeploymentCreatingProcessor`.

It would also be good if the deployment partition has the workflow as fast as possible in the workflow index. At best after `CREATE` was processed as we can then achieve that as long as the user got a positive response to the deploy request at least one partition can create instances.

Reason for that is that we in general do the state changes and responses in the command processor. Normally events are not processed by the stream processors. The reasons for this are that at the moment the command processor does the decision we already know the new state and can use it. Assume someone creates a deployment and after short time starts to create millions of instances. If these millions of create wf instance commands are written after the `CREATING` command and before the `CREATED` event all of them are rejected. Although the workflow is already known.

2018-08-28 14:59 UTC, menski requested changes

2018-08-28 14:59 UTC, menski commented on qa/integration-tests/src/test/java/io/zeebe/broker/it/data/ZeebeObjectMapperTest.java
> +      latch.await();
Please add a timeout to the `await` call and check that it returned `true`.

2018-08-28 14:59 UTC, menski commented on test/src/test/java/io/zeebe/test/WorkflowTest.java
> +    latch.await();
Please add a timeout to the `await` call and check that it returned `true`.

2018-08-28 15:13 UTC, menski commented
I think we don't need the await hacks in the tests anymore if the workflow is added to the index after the create command was processed.

2018-08-29 05:46 UTC, Zelldon commented
> Please merge DeploymentDistributeProcessor and DeploymentRejectedProcessor into DeploymentCreateProcessor. Also merge DeploymentCreatedProcessor into DeploymentCreatingProcessor.

Hm can do. Personally I found it clearer and it is a bit separation of concerns.

> It would also be good if the deployment partition has the workflow as fast as possible in the workflow index. At best after CREATE was processed as we can then achieve that as long as the user got a positive response to the deploy request at least one partition can create instances.

Since we removing the workflow fetching stuff in #1165 I would try to not couple the processors more then necessary. We could think about sending the response in the CREATING processing, then we can be sure that all partitions have the deployment and we can start WF instances without any problems.

> Reason for that is that we in general do the state changes and responses in the command processor. 

Disagree. The Deployment reject and create processor are not new there already exists before my changes, furthermore there exist processors for Workflow created and rejected which does the same :sweat_smile: . 

> Normally events are not processed by the stream processors. The reasons for this are that at the moment the command processor does the decision we already know the new state and can use it. 

Makes sense but is currently not the case. We can change that.

> Assume someone creates a deployment and after short time starts to create millions of instances. If these millions of create wf instance commands are written after the CREATING command and before the CREATED event all of them are rejected. Although the workflow is already known.

Yes that is the reason why I never understood your request of directly sending the response :D 
I would say that sending the response on CREATING solve this. Did you think that we then could have some timeout problems?

2018-08-29 11:46 UTC, menski approved these changes

2018-08-29 11:46 UTC, menski commented
bors r+

2018-08-29 11:54 UTC, merged