Updated Slack and forum link
camunda/camunda pull request #12174
Opened 2023-03-28 15:00 UTC by xomiamoore

Updated Slack and forum link

## Description

Updated links to be current

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-03-29 11:23 UTC, abbasadel approved these changes

2023-03-29 11:29 UTC, abbasadel requested changes

2023-03-29 11:29 UTC, abbasadel commented on CONTRIBUTING.md
> +If you have a general usage question please ask on the [forum](forum.camunda.io/) or [Slack](http://www.camunda.com/slack) channel.
@xomiamoore I think you should add `https://` before the forum link to make it work. 
Also, I think we should always use `https` for the slack channel.

2023-04-18 09:03 UTC, saig0 commented
@abbasadel this PR is waiting for your review. :bell: 

The PR is already open for a long time. Let's finish it. :rocket:

2023-04-18 10:01 UTC, abbasadel approved these changes
LGTM

2023-04-18 10:01 UTC, merged