Support broadcast signal for signal intermediate throw events
camunda/camunda pull request #12206
Opened 2023-04-01 13:36 UTC by skayliu

## Description

Support broadcast signal for signal intermediate throw events

- When Signal Intermediate Throw Event activates:
  - Apply input mappings
  - Transition to activated
  - Write `Signal:Broadcast` command
  - Apply output mappings
  - Transition to complete the element

## Related issues

closes #11919
closes #11918

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-04-03 04:49 UTC, skayliu commented
Hey, @korthout. Please take a moment to check this out, When you have time. 🙇

2023-04-05 14:50 UTC, korthout requested changes
As I've said before 👏 Well done @skayliu 

👍 This looks great!

❌ I only have some minor remarks. Please have a look and make the requested changes. Then we should be able to merge this soon after.

2023-04-05 14:50 UTC, korthout commented on engine/src/test/java/io/camunda/zeebe/engine/processing/signal/SignalThrowEventTest.java
> +public class SignalThrowEventTest {
🔧 Let's rename this to `SignalIntermediateThrowEventTest` to clarify that this only tests the Intermediate Throw Events, not also the End Events.

2023-04-05 15:10 UTC, korthout approved these changes
Thanks @skayliu 🥇 

LGTM 👍 

bors merge

2023-04-05 15:28 UTC, merged