feat(engine): support bpmn converging inclusive gateway
camunda/camunda pull request #12642
Opened 2023-05-03 06:03 UTC by lzgabel

## Description
This PR adds support for converging/joining inclusive gateway.

## Related issues
closes #10031

## Definition of Done
Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-05-03 06:06 UTC, lzgabel commented
Hi @camunda/zeebe-process-automation. Please take a moment to review this feature. 🙇

2023-05-03 08:38 UTC, koevskinikola commented
Hey @lzgabel,

Thank you for submitting this contribution! I'll review the code this week and provide you with feedback.

Cheers,
Nikola

2023-05-10 14:21 UTC, koevskinikola requested changes
The changes look great @lzgabel. :rocket: 

I just have some small feedback for the test coverage. You can see it in the comment below.

2023-05-10 14:21 UTC, koevskinikola commented on engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/gateway/InclusiveGatewayTest.java
> +  public void shouldMergeAndSplitInOneGateway() {
:+1: Great test coverage on the new converging inclusive gateway behavior!

:x: However, I think we should add a test case when one gateway splits and merges, but only one, or a subset of the incoming sequence flows are activated.

2023-05-10 16:44 UTC, lzgabel commented
Hi @koevskinikola . Please check this out. :heart:

2023-05-10 16:51 UTC, lzgabel commented
🤔 I received this emai. What's wrong? Am I missing something?

![86F8D1D6-8078-467A-8045-0549873130CC](https://github.com/camunda/zeebe/assets/24605947/d6dcca66-fc90-454d-b933-b9b55707d2e3)

2023-05-11 07:42 UTC, koevskinikola commented
@lzgabel the email is a bit strange, I haven't triggered any benchmark workflows. I'll check with the team if someone changed anything regarding the PR workflows.

Thank you for reporting this!

2023-05-15 08:19 UTC, koevskinikola approved these changes
@lzgabel seems like the PR benchmark CI job was triggered by accident and it failed due to some flaky tests.

The PR looks good now, thank you for providing support for the converging inclusive gateway! :rocket: 

Cheers!

bors merge

2023-05-15 08:31 UTC, merged