fix(engine): catch-all error events with empty errorCode
camunda/camunda pull request #12840
Opened 2023-05-23 18:43 UTC by lzgabel

## Description

If 'errorCode' is omitted, an empty error without errorCode will be created to facilitate finding catch-all error events.

## Related issues
closes #12837

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-05-23 18:44 UTC, lzgabel commented
Hi @korthout. Please take a moment to check this out. Thanks. :heart:

2023-05-26 12:08 UTC, koevskinikola requested changes
@lzgabel thank you for providing a quick fix for this bug.

However, your fix breaks the existing functionality of the feature.

I would suggest that you first create a test case in `ErrorEventTest` that reproduces this bug. This would also give us more complete test coverage on this feature.

2023-05-26 12:59 UTC, lzgabel commented on engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/CatchEventTransformer.java
> +    ExecutableError executableError = context.getError(error.getId());
I'm very sorry, maybe I was too hasty. :bow:

2023-05-26 13:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/zeebe?pullRequest=12840) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/camunda/zeebe?pullRequest=12840) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: lzgabel<br/>:x: LiZhi<br/><hr/>**LiZhi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/zeebe?pullRequest=12840) it.</sub>

2023-05-26 13:22 UTC, lzgabel commented
Hi @koevskinikola. Please check this out. :heart:

2023-06-01 09:55 UTC, koevskinikola approved these changes
:+1: Nicely done @lzgabel. Thank you for fixing this bug :rocket: 

bors merge

2023-06-01 11:33 UTC, lzgabel commented
🤔 Hi @koevskinikola. Do I need to rebase this change on top of `main`?

2023-06-01 12:25 UTC, koevskinikola commented
Hey @lzgabel, usually `bors` takes care of the rebasing, but it seems stuck for some reason.

Let's wait and see if `bors` just has a high work load, or we need to do something about it. :smile:

2023-06-02 02:24 UTC, lzgabel commented
🤔 Seems like `bors` not working.

2023-06-05 10:35 UTC, koevskinikola approved these changes
Let's try again.

bors r+

2023-06-05 10:46 UTC, merged

2023-06-05 10:49 UTC, lzgabel commented
🤔 Seems like it's working fine. 

When anyone is free, see if this can be avoided. :bow:

2023-06-05 10:53 UTC, lzgabel commented
Hi @koevskinikola. Please trigger a `backport` for this PR. Thanks ❤️

2023-06-05 10:59 UTC, koevskinikola commented
/backport

2023-06-05 10:59 UTC, backport-action commented
Successfully created backport PR for `stable/8.2`:
- #12958