a send task or message throw event can reference a message definition
camunda/camunda pull request #12879
Opened 2023-05-28 16:41 UTC by lzgabel

## Description

* add the new Zeebe extension element `messageDefinition` with the attributes
    * `messageName`
    * `messageId`
    *  `correlationKey`
    *  `timeToLive`
* extend the builder of send tasks and intermediate throw events to define the message definition

## Related issues
closes #12878

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-05-28 16:42 UTC, lzgabel commented
Hi @korthout. Please take a moment to review this feature. 🙇

2023-06-06 08:39 UTC, korthout requested changes
We're currently defining what is needed for this topic in:
- #12878 

@lzgabel Since I receive a notification about this pull request every moring, I'm now requesting the changes explicitly. This should stop the notification from pinging me every day. Sorry for the noise.

2023-06-06 09:56 UTC, lzgabel commented
> Since I receive a notification about this pull request every moring, I'm now requesting the changes explicitly. This should stop the notification from pinging me every day. 

@korthout Sorry about that. :bow:
I'll convert it to a draft and adjust it next week.

2023-07-01 15:36 UTC, lzgabel commented
Hi @korthout. Please take a moment to review this feature when you have time. 🙇

2023-07-03 09:35 UTC, korthout commented
Thanks @lzgabel. I'll do my best to review it ASAP, but I have some other priorities. I'll find time for it in the next few days. And as always, thanks for the awesome contribution ❤️

2023-07-06 14:19 UTC, korthout requested changes
Thanks @lzgabel 👏 

It looks great! I just have one request.

Please have a look 🙇

2023-07-06 14:19 UTC, korthout commented on bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/MessageValidator.java
> +                    && ((MessageEventDefinition) e).getMessage() == element);
💭 Not sure if this is actually better, but here's an alternative:

```java
.filter(MessageEventDefinition.class::isInstance)
.map(MessageEventDefinition.class::cast)
.anyMatch(e -> e.getMessage() == element);
```

And another 🤔 Maybe I like this one better

```java
.filter(MessageEventDefinition.class::isInstance)
.anyMatch(e -> ((MessageEventDefinition) e).getMessage() == element);
```

Feel free to ignore this

2023-07-07 11:44 UTC, lzgabel commented
Hi @korthout. Please check again.  I'll squash all commits when you're done checking this out. 🙇

2023-07-07 15:00 UTC, korthout approved these changes
Thanks @lzgabel ❤️ 

LGTM 👍

2023-07-07 16:35 UTC, lzgabel commented
Hi @korthout. I've squashed all commits. Please check this out. :heart:

2023-07-07 16:51 UTC, korthout approved these changes
Thanks again @lzgabel ✉️ 

LGTM 👍 

bors merge

2023-07-07 17:01 UTC, merged