Added abstract (undefined) tasks to process generator
camunda/camunda pull request #13236
Opened 2023-06-29 11:14 UTC by qfcgc

## Description

In this PR, the process generator is extended, so now it generates undefined (abstract) tasks as well.

## Related issues

closes https://github.com/camunda/zeebe/issues/11319

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-06-29 11:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/zeebe?pullRequest=13236) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/zeebe?pullRequest=13236) before we can accept your contribution.<br/><hr/>**vdenisov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/zeebe?pullRequest=13236) it.</sub>

2023-07-03 11:27 UTC, berkaycanbc commented
Hey @qfcgc, thanks for the contribution! I will take a look in my first availability. 👍

2023-07-14 13:21 UTC, berkaycanbc requested changes
Good job! 🚀 I asked for one change to make changes aligned with the current implementation of other components.

2023-07-14 13:21 UTC, berkaycanbc commented on test-util/src/main/java/io/camunda/zeebe/test/util/bpmn/random/blocks/AbstractBlockBuilder.java
> +    return nodeBuilder.manualTask(elementId).name(elementId);
❌ Let's keep this in `ManualTaskBlockBuilder` class and create a new method in `AbstractFlowNodeBuilder`. Afterwards, we can call it here as `nodeBuilder.abstractTask(elementId).name(elementId);`. This way, the implementation will be aligned with other elements as well.

2023-09-01 10:09 UTC, abbasadel commented
Hey @qfcgc, thanks again for the contribution. I just wanted to make sure that you got the chance to check the review from @berkaycanbc.

2023-10-26 11:47 UTC, berkaycanbc commented
Since we did not get an update on this issue for a long time, I am closing this PR and moving the issue back to our backlog.

@qfcgc Please reopen the PR if you think you can further contribute on that based on the feedback.

Cc: @abbasadel

2023-10-26 11:47 UTC, closed without merging