Resolve regression for large payloads deploy
camunda/camunda pull request #13505
Opened 2023-07-17 08:49 UTC by nicpuppa

## Description

Removed resource from `Deployment:CREATED` event. Resource is still available in `Process:CREATED` or `DecisionRequirements:CREATED`

## Related issues

closes #13233 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-07-19 12:18 UTC, korthout requested changes
Nice work @nicpuppa 👏 

👍 I like your approach to removing the resources!

👍 Nice work on improving the test cases

💭 Seems that there were more changes involved than we originally estimated for it. Especially getting the tests right was harder than expected

❌ I have two change requests. Please have a look below

2023-07-19 12:18 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java
> +   * @param deploymentEvent the record to clone and modify
>and modify

🔧 This reads as if the parameter may be modified as well, but only the copy is modified

2023-07-20 07:09 UTC, nicpuppa commented on engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java
> +        key, DeploymentIntent.CREATED, recordWithoutResource, command);
Seems the response is [builded](https://github.com/camunda/zeebe/blob/e7965416755a1fac14129b60889f6d22d260fd19/gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java#L81-L90) with metadata information and not with information from resources. This is why the test do not fail. What we want to do ?

2023-07-20 07:41 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java
> +        key, DeploymentIntent.CREATED, recordWithoutResource, command);
Ah great. If it does not break user space there's no need to make further changes. Thanks for looking into it 👍

2023-07-20 08:19 UTC, nicpuppa commented on engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentTest.java
> -            Bpmn.convertToString(process).getBytes(), Bpmn.convertToString(process2).getBytes());
Thank you for spotting it

2023-07-20 08:30 UTC, korthout approved these changes
Thanks for applying the requested changes @nicpuppa 💯 

👍 LGTM

💭 As this fixes a regression that is only present on `main` there's no need to backport it to other branches

bors merge

2023-07-20 08:39 UTC, merged