Distribute broadcasted signal to other partitions
camunda/camunda pull request #13709
Opened 2023-07-30 03:22 UTC by lzgabel

## Description
Distribute broadcasted signal to other partitions.

## Related issues

closes #13242

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-07-31 04:22 UTC, lzgabel commented
Hi @korthout. Please take a moment to review this feature. Thanks! :heart:

2023-08-01 08:16 UTC, korthout commented
Hi @lzgabel 🚀 Thanks for your contribution. 

@abbasadel and @nicpuppa indicated to me that they would like to review this 👏

2023-08-01 13:17 UTC, nicpuppa commented on engine/src/main/java/io/camunda/zeebe/engine/processing/signal/SignalBroadcastProcessor.java
> +    activateInstance(command);
❌ There is no need to activate an instance in a `distributedCommand`. You can see the discussion in the signal logic overview [here](https://github.com/camunda/zeebe/issues/10777)

2023-08-01 14:57 UTC, nicpuppa requested changes
Awesome work @lzgabel 👏🎉 Thank you for your contribution!

❌ I have a change requests and some suggestions. Please have a look.

2023-08-01 15:08 UTC, lzgabel commented on engine/src/main/java/io/camunda/zeebe/engine/processing/signal/SignalBroadcastProcessor.java
> +    activateInstance(command);
> reuse [the current logic](https://github.com/camunda/zeebe/blob/af7abd158ff459127d236f7785ea9e7f1e86a58c/engine/src/main/java/io/camunda/zeebe/engine/processing/signal/SignalBroadcastProcessor.java#L62-L78) for both [new commands](https://github.com/camunda/zeebe/blob/af7abd158ff459127d236f7785ea9e7f1e86a58c/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/DistributedTypedRecordProcessor.java#L42) as well as [distributed commands](https://github.com/camunda/zeebe/blob/af7abd158ff459127d236f7785ea9e7f1e86a58c/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/DistributedTypedRecordProcessor.java#L49)

❓  @korthout . I'm not sure if I understand something wrong, do you have time to take a look?

2023-08-01 15:16 UTC, lzgabel commented on engine/src/test/java/io/camunda/zeebe/engine/processing/signal/BroadcastSignalMultiplePartitionsTest.java
> +            .limit(2)
The purpose of the truncated stream is to speed up tests.

2023-08-01 15:30 UTC, lzgabel commented on engine/src/main/java/io/camunda/zeebe/engine/processing/signal/SignalBroadcastProcessor.java
> +    activateInstance(command);
> responseWriter.writeEventOnCommand(eventKey, SignalIntent.BROADCASTED, signalRecord, command);

❓ @korthout Why do we need to reuse this line for distributed commands?  I understand that `responseWriter` is to write a response to the client? When reusing this logic to distribute commands, won't multiple responses be written?

2023-08-01 16:02 UTC, lzgabel commented
Hi @nicpuppa.  Please check again. I'll squash all commits when you're done checking this out. 🙇

2023-08-02 07:02 UTC, nicpuppa approved these changes
Thank you @lzgabel for applying my suggestion 🚀 

LGTM 👍 

There is still an open point, please @korthout have a look, then we can merge this PR 🥳

2023-08-02 09:23 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/processing/signal/SignalBroadcastProcessor.java
> +    activateInstance(command);
Another mistake of mine, sorry about that 🙇 You're both right. No need to respond to the distributed commmand.

2023-08-02 09:44 UTC, nicpuppa commented
Nice job @lzgabel 

bors merge

2023-08-02 09:46 UTC, lzgabel commented
> Nice job @lzgabel
> 
> bors merge

@nicpuppa Please cancel this bors job, I need to rebase all commits. :heart:

2023-08-02 09:49 UTC, nicpuppa commented
bors cancel

2023-08-02 10:03 UTC, lzgabel commented
Hi @nicpuppa.  I've squashed all commits. Please check this out. ❤️

2023-08-02 12:01 UTC, nicpuppa approved these changes
LGTM 🚀 

bors merge

2023-08-02 12:12 UTC, merged