Extend process version management
camunda/camunda pull request #13721
Opened 2023-07-31 13:41 UTC by remcowesterhoud

## Description

The current way of managing versions of process management is pretty limited. We only store a single version for each process id, which is the latest one.

For resource deletion we need more information than this. We don't want to reuse versions, so for one we must always keep track of the highest version for a process id.
Additionally we must make sure that if we delete the latest version a process, the previous undeleted version becomes the new lated. Because of this we need to keep track of a list of all undeleted process versions.

This PR makes this change. It changes the object we store in the state to contain more data and does some refactoring to try and make the difference between versions more clear.

## Related issues

closes #13588 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-08-05 10:27 UTC, remcowesterhoud commented
@korthout I tried splitting it, but I don't see a way to do it. The migration needs the changes and the changes without migration breaks tests.

In did split it up in a lot of small (hopefully understandable) commits. It still turned out to be a relatively large PR. Let me know if you want to review face-to-face.

2023-08-08 10:11 UTC, korthout requested changes
👏 Well written commits @remcowesterhoud 

💭 I only struggled a bit with 50981ae94f9694c75214011a3dc04d7e75bf7e45 which seemed to do something different than described. But luckily that problem seemed to have been resolved in 14ae8c5c495e9abdc4c1d97c59d37b47b88b4bd1.

🔧 I have a few suggestions which may be worthwhile to try

❌ I've also added a change request that if left unchanged could easily lead to bugs in the future.

Please have a look 🙇

2023-08-08 10:11 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/state/deployment/ProcessVersionManager.java
🔧 I think we can improve the readability of this class by changing the method ordering.

We could move the `getVersionInfo` method to the top. It's used by practically all other methods in this class. So it's useful for readers to understand this first before looking at any of the other methods.

Next most important are the state-changing methods `addProcessVersion`, `deleteProcessVersion`, and `clear`. 

All the other methods are simply getting some state.

2023-08-08 14:08 UTC, remcowesterhoud commented on engine/src/main/java/io/camunda/zeebe/engine/state/deployment/NextValue.java
> +    }
👍 I was hoping there was a `SetProperty` but alas. I will change it so when adding a version it will check if it exists first.

2023-08-08 14:10 UTC, remcowesterhoud commented on engine/src/main/java/io/camunda/zeebe/engine/state/deployment/ProcessVersionInfo.java
> +    setHighestVersion(version);
> Alternatively, we could move the if statement into the addKnownVersion method (my preference)

I see what you mean, but this is not my preference. This method is exposed and by doing it in this method it's safe for potential mistakes in the future. I will rename to `setHighestVersionIfHigher` instead.

2023-08-08 14:15 UTC, remcowesterhoud commented
Thanks for the review @korthout 🙇 I've addressed your comments.

2023-08-08 16:39 UTC, korthout approved these changes
LGTM 👍

2023-08-08 16:45 UTC, remcowesterhoud commented
Bors merge

2023-08-08 16:57 UTC, merged