Independent partition startup
camunda/camunda pull request #13819
Opened 2023-08-07 12:52 UTC by oleschoenburg

closes #5209

2023-08-08 13:22 UTC, oleschoenburg commented on broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java
> +        .onComplete(
:thought_balloon: Now we are getting a warning every time :roll_eyes: 

`No executor provided for ActorFuture#onComplete callback`

2023-08-09 12:13 UTC, deepthidevaki requested changes
Thanks @oleschoenburg. Just have one thing to fix. Otherwise changes looks good.

2023-08-09 12:13 UTC, deepthidevaki commented on broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java
> +                partitionStart
Having said that, we should have some way to catch this. Currently it just logs and continue. I'm not sure if health check catches this install fails for a valid partition.

2023-08-09 15:05 UTC, oleschoenburg commented on broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java
> +                partitionStart
Ouch, yeah I completely missed that :+1: I'll see if we can make this more visible.

2023-08-09 15:23 UTC, oleschoenburg commented on broker/src/main/java/io/camunda/zeebe/broker/transport/adminapi/AdminApiRequestHandler.java
> +    transport.subscribe(raftPartition.id().id(), RequestType.ADMIN, this);
Nice catch. I guess we didn't need it before because the broker would shut down anyway.

2023-08-14 13:02 UTC, oleschoenburg commented
@deepthidevaki I've updated the description with changes to the probes.

The readiness probe is interesting because until we report as ready, the broker will not be part of the k8s service. I'm wondering if this is problematic for embedded gateways where we do want to accept traffic even when not all partitions are started yet.
For normal brokers without an embedded gateway we also want to accept traffic (we actually have to, otherwise partitions would never install) but I guess we don't have to care about the readiness probe because brokers are not accessed through a service.

2023-08-15 07:22 UTC, deepthidevaki approved these changes
:rocket: Thanks. LGTM.

2023-08-15 07:35 UTC, oleschoenburg commented
:tada: 

bors merge

2023-08-15 07:46 UTC, oleschoenburg commented
bors retry

2023-08-15 07:58 UTC, merged