Migrate last remaining state to RocksDB
camunda/camunda pull request #1389
Opened 2018-09-26 13:07 UTC by Zelldon

* migrated the old ElementInstanceIndex to RocksDB
 * ElementInstance and IndexedRocks remains, the structure changed a bit
 * Three column families to store the instances
   * One to map the key to an instance
   * One to map the parent-child identifier to the instance (to find childs and parent nodes)
   * One to store records which are used later
 * Access to ElementInstances are cached, this means #getInstance
   will return every time the same object until flush is called

 * since the migration to rocks db is done with this PR recovery is now working again
 * fixed column family problem - they need to be defined on rocksDB opening

closes #1355
closes #1219
closes #1188

2018-09-27 12:20 UTC, ThorbenLindhauer requested changes

2018-09-27 13:40 UTC, Zelldon commented
@ThorbenLindhauer please take a look into the latest changes. I also did a bit of refactoring, for example  I saw that the PersistenceHelper can be used elsewhere.

2018-09-27 13:46 UTC, Zelldon commented on broker-core/src/main/java/io/zeebe/broker/workflow/state/WorkflowState.java
> +  }
Sorry still need to do this

2018-09-27 15:42 UTC, ThorbenLindhauer commented
Building this branch (with and without my last commit) produces quite a lot of failing test cases on my machine: https://gist.github.com/ThorbenLindhauer/915294b921513ad32edf02fd3322349b

2018-09-27 15:43 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/workflow/state/WorkflowState.java
> +  }
done, see https://github.com/zeebe-io/zeebe/pull/1389/commits/c14ce63be110396431b5aa1437d858ef94176526

2018-09-27 15:46 UTC, Zelldon commented
Yes will fix the broken tests tomorrow thanks for the changes !

2018-09-28 05:59 UTC, Zelldon commented
@ThorbenLindhauer Ok tests are running again :)  Please approve if everything is ok

2018-09-28 07:53 UTC, ThorbenLindhauer approved these changes

2018-09-28 08:21 UTC, Zelldon commented
bors r=ThorbenLindhauer

2018-09-28 08:30 UTC, merged