feat(engine): save form to the state
camunda/camunda pull request #14161
Opened 2023-09-05 13:40 UTC by berkaycanbc

This PR includes:

* Form DB classes
* Form column family definitions
* A method to store the Form
* A method to retrieve the latest form by form id
* A method to retrieve a Form by key
* Tests for implemented repository methods

## Description

## Related issues

closes #14133 
closes #14137 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-09-05 15:35 UTC, nicpuppa approved these changes
LGTM 🚀

2023-09-05 15:47 UTC, nicpuppa requested changes

2023-09-05 15:47 UTC, nicpuppa commented on protocol/src/main/java/io/camunda/zeebe/protocol/record/value/deployment/Form.java
> +@ImmutableProtocol(builder = ImmutableProcess.Builder.class)
❌ I give a look at the failed test and the error is pretty clear

```suggestion
@ImmutableProtocol(builder = ImmutableForm.Builder.class)
```

2023-09-06 09:45 UTC, nicpuppa approved these changes
LGTM 💪

2023-09-06 10:46 UTC, berkaycanbc commented
bors merge

2023-09-06 11:17 UTC, merged