Bind forms by formId
camunda/camunda pull request #14177
Opened 2023-09-06 10:11 UTC by nicpuppa

## Description

This PR allows forms to be linked to `User Task` and `Start Event` by `formId`

## Related issues

closes #14135 
closes #14134 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-09-06 13:33 UTC, berkaycanbc requested changes
Good one! 🚀 I asked for minor changes only.

🔧 Since the PR mentions that it closes #14135, let's make sure we include start event changes to this PR as well. Also, we can remove the closes mention and implement it in a separate PR.

2023-09-06 13:51 UTC, nicpuppa commented on bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/validation/ZeebeUserTaskValidationTest.java
> +            expect(
Good suggestion 💪

2023-09-07 07:25 UTC, berkaycanbc approved these changes
LGTM! 👍

2023-09-07 07:56 UTC, nicpuppa commented
bors merge

2023-09-07 08:08 UTC, merged