Allow configuration of job streaming via env variables and client properties
camunda/camunda pull request #14185
Opened 2023-09-06 12:55 UTC by rodrigo-lourenco-lopes

## Description

Allow configuration of job streaming via env variables and client properties.
The Environment variable should override the client properties if `applyEnvironmentVariableOverrides` is true.
## Related issues

closes https://github.com/camunda/zeebe/issues/14152

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-09-13 09:16 UTC, npepinpe requested changes

2023-09-13 09:16 UTC, npepinpe commented on clients/java/src/main/java/io/camunda/zeebe/client/ZeebeClientBuilder.java
> +  ZeebeClientBuilder streamEnabled(boolean streamEnabled);
:x: Let's make it clear this is a default and will be overridden by the worker specific setting, by calling it defaultJobWorkerStreamEnabled :+1:

2023-09-13 09:16 UTC, npepinpe commented on clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientBuilderImpl.java
> +      "ZEEBE_CLIENT_WORKER_STREAM_ENABLE";
:x: Same as with the property, keep it aligned, so ENABLED instead of ENABLE.

2023-09-20 08:50 UTC, npepinpe approved these changes
:+1:

2023-09-20 15:46 UTC, rodrigo-lourenco-lopes commented
bors merge

2023-09-20 15:58 UTC, merged