Activate Jobs using Java gRPC client
camunda/camunda pull request #1431
Opened 2018-10-05 14:15 UTC by menski

- adds new ActivateJobs gRPC method
- adds newActivateJobsCommand to JobClient to create new command
- gateway will request jobs from all partitions in round robin fashion

closes #1426

2018-10-08 06:39 UTC, npepinpe commented on clients/java/src/main/java/io/zeebe/client/api/commands/ActivateJobsCommandStep1.java
> +     * <p>This name is used to identify the worker to which a job is exclusively assigned to.
Jobs aren't exclusively assigned to a worker though; it's just harder to figure out which jobs are activated at a time. I mean, it's an extremely minor point, I'm just wondering if we ever plan on clarifying these things to users.

2018-10-08 08:00 UTC, npepinpe requested changes
Looks good in general.

One thing missing is gateway-broker tests (or at least more complete IT tests), and the retries property for the ActivateJobs request. We used to set retries on subscriptions, but I didn't see where this is done now. Wouldn't it make sense on the request?

2018-10-09 12:09 UTC, menski commented
@npepinpe should be ready for review again. Please see the commits from bfc2dea onwords. I will squash all the commits in the actual feature commit after review.

2018-10-09 17:19 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: d6e6565beada67d6462dbc9687d8af5e5f454399
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-10-10 08:29 UTC, npepinpe approved these changes
Looks good, I'll let you rewrite the history and merge.

2018-10-10 08:56 UTC, menski commented
bors r+

2018-10-10 09:27 UTC, menski commented
bors retry

2018-10-10 09:35 UTC, merged