Support multi-tenancy for process instance creation in the engine
camunda/camunda pull request #14334
Opened 2023-09-15 14:34 UTC by koevskinikola

## Description

Support multi-tenancy for process instance creation in the engine.

## Related issues

closes #13279 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-09-15 14:37 UTC, koevskinikola commented
@remcowesterhoud commits f96602f6f7c2ce3db60c65a899e94a7daa526f0e and 8dc635e49842a42302d2ece0e06c5bb327c97bd5 forward the `tenantId` to the `VariableBehavior` class so that it's ready to be used when we start #13388.

2023-09-18 08:02 UTC, remcowesterhoud commented
@koevskinikola Fyi, there's some failing test cases. I'll review it anyway but wanted to notify you early.

2023-09-18 08:34 UTC, remcowesterhoud requested changes
Nice work @koevskinikola! You've missed to declare 1 property and there's some failing tests. Otherwise it LGTM!

2023-09-18 08:34 UTC, remcowesterhoud commented on engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java
> +            .getProcessByKeyAndTenant(timer.getProcessDefinitionKey(), timer.getTenantId())
👍 Good catch

2023-09-18 08:34 UTC, remcowesterhoud commented on engine/src/main/java/io/camunda/zeebe/engine/state/instance/TimerInstance.java
> +  private final StringProperty tenantIdProp =
❌ You forgot to declare the property in the constructor

2023-09-18 08:34 UTC, remcowesterhoud commented on engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/CreateProcessInstanceProcessor.java
> +      "Expected to find process definition with process ID '%s',  tenant ID '%s', and version '%d', but none found";
🙃 you put two whitespaces in the message

2023-09-18 10:31 UTC, koevskinikola commented
@remcowesterhoud I implemented your feedback, and the CI is passing now.

2023-09-18 12:54 UTC, remcowesterhoud approved these changes
Awesome, thanks! 🚀 

bors merge

2023-09-18 13:06 UTC, merged