Add multi-tenancy support for signals in the engine
camunda/camunda pull request #14842
Opened 2023-10-24 12:36 UTC by koevskinikola

## Description

Add multi-tenancy support for signals in the engine

## Related issues

closes #13336 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-11-02 09:04 UTC, remcowesterhoud requested changes
Thanks @koevskinikola! 🚀 

I have quite a few comments, mostly regarding some issues in the state and migration. Please have a look at those and let me know if you have questions.

2023-11-02 16:10 UTC, koevskinikola commented on engine/src/main/java/io/camunda/zeebe/engine/state/signal/DbSignalSubscriptionState.java
> +          // the signalName and tenantIdKey are wrapped on look-up in the background
Sure, it definitely makes things more readable.

2023-11-02 16:49 UTC, koevskinikola commented
@remcowesterhoud thanks for all the review feedback. I've implemented all of it. Have a look when you have the time.

2023-11-03 09:54 UTC, remcowesterhoud approved these changes
LGTM! 

bors merge

2023-11-03 10:10 UTC, koevskinikola commented
bors retry

2023-11-03 10:32 UTC, merged