feat(documentation): parallel gateway
camunda/camunda pull request #1496
Opened 2018-10-11 13:49 UTC by ThorbenLindhauer

closes #1444

2018-10-12 07:29 UTC, saig0 requested changes

2018-10-12 07:29 UTC, saig0 commented on docs/src/bpmn-workflows/gateways.md
> +A parallel gateway is only activated, when each of its incoming sequence flows has been signalled. Once activated, it signals all of its outgoing sequence flows.
Can you describe more in detail how a parallel gateways works? How is the fork working? What happens to the payload?

Also, I think it's a bit confusing when you talk about that a sequence flow is signaled.

2018-10-15 11:45 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 02043168d81ae7743795d2464d898d75780b4424
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci, build**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-10-15 11:46 UTC, ThorbenLindhauer commented
@saig0 I expanded the explanation.

2018-10-15 11:48 UTC, saig0 approved these changes

2018-10-15 12:34 UTC, ThorbenLindhauer commented
bors r+

2018-10-15 12:46 UTC, merged