Respond to `MIGRATE` command with `MIGRATED` event
camunda/camunda pull request #15215
Opened 2023-11-15 12:40 UTC by korthout

## Description

> **Warning**
> This PR is based on #15164. We should merge that first.

Adds a new `ProcessInstanceMigrationProcessor` that processes the new `ProcessInstanceMigration:MIGRATE` command, by:
- appending the `MIGRATED` event
- responding the `MIGRATED` event

This pull request also builds up the necessary testing infrastructure and boyscouts a small naming improvement.

## Related issues

closes #15106

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-11-16 14:48 UTC, berkaycanbc requested changes
Clean one, thanks @korthout! ⭐ 

I asked two questions for clarification and added a suggestion. 👍

2023-11-16 16:16 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java
> +public final class ProcessInstanceModificationModifyProcessor
Good question. @remcowesterhoud's last contribution was [to bring more consistency to the processors](https://github.com/camunda/zeebe/pull/15078). They now follow the schema: `<ValueType><Intent>Processor`.

One reason we wanted this, is to make it easier to find classes in your IDE. If you're interested in command processors for Job records then type `JobProcessor` and you'll find them all in alphabetical order. The `ProcessInstanceModification` and `ProcessInstanceMigration` value types both only have one command processor right now, but it doesn't really matter. Consistency makes it easy to find and understand this code in relation to other code.

2023-11-16 16:16 UTC, korthout commented on engine/src/test/java/io/camunda/zeebe/engine/util/client/ProcessInstanceClient.java
> +    public ProcessInstanceMigrationClient withMappingInstruction(
Sounds good 👍

2023-11-16 16:38 UTC, korthout commented
@berkaycanbc Please have another look 🙇

2023-11-17 09:11 UTC, berkaycanbc commented on engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java
> +public final class ProcessInstanceModificationModifyProcessor
Right! I was thinking this will be implemented later but already there. Makes sense! 👍

2023-11-17 09:13 UTC, berkaycanbc approved these changes
LGTM! 🚀 @korthout

2023-11-17 09:41 UTC, korthout commented
bors merge

2023-11-17 10:26 UTC, korthout commented
Self-hosted runner disconnected

bors retry

2023-11-17 12:34 UTC, korthout commented
> Container startup failed for image bitnami/keycloak:22.0.1

bors merge

2023-11-17 12:47 UTC, korthout commented
Wow, another known flaky test...

bors merge

2023-11-17 13:04 UTC, merged