Apply `ProcessInstance:ELEMENT_MIGRATED` events
camunda/camunda pull request #15217
Opened 2023-11-15 15:45 UTC by korthout

## Description

> [!WARNING]  
> This PR is based on https://github.com/camunda/zeebe/pull/15215. We should merge that first.

Adds an event applier for the `ELEMENT_MIGRATED` intent of the `ProcessInstance` records.

## Related issues

closes #15110

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-11-20 16:18 UTC, korthout commented
@berkaycanbc while working on a next issue, I discovered I had forgotten to adjust the reference between the process instance and the process definition tracked by the `processInstanceKeyByProcessDefinitionKeyColumnFamily`. I've added commits for this.

I don't expect other changes on this PR so it's still ready for review.

2023-11-21 12:16 UTC, berkaycanbc requested changes
Clean one @korthout! 🚀 I only added a minor suggestion.

**At the same time, I have questions related to possibly affected appliers:**
1) In [TimerCreatedApplier.applyState](https://github.com/camunda/zeebe/blob/5be1d12c14d580a0ae3fe66bba939cd7fdb0087b/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/TimerCreatedApplier.java#L26), we store both processDefinitionKey and processInstanceKey. Do we need to change anything for that part? I assume, it is not required at this point because we will not allow migration process instances with boundary events and event subprocesses.
2) We have a similar behaviour in [DbEventScopeInstanceState.triggerStartEvent](https://github.com/camunda/zeebe/blob/5be1d12c14d580a0ae3fe66bba939cd7fdb0087b/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbEventScopeInstanceState.java#L127) as above. I again assume, this is not an issue at the moment.

2023-11-21 12:16 UTC, berkaycanbc commented on engine/src/main/java/io/camunda/zeebe/engine/state/appliers/ProcessInstanceElementMigratedApplier.java
> +    if (value.getBpmnElementType() == BpmnElementType.PROCESS) {
👍 Good catch!

2023-11-21 15:30 UTC, korthout commented
🙇 Thanks @berkaycanbc, I've made the requested. Please have another look.

Regarding your questions:
1. We'll encounter this in the issue `Migrate timer event subscriptions` (currently) in the `Later` section of the breakdown. Until then, no timer subscriptions can be active in the process instance that is under migration. After migration, any timer event subscription will automatically be created using the new process definition. So there are no changes needed now.
2. The same is true for Event Triggers. These are typically created when an event triggers that is going to affect the process instance. Again, that cannot be the case in our initial iteration, as events are completely out of scope.

2023-11-21 16:44 UTC, berkaycanbc approved these changes
LGTM! 🚀

2023-11-21 17:00 UTC, korthout commented
bors merge

2023-11-22 08:16 UTC, korthout commented
>The self-hosted runner: [redacted] lost communication with the server

bors retry

2023-11-22 08:31 UTC, merged