chore(broker): simplify workflow instance command handling
camunda/camunda pull request #1529
Opened 2018-10-17 12:47 UTC by ThorbenLindhauer

- removes record processors for workflow instance CREATED and REJECTED
- introduces command handler interface that provides common context

closes #1229, #1411

2018-10-22 07:00 UTC, ChrisKujawa requested changes

2018-10-22 07:04 UTC, ChrisKujawa requested changes
Looks good, please make some changes on the commented lines.

2018-10-22 07:05 UTC, ChrisKujawa requested changes
Looks good, please make some changes on the commented lines.

2018-10-22 07:19 UTC, ChrisKujawa requested changes
Looks good, please make some changes on the commented lines.

2018-10-22 14:09 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/WorkflowInstanceStreamProcessor.java
> +        environment.newStreamProcessor().keyGenerator(keyGenerator).withListener(engineState);
I think it is still required, because that's how the stream writer is handed the key generator.

2018-10-22 14:11 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/instance/CancelWorkflowInstanceHandler.java
> +
This is now done transparently via `EventOutput#writeFollowUpEvent` => `WorkflowEngineState#onEventProduced`.

2018-10-22 14:11 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/workflow/state/WorkflowEngineState.java
> +
Re first comment: I will apply some extract method refactoring.

2018-10-22 14:12 UTC, ThorbenLindhauer commented on broker-core/src/main/java/io/zeebe/broker/workflow/state/WorkflowEngineState.java
> +
Re first comment: I will apply some extract method refactoring.

2018-10-23 06:05 UTC, ChrisKujawa approved these changes
bors r+

2018-10-23 06:06 UTC, Zelldon commented
bors r-

2018-10-23 06:11 UTC, Zelldon commented
bors retry

2018-10-23 06:14 UTC, Zelldon commented
bors r+

2018-10-23 06:29 UTC, Zelldon commented
bors retry

2018-10-23 06:41 UTC, merged