Rename 'activity' to 'element' in all records
camunda/camunda pull request #1536
Opened 2018-10-22 14:02 UTC by ThorbenLindhauer

- workflow instance record
- incident record
- job headers
- message subscription
- workflow subscription

closes #1528

2018-10-22 15:41 UTC, menski commented
The elasticsearch exporter mappings have to be adjusted to the changes, see https://github.com/zeebe-io/zeebe/tree/1528-element-id/exporters/elasticsearch-exporter/src/main/resources

2018-10-23 16:06 UTC, menski commented
Reminder we have to regenerate the Go gRPC stub and mocks as this is not done automatically. See for instructions:
- https://github.com/zeebe-io/zeebe/blob/develop/gateway-protocol/README.md
- https://github.com/zeebe-io/zeebe/blob/develop/clients/go/README.md

In case you need help or want me to do it just ping me

2018-10-24 07:50 UTC, saig0 requested changes

2018-10-24 07:50 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/job/JobCompletedEventProcessor.java
> +    final long activityInstanceKey = jobHeaders.getElementInstanceKey();
```suggestion
    final long elementInstanceKey = jobHeaders.getElementInstanceKey();
```

2018-10-24 07:50 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/job/JobCreatedProcessor.java
> +    final long activityInstanceKey = jobHeaders.getElementInstanceKey();
```suggestion
    final long elementInstanceKey = jobHeaders.getElementInstanceKey();
```

2018-10-24 07:50 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/servicetask/TerminateServiceTaskHandler.java
> +          .setElementId(activityInstanceEvent.getElementId())
```suggestion
          .setElementId(elementInstanceEvent.getElementId())
```

2018-10-24 07:50 UTC, saig0 commented on clients/java/src/main/java/io/zeebe/client/api/response/JobHeaders.java
>    /** @return id of the activity */
```suggestion
  /** @return id of the element */
```

2018-10-24 07:50 UTC, saig0 commented on clients/java/src/main/java/io/zeebe/client/api/response/JobHeaders.java
>    /** @return key of the activity instance */
```suggestion
  /** @return key of the element instance */
```

2018-10-24 07:50 UTC, saig0 commented on gateway/src/main/java/io/zeebe/gateway/api/record/IncidentRecord.java
>     * @return the id of the activity this incident belongs to. Can be <code>null</code> if the
```suggestion
   * @return the id of the element this incident belongs to. Can be <code>null</code> if the
```

2018-10-24 07:50 UTC, saig0 commented on gateway/src/main/java/io/zeebe/gateway/api/record/IncidentRecord.java
>     * @return the key of the activity instance this incident belongs to. Can be <code>null</code> if
```suggestion
   * @return the key of the element instance this incident belongs to. Can be <code>null</code> if
```

2018-10-24 07:50 UTC, saig0 commented on gateway/src/main/java/io/zeebe/gateway/api/record/WorkflowInstanceRecord.java
>     * @return the id of the current activity, or empty if the event does not belong to an activity.
```suggestion
   * @return the id of the current element, or empty if the event does not belong to an activity.
```

2018-10-24 07:50 UTC, saig0 commented on gateway/src/main/java/io/zeebe/gateway/impl/command/IncidentCommandImpl.java
>      builder.append(", activityId=");
```suggestion
    builder.append(", elementId=");
```

2018-10-24 07:50 UTC, saig0 commented on gateway/src/main/java/io/zeebe/gateway/impl/command/WorkflowInstanceCommandImpl.java
>      builder.append(", activityId=");
```suggestion
    builder.append(", elementId=");
```

2018-10-24 07:50 UTC, saig0 commented on gateway/src/main/java/io/zeebe/gateway/impl/event/IncidentEventImpl.java
>      builder.append(", activityId=");
```suggestion
    builder.append(", elementId=");
```

2018-10-24 07:50 UTC, saig0 commented on gateway/src/main/java/io/zeebe/gateway/impl/event/WorkflowInstanceEventImpl.java
>      builder.append(", activityId=");
```suggestion
    builder.append(", elementId=");
```

2018-10-24 12:05 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 5833cebad35ae1691e29dffc5cd7991f4cdac7fa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-10-29 14:45 UTC, ThorbenLindhauer commented
@saig0

I have made the following changes:

- updated the locations that you marked
- re-generated the go client and adapted where necessary
- updated the debug http exporter (was @menski actually :)

2018-10-30 09:25 UTC, saig0 approved these changes

2018-10-30 13:39 UTC, ThorbenLindhauer commented
bors r+

2018-10-30 13:47 UTC, merged