Introduce new CompensationSubscription record
camunda/camunda pull request #15392
Opened 2023-11-28 17:03 UTC by nicpuppa

## Description

With this PR a new record CompensationSubscription is added into the protocol

## Related issues

closes #15063 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-11-30 13:06 UTC, saig0 requested changes
@nicpuppa nice work. :tada: 

I have one minor comment about the record property names. They don't align well with existing property names, for example, in `ProcessInstanceRecordValue`, `ProcessEventRecordValue`, and `SignalSubscriptionRecordValue`.

But finding names is difficult. I made some suggestions. Please have a look if you agree. :cookie:

2023-11-30 14:33 UTC, nicpuppa commented
Thanks @saig0 for the review, naming is always hard 🤣 Please have another look 👀

2023-12-01 05:31 UTC, saig0 approved these changes
@nicpuppa LGTM. :tada:

2023-12-01 05:31 UTC, saig0 commented on protocol/src/main/java/io/camunda/zeebe/protocol/record/value/CompensationSubscriptionRecordValue.java
> +   */
:wrench: Correct JavaDoc.

```suggestion
  /**
   * @return the element id of the activity with the compensation handler
   */
```

2023-12-01 05:31 UTC, saig0 commented on protocol/src/main/java/io/camunda/zeebe/protocol/record/value/CompensationSubscriptionRecordValue.java
> +   */
:wrench: Correct JavaDoc.

```suggestion
  /**
   * @return the element id of the flow scope that contains the activity with the compensation handler
   */
```

2023-12-01 06:06 UTC, merged