Reject unsupported migration
camunda/camunda pull request #15408
Opened 2023-11-29 09:51 UTC by korthout

## Description

Rejects the migration command when the process instance has an active element that is currently unsupported.

At this time, only `PROCESS` and `SERVICE_TASK` elements are supported. Active elements of any other type result in a rejected migration.

> [!NOTE]
> While working on this, I wanted to reject all unsupported scenarios rather than just all unsupported elements. So I also tried to work on #15405 and #15406. However, those issues contain a lot of hidden complexity. For now, I've scoped these out of this pull request's related issue. We may want to consider implementing #15407 instead of the extracted issues.

## Related issues

closes #15123

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-11-29 15:40 UTC, berkaycanbc commented on engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceModificationModifyProcessor.java
> +      EnumSet.complementOf(UNSUPPORTED_ELEMENT_TYPES);
Nice one! 🚀

2023-11-29 16:06 UTC, berkaycanbc commented on engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java
> +      tryMigrateElementInstance(elementInstance, processDefinition, mappedElementIds);
Really good one! 🚀

2023-11-29 16:42 UTC, berkaycanbc requested changes
Nice work @korthout! 🚀 

1️⃣ I asked for one change only.

👍 I agree with using exceptions. It conforms better with how our code handles expected errors. Also, I expect users not to send migration commands over an over again since we will present them a meaningful message why migration failed.

❓I didn't see a test case for `EVENT_BASED_GATEWAY`. Is it intentional? I think, a process might be waiting on active event based gateway, so would be good to test against.

❓What about the case where process definitions look like:

```java
 Bpmn.createExecutableProcess(SOURCE_PROCESS)
                     .startEvent()
                     .userTask("A")
                     .endEvent()
                     .done()
Bpmn.createExecutableProcess(TARGET_PROCESS)
                     .startEvent()
                     .subProcess(
                         "sub",
                         s ->
                             s.embeddedSubProcess()
                                 .startEvent()
                                 .serviceTask("B")
                                 .endEvent())
                     .endEvent()
                     .done()
```

the case above should be rejected as well right? Because, since sub process will not be migrated, the target process flow will not continue as expected. Will it be handled in another issue?

2023-11-29 16:42 UTC, berkaycanbc commented on engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java
> +          "Expected to migrate process instance '%s' but it contains an active element that is unsupported: %s"
❌  The syntax is a bit blurry with indicating the element id. Would be better if we make the element id more explicit by saying:

`"Expected to migrate process instance '%s' but it contains an active element that is unsupported. Element id: %s"`

or something similar.

2023-11-30 10:44 UTC, korthout commented
@berkaycanbc I've added the requested test case. As mentioned, the error message is adjusted in https://github.com/camunda/zeebe/pull/15417.

Please have another look.

2023-11-30 15:22 UTC, berkaycanbc approved these changes
LGTM @korthout! 🚀 

I also checked the error message reformatting in the other PR. 👍

2023-11-30 15:22 UTC, korthout commented
bors merge

2023-11-30 15:31 UTC, merged