Adding test for job timeout update
camunda/camunda pull request #15423
Opened 2023-11-29 15:29 UTC by ana-vinogradova-camunda

## Description

Adding IT for Job timeout update to `MultiTenancyOverIdentityIT`.

## Related issues

closes #15382

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-11-29 15:38 UTC, koevskinikola requested changes
Nice job @ana-vinogradova-camunda! :+1: 

I left a suggestion for an additional test, and the PR should be done after that.

2023-11-29 15:38 UTC, koevskinikola commented on qa/integration-tests/src/test/java/io/camunda/zeebe/it/multitenancy/MultiTenancyOverIdentityIT.java
> +  void shouldUpdateJobTimeoutForTenant() {
:+1: Nice one!

2023-11-29 15:38 UTC, koevskinikola commented on qa/integration-tests/src/test/java/io/camunda/zeebe/it/multitenancy/MultiTenancyOverIdentityIT.java
:x: It would be good to add a test that the timeout is not updated when the client uses an unauthorized tenant. 
This would ensure that we catch any regressions in the related job processor in the future.

The test [here](https://github.com/camunda/zeebe/pull/15423/files#diff-186bd54a3f19ebda8ffbbab3f07c3886bc67629e87c3982a8fa732207dc3c066R832-R873) does a similar thing.

2023-11-29 15:53 UTC, ana-vinogradova-camunda commented on qa/integration-tests/src/test/java/io/camunda/zeebe/it/multitenancy/MultiTenancyOverIdentityIT.java
Added another test, thank you.

2023-11-30 08:16 UTC, koevskinikola approved these changes
LGTM :rocket: 

bors merge

2023-11-30 08:33 UTC, merged