Special characters in static inputs should not be escaped
camunda/camunda pull request #15449
Opened 2023-12-01 19:24 UTC by nicpuppa

## Description

This PR fix the behaviour of static expression in Zeebe. Using the built-in `translateEscapes()` API allow Zeebe to not escape special characters also in a Static Inputs

## Related issues

closes #15447 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2023-12-04 10:31 UTC, saig0 requested changes
@nicpuppa thank you for fixing the issue. :rocket: 

There are test failures. Please have a look. :cookie:

2023-12-18 07:22 UTC, nicpuppa commented
Hey @saig0, I tried to have a deeper look into the other cases that you suggested but I wasn't able to find anything. Since I want to merge this PR before the code freeze, please can you have another look ? 👀 

One more point, the behaviour of `translateEscape()` API was not correct, so I remove every escaping function in the method

2023-12-19 13:17 UTC, saig0 requested changes
@nicpuppa good catch. :+1: 

I would like to request a change for the test cases. Please have a look. :cake:

2023-12-19 13:17 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/activity/ActivityTest.java
> +                      .zeebeInput("My Name is \\\"Zeebe\\\", nice to meet you", "quotesStatic")
:x: This is different from the reported issue.

In the issue, the static input was `Hello\n\nYOU!`. With this change, we escape the double quotes. I don't expect a user or the modeler to write an escaped quote. 

In the Modeler, the double quotes are encoded as `&#34;`. So, the example would be `"My Name is &#34;Zeebe&#34;, nice to meet you"`.

I suggest aligning with the modeler.

2023-12-19 13:17 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/processing/variable/mapping/VariableMappingTransformerTest.java
> +  public void shouldNotEscapeCharactersInStaticExpression() {
:wrench: Let's add a test case for the double quotes encoded as `&#34;`.

2023-12-19 13:17 UTC, saig0 commented on engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/VariableMappingTransformer.java
> +          expression = String.format("\"%s\"", sourceExpression.getExpression());
No escaping. No problem. :laughing:

2023-12-19 13:28 UTC, nicpuppa commented
> @nicpuppa BTW: I found out that the static inputs are used from the connector templates. 🤯 For example, the REST connector:
> 
> ![Screenshot from 2023-12-19 14-19-38](https://private-user-images.githubusercontent.com/4305769/291597750-0772a896-568d-45f7-a369-46b14eb40aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTIzMDksIm5iZiI6MTcwMjk5MjAwOSwicGF0aCI6Ii80MzA1NzY5LzI5MTU5Nzc1MC0wNzcyYTg5Ni01NjhkLTQ1ZjctYTM2OS00NmIxNGViNDBhYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTMyMDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU3MDc0MWU1NGEyOTNiZGQzZjc2OTdmN2E0NzExMTQyNjE3NzRmYTg2NDk0MTBjNWNhM2I3YzhlYmNiMjZhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zy4ct-FwazgXeEyxGakp6hNhhfwlXMjQdhWjrGrrv4k)

Yeah, but this should be covered by the test cases that we have right ? They are using static inputs inside the service task

2023-12-19 13:42 UTC, saig0 commented
> Yeah, but this should be covered by the test cases that we have right ?

Yes. This case is covered by `ActivityTest`. :+1: 

I was just not aware that it is used by the connector templates. :smile:

2023-12-19 13:47 UTC, nicpuppa commented
> I was just not aware that it is used by the connector templates. 😄

Oh ok, now we are aware 😄 Good discover 🚀

2023-12-19 14:03 UTC, nicpuppa commented
@saig0 I updated the test cases as suggested, please have another look 🙇

2023-12-19 14:43 UTC, saig0 approved these changes
@nicpuppa nice. :rocket: 

bors merge

2023-12-19 14:56 UTC, merged