chore(broker-code): close subscription when event scope is left
camunda/camunda pull request #1546
Opened 2018-10-24 12:39 UTC by saig0

* new subscription command CLOSE
* send CLOSE command when the message catch element is terminated
* send the command again if not acknowledged

closes #1166

2018-10-24 12:40 UTC, saig0 commented
Name `activityInstanceKey` as `elementInstanceKey` as part of #1536

2018-10-26 06:12 UTC, ChrisKujawa requested changes

2018-10-26 06:12 UTC, Zelldon commented on broker-core/src/test/java/io/zeebe/broker/workflow/MessageCorrelationTest.java
> +        .containsExactly(
Please change to Recordingexporter

2018-10-26 06:36 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/subscription/command/SubscriptionApiCommandMessageHandler.java
> +
Good point.

2018-10-26 06:36 UTC, saig0 commented on broker-core/src/test/java/io/zeebe/broker/workflow/MessageCorrelationTest.java
> +        .containsExactly(
Agree.

2018-10-26 09:19 UTC, saig0 commented
@Zelldon  I applied the review hints.

2018-10-26 09:34 UTC, ChrisKujawa approved these changes
bors r+

2018-10-26 10:55 UTC, menski commented
bors retry

2018-10-26 11:41 UTC, menski commented
bors r+

2018-10-26 11:55 UTC, merged