Cancel compensation handlers on process instance termination
camunda/camunda pull request #15761
Opened 2024-01-02 14:49 UTC by nicpuppa

## Description

When a process instance is cancelled, all the active compensation handler should be terminated

## Related issues

closes #15065 

⚠️ Depends on: https://github.com/camunda/zeebe/pull/15760

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2024-01-09 05:53 UTC, saig0 requested changes
@nicpuppa looks good. :+1: But, we don't fulfill all requirements yet. :wink: 

Please have a look at my comments. :cookie:

2024-01-09 05:53 UTC, saig0 commented on engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/task/JobWorkerTaskProcessor.java
> +    compensationSubscriptionBehaviour.terminateCompensationHandler(context, element);
:x: Let's add two test cases for completing and canceling a process instance in case the compensation handlers are not invoked.

2024-01-09 12:31 UTC, nicpuppa commented
Thanks for the review @saig0, also thanks for spotting the missing implementation 🤖 💯 

I changed the behaviour to align with your comments, please have a look 👀

2024-01-10 05:26 UTC, saig0 approved these changes
@nicpuppa very good. :tada: LGTM. :rocket:

2024-01-10 05:26 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/processing/bpmn/compensation/CompensationEventExecutionTest.java
> +        .containsSubsequence(
:wrench: We verify only a single event.

```suggestion
        .contains(
```

2024-01-10 05:30 UTC, saig0 commented
bors merge

2024-01-10 10:39 UTC, merged