refactor(broker-core): merge stream processors into one
camunda/camunda pull request #1609
Opened 2018-11-01 08:37 UTC by Zelldon

* Creatied an stream processor service, which adds all event processors and install the typed stream processor, besides the incident stream processor. The incident processors will be added in a later PR.
 * Created new classes in each processor package, with static methods to add the EventProcessors. This makes it easier to test the different processors.
 * The states of the processors are merged into one. The `ZeebeState` is a composite state, of all other and the only remaining state controller. I hope this make this also easier for the refactoring in #1195 . This means we will have only one RocksDb instance per partition, which should be good.
 * The other states are no longer state controller, but impl. the `StateLifecycleListener` so they are called after the ZbRocksDB was opened. In the state controller the `ZbRocksDb` is used, instead of the RocksDb instance.
 * For the single processor only one KeyGenerator is needed, after merging the incident stream processor I will work on #1387 to iterate over the KeyGenerator.
 * Refactored a bit the JobProcessors and move them in outer classes.

closes #1571
closes #1572

2018-11-05 12:34 UTC, ThorbenLindhauer requested changes
It looks like some state classes now declare and use the same column families, e.g. `MessageState` and `JobState` both have `deadlines` (I didn't check for more occurrences). Please make those names unique, for example by applying a namespace convention. To prevent this situation in the future, it could be a good idea to add a check to for example `StateController` that detects if a column family is declared twice.

2018-11-06 08:40 UTC, Zelldon commented
@ThorbenLindhauer sorry you 're right. I fixed the family names and added a duplicate check.

2018-11-06 09:22 UTC, ThorbenLindhauer approved these changes

2018-11-06 14:38 UTC, Zelldon commented
bors r+

2018-11-06 14:48 UTC, merged