feat(gateway-protocol): define an openapi specification document
camunda/camunda pull request #16194
Opened 2024-02-02 16:06 UTC by koevskinikola

## Description

Define an OpenAPI specification document in the gateway-protocol module. This document will be used to define the REST API endpoints for Zeebe. It will also be used to generate the appropriate model classes that will be used in the Zeebe REST API controllers.

The OpenAPI specification document currently defines only the OpenAPI spec version, as well as the `info` and `servers` sections. The `info` section provides details on the purpose of the document, the version of the document, license and external documentation. The `servers` section defines the URL format.
## Related issues

closes #16163 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2024-02-02 16:12 UTC, npepinpe approved these changes

2024-02-02 16:12 UTC, npepinpe commented on gateway-protocol/src/main/proto/rest-api.yaml
> +    url: https://docs.camunda.io/docs/apis-tools/zeebe-api-rest/overview/
💭 i guess this will change?

2024-02-04 16:41 UTC, npepinpe requested changes

2024-02-04 16:41 UTC, npepinpe commented on gateway-protocol/src/main/proto/rest-api.yaml
> +    url: https://docs.camunda.io/docs/apis-tools/zeebe-api-rest/overview/
:x: This is invalid, it's a root property, and not a member of `info`

```suggestion
externalDocs:
  description: Find out more
  url: https://docs.camunda.io/docs/apis-tools/zeebe-api-rest/overview/
```

2024-02-04 16:41 UTC, npepinpe commented on gateway-protocol/src/main/proto/rest-api.yaml
> +openapi: "3.0.2"
```suggestion
openapi: "3.1.0"
```

We can use the latest version of OpenAPI released in 2021

2024-02-04 16:42 UTC, npepinpe commented on gateway-protocol/src/main/proto/rest-api.yaml
> +
:x: Missing the required `paths` field (can be left empty for now)

2024-02-05 07:04 UTC, koevskinikola commented on gateway-protocol/src/main/proto/rest-api.yaml
> +    url: https://docs.camunda.io/docs/apis-tools/zeebe-api-rest/overview/
Yup, it's just a dummy URL for now

2024-02-05 07:09 UTC, koevskinikola commented
@npepinpe I implemented you feedback with [a7eec6f](https://github.com/camunda/zeebe/pull/16194/commits/a7eec6f17a98bea331ed9a72aa4d2e0bea5f75c6)

2024-02-05 07:57 UTC, npepinpe approved these changes

2024-02-05 08:44 UTC, npepinpe commented
should we merge? :eyes:

2024-02-05 09:35 UTC, merged