Refactor Backups: reuse common code between Azure and GCS
camunda/camunda pull request #16244
Opened 2024-02-06 10:21 UTC by rodrigo-lourenco-lopes

## Description

- Move manifests implementation, file sets, and some exceptions to backup.common

So far these common parts of the code were only being repeated between Azure and GCS, some further changes would be necessary to also abstract from S3. Additionally address some raised issues by the commit checker.

## Related issues

relates https://github.com/camunda/zeebe/issues/16105

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2024-02-12 13:44 UTC, oleschoenburg requested changes
:x: I don't think these types should be in the backup module, I'd rather have a new module in `backup-stores/common`.

2024-02-27 09:36 UTC, rodrigo-lourenco-lopes commented
> ❌ I don't think these types should be in the backup module, I'd rather have a new module in `backup-stores/common`.

@oleschoenburg if we abstract these types to a new module we get a circular reference between this new module and the backup, unless we move the method toStaus() back to the respective `AzureBackupStore` and `GcsBackupStore` respectively. Is it worth it?

2024-02-27 09:39 UTC, oleschoenburg commented
Could we just move the `toStatus` method somewhere else? AFAICT it doesn't need to be in the `backup` module.

2024-02-27 16:07 UTC, lenaschoenburg requested changes

2024-02-27 16:07 UTC, oleschoenburg commented on zeebe/backup-stores/common/pom.xml
> +      <version>2.16.1</version>
:x: We should not specify a version here, we should use the one from the parent.

2024-02-28 11:23 UTC, oleschoenburg approved these changes
Thanks @rodrigo-lourenco-lopes :+1: 

I approved now but please address the one remaining issue. I think you accidentally marked it as resolved before.

2024-02-28 11:23 UTC, oleschoenburg commented on zeebe/backup-stores/common/pom.xml
> +    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
I reopened because it's not resolved yet.

2024-02-28 12:31 UTC, rodrigo-lourenco-lopes commented on zeebe/backup-stores/common/pom.xml
> +    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
ups, yes, I think i resolved it accidentally

2024-02-28 14:03 UTC, merged