refactor(engine): `BpmnElementProcessor` methods to return types
camunda/camunda pull request #16305
Opened 2024-02-12 08:51 UTC by ce-dmelnych

## Description

### Overview
This PR introduces enhancements to the `BpmnElementProcessor` by changing the return types of the `onActivate` and `onComplete` methods from `void` to `Either<Failure, Void>`. This alteration aims to provide a more structured approach to error handling and process management within our system. Additionally, it centralises the incident creation logic within the `BpmnStreamProcessor`, streamlining error management and improving maintainability.
### Key Changes
- Updated `onActivate` and `onComplete` methods in `BpmnElementProcessor.java` to return `Either<Failure, Void>`.
- Modified all implementations of the `BpmnElementProcessor` interface to comply with the new method signatures.
- Transferred the responsibility for incident creation from individual `BpmnElementProcessor` implementations to the `BpmnStreamProcessor`.
### Motivation
1. To enhance the system's ability to handle errors more effectively and provide clear, actionable feedback for process management.
2. To prepare the interface for the introduction of new lifecycle methods.

This work lays the groundwork for subsequent enhancements.

## Related issues
closes #16207 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2024-02-12 12:56 UTC, ce-dmelnych commented on engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/BpmnElementProcessor.java
>     * The element is going to be terminated. Perform every action to terminate the element and
Regarding the `default void onTerminate(final T element, final BpmnElementContext context) {}` method, I noticed that we typically don't include incident creation logic there. 
@saig0 what do you think, would it be worth to also add an `Either<Failure, Void>` return type to it?

2024-02-13 14:12 UTC, saig0 requested changes
@ce-dmelnych great changes. :tada: 

I love the new structure. Extracting the incident handling out of the processors looks good. :star_struck: 

I have a few minor comments. Please have a look. :cookie: 

--- 

For the next PR, consider splitting the PR into multiple commits. This can ease the reviewing effort.

2024-02-13 20:34 UTC, ce-dmelnych commented on engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/EventSubProcessProcessor.java
> +        .flatMap(ok -> EMPTY_RIGHT);
Thank you for a nice suggestion! 
I've updated the signatures for the `onActivate` & `onComplete` methods to return `Either<Failure, ?>` in order not to tie the successful response to the `Void` type.

2024-02-13 20:35 UTC, ce-dmelnych commented on engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/ProcessProcessor.java
> +          .ifLeft(failure -> incidentBehavior.createIncident(failure, context));
Yep, removed Left value processing.

2024-02-13 20:35 UTC, ce-dmelnych commented on engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/ProcessProcessor.java
> +            .ifLeft(failure -> incidentBehavior.createIncident(failure, flowScopeContext));
Yep, removed)

2024-02-13 20:36 UTC, ce-dmelnych commented on engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/gateway/ExclusiveGatewayProcessor.java
> +                        return null;
Done, simplified it.

2024-02-13 20:50 UTC, ce-dmelnych commented on util/src/main/java/io/camunda/zeebe/util/Either.java
> +  Either<L, Void> thenDo(Consumer<R> action);
@saig0, thank you so much for your feedback and encouragement! 🙏

I fully agree with your suggestions. 
Your point about the `EitherTest` test class was spot-on—I had overlooked it during the initial implementation. I've now added several tests to cover the behaviour of the new `thenDo` method in various scenarios.
Additionally, I've updated the method signature to `Either<L, R>`, which better reflects that the action does not alter the value, thereby preserving the original type.

2024-02-14 09:06 UTC, saig0 approved these changes
@ce-dmelnych nice. LGTM. :tada: 

Before merging, please have a look at my comment. Then, feel free to merge the PR, no additional review is required.

2024-02-14 09:39 UTC, ce-dmelnych commented on engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/ProcessProcessor.java
> +          .ifLeft(failure -> incidentBehavior.createIncident(failure, context));
Ouch 😸, really it was missed
cleaned))

2024-02-14 10:30 UTC, merged