Exporter can soft pause and resume
camunda/camunda pull request #16345
Opened 2024-02-14 10:24 UTC by rodrigo-lourenco-lopes

## Description

Exporter can soft pause and resume. This means if the exporter is soft paused, we keep exporting the records without updating the exporter state. upon resuming The exporter state is updated with the position and metadata of the last exported record.

## Related issues

closes https://github.com/camunda/zeebe/issues/16344

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2024-02-15 08:01 UTC, deepthidevaki requested changes
:rocket: Awesome. I like the behavior of consecutive calls of pause vs soft-pause, and resume always resumes full exporting, no matter if it was soft paused or hard paused. :+1: 

:x: I have only one main comment. The exporter director should be able to start with phase soft-paused if it was soft-paused before restart. You can do it in a follow up PR. If so please create an issue for it and link it here for transparency.

Other comments are minor - like improvements to tests and documentation. Please address them in this PR itself.

2024-02-29 21:06 UTC, rodrigo-lourenco-lopes commented on broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java
> +    isHardPaused = shouldPauseOnStart;
I will also implement this part in another PR for this issue https://github.com/camunda/zeebe/issues/16642

2024-03-11 10:35 UTC, deepthidevaki approved these changes
:rocket:

2024-03-11 13:01 UTC, merged

2024-04-25 09:17 UTC, rodrigo-lourenco-lopes commented
/backport

2024-04-25 09:17 UTC, backport-action commented
Successfully created backport PR for `stable/8.2`:
- #17809

2024-04-25 09:17 UTC, backport-action commented
Successfully created backport PR for `stable/8.3`:
- #17810

2024-04-25 09:17 UTC, backport-action commented
Successfully created backport PR for `stable/8.4`:
- #17811

2024-04-25 21:28 UTC, rodrigo-lourenco-lopes commented
/backport

2024-04-25 21:28 UTC, backport-action commented
Git push to origin failed for stable/8.3 with exitcode 1

2024-04-25 21:29 UTC, backport-action commented
Backport failed for `stable/8.4`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin stable/8.4
git worktree add -d .worktree/backport-16345-to-stable/8.4 origin/stable/8.4
cd .worktree/backport-16345-to-stable/8.4
git switch --create backport-16345-to-stable/8.4
git cherry-pick -x ce0234a6de7451e147a8981262aad60f452c337e 3a123e4e7763ee11565044764288caf74a6db462 adc1dba80868c3cbacb57d59ac5425798223a593
```

2024-04-25 21:29 UTC, backport-action commented
Backport failed for `stable/8.5`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin stable/8.5
git worktree add -d .worktree/backport-16345-to-stable/8.5 origin/stable/8.5
cd .worktree/backport-16345-to-stable/8.5
git switch --create backport-16345-to-stable/8.5
git cherry-pick -x ce0234a6de7451e147a8981262aad60f452c337e 3a123e4e7763ee11565044764288caf74a6db462 adc1dba80868c3cbacb57d59ac5425798223a593
```