Support I/O mapping variables starting with _
camunda/camunda pull request #16482
Opened 2024-02-20 08:00 UTC by skayliu

## Description

At the moment it is not possible to use I/O mappings where the variable name starts with an _. It is possible to create variable names like this in other ways, for example using the SetVariables RPC.

Restrictions around variable names should be consistent across the system. If we allow variables to start with an _ in one place, we should also allow it in the I/O mappings.

## Related issues

closes #11397 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.ink/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.ink/camunda/operate/issues)
- [ ] [Tasklist](https://github.ink/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.ink/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.ink/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.ink/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.ink/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2024-02-20 08:02 UTC, skayliu commented
Hey, @korthout, ✋  Please take a moment to review this PR when you have time. Thank you.

2024-02-22 14:58 UTC, nicpuppa reviewed
Hey @skayliu thanks for the great work. Overall I don't see any issue with your implementation. I have just a suggestion/question.

🔧 Should we add more tests in other places ? (eg. JobInputMappingTest or SignalEndEventOutputMappingTest ecc.) 

There are more test classes that use variables, what do you think ?

2024-02-22 15:15 UTC, skayliu commented
> Hey @skayliu thanks for the great work. Overall I don't see any issue with your implementation. I have just a suggestion/question.
> 
> 🔧 Should we add more tests in other places ? (eg. JobInputMappingTest or SignalEndEventOutputMappingTest ecc.)
> 
> There are more test classes that use variables, what do you think ?

Ok, I'll add for those tests.

2024-02-26 08:41 UTC, nicpuppa requested changes
Thanks @skayliu for the great work 🚀 

I added some more question/suggestion. Please let me what you thought 🍪

2024-02-26 13:18 UTC, skayliu commented on engine/src/test/java/io/camunda/zeebe/engine/processing/variable/mapping/MessageCatchElementOutputMappingTest.java
> +  private static final String CORRELATION_VARIABLE = "_key";
ok, i‘ll revert this.

2024-02-26 14:44 UTC, skayliu commented on engine/src/test/java/io/camunda/zeebe/engine/processing/variable/mapping/MessageCatchElementOutputMappingTest.java
> +        .withVariables(asMsgPack("_foo", "bar"))
I've applied you suggestion, please review again.

2024-02-27 09:58 UTC, nicpuppa approved these changes
Thanks @skayliu , LGTM. Great work! 🚀 

Can you please rebase your branch ? Thank you

2024-02-27 14:07 UTC, skayliu commented
> Thanks @skayliu , LGTM. Great work! 🚀
> 
> Can you please rebase your branch ? Thank you

It's done, @nicpuppa, should i squash these commits now?

2024-02-27 15:11 UTC, nicpuppa commented
> It's done, @nicpuppa, should i squash these commits now?

Yes please 👍

2024-02-27 15:42 UTC, nicpuppa approved these changes

2024-02-27 16:01 UTC, nicpuppa commented
Hey @skayliu can you check the commit linter ?

2024-02-28 10:58 UTC, merged