Skip Exporting Specific Records
camunda/camunda pull request #16613
Opened 2024-02-28 14:39 UTC by rodrigo-lourenco-lopes

## Description

This pr allows the confiration of record's positions to skip in the exporters. A record positon in this list will be treated as a record to skip similar to event filter (`ExporterDirector.skipRecord()`).

The configuration has to be done per exporter, for example: `ZEEBE_BROKER_EXPORTERS_[exporter name]_SKIPRECORDS: 1`
## Related issues

closes https://github.com/camunda/zeebe/issues/16177

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2024-02-29 15:13 UTC, oleschoenburg requested changes

2024-02-29 15:13 UTC, oleschoenburg commented on dist/src/main/config/broker.standalone.yaml.template
> +
:x: This is unexpected behavior and a bit confusing on multiple levels.
I think we should just add the `skipRecords` configuration on another level, so not in `zeebe.broker.exporters` but something like `zeebe.broker.exporting`.

2024-02-29 15:13 UTC, oleschoenburg commented on zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java
> +              && !positionsToSkip.contains(currentEvent.getPosition())) {
:wrench: We should reuse the `SkipPositionsFilter` I've built for skipping positions during processing.

2024-03-04 15:15 UTC, lenaschoenburg requested changes

2024-03-04 15:15 UTC, oleschoenburg commented on dist/src/main/config/broker.standalone.yaml.template
> +      # Skip records Exporter ------------
:x: This appears to be left-over. There is no "Skip records Exporter". The following lines should be indented one level less.

2024-03-04 15:15 UTC, oleschoenburg commented on dist/src/main/config/broker.yaml.template
> +      # Skip records Exporter ------------
:x: Same as above

2024-03-04 15:15 UTC, oleschoenburg commented on zeebe/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java
> +    eventFilter = createEventFilter(containers).and(positionsToSkipFilter);
:wrench: I'd flip the order to first use the position skip filter. That way the other filters don't even have to decode (possibly corrupted) events.

2024-03-04 15:15 UTC, oleschoenburg commented on zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/configuration/ExporterCfg.java
> +  private Set<Long> skipRecords;
:x: This needs to be removed here, the config moved.

2024-03-04 15:35 UTC, lenaschoenburg approved these changes
Nice :rocket:

2024-03-05 09:59 UTC, merged

2024-03-05 09:59 UTC, backport-action commented
Backport failed for `stable/8.2`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin stable/8.2
git worktree add -d .worktree/backport-16613-to-stable/8.2 origin/stable/8.2
cd .worktree/backport-16613-to-stable/8.2
git switch --create backport-16613-to-stable/8.2
git cherry-pick -x ca93d12d55b2b4bb4a95ee7f581ca67222b71a15 769599b9fd822c86702bcc04d2a226ff1ece656f 808538ecd9a56787de0ddcc1955694e795cd873e 5a7210323a0df7edb9491dfe173946536320a9b4 22236f50c2d21b991e29d98064f62e88156cdc80 663685ce0b39bd20fa5f65728c01ff52b03e71f8 4e3228d888c128b398a3a76e59fc17717742407e
```

2024-03-05 10:00 UTC, backport-action commented
Backport failed for `stable/8.3`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin stable/8.3
git worktree add -d .worktree/backport-16613-to-stable/8.3 origin/stable/8.3
cd .worktree/backport-16613-to-stable/8.3
git switch --create backport-16613-to-stable/8.3
git cherry-pick -x ca93d12d55b2b4bb4a95ee7f581ca67222b71a15 769599b9fd822c86702bcc04d2a226ff1ece656f 808538ecd9a56787de0ddcc1955694e795cd873e 5a7210323a0df7edb9491dfe173946536320a9b4 22236f50c2d21b991e29d98064f62e88156cdc80 663685ce0b39bd20fa5f65728c01ff52b03e71f8 4e3228d888c128b398a3a76e59fc17717742407e
```

2024-03-05 10:00 UTC, backport-action commented
Backport failed for `stable/8.4`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin stable/8.4
git worktree add -d .worktree/backport-16613-to-stable/8.4 origin/stable/8.4
cd .worktree/backport-16613-to-stable/8.4
git switch --create backport-16613-to-stable/8.4
git cherry-pick -x ca93d12d55b2b4bb4a95ee7f581ca67222b71a15 769599b9fd822c86702bcc04d2a226ff1ece656f 808538ecd9a56787de0ddcc1955694e795cd873e 5a7210323a0df7edb9491dfe173946536320a9b4 22236f50c2d21b991e29d98064f62e88156cdc80 663685ce0b39bd20fa5f65728c01ff52b03e71f8 4e3228d888c128b398a3a76e59fc17717742407e
```