Distribute commands to subset of partitions
camunda/camunda pull request #16842
Opened 2024-03-12 17:31 UTC by korthout

## Description

Work in progress.

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2024-03-18 17:49 UTC, berkaycanbc requested changes
Thanks @korthout! 🚀 

⭐ I really like the idea of testing this in isolation.

👀 I've added some comments and suggestions, please take a look.

2024-03-18 17:49 UTC, berkaycanbc commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java
> +   * @param distributionKey the key to identify this unique command distribution. The key is used to
🔧 The second sentence can be re-written to make it more understandable. E.g.

`The key used for three purposes: storing the pending distribution as the key of distributed command, identifying for the distributed command's partition, and correlating the ACKNOWLEDGE command to the pending distribution.`

Or maybe something similar.

2024-03-18 17:49 UTC, berkaycanbc commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java
> +        commandDistributionStarted
💭 What about implementing a reset method for the record and calling it before or after each usage? For now, it is not used around, so seems clear but for future changes, that can make the re-using more explicit. WDYT?

2024-03-18 17:49 UTC, berkaycanbc commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/distribution/CommandDistributionBehavior.java
>      final var distributionRecord =
❓Why we didn't create a re-usable record for the acknowledged command as we did refactoring for others?

2024-03-29 06:22 UTC, Zelldon commented
@berkaycanbc @korthout what is the status of this?

2024-04-05 16:11 UTC, korthout commented
@Zelldon it's part of process instance migration, but the functionality is not needed right away. Focus was elsewhere for the time being. Please keep this open for when we need it. Until then, there's no need to merge this as it will not be in use.

2024-05-08 11:11 UTC, korthout commented
This is needed for [PIM phase 3](https://github.com/camunda/zeebe/issues/17349) as part of:
- https://github.com/camunda/zeebe/issues/16386

2024-05-13 13:41 UTC, korthout commented
@berkaycanbc I've rebased on top of `main` to allow running the new SDK test summary. The only commits that are new are `9ecfa38..e44d0eb`

2024-05-13 15:12 UTC, berkaycanbc approved these changes
Thanks for the latest changes @korthout, LGTM 🚀.

2024-05-13 15:53 UTC, merged