Resolve incident explicit with command request
camunda/camunda pull request #1692
Opened 2018-11-21 19:43 UTC by Zelldon

The incident resolving for message subscriptions had the problem that in CatchEventOutput the side effect is overwritten. I hand crafted shortly something, which can replaced when #1680 is merged (SideEffectQueue). But it works for now and can be reviewed.

Added resolve incident command to the gateway protocol and to the java client.
The broker and qa tests are also using the resolve method. There is no inplicit incident resolving anymore.

closes #1651 
closes #1649

2018-11-22 12:35 UTC, Zelldon commented
@saig0 rebased to develop and used the side effect queue instead of the hack :sweat_smile: It seems there is a deadlock in the ElasticsearchExporter I dont know why :man_shrugging:

2018-11-23 10:08 UTC, saig0 requested changes
:+1:

2018-11-23 11:33 UTC, Zelldon commented on exporters/elasticsearch-exporter/src/test/java/io/zeebe/exporter/ElasticsearchExporterIT.java
> +                zeebeClient
I aggree on this, maybe i find a better solution

2018-11-23 11:34 UTC, Zelldon commented on broker-core/src/test/java/io/zeebe/broker/incident/ExpressionIncidentTest.java
> +    final Record<IncidentRecordValue> incidentEvent =
Yeah maybe we can split it

2018-11-26 07:56 UTC, saig0 approved these changes

2018-11-26 12:46 UTC, Zelldon commented
bors r+

2018-11-26 12:56 UTC, merged