feat: azure backup store can discover credentials from runtime environment
camunda/camunda pull request #16958
Opened 2024-03-18 16:22 UTC by rodrigo-lourenco-lopes

## Description

This feature allow azure backup store to use auto configuration. If account credentials or connection string are not provided, the client falls back to `DefaultAzureCredential` which discovers credentials from the runtime environment:
https://learn.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable

A new config value was added to the azure config where if auth is set as auto, the DefaltAzureCredentials methods for building the client will be used.
`DefaultAzureCredential` supports multiple authentication methods and determines which method should be used at runtime.
Default credentials are appropriate for most scenarios where the application is intended to ultimately be run in Azure.

closes #16736

2024-03-20 13:27 UTC, oleschoenburg requested changes
:thought_balloon: I think we might not need the new `auth` config and instead use the following logic:

1. If `connectionString` is set, use that.
2. If `accountName` and `accountKey` is set, use that (and fail if either one is set but not the other)
3. If none of the above are set, use the `DefaultAzureCredentialBuilder`.

That way we don't change behavior for existing setups while still keeping the necessary configuration to a minimum. Does that make sense to you or am I missing something?

2024-03-20 13:27 UTC, oleschoenburg commented on zeebe/backup-stores/azure/src/main/java/io/camunda/zeebe/backup/azure/AzureBackupStore.java
> +    if (config.auth() != null && config.auth().equals("auto")) {
:upside_down_face: 
```suggestion
    if ("auto".equals(config.auth())) {
```

2024-03-20 13:27 UTC, oleschoenburg commented on zeebe/backup-stores/azure/src/main/java/io/camunda/zeebe/backup/azure/AzureBackupConfig.java
> +    private String auth;
:wrench: Either define an enum for it or declare "auth" as a static field. Currently it's hard-coded in at least two places that could go out of sync eventually.

2024-03-20 13:27 UTC, oleschoenburg commented on dist/src/main/config/broker.standalone.yaml.template
> +          # discovers appropriate credentials from the runtime environment: https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identi
:thought_balloon: Should we rather link to https://learn.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable? This at least explains how the credentials are discovered, precedence rules etc.

2024-03-20 13:27 UTC, oleschoenburg commented on dist/src/main/config/broker.standalone.yaml.template
> +          # Leaving it empty means that the authentication will with the other configuration values.
:x: Broken sentence, I'm not sure what this was supposed to say

2024-03-20 13:27 UTC, oleschoenburg commented on zeebe/backup-stores/azure/pom.xml
:wrench: Apologies, I think I mislead you a bit when we discussed how to resolve version conflicts. I think the proper way to do it this:

1. Just add a dependency on `azure-identity` without any exclusions
2. Remove the `ignoredUnusedDeclaredDependencies` again
3. To resolve the version conflicts add the following:

```xml
  <dependencyManagement>
    <dependencies>
      <!-- Resolve conflicting dependencies from azure-identity -->
      <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>msal4j</artifactId>
        <version>1.14.0</version>
      </dependency>
      <dependency>
        <groupId>net.java.dev.jna</groupId>
        <artifactId>jna-platform</artifactId>
        <version>5.13.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

This is much cleaner IMO because we only declare that we depend on `azure-identity` and then use `dependencyManagement` to sort out the version conflicts.

2024-03-20 15:48 UTC, rodrigo-lourenco-lopes commented
> I think we might not need the new `auth` config and instead use the following logic:
> 
> 1. If `connectionString` is set, use that.
> 2. If `accountName` and `accountKey` is set, use that (and fail if either one is set but not the other)
> 3. If none of the above are set, use the `DefaultAzureCredentialBuilder`.
> 
> That way we don't change behavior for existing setups while still keeping the necessary configuration to a minimum. Does that make sense to you or am I missing something?

During implementation, I was thinking if it would make sense to explicitly let the user know that the Azure platform-managed credentials are being used by having to change this config to auto. 
But in terms of implementation yes that would also work 

> 💭 I think we might not need the new `auth` config and instead use the following logic:
> 
> 1. If `connectionString` is set, use that.
> 2. If `accountName` and `accountKey` is set, use that (and fail if either one is set but not the other)
> 3. If none of the above are set, use the `DefaultAzureCredentialBuilder`.
> 
> That way we don't change behavior for existing setups while still keeping the necessary configuration to a minimum. Does that make sense to you or am I missing something?

During implementation, I thought that it would be useful to change which set of credentials would be used by just switching this authentication config, wtyt? But even if we remove it, part of the documentation for the automatic authentication should probably stay 🤔

2024-03-20 15:52 UTC, oleschoenburg commented on zeebe/backup-stores/azure/pom.xml
In your latest commit https://github.com/camunda/zeebe/pull/16958/commits/561e7560b5067fed6f6183c462ac0ec481188195 you still have an exclusion for `msal4j` in the `azure-identity` dependency declaration, that's probably why the class is not available. Please try _without_ the exclusions (see step 1 in my original comment)

2024-03-20 15:55 UTC, oleschoenburg commented
> During implementation, I thought that it would be useful to change which set of credentials would be used by just switching this authentication config, wtyt?

This only works for switching to `auto` and not between the other two options.
Documentation should remain, yes. Maybe just adding a comment to the other configuration options explaining that if not set, `auto` will be used?

2024-03-20 16:58 UTC, rodrigo-lourenco-lopes commented on zeebe/backup-stores/azure/pom.xml
Without the exclusions it also fails to pass the verify stage, even with the dependency management: 
```
Rule 0: org.apache.maven.enforcer.rules.dependency.DependencyConvergence failed with message:
Failed while enforcing releasability.

Dependency convergence error for net.java.dev.jna:jna-platform:jar:5.13.0 paths to dependency are:
+-io.camunda:zeebe-broker:jar:8.5.0-SNAPSHOT
  +-io.camunda:zeebe-backup-store-azure:jar:8.5.0-SNAPSHOT:compile
    +-com.azure:azure-identity:jar:1.11.2:compile
      +-com.microsoft.azure:msal4j-persistence-extension:jar:1.2.0:compile
        +-net.java.dev.jna:jna-platform:jar:5.13.0:compile
and
+-io.camunda:zeebe-broker:jar:8.5.0-SNAPSHOT
  +-io.camunda:zeebe-backup-store-azure:jar:8.5.0-SNAPSHOT:compile
    +-com.azure:azure-identity:jar:1.11.2:compile
      +-net.java.dev.jna:jna-platform:jar:5.6.0:compile


Dependency convergence error for com.microsoft.azure:msal4j:jar:1.14.0 paths to dependency are:
+-io.camunda:zeebe-broker:jar:8.5.0-SNAPSHOT
  +-io.camunda:zeebe-backup-store-azure:jar:8.5.0-SNAPSHOT:compile
    +-com.azure:azure-identity:jar:1.11.2:compile
      +-com.microsoft.azure:msal4j:jar:1.14.0:compile
and
+-io.camunda:zeebe-broker:jar:8.5.0-SNAPSHOT
  +-io.camunda:zeebe-backup-store-azure:jar:8.5.0-SNAPSHOT:compile
    +-com.azure:azure-identity:jar:1.11.2:compile
      +-com.microsoft.azure:msal4j-persistence-extension:jar:1.2.0:compile
        +-com.microsoft.azure:msal4j:jar:1.4.0:compile
       
```

2024-03-21 12:04 UTC, oleschoenburg commented on zeebe/backup-stores/azure/pom.xml
Ah, I figured out why: adding the dependencyManagement section to the azure backup store pom is not enough, dependency convergence on the parent still fails. So let's add these two `dependencyManagement` entries in the parent pom instead. I've checked with `mvn verify -DskipTests`, everything passes now.

2024-03-21 15:41 UTC, oleschoenburg approved these changes

2024-03-21 17:09 UTC, merged