Update job state on update retries
camunda/camunda pull request #1700
Opened 2018-11-22 13:14 UTC by Zelldon

You are correct the job was not updated correctly on the update retries processor.

@menski is there a good reason that I'm able to update the retries only if the job is in failed state?

closes #1693

2018-11-22 14:39 UTC, npepinpe commented
This is behaviour that was there since a long time, my guess is that before the only way to resolve an incident (i.e. failed job) was to update the retries, and there was no use case for updating retries outside of that. I don't see anything wrong with allowing retry updates even when not failing, but I also don't think it's a big use case.

2018-11-27 16:08 UTC, menski commented
> is there a good reason that I'm able to update the retries only if the job is in failed state?

No. Actually we decided to allow update retries in any state. If this is not possible to do right now, then I would ask you to create a ticket for this feature. Thanks

2018-11-27 16:37 UTC, Zelldon commented
Done #1717

2018-11-28 14:31 UTC, Zelldon commented
@menski can we merge this?

2018-11-28 15:50 UTC, menski commented
@Zelldon sorry didn't had time for a review yet

2018-11-29 07:52 UTC, menski requested changes
Please add a test case that verifies that we fixed this issue, so we don't break it in the future again. For example you can take the one from my branch https://github.com/zeebe-io/zeebe/commit/1c67d5ffb3f87a69ec846e015985570de2c00b44

2018-11-29 11:07 UTC, menski approved these changes

2018-11-29 11:07 UTC, menski commented
bors r+

2018-11-29 11:36 UTC, merged