feat(broker-core): support non-interrupting timer boundary events
camunda/camunda pull request #1716
Opened 2018-11-27 14:55 UTC by npepinpe

# Not ready yet

closes #1703

2018-11-27 15:18 UTC, npepinpe commented
There is a slight issue with how tokens are handled; for boundary events, we want to spawn a token but not consume one on triggering; for event based gateways, we want to consume one.

I think #1698 or #1699 might solve this, i.e. boundary events using deferred tokens, which would then work in all cases.

2018-11-28 13:44 UTC, npepinpe commented
A few things to note for the review:

1. The `ExecutableIntermediateCatchEvent` at the moment accepts a `RepeatingInterval` as its timer; obviously this won't fit when we implement it with specific dates, but for now it's fine.
1. `TimerRecord` and `TimerInstance` are more or less the same thing, and I was on the fence about simply storing `TimerRecord` directly in the timer state, but msgpack is a little heavier to use...I feel like there should be something we could do about this in the future, since I don't think it's going to be a unique case.
1. Introduces `ExecutableCatchEventElement` (i.e. executable representation of a `CatchEvent` element), which might be a bit confusing to differentiate with `ExecutableCatchEvent` (i.e. something that behaves like a `CatchEvent`, currently used for `ReceiveTask`). Introducing this class simplifies transforming the actual events (i.e. it's always the same either for `IntermediateCatchEvent` or `BoundaryEvent` or in the future, `StartEvent`), and as a side effect transforms `StartEvent` elements to `ExecutableCatchEventElement`, which I think should have no downside for now, and will be helpful in the future (again, parsing the event definitions).
1. I think this is the first time we introduce time zones to the broker; right now, the timer is scheduled using the system's default time zone. In the future this could be configurable, as I expect it will be required if you're, say, running a fault-tolerant cluster across multiple availability zones in different time zones. I'm not sure if it makes sense to create an issue for this yet, or when the need arise.
1. `BoundaryEventActivator` now relies on `CatchEventOutput`, which is a bit better, and exposes it so that in the `TriggerTimerProcessor` we can reschedule a timer. I wasn't really 100% sure about this, as I think neither class is really good...I think think we might need to rethink these when we implement #1699 or something similar...
1. The number of repetitions left for a timer cycle is currently passed around with the `TimerRecord`/`TimerInstance`, which is fine, but I'm wondering if that's ideal. One upside is that someone inspecting the stream has a clear idea of how many repetitions are left (or if it's infinite), which could be interesting.

2018-11-29 14:22 UTC, saig0 requested changes
I like it :+1:

2018-12-03 08:32 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/workflow/model/transformation/transformer/FlowElementInstantiationTransformer.java
> +    ELEMENT_FACTORIES.put(CatchEvent.class, ExecutableCatchEventElement::new);
Oops, you're right, force of habit :see_no_evil:

2018-12-03 08:52 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/CatchEventOutput.java
> +    final long dueDate = zonedNow.plus(timer.getInterval()).toInstant().toEpochMilli();
True. I added a check here, though I'm not sure if there might not be a nicer API for this directly from the `Interval` class. (maybe with `TemporalAdjuster` or something).

2018-12-05 07:09 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/CatchEventOutput.java
> +    final long dueDate = zonedNow.plus(timer.getInterval()).toInstant().toEpochMilli();
I would prefer that this logic is inside the `Interval` class.

2018-12-05 08:04 UTC, npepinpe commented
I moved the dude date calculation logic to `Interval#toEpochMilli(long fromEpoch)`, I will add the documentation whenever I have time today

2018-12-05 10:34 UTC, saig0 approved these changes

2018-12-05 10:44 UTC, npepinpe commented
bors r+

2018-12-05 11:00 UTC, merged