docs(BPMN): adds documentation for boundary events
camunda/camunda pull request #1732
Opened 2018-12-03 08:20 UTC by npepinpe

- expands documentation on events in BPMN
- updates timer documentation to reflect changes in how durations are
parsed
- updates timer documentation to add timerWithCycle
- updates bpmn coverage table to show interrupting message/timer
boundary events as implemented

closes #1722

2018-12-03 08:21 UTC, npepinpe commented
One thing to note, I'm not 100% sure about the added documentation in the events main page. Also the image kind of sucks, and it seemed a good idea at the time but now I'm not so sure...

2018-12-04 08:10 UTC, saig0 requested changes

2018-12-04 08:10 UTC, saig0 commented on docs/src/bpmn-workflows/events.md
> +### Normal flow
I would not say that a boundary event is an intermediate event that is attached to an activity. I think this doesn't fit to BPMN well. 

```suggestion
## Intermediate Events
```

2018-12-04 12:31 UTC, npepinpe commented on docs/src/bpmn-workflows/timer-events.md
> +Durations can also be negative; a negative timer will fire immediately, and can be expressed as `-PT5S`, or minus 5 seconds.
How did you do that? :open_mouth:

2018-12-04 12:31 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: c0b239523bf725a79cab19dadf133c3e44b56c58
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-12-04 12:31 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: c0b239523bf725a79cab19dadf133c3e44b56c58
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-12-04 12:32 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: c0b239523bf725a79cab19dadf133c3e44b56c58
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ac9626c677fd1bca1c37a7a7272eb8fe7d89edbf
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-12-04 12:32 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: c0b239523bf725a79cab19dadf133c3e44b56c58
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ac9626c677fd1bca1c37a7a7272eb8fe7d89edbf
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 18fcb258c750618135b1c31c15ca11db20bc9709
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-12-04 12:46 UTC, npepinpe commented on docs/src/bpmn-workflows/events.md
> +![workflow](/bpmn-workflows/events.png)
Yeah, like I said in my comment, it seemed a good idea at the time, but then I wasn't so sure, and I figured a second opinion would be interesting. I think I would not even have the image at all.

2018-12-04 12:47 UTC, npepinpe commented
I think I addressed all feedback points with the last commits.

2018-12-05 06:55 UTC, saig0 approved these changes

2018-12-05 07:38 UTC, merged