feat(zbctl): allows scope to be supplied via command line parameter
camunda/camunda pull request #17429
Opened 2024-04-10 23:44 UTC by jessesimpson36

example usage:

```
./zbctl --address zeebe-gateway.dev.jlscode.com:443 \
    --clientId zeebe \
    --clientSecret EasySecret \
    --authzUrl 'https://dev.jlscode.com/auth/realms/camunda-platform/protocol/openid-connect/token' \
    --audience zeebe-api --scope camunda-identity status
```

## Description

This allows users to set the scope for zbctl. For some reason, this scope attribute appears mandatory in 8.5 when installed with identity. I'm not sure why. 

## Related issues

closes #

2024-04-12 12:59 UTC, npepinpe requested changes
I would suggest making the help message consistent with the other options. Other than that, looks good :)

That said, I assume just setting the env var now without the flag would work anyway, no? :shrug:

2024-04-17 02:17 UTC, jessesimpson36 commented
I think you're right, the environment variable would work.  However, I started writing this PR before I knew the environment variable existed.  by that point, might as well follow through.

2024-04-17 02:18 UTC, jessesimpson36 commented on clients/go/cmd/zbctl/internal/commands/root.go
> +	rootCmd.PersistentFlags().StringVar(&scopeFlag, "scope", "", fmt.Sprintf("Specify the scope"))
I do like your message a lot better. I didn't quite know how to describe it.

2024-04-17 10:46 UTC, mustafadagher commented
@jessesimpson36 
❌ May I ask you to squash your commits into one with the message that follows our [Contributions Guide](https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md#commit-message-header)? 
PS: your first commit message was perfect! It's the second one that was generated by accepting github suggestion that's the issue

❌ Also, can you please rebase your PR branch on `main` to pass the `Tasklist merge queue CI`?

Thanks

2024-04-17 13:25 UTC, jessesimpson36 commented
Sounds good. I rebased  on main, and squashed the 2nd commit since it wasn't necessary to have that commit on it's own.

2024-04-17 13:27 UTC, npepinpe approved these changes
:+1:

2024-04-17 13:28 UTC, npepinpe commented
While not a bug fix, I think it's small enough to backport to 8.5, and as you mentioned this is more or less required for users on 8.5.

2024-04-17 15:47 UTC, merged

2024-04-17 15:47 UTC, backport-action commented
Successfully created backport PR for `stable/8.5`:
- #17553

2024-05-02 05:25 UTC, megglos commented
FYI the scope param is actually optional in the default SM setups, the failure on the scope was a bug in the go client, a [fix](https://github.com/camunda/zeebe/pull/18154) is ready