E2e tests restucture
camunda/camunda pull request #17506
Opened 2024-04-16 10:50 UTC by esraagamal6

## Description
Move filling fields functions from taskDetailsPage to utilitiesPage to reuse them in different pages

## Related issues

closes https://github.com/camunda/team-hto/issues/578

2024-04-16 13:57 UTC, vsgoulart requested changes
@esraagamal6 2 others things:

1. Please follow the instructions in [here](https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md/#commit-message-guidelines) for the commits
I recommend you squash all commits into one so it's easier

2. It looks like your IDE is not configured to auto-format/auto-fix linting issues. You have to looks how to configure ESLint and Prettier in it.
Please ping me on Slack if you need help

2024-04-16 13:57 UTC, vsgoulart commented on tasklist/client/e2e/tests/task-details.spec.ts
> +} from '../pages/UtilitiesPage';
Let's inject the page object model like we're doing with other page object classes instead of importing it like this

2024-04-16 13:57 UTC, vsgoulart commented on tasklist/client/e2e/pages/UtilitiesPage.ts
`UtilitiesPage` is too generic, let's use a more specific name.

We could try `FormJSDetailsPage` instead

2024-04-16 14:40 UTC, esraagamal6 commented on tasklist/client/e2e/pages/UtilitiesPage.ts
@vsgoulart It was intended to have it generic in order to use this page for all helper functions not just the formJS. WDYT

2024-04-16 15:10 UTC, vsgoulart commented on tasklist/client/e2e/pages/UtilitiesPage.ts
It's better to have a page object per concern, otherwise we'll end up throwing everything in this file and it will become giant an unmaintainable.

2024-04-18 09:05 UTC, vsgoulart requested changes

2024-04-18 09:58 UTC, esraagamal6 commented on tasklist/client/e2e/pages/FormJSDetailsPage.ts
> +    this.dateInput = page.getByPlaceholder('mm/dd/yyyy');
getByRole will have it as a textbox so it will be fail in case having a form with both components types

2024-04-18 12:26 UTC, vsgoulart requested changes

2024-04-18 12:26 UTC, vsgoulart commented on tasklist/client/e2e/pages/FormJSDetailsPage.ts
> +//import {TaskDetailsPage} from '../pages/TaskDetailsPage';
@esraagamal6 You forgot this one

```suggestion
```

2024-04-18 16:45 UTC, vsgoulart approved these changes

2024-04-18 17:09 UTC, merged