Convert numeric correlation key to string
camunda/camunda pull request #1761
Opened 2018-12-06 12:46 UTC by MiguelPires

Takes a numeric correlation key from the payload and converts it to a String such that it can be matched with an equivalent String correlation key from a published message.

closes #1667

2018-12-06 12:46 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9292073bddf54b0e57074234e79753338427fd79
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2018-12-07 07:08 UTC, saig0 requested changes

2018-12-07 07:08 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/CatchEventOutput.java
> +        final DirectBuffer buffer = result.getLongAsBuffer();
I think we can move this logic into `QueryResults`.

2018-12-07 07:08 UTC, saig0 commented on docs/src/bpmn-workflows/message-events.md
> +The correlation key is specified as [JSON Path](reference/json-conditions.html) expression. It is evaluated when the message event is entered and extracts the value from the workflow instance payload
I think a sentence is removed by merging ;)

2018-12-07 12:01 UTC, MiguelPires commented
Moved the conversion logic into the getLongAsString method in QueryResult and deleted getLongAsBuffer since it was no longer used. Also modified the tests and the documentation to reflect the changes.

2018-12-07 12:06 UTC, saig0 approved these changes

2018-12-07 12:06 UTC, saig0 commented
bors r+

2018-12-07 12:15 UTC, merged