feat(broker-core): allow multiple correlations on single message sub
camunda/camunda pull request #1768
Opened 2018-12-10 14:25 UTC by npepinpe

- adds closeOnCorrelate to records/commands to indicate a subscription should be implicitly closed on correlation; this is the default behaviour.
- publishing will correlate more than one message at a time to the same subscription if closeOnCorrelate is false.
- removes workflow instance sub from state on correlate if closeOnCorrelate

closes #1581

2018-12-10 14:32 UTC, npepinpe commented
I'm not a fan of the name `closeOnCorrelate` for the attribute of whether or not we implicitly close subscriptions on correlate, but I didn't come up with anything much better, so if you have an idea, I'm all for it!

Otherwise it should be as discussed: 

1. On opening a message subscription, we encoded whether or not we want to have it implicitly be closed on correlate.
1. A subscription `isCorrelatable` if it is non-implicitly closable on correlate, or if it is, if it is not currently correlating.
1. If a subscription is correlatable, on publish we will try to correlate it.
1. On correlating a message/workflow subscription, if it has `closeOnCorrelate` true, we remove it from the state, or reset its `sentTime`/remove deadlines if it is false.

2018-12-12 14:27 UTC, saig0 requested changes

2018-12-13 08:45 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/message/CorrelateWorkflowInstanceSubscription.java
> +          "subscription was already correlated or is closing");
I don't think we do, no. You mean handling that on the message partition side and remove the subscription that initially sent the correlate to the workflow partition?

2018-12-13 08:49 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/message/PendingWorkflowInstanceSubscriptionChecker.java
> +    } else { // neither closing nor opening, nothing to be done
Ah, you're right, I guess it's just a bit hidden since we actually have three states.

2018-12-13 08:58 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/subscription/message/processor/PublishMessageProcessor.java
> +          if (subscription.isCorrelatable()
It partially works at the moment, and it's related to the previous point with the pending checker. At the moment, the initial correlate workflow commands would contain each their correct payloads, but then if the pending checker were to process them they'd always contain the latest payload. My bad, I'll fix that today

2018-12-17 15:51 UTC, npepinpe commented
After spending time trying to allow many in-flight correlations, I realized this was way more complicated than it's worth, so I went back to correlating one message at a time.

Missing some tests at the moment, will add them tomorrow.

2018-12-18 14:21 UTC, npepinpe commented
Should be complete now.

I removed tracking all correlations and decided to go for the less sexy but simpler way of correlating a single message at a time; when the correlation is finished (i.e. the workflow partition has acknowledged it), we attempt to correlate the next not-yet correlated message available for the subscription (if any).

2018-12-19 07:13 UTC, saig0 approved these changes

2018-12-19 08:05 UTC, npepinpe commented
bros r+

2018-12-19 08:05 UTC, npepinpe commented
bors r+

2018-12-19 08:28 UTC, merged