chore(bpmn-model): allow timer start events in model
camunda/camunda pull request #1788
Opened 2018-12-14 08:18 UTC by MiguelPires

Allows BPMN models to specify start events with timer definitions.

closes #1786

2018-12-14 09:08 UTC, menski requested changes
A sub process can only have a none start event, at the moment a sub process with a timer would validate, which I think we should prevent.

2018-12-14 09:08 UTC, menski commented on bpmn-model/src/main/java/io/zeebe/model/bpmn/validation/zeebe/StartEventValidator.java
> +              0, "Start event must of one of the following types: none, timer");
```suggestion
              0, "Start event must be one of the following types: none, timer");
```

2018-12-14 11:07 UTC, MiguelPires commented
Changed the subprocess validation to only allow none start events

2018-12-17 09:20 UTC, menski approved these changes

2018-12-17 10:20 UTC, MiguelPires commented
bors r+

2018-12-17 10:23 UTC, menski commented
bors r-

2018-12-17 10:39 UTC, MiguelPires commented
Sorry, forgot. All done now

2018-12-17 10:39 UTC, MiguelPires commented
bors r+

2018-12-17 10:49 UTC, merged