fix: updates ILM policy based on settings
camunda/camunda pull request #18122
Opened 2024-04-30 14:52 UTC by robert-sorkin

## Description

On restart, applies ILM policy to all existing indices if ILM is enabled, or removes it if it is disabled

## Related issues

closes #17147

2024-05-02 12:39 UTC, ralfpuchert requested changes
I tested with Elasticsearch and OpenSearch. Works and LGTM, but not all indices are involved see comments.

2024-05-02 12:39 UTC, ralfpuchert commented on operate/schema/src/main/java/io/camunda/operate/schema/elasticsearch/ElasticsearchSchemaManager.java
> +    indexDescriptors.forEach(
I think you missed the other indices which can be find under 

`List<TemplateDescriptor> templateDescriptors;`

If you debug or use logs like these in `SchemaManager`s
```java
final var added =
                setIndexSettingsFor(indexSettings, descriptor.getDerivedIndexNamePattern());
            LOGGER.info("Add ILM for {}: {}", descriptor.getDerivedIndexNamePattern(), added);
```
and for delete
```java
 final var deleted =
                retryElasticsearchClient.deleteIndexPolicyFor(
                    descriptor.getDerivedIndexNamePattern());
            LOGGER.info("Deleted ILM for {}: {}", descriptor.getDerivedIndexNamePattern(), deleted);
```
you can see which indices are affected.

2024-05-03 07:31 UTC, ralfpuchert approved these changes

2024-05-03 15:15 UTC, matt-whiteman commented
@robert-sorkin This PR needs to be rebased to main to pick up the license header changes, and the two new files need to have the correct license header. The merge queue issues are because they're failing that check.

2024-05-03 16:35 UTC, merged