feat: add and setup C3 configuration provider component to operate
camunda/camunda pull request #18189
Opened 2024-05-02 14:26 UTC by vitorwtavares

## Description
- Adds and configures C3UserConfigurationProvider to Operate
- Refactor of App Header
- Addition of teaser pages for other apps

## Related issues

closes camunda/operate#6293

2024-05-27 15:06 UTC, pedesen requested changes

2024-05-27 15:06 UTC, pedesen commented on operate/client/package.json
> +    "@carbon/react": "1.57.0",
This is 1.57.0 on `main` now. So you should be able to rebase. Then there should be no changes needed for package.json and yarn.lock

2024-05-27 19:24 UTC, pedesen approved these changes
The visual regression snapshots are part of the changelog even though they are identical. I think you could squash the two commits https://github.com/camunda/camunda/pull/18189/commits/2d84c69de4ad493fc6f12b0bb67cb9785dea595e and https://github.com/camunda/camunda/pull/18189/commits/3d542cf7761919946ffc8c7d608a2559c12ed2e8 to avoid this. But it's not a big deal.

2024-05-29 19:44 UTC, Szik commented
![Bildschirmfoto vom 2024-05-29 19-34-32](https://github.com/camunda/camunda/assets/26524171/1ab55364-ea29-43c5-899b-2e1e5033a494)

List of Camunda Components is empty

2024-06-03 12:05 UTC, Szik requested changes
Camunda Compontents list is empty

2024-11-25 21:22 UTC, vitorwtavares commented
Closing this PR as it's stale and this feature is not high priority at the moment. The branch will be kept so we can update it and keep the work already done whenever we decide to pick this back up.

2024-11-25 21:22 UTC, closed without merging