feat(broker): support timer start event
camunda/camunda pull request #1818
Opened 2018-12-19 16:28 UTC by MiguelPires

Implements timer start events with the restriction that there can be only one per workflow.

closes #1787

2018-12-20 10:26 UTC, saig0 requested changes

2018-12-20 17:06 UTC, MiguelPires commented
I made some changes incorporating your feedback. This commit does a couple of things:

- Refactors the tests
- Only creates the timer in the partition with the lowest id
- Uses the workflow key instead of the bpmn id to avoid rescheduling the timer with the new properties
- Creates and removes timers using existing processors/methods

2018-12-21 08:24 UTC, saig0 requested changes

2019-01-02 07:03 UTC, saig0 requested changes
Almost perfect. Just a few tiny things to speed up the tests.

2019-01-02 07:03 UTC, saig0 commented on broker-core/src/test/java/io/zeebe/broker/workflow/TimerStartEventTest.java
>              .getLast()
Same here, the test waits 5 seconds because of `getLast()`.

2019-01-02 09:43 UTC, saig0 requested changes

2019-01-02 09:43 UTC, saig0 commented on broker-core/src/test/java/io/zeebe/broker/workflow/TimerStartEventTest.java
> +        RecordingExporter.timerRecords(TimerIntent.CREATED).limit(3).asList().get(2).getValue();
This is a bit shorter:

```suggestion
        RecordingExporter.timerRecords(TimerIntent.CREATED).skip(2).getFirst().getValue();
```

2019-01-02 09:58 UTC, saig0 approved these changes

2019-01-02 10:10 UTC, MiguelPires commented
bors r+

2019-01-02 10:13 UTC, MiguelPires commented
bors cancel

2019-01-02 10:15 UTC, MiguelPires commented
bors r-

2019-01-02 10:34 UTC, MiguelPires commented
bors r+

2019-01-02 10:44 UTC, merged