chore(broker-core): support multiple timer start events
camunda/camunda pull request #1829
Opened 2019-01-02 11:48 UTC by MiguelPires

This feature enables the user to use muliple timer start events. It uses a deferred token to start the event that triggered the workflow creation.

closes #1816

2019-01-03 11:02 UTC, saig0 requested changes
It is a good idea and it works! However, it is different from the other event handling and I think also different from the message start event handling. We should talk about it and find a uniform way.

2019-01-03 12:53 UTC, MiguelPires commented
Thanks. The latest changes incorporate your feedback on the logic and remove a couple of redudant tests. For reference, the uniformization between approaches will be done in #1835

2019-01-03 13:57 UTC, saig0 requested changes
Just one tiny thing left.

2019-01-03 13:57 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/instance/CreateWorkflowInstanceHandler.java
> +      } else if (workflowDefinition.getWorkflow().getStartEvents().size() > 1) {
The command should be also rejected if the workflow has exactly one timer/message start event.

2019-01-03 15:42 UTC, MiguelPires commented
I changed what you mentioned

2019-01-04 06:52 UTC, saig0 requested changes

2019-01-04 06:52 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/subprocess/TriggerStartEventHandler.java
> +  public static boolean isNoneStartEvent(ExecutableCatchEventElement startEvent) {
I think it's better to move this logic into `ExecutableCatchEventElement` instead of having a dependency between the handlers.

2019-01-04 08:24 UTC, saig0 approved these changes

2019-01-04 08:56 UTC, MiguelPires commented
bors r+

2019-01-04 09:06 UTC, merged