chore(gateway): re-poll partition if BatchRecord was truncated
camunda/camunda pull request #1904
Opened 2019-01-23 10:24 UTC by MiguelPires

This PR re-polls the broker to obtain new jobs if the previous JobBatchRecord was truncated.

closes #1896

2019-01-23 12:20 UTC, saig0 requested changes

2019-01-23 12:20 UTC, saig0 commented on qa/integration-tests/src/test/java/io/zeebe/broker/it/job/ActivateJobsTest.java
> +        .isEqualTo(numJobs);
We should ensure that truncation has happened. It can be that we increase the limit or change the JSON.

2019-01-23 15:50 UTC, MiguelPires commented
I included an assertion making sure the BatchRecord was truncated.

2019-01-24 06:20 UTC, saig0 requested changes

2019-01-24 06:20 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/exporter/record/value/JobBatchRecordValueImpl.java
> +  public boolean getTruncated() {
```suggestion
  public boolean isTruncated() {
```

2019-01-24 11:35 UTC, saig0 approved these changes

2019-01-24 11:42 UTC, MiguelPires commented
bors r+

2019-01-24 11:53 UTC, merged