fix(broker-core): ignore empty or invalid task headers
camunda/camunda pull request #1909
Opened 2019-01-23 17:22 UTC by MiguelPires

Changes:
* Ignores empty or invalid task headers while logging it in the broker
* Improves the error the user gets when model's XML is invalid

closes #1902

2019-01-24 15:32 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/workflow/model/transformation/transformer/ServiceTaskTransformer.java
> +        LOG.warn("Found task headers with no key or value. Ignoring");
We don't care which headers where invalid?

2019-01-24 15:37 UTC, npepinpe requested changes
Looks good, only 2 things.

2019-01-24 15:37 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/workflow/model/transformation/transformer/ServiceTaskTransformer.java
> +      if (validHeaders != null && !validHeaders.isEmpty()) {
In which case would `validHeaders` be null? Even if we filter an empty list, we still get an empty list, no?

2019-01-24 15:37 UTC, npepinpe commented on broker-core/src/test/java/io/zeebe/broker/workflow/activity/ActivityTest.java
> +  public void shouldIgnoreTaskHeadersIfEmptyOrNull() {
Can we split this into two tests, one testing empty, and the other testing null? Ideally we'd test also when the key and values are valid (i.e. key is empty or null, but value isn't, and vice versa).

2019-01-24 16:47 UTC, MiguelPires commented
Thanks for the feedback. I updated the code to fix those issues

2019-01-25 10:09 UTC, npepinpe approved these changes
Looks good :+1:

2019-01-25 10:51 UTC, MiguelPires commented
bors r+

2019-01-25 11:01 UTC, merged