Not subscribe to new subscription if element is in ACTIVATING state
camunda/camunda pull request #19256
Opened 2024-06-11 11:27 UTC by nicpuppa

## Description

During PIM (Process Instance Migration) an element shouldn't subscribe into a new subscription if the element state is `ACTIVATING`, due to a previous incident occurred

## Related issues

closes #19212

2024-06-11 12:53 UTC, korthout requested changes
Thanks @nicpuppa 

❌ We need some more changes, because the bug can also surface when completing the activity.

2024-06-11 14:30 UTC, korthout commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java
> +      final long processInstanceKey, final String elementId) {
This will require some auto formatting: `mvn spotless:apply`

2024-06-11 14:48 UTC, korthout commented
@nicpuppa Can you have a look at my last changes?

2024-06-11 14:48 UTC, korthout approved these changes

2024-06-11 14:50 UTC, korthout commented
@berkaycanbc Would be nice to have a review from you on these changes as well 🙇

2024-06-11 14:57 UTC, nicpuppa reviewed
LGTM

2024-06-11 16:37 UTC, berkaycanbc approved these changes
✅ Allowing incident migration on intents `ELEMENT_TERMINATING` and `ELEMENT_COMPLETING` looks okay. For `ELEMENT_TERMINATING`, we already resolve incidents right after writing the command, so we won't fall into this case at all. For `ELEMENT_COMPLETING`, we already have the message subscription created.

👍 I requested one change which only adds more clarity around the implementation. Feel free to merge afterwards. 


⚠️ **Note:** for the implementation of message subscriptions migration (migrating message subscriptions instead of re-creating), we need to reject migration when the element is in `ELEMENT_ACTIVATING` state. Because, a boundary event actually exists in the source definition but the subscription is not created, so nothing to migrate.

2024-06-11 16:37 UTC, berkaycanbc commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationMigrateProcessor.java
> +      // element in ACTIVATING state should not be subscribed into new subscription during migration
🔧 This comment doesn't explain the "why". Let's mention the ACTIVATING element will not have any message subscriptions created yet, so we shouldn't create one in the target process. The subscription will be created when the incident is resolved in the target element.

2024-06-11 19:28 UTC, berkaycanbc approved these changes

2024-06-12 07:55 UTC, korthout commented
> ⚠️ Note: for the implementation of message subscriptions migration (migrating message subscriptions instead of re-creating), we need to reject migration when the element is in ELEMENT_ACTIVATING state. Because, a boundary event actually exists in the source definition but the subscription is not created, so nothing to migrate.

@berkaycanbc I believe we can find a better solution. I'll write down my thoughts in some follow-up issues that we should take a long with the instance migration topic.

2024-06-12 12:17 UTC, korthout commented
What is happening with the merge queue? 🤔

2024-06-12 12:42 UTC, korthout commented
Keep on getting `Could not acquire write lock for ...` maven build errors. Another try

2024-06-12 12:53 UTC, korthout commented
>java.lang.IllegalStateException: Could not acquire lock(s)

Again...

2024-06-12 13:33 UTC, merged

2024-06-12 13:33 UTC, backport-action commented
Successfully created backport PR for `main`:
- #19302