chore(broker-core): migrate membership management to atomix
camunda/camunda pull request #1940
Opened 2019-01-30 12:31 UTC by deepthidevaki

closes #1924

2019-01-30 12:43 UTC, ChrisKujawa requested changes
Looks good, just some small requests :+1:

2019-01-30 12:43 UTC, Zelldon commented on broker-core/src/main/java/io/zeebe/broker/clustering/ClusterComponent.java
> +        .dependency(ATOMIX_SERVICE, atomixJoinService.getAtomixInjector())
Can we have also a dependency on `TOPOLOGY_MANAGER_SERVICE`, so we can be sure that they start in order. I think this is also a bug in the old implementation.

2019-01-30 12:43 UTC, Zelldon commented on broker-core/src/main/java/io/zeebe/broker/clustering/base/gossip/AtomixService.java
> +  public void stop(ServiceStopContext stopContext) {}
we can remove this

2019-01-30 12:43 UTC, Zelldon commented on broker-core/src/main/java/io/zeebe/broker/clustering/base/topology/TopologyManagerImpl.java
> +  protected void onActorStarting() {}
Please remove the empty methods :)

2019-01-30 12:43 UTC, Zelldon commented on broker-core/src/main/java/io/zeebe/broker/clustering/base/topology/TopologyManagerImpl.java
> +              final Properties newProperties = eventSource.properties();
Can we extract this in a new method so this method is not that long, please?

2019-01-30 12:43 UTC, Zelldon commented on broker-core/src/main/java/io/zeebe/broker/clustering/base/topology/TopologyManagerImpl.java
> +              final ObjectMapper mapper = new ObjectMapper();
We can reuse the ObjectMapper in this class, simply create one on creation time.

2019-02-03 10:44 UTC, Zelldon commented
Hey guys,

had over the weekend a closer look why the IT tests are failing and at our atomix setup. You can take a 
look at atomix-gossip-test branch for the latest changes.

As @deepthidevaki found out that PartitionGroup creating only on the first node is problematic on start up it is also error prone on closing the fist node. See this bug issue https://github.com/atomix/atomix/issues/999 , which I opend yesterday. That was an issue which we had in the IT tests.

We should also not use the `Atomix` class, instead more his base class `AtomixCluster`.
The `AtomixCluster` can be used without partition groups and is more for cluster bootstrapping, cluster membership and communication, which is currently our use case. If you want to use primitives on top, then you can use the `Atomix` class. This will reduce our memory and threading footprint for now as well.

Setup would look similar then before, but without the partition groups. I also configured the SwimProtocol, such that the leave time out is 2 sec instead of 10 (default). In some test we wait until a member is removed from the topology, which will only happen after the `MEMBER_REMOVED` is published. 

Currently on the atomix-gossip-test I have still failing tests, because some ports are not freed.

2019-02-04 09:06 UTC, deepthidevaki commented
Thanks @zell for looking into the issue. We can incorporate your findings in a separate PR. I am finishing up this PR. @menski You can have a look at this.

2019-02-04 16:24 UTC, menski commented
@deepthidevaki this change introduces some info log messages, do you thing they are useful and should be logged on info level? Maybe some should be removed, trace or debug? 

Also the message `Im node {}, event received from {} {}. Nothing to do` should be reworded in my opinion, or maybe just removed?

2019-02-04 16:44 UTC, merged