feat: add role management for a group to identity's UI
camunda/camunda pull request #19773
Opened 2024-06-26 08:34 UTC by maryarm

## Description
We need to be able to view/assign/unassign roles to a Groupin UI.

## Related issues
Part of identity issue ([#2946](https://github.com/camunda-cloud/identity/issues/2947))

2024-06-27 15:33 UTC, dlavrenuek requested changes
Looks good already. I would do some refactoring (as part of copying current implementation) so we have a clean and structured code to work with in the future

2025-04-07 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda?pullRequest=19773) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda?pullRequest=19773) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda?pullRequest=19773) it.</sub>

2025-08-20 13:05 UTC, npepinpe commented
@maryarm - I guess we should close this? It's probably very outdated, no?

2025-10-01 08:04 UTC, cmur2 commented
@maryarm can this be closed?

2025-11-13 12:07 UTC, closed without merging