[Backport stable/8.5] feat: allow overriding default maxInboundMetadataSize through config and change default to 16KB
camunda/camunda pull request #20059
Opened 2024-07-04 15:06 UTC by mustafadagher

# Description
Backport of #20002 to `stable/8.5`.

relates to #19829 #11284 #19591

2024-07-04 15:07 UTC, mustafadagher commented
I have no clue what happened with this one https://github.com/camunda/camunda/pull/20044

2024-07-04 15:16 UTC, korthout requested changes, later dismissed
❌ The tests for `spring-boot-starter-camunda-sdk` are missing. As the code is so different, we need to test this in order to release it.

2024-07-10 07:17 UTC, remcowesterhoud approved these changes

2024-07-10 07:18 UTC, remcowesterhoud commented
I cannot merge this yet as it requires approval from @korthout

2024-07-16 11:18 UTC, merged