fix: timers of banned instances are forever re triggered
camunda/camunda pull request #20462
Opened 2024-07-23 14:47 UTC by berkaycanbc

## Description

## Related issues

closes #14213

2024-07-25 09:15 UTC, korthout requested changes
Thanks @berkaycanbc 

💭 I'm still in favor of options 2 and 3 over the proposal in this PR. When we take either of those options, we'd revert the changes in this PR again. So, my proposal is not to take merge this PR and instead apply option 2 or 3 immediately. AFAIK, [you already found a solution](https://github.com/camunda/camunda/issues/14213#issuecomment-2239304772) for options 2 or 3.

❌ In case you do want to continue with this PR: I've requested changes that must be applied before merging.

2024-07-25 09:15 UTC, korthout commented on zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/TimerTriggerBannedInstanceIT.java
> +                .limit(t -> t.getIntent() == TimerIntent.TRIGGERED)
❌ This limit is placed wrongly causing slow test execution. 

There is no `TRIGGERED` event on the banned process instance, only on the second (non-banned) process instance. So, this limit simply waits 5 seconds and then continues. To ensure a fast test, you'll need to flip the order of these calls. First limit for a `TRIGGERED` event, then filter the stream for the records of the banned process instance, before finally asserting that only a single `TRIGGER` command exists.

2024-07-25 09:15 UTC, korthout commented on zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/TimerTriggerBannedInstanceIT.java
> +                .onlyCommands())
🔧 `.onlyCommands()` is redundant after filtering for the `TRIGGER` intent

2024-07-26 13:20 UTC, berkaycanbc commented
@korthout thanks for reviewing the PR!

> 💭 I'm still in favor of options 2 and 3 over the proposal in this PR. When we take either of those options, we'd revert the changes in this PR again. So, my proposal is not to take merge this PR and instead apply option 2 or 3 immediately. AFAIK, https://github.com/camunda/camunda/issues/14213#issuecomment-2239304772 for options 2 or 3.

I agree actually, this one was a half day effort, so will not hurt to throw away. We can start with implementing option 3 and tackle the option 2 in a separate PR. If we implement them successfully, we can close this one.

2024-07-26 13:40 UTC, korthout commented
In that case let's close this PR @berkaycanbc

2024-08-05 12:40 UTC, closed without merging