ci: update optimize snapshot and latest docker tags
camunda/camunda pull request #20614
Opened 2024-07-30 09:10 UTC by OmranAbazid

## Description

See https://github.com/camunda/camunda-optimize/issues/13498

2024-08-01 15:14 UTC, OmranAbazid commented
We need to adjust this PR to respect the changes done in:
https://github.com/camunda/camunda/pull/20613

2024-08-26 13:00 UTC, RomanJRW requested changes
In the pom, there is a section for cleaning up the docs linked, marked with: `<!-- Remove -SNAPSHOT, -rcX, and -alphaX from docs version if it exists -->`. Does the logic here need adjusting too?

2024-08-26 13:08 UTC, OmranAbazid commented on .github/optimize/scripts/build-docker-image.sh
> +    tags+=("${DOCKER_IMAGE_DOCKER_HUB}:8-SNAPSHOT")
Not sure what you mean here.
I think the snapshot docker tag is not preceded with a version number.
When pulling the snapshot, we used to pull it like this: `docker image pull camunda/optimize:SNAPSHOT`

If we keep it as it is now, both optimize 7 and optimize 8 will keep overriding the image.

2024-08-26 18:25 UTC, RomanJRW approved these changes
Approve here, as long as the dependencies listed on the issue are also taken care of 👍

2024-08-27 10:22 UTC, OmranAbazid commented
> In the pom, there is a section for cleaning up the docs linked, marked with: " Remove -SNAPSHOT, -rcX, and -alphaX from docs version if it exists ". Does the logic here need adjusting too?

I think there is a difference between the snapshot version of the docker image and the snapshot development version.
I only adjusted the snapshot docker image, but the snapshot development version is still the same.

Therefore, I think we do not need to update the regex logic.

2024-08-27 16:28 UTC, merged