feat: store deployment key for deployed decisions
camunda/camunda pull request #20628
Opened 2024-07-30 14:03 UTC by jfriedenstab

## Description

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues
part of #19709

2024-07-30 16:21 UTC, jfriedenstab commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbDecisionState.java
> -    dbDecisionKey.wrapLong(record.getDecisionKey());
Decision key is already wrapped in line 347.

2024-07-31 14:45 UTC, korthout approved these changes
Awesome @jfriedenstab 🚀 

👍 LGTM

2024-07-31 14:45 UTC, korthout commented on zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/CreateDeploymentMultiplePartitionsTest.java
> +                  .getFirst();
🔧 Nit: no need to limit to 1 if we're getting the first. `getFirst()` would already short circuit if an entry is available.

2024-07-31 14:45 UTC, korthout commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/mutable/MutableDecisionState.java
> +   */
👍 I like the docs

2024-07-31 14:45 UTC, korthout commented on zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/deployment/DecisionStateTest.java
> +  void shouldFindDeployedDecisionByIdAndDeploymentKey() {
👍 Good test

2024-07-31 14:45 UTC, korthout commented on zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/deployment/DecisionStateMultiTenantTest.java
> +    final var drg2 = sampleDecisionRequirementsRecord(tenant2, drgKey, drgId, version);
💭 This test is a bit strange. It considers 2 DRGs belonging to different tenants, but they have the same key (`drgKey`). This already is the case in the test above (where this is likely copied from), so let's just accept it. It's not what this test focusses on, but just seems a bit strange.

2024-07-31 14:49 UTC, korthout requested changes
I see now that there's something missing

❌ Please ensure we remove decisions from the new column family on deletion

2024-07-31 15:14 UTC, jfriedenstab commented
Thanks for the review!

> ❌ Please ensure we remove decisions from the new column family on deletion

This is actually done here:
https://github.com/camunda/camunda/blob/eba24c9386eaff49e48608dd4b1cf60aec2540a3/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbDecisionState.java#L461
(and also covered by "should not find decision after it has been deleted" in `DecisionStateTest`).

Or did I miss anything?

2024-07-31 15:24 UTC, korthout commented
Oops. I missed it. Sorry @jfriedenstab

2024-07-31 15:24 UTC, korthout approved these changes
LGTM

2024-07-31 16:40 UTC, merged

2024-08-01 06:04 UTC, megglos commented
/backport

2024-08-01 06:04 UTC, backport-action commented
Successfully created backport PR for `release-8.6.0-alpha4`:
- #20685