Include Zeebe User Task priority in Tasklist
camunda/camunda pull request #20828
Opened 2024-08-06 14:32 UTC by panagiotisgts

## Description

Include the new Priority field for ZeebeUserTasks in Tasklist indices and ES/OS searching and sorting.
## Related issues

closes #20604

2024-08-08 12:59 UTC, marcosgvieira requested changes
Hey @panagiotisgts I believe you did the implementation on GraphQL (we don't need to cover GraphQL for priority field, only REST V1)

I was expecting to see changes on:

- https://github.com/camunda/tasklist/blob/dfccae9e92e26a42c1b9c85cb09774845a7854e0/webapp/src/main/java/io/camunda/tasklist/webapp/api/rest/v1/entities/TaskSearchRequest.java
- https://github.com/camunda/tasklist/blob/fd7be96ed0e050520b40b981836b4ea5d03332c0/webapp/src/main/java/io/camunda/tasklist/webapp/api/rest/v1/entities/TaskSearchResponse.java
- https://github.com/camunda/tasklist/blob/1ddd748972c150b0291745e8dc61b0f3ed65446c/webapp/src/main/java/io/camunda/tasklist/webapp/api/rest/v1/controllers/TaskController.java#L107

Was this covered already?

2024-08-08 13:01 UTC, panagiotisgts commented
@marcosgvieira These will be on a different PR for the respective #20605 ticket.

2024-08-12 10:00 UTC, marcosgvieira commented
@panagiotisgts overall, looks good, just a minor change on the importers to review :)
good work.

2024-08-12 11:06 UTC, panagiotisgts commented on tasklist/importer-860/src/main/java/io/camunda/tasklist/zeebeimport/v860/processors/common/UserTaskRecordToTaskEntityMapper.java
The default value is being set by Zeebe, so I don't think it would make any difference in having Tasklist support it in 8.5 records. Also, since there would never be a value for this field until 8.6, it would just be a NULL filled column in the schema.

On Tasklist 8.6 migration, everything will have the sort value of 50 if queried. The column itself (i believe) will be generated with the first Zeebe User Task 8.6 record ingestion, defaulting to NULL for everything present. Is there something I am missing? @marcosgvieira

2024-08-12 12:24 UTC, marcosgvieira commented on tasklist/importer-860/src/main/java/io/camunda/tasklist/zeebeimport/v860/processors/common/UserTaskRecordToTaskEntityMapper.java
The only thing we may miss is when creating the new version (we usually just rename the old package to the new version - as is much easier then duplicate everything). When doing that we need then to duplicate the newest version and refactor it, rather than renaming the old version (that seems more correct to me tbh), when creating the 8.7 importers/exporters please remember the team about that :)

2024-08-12 12:24 UTC, marcosgvieira approved these changes

2024-08-13 10:31 UTC, merged