test: ensure that controlled actor scheduler starts idle
camunda/camunda pull request #21043
Opened 2024-08-12 10:56 UTC by lenaschoenburg

When starting the `ControlledActorScheduler`, we also need to ensure that it runs long enough to become idle initially. Without waiting, the thread might start a bit late, after initial actor tasks were submitted already. In that case the thread _should_ be idle and wait for an explicit `workUntilDone` call and not execute the task. We now ensure this by waiting for idle state after starting the thread.

This hopefully closes #13493 because the mocked/spied objects are no longer accessed concurrently.

2024-08-13 15:03 UTC, npepinpe requested changes
:x: I think we need to add it to the `ControlledActorSchedulerExtension` as well, no?

2024-08-13 15:39 UTC, lenaschoenburg commented
Good catch, didn't think of that one :+1:

2024-08-14 06:26 UTC, deepthidevaki approved these changes
Thanks

2024-08-14 06:31 UTC, npepinpe approved these changes

2024-08-14 06:48 UTC, merged

2024-08-14 06:49 UTC, backport-action commented
Successfully created backport PR for `stable/8.2`:
- #21118

2024-08-14 06:49 UTC, backport-action commented
Successfully created backport PR for `stable/8.3`:
- #21119

2024-08-14 06:49 UTC, backport-action commented
Successfully created backport PR for `stable/8.4`:
- #21120

2024-08-14 06:49 UTC, backport-action commented
Successfully created backport PR for `stable/8.5`:
- #21121