chore: remove optimize C7 test dependencies
camunda/camunda pull request #21166
Opened 2024-08-14 21:02 UTC by RomanJRW

## Description

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

2024-08-15 07:49 UTC, misiekhardcore commented
@RomanJRW I added one more commit with more cleanup

2024-08-20 12:37 UTC, misiekhardcore commented on .github/workflows/optimize-deploy-artifacts.yml
> +        timeout: 600
we need to reduce this timeout to something reasonable

2024-08-20 12:41 UTC, misiekhardcore commented on .github/workflows/optimize-deploy-artifacts.yml
> +        OPTIMIZE_IMAGE_TAG: ${{ env.RELEASE_VERSION }}
why do we do this change here?

2024-08-28 06:43 UTC, misiekhardcore commented on .github/workflows/optimize-deploy-artifacts.yml
> +        timeout: 600
actually we can remove this param here completely, the default value of 300s works fine

2024-08-28 14:57 UTC, matthewBearCamunda requested changes
The changes LGTM, however I did find references to h2 and postgres in `optimize/backend/src/it/java/io/camunda/optimize/test/it/extension/EngineDatabaseExtension.java.out`

Does that file, and possibly the others in the same directory, need adjusting too?

2024-08-28 15:03 UTC, RomanJRW commented
@matthewBearCamunda - good question. Ultimately, we are likely to delete all the IT things because of their C7-centricity, including this extension (this is even Engine specific). So it will be deleted in a separate PR. For the moment, the code is commented out and it has no impact here

2024-08-28 15:04 UTC, matthewBearCamunda approved these changes
Makes sense, approved!

2024-08-29 09:31 UTC, merged