fix(broker-core): set repetitions on cancel timer
camunda/camunda pull request #2117
Opened 2019-03-01 08:50 UTC by MiguelPires

Besides the bug fix and test, this PR also adds some data that was missing from the timer's exported record.

closes #2114

2019-03-01 10:29 UTC, npepinpe requested changes
Just ping me when you've worked in what we discussed.

2019-03-01 14:25 UTC, MiguelPires commented
Hey @npepinpe, I made the changes you suggested. Let me know what you think

2019-03-04 11:18 UTC, npepinpe approved these changes

2019-03-04 13:26 UTC, MiguelPires commented
bors r+

2019-03-04 13:58 UTC, merged