Operate/incident controller
camunda/camunda pull request #21414
Opened 2024-08-21 09:03 UTC by ralfpuchert

## Description

* Add Incident endpoint structure for /v2/incidents/search
* Add Controller, Filter, Sort components

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

Related to #20661

2024-08-22 12:33 UTC, nathansandi requested changes
Great work here, just minors suggestions/improvements.

2024-08-22 12:33 UTC, nathansandi commented on zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/IncidentQueryController.java
> +      final var problemDetail =
🔧  Related to my previous comment, 
This error could be managed like this 

```
  } catch (final ValidationException e) {
      final var problemDetail =
          RestErrorMapper.createProblemDetail(
              HttpStatus.BAD_REQUEST,
              e.getMessage(),
              "Validation failed for UserTask Search Query");
      return RestErrorMapper.mapProblemToResponse(problemDetail);
    } catch (final Exception e) {
      final var problemDetail =
          RestErrorMapper.createProblemDetail(
              HttpStatus.INTERNAL_SERVER_ERROR,
              e.getMessage(),
              "Failed to execute UserTask Search Query");
      return RestErrorMapper.mapProblemToResponse(problemDetail);
```

So we separate validation erros vs. Internal ones

2024-08-23 06:15 UTC, ralfpuchert commented on service/src/main/java/io/camunda/service/search/filter/IncidentFilter.java
> +    DateValueFilter creationTimeFilter,
Thank you, haven't noticed yet. Will remove this.

2024-08-23 08:22 UTC, nathansandi approved these changes
Great work 💯  :)

2024-08-23 09:32 UTC, merged