fix: Operate OpenSearch AWS config can't be disabled
camunda/camunda pull request #21481
Opened 2024-08-22 09:36 UTC by kristinkomschow

## Description
Introduced the property `camunda.operate.opensearch.awsEnabled` which is now checked for before using AWS credentials to allow for using basic auth even when AWS credentials are set.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #https://github.com/camunda/camunda/issues/20939

2024-08-23 05:31 UTC, ralfpuchert requested changes
LGTM so far. Can you check whether the changed code can be tested (by unit tests)? 
I think we need to change also [documentation](https://github.com/camunda/camunda-docs/blob/main/docs/self-managed/operate-deployment/operate-configuration.md) for it and need to inform or create an issue for [distribution](https://github.com/camunda/distribution) team to adjust helm charts setting the right value. I'm not sure if this was already clarified.

2024-08-23 05:31 UTC, ralfpuchert commented on operate/common/src/main/java/io/camunda/operate/connect/OpensearchConnector.java
> +    if (hasAwsCredentials()) {
Thanks for making this clearer :)

2024-08-23 06:58 UTC, kristinkomschow commented
I'll look into adding unit tests and updating the documentation today. Thanks!

There already is an issue for updating the helm charts: https://github.com/camunda/camunda-platform-helm/issues/2215

2024-09-03 13:45 UTC, kristinkomschow commented
Documentation update PR is here: https://github.com/camunda/camunda-docs/pull/4234

2024-09-03 14:38 UTC, ralfpuchert approved these changes

2024-09-03 15:02 UTC, merged

2024-09-03 15:02 UTC, backport-action commented
Successfully created backport PR for `stable/operate-8.5`:
- #21883