fix: stop zeebe task completion variables from being serialized
camunda/camunda pull request #21764
Opened 2024-08-30 09:28 UTC by panagiotisgts

## Description

Address tasklist issue mentioned [here](https://camunda.slack.com/archives/C046XS3GGCR/p1724945281241419?thread_ts=1724936257.713079&cid=C046XS3GGCR): Completed Zeebe User Task form variables were being flushed as serialized JSON values in ES/OS

2024-09-09 12:25 UTC, nathansandi commented
The importers were just updated with the list-view setup,

Is this change necessary on the list view requests as well?

2024-09-09 14:45 UTC, houssain-barouni commented
@panagiotisgts before `Json.createValue` we were previously using org.json.JSONObject(string) that transforms primitive types (booleans, numbers, nulls) to their respective types
We have removed the use of org.json.JSONObject in https://github.com/camunda/camunda/pull/19279  but probably not with the right implementation
can you confirm that it works with native types ? for example `"true"` should not be replaced with `"\"true\""`

2024-09-10 05:31 UTC, panagiotisgts commented
Hey @houssain-barouni, run over a form to provide the values for cross checking, I believe we are good, if you can verify this also.  This is the view from the `tasklist-task-variable` index regarding a set of variables present on the form
![image](https://github.com/user-attachments/assets/49cdb716-3b10-4f1b-b4e2-c3830bf84a19)

And this is the response of the API for `v1/tasks/{uuid}/variables/search`
```json
[ {
  "id" : "2251799813685272-checkbox_pw88bp",
  "name" : "checkbox_pw88bp",
  "value" : "\"false\"",
  "isValueTruncated" : false,
  "previewValue" : "\"false\"",
  "draft" : null
}, {
  "id" : "2251799813685272-checkbox_zvnb6",
  "name" : "checkbox_zvnb6",
  "value" : "\"true\"",
  "isValueTruncated" : false,
  "previewValue" : "\"true\"",
  "draft" : null
}, {
  "id" : "2251799813685272-datetime_zy5lc",
  "name" : "datetime_zy5lc",
  "value" : "\"2024-09-12\"",
  "isValueTruncated" : false,
  "previewValue" : "\"2024-09-12\"",
  "draft" : null
}, {
  "id" : "2251799813685272-radio_f3pz6n",
  "name" : "radio_f3pz6n",
  "value" : "\"value2\"",
  "isValueTruncated" : false,
  "previewValue" : "\"value2\"",
  "draft" : null
}, {
  "id" : "2251799813685272-textfield_first",
  "name" : "textfield_first",
  "value" : "\"testField1\"",
  "isValueTruncated" : false,
  "previewValue" : "\"testField1\"",
  "draft" : null
}, {
  "id" : "2251799813685272-textfield_second",
  "name" : "textfield_second",
  "value" : "\"123\"",
  "isValueTruncated" : false,
  "previewValue" : "\"123\"",
  "draft" : null
} ]
```

2024-09-10 07:24 UTC, houssain-barouni commented
> Hey @houssain-barouni, run over a form to provide the values for cross checking, I believe we are good, if you can verify this also. This is the view from the `tasklist-task-variable` index regarding a set of variables present on the form ![image](https://private-user-images.githubusercontent.com/11016816/365904420-49cdb716-3b10-4f1b-b4e2-c3830bf84a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTMyMTYsIm5iZiI6MTcyNTk1MjkxNiwicGF0aCI6Ii8xMTAxNjgxNi8zNjU5MDQ0MjAtNDljZGI3MTYtM2IxMC00ZjFiLWI0ZTItYzM4MzBiZjg0YTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA3MjE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZGM0NzI4OWI1YjMwMjE0NWYzYzRiZDA0NjI0OGM5NDc5MTFmMDJmNmViNzZhMjQzYjQ3YjZmOWEzODFiMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jNXNgZ66Y5TTp-XJn3bOxpeHoy3c3azoSu82AiD2th8)
> 
> And this is the response of the API for `v1/tasks/{uuid}/variables/search`
> 
> ```json
> [ {
>   "id" : "2251799813685272-checkbox_pw88bp",
>   "name" : "checkbox_pw88bp",
>   "value" : "\"false\"",
>   "isValueTruncated" : false,
>   "previewValue" : "\"false\"",
>   "draft" : null
> }, {
>   "id" : "2251799813685272-checkbox_zvnb6",
>   "name" : "checkbox_zvnb6",
>   "value" : "\"true\"",
>   "isValueTruncated" : false,
>   "previewValue" : "\"true\"",
>   "draft" : null
> }, {
>   "id" : "2251799813685272-datetime_zy5lc",
>   "name" : "datetime_zy5lc",
>   "value" : "\"2024-09-12\"",
>   "isValueTruncated" : false,
>   "previewValue" : "\"2024-09-12\"",
>   "draft" : null
> }, {
>   "id" : "2251799813685272-radio_f3pz6n",
>   "name" : "radio_f3pz6n",
>   "value" : "\"value2\"",
>   "isValueTruncated" : false,
>   "previewValue" : "\"value2\"",
>   "draft" : null
> }, {
>   "id" : "2251799813685272-textfield_first",
>   "name" : "textfield_first",
>   "value" : "\"testField1\"",
>   "isValueTruncated" : false,
>   "previewValue" : "\"testField1\"",
>   "draft" : null
> }, {
>   "id" : "2251799813685272-textfield_second",
>   "name" : "textfield_second",
>   "value" : "\"123\"",
>   "isValueTruncated" : false,
>   "previewValue" : "\"123\"",
>   "draft" : null
> } ]
> ```

that's actually the problem , `true`, `false`, `123`, should be stored in ES without the double quotes
and they should be returned by the API as `"true"`, `"false"`, `"123"`

2024-09-10 08:17 UTC, panagiotisgts commented
@houssain-barouni Thanks for the feedback, I can confirm that for `Boolean` types, they are not stored with quotes ("true") for JobWorker User Tasks, but regarding `Number` values they are stored quoted for JobWorkers as well.

2024-09-10 08:29 UTC, nathansandi approved these changes
Great work here 💯

2024-09-10 08:48 UTC, houssain-barouni commented
> @houssain-barouni Thanks for the feedback, I can confirm that for `Boolean` types, they are not stored with quotes ("true") for JobWorker User Tasks, but regarding `Number` values they are stored quoted for JobWorkers as well.

I don't get it, maybe we can have a call

2024-09-11 16:40 UTC, houssain-barouni reviewed
@panagiotisgts I need a sync call to walk me through the Mapper that removes/adds the double quotes

2024-09-18 20:40 UTC, nathansandi commented on tasklist/importer-860/src/main/java/io/camunda/tasklist/zeebeimport/v860/processors/common/UserTaskRecordToVariableEntityMapper.java
> +          throw new RuntimeException(e);
Lets use the Tasklist Custom Exception here  
'TasklistRuntimeException'
over here

2024-09-18 20:42 UTC, nathansandi commented on tasklist/importer-860/src/main/java/io/camunda/tasklist/zeebeimport/v860/processors/es/UserTaskZeebeRecordProcessorElasticSearch.java
> +      updateFields.put(TaskVariableTemplate.VALUE, variable.getValue());
Did you test the situation if the`variable`comes null? 
Is this not gonna throw a null pointer exception?

2024-09-18 20:49 UTC, nathansandi requested changes
Nice work here, I have some questions in order to understand more this fix: 
If we dont save anymore the values with `\"`

- Does will impact in API Search calls? For example when we search a Task by Variable Name/Value?

- Did you check if this impacts on this functionality from Search Task in V1/V2? Or the variables are saved in the same way

2024-09-19 07:27 UTC, panagiotisgts commented
> * Does will impact in API Search calls? For example when we search a Task by Variable Name/Value?
> * Did you check if this impacts on this functionality from Search Task in V1/V2? Or the variables are saved in the same way

Since it's the same way that Job Worker variables are being persisted it should cause no issue. String variables are still stored wrapped in quotes.

2024-09-23 12:54 UTC, nathansandi approved these changes
LGMT, nice changes on test.

2024-09-23 13:18 UTC, merged