Add retry strategy for write event and execute side effects
camunda/camunda pull request #2204
Opened 2019-03-18 12:12 UTC by Zelldon

* add endless retry strategy, which retries if return value is false or `RecoverableException`
 was thrown. Retrying is done until operation is successful or non recoverable exception is thrown
 * add limited retry strategy, which limits the retries on recoverable
 exceptions
 * use for` writeEvent` endless retry strategy
 * introduce new life cycle method `writeEventFailed`
 * use for `executeSideEffects` limited retry strategy
 * if `writeEventFailed` is called workflow instance is blacklisted

closes #2049
closes #2050

2019-03-19 06:16 UTC, Zelldon commented
I updated the PR to fix the issue found by LGTM.

After this PR is merged and #2198 I will work on https://github.com/zeebe-io/zeebe/issues/2201 on which I commit the transaction in the `updateState` method. This makes it possible to rollback the transaction on error, even if the error appears on the `#writeEvent` call.

2019-03-19 08:10 UTC, saig0 approved these changes
Looks good from code side. But I think that we don't have any `RecoverableException` yet which can be thrown on `executeSideEffects()` or `writeEvent()`. Maybe we should wait until we need it. Also, I'm not sure about the 3 retries for `executeSideEffects()`. I would assume that a failure is not fixed within this short amount of time.

2019-03-20 08:42 UTC, menski commented
bors r+

2019-03-20 08:42 UTC, menski commented
bors r-

2019-03-20 08:43 UTC, menski commented
sorry missed that nobody talked to bors before, go ahead and merge when ready

2019-03-21 07:46 UTC, Zelldon commented
Hey @saig0 please review this again I made new changes. 

I refactored the stream processor controller and make now more use of the transaction, such that we rollback the transaction on error cases and only commit the transaction if the write event was successful.
All states in the state machines now use retry strategies and will end in the `onError` state if an exception is thrown.

2019-03-21 10:49 UTC, saig0 requested changes
Nice :+1:  Just a small thing.

2019-03-21 10:49 UTC, saig0 commented on logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java
> +    logStreamWriter.producerId(streamProcessorContext.getId());
The producer id needs to be set every time because it is reset. If the producer id is not set then we may have problems on reprocessing.

2019-03-21 10:49 UTC, saig0 commented on zb-db/src/main/java/io/zeebe/db/ZeebeDb.java
> +   * <p><b>NOTE</b>: This will return automatically commit the transaction and rollback on error
```suggestion
   * <p><b>NOTE</b>: This will automatically commit the transaction and rollback on error
```

2019-03-21 11:03 UTC, saig0 approved these changes

2019-03-21 11:04 UTC, Zelldon commented
bors r+

2019-03-21 12:04 UTC, Zelldon commented
bors retry

2019-03-21 12:22 UTC, Zelldon commented
Bors retry

2019-03-21 12:24 UTC, Zelldon commented
Bors r+

2019-03-21 12:44 UTC, Zelldon commented
Bors retry

2019-03-21 12:47 UTC, Zelldon commented
Bors r+

2019-03-21 12:59 UTC, merged