ci: support OS in FE developmnet scripts
camunda/camunda pull request #22197
Opened 2024-09-11 11:59 UTC by misiekhardcore

## Description

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to #22188

2024-09-11 14:47 UTC, OmranAbazid requested changes
The e2e tests seems to be failing here.

2024-09-12 07:28 UTC, misiekhardcore commented on optimize/client/docker-compose.yml
> -      KEYCLOAK_USERS_5_FIRST_NAME: 'abse1978'
I copied it over from `camunda/camunda-optimize`, what's the reason they were different in this repo?

2024-09-12 08:42 UTC, OmranAbazid commented on optimize/client/docker-compose.yml
> -      KEYCLOAK_USERS_5_FIRST_NAME: 'abse1978'
I believe i changed this because I believe elasticsearch endpoints does not work well with capitalization of users.

2024-09-12 08:42 UTC, OmranAbazid approved these changes

2024-09-12 08:59 UTC, merged