WIP: Refactoring camunda search api
camunda/camunda pull request #22419
Opened 2024-09-17 16:06 UTC by p-wunderlich

## Description

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

2024-09-17 16:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda?pullRequest=22419) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda?pullRequest=22419) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: p-wunderlich<br/>:x: stoerti<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda?pullRequest=22419) it.</sub>

2024-09-19 08:59 UTC, houssain-barouni requested changes
Great work! I really like the new organization of the code and modules. This is a solid step toward having a service layer that is abstracted from the datastore vendor. I do have a few comments to consider—feel free to reach out if you have any questions.

2024-09-19 08:59 UTC, houssain-barouni commented on service-domain/pom.xml
> +      <artifactId>zeebe-broker-client</artifactId>
This dependency is required for `CamundaServiceException` (to import `BrokerError` and `BrokerRejection`), I wonder if we can get rid of it

2024-09-19 08:59 UTC, houssain-barouni commented on service-domain/pom.xml
> +      <artifactId>zeebe-cluster-config</artifactId>
This dependency is required for import `@VisibleForTesting` annotation, it will be removed after moving back LicenseType to service module

2024-09-19 08:59 UTC, houssain-barouni commented on search/search-client-elasticsearch/src/main/java/io/camunda/search/es/clients/ElasticsearchSearchClient.java
>        return Either.left(ioe);
Can we throw `SearchQueryExecutionException` from here to:
- lighten the return type of this method from  `Either<Exception, SearchQueryResponse<T>>` to `SearchQueryResponse<T>`
- avoid the service layer handing this exception, the same code `fold(e->{throw new SearchQueryExecutionException("Failed to execute search query", e);})` is applied to all service classes

2024-09-19 11:50 UTC, p-wunderlich commented on zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceQueryController.java
> +  public ProcessInstanceQueryController(final ProcessInstanceServices processInstanceServices) {
Then I would vote for changing also the other controllers. Field injection is not recommended by Spring, and with Constructor Injection, it's easier to test the classes.

2024-09-19 11:53 UTC, p-wunderlich commented on service-domain/pom.xml
> +  <artifactId>camunda-service-domain</artifactId>
Good idea! :)

2024-09-19 11:54 UTC, p-wunderlich commented on search/search-client-elasticsearch/src/main/java/io/camunda/search/es/clients/ElasticsearchSearchClient.java
> +public class ElasticsearchSearchClient
Missing Cleanup, for a short time we had sub services for each business entity, but we decided to keep the methods in the global ElasticsearchSearchClient for now.

2024-09-19 11:55 UTC, p-wunderlich commented on search/search-client-elasticsearch/src/main/java/io/camunda/search/es/clients/ElasticsearchSearchClient.java
> +  protected final ElasticsearchTransformers transformers;
Also here, missing cleanup.

2024-09-23 12:21 UTC, stoerti commented on service-domain/pom.xml
> +  <artifactId>camunda-service-domain</artifactId>
Moved it to search-domain [camunda-search-domain]. Unfortunately this caused again a huge amount of files to change and I had to put it into a separate commit.

2024-09-23 12:21 UTC, stoerti commented on search/search-client-opensearch/src/main/java/io/camunda/search/os/clients/OpensearchProcessInstanceSearchClient.java
> +  public Either<Exception, SearchQueryResult<ProcessInstanceEntity>> searchProcessInstances(
Deleted

2024-09-23 12:22 UTC, stoerti commented on zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceQueryController.java
> +  public ProcessInstanceQueryController(final ProcessInstanceServices processInstanceServices) {
Changed all controllers where necessary (actually it already was inconsistent between the Controllers).

2024-09-23 15:39 UTC, houssain-barouni approved these changes
LGTM! Thanks for taking into account all my comments!
There are still some merge conflicts to solve.

2024-09-29 22:40 UTC, merged