chore(broker-core): migrates TimerCatchEventTest to use static broker
camunda/camunda pull request #2244
Opened 2019-03-25 14:03 UTC by npepinpe

2019-03-25 14:04 UTC, npepinpe commented
Extracted from ongoing issue as I used this class initially as to test changes, and migrated it to using a static embedded broker to speed it up.

2019-03-26 12:46 UTC, saig0 requested changes

2019-03-26 12:46 UTC, saig0 commented on broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java
> +                .withElementId(processId)
Filter by workflow instance key.

2019-03-26 12:46 UTC, saig0 commented on broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java
> +        Bpmn.createExecutableProcess(processId)
I think it is not necessary to generate a process id. To be safe, we could use the workflow key.

2019-03-26 12:46 UTC, saig0 commented on broker-core/src/test/java/io/zeebe/broker/workflow/timer/TimerCatchEventTest.java
> +    final String timerId = Strings.newRandomValidBpmnId();
No need to generate the element id if you filter the records by workflow instance key. Random id may make it harder to understand the records if the test fails.

2019-03-26 13:20 UTC, npepinpe commented
Updated after review; I prefer deploying with workflow key than process. Seems redundant for those with static names, but I think its a better habit to create an instance based on the exact process you just deployed, and makes it easier in case we ever change the process for a given test.

2019-03-28 15:15 UTC, npepinpe commented
Hi, sorry, apparently I forgot how to git and borked the code while rebasing, it should be fixed now with your review hints applied.

2019-03-29 07:10 UTC, saig0 approved these changes

2019-03-29 08:25 UTC, npepinpe commented
bors r+

2019-03-29 08:25 UTC, npepinpe commented
bors r+

2019-03-29 09:01 UTC, merged