chore(broker-core): extract event subscription logic
camunda/camunda pull request #2246
Opened 2019-03-25 14:51 UTC by npepinpe

closes #1968

2019-03-25 14:54 UTC, npepinpe commented
Most of the PR is unit tests for the single element-lifecycle tests.

One thing to note regarding the original issue, I decided against moving towards adding generations to the class hierarchy and try to move towards composition; there's a few (major) problems with what I did when I added the element state handler hierarchy, but with no time to fix them at once, I figured little by little (i.e. adding a `CatchEventSubscriber` instead of a `CatchEventSupplierElementActivatingHandler` in the hierarchy) woud be best.

2019-03-26 14:17 UTC, saig0 requested changes
Just small things. But I would like to discuss if we should write this kind of workflow processing tests.

2019-03-26 14:57 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/handlers/activity/ActivityEventOccurredHandler.java
> +  private boolean isActivityEventHandler(BpmnStepContext<T> context, EventTrigger event) {
My bad, it was moved to another class and there it's called.

2019-03-26 14:58 UTC, npepinpe commented on broker-core/src/main/java/io/zeebe/broker/workflow/processor/handlers/activity/ActivityElementCompletingHandler.java
> +    return super.handleState(context);
Let's discuss that as well tomorrow in the office.

2019-03-29 07:05 UTC, saig0 approved these changes

2019-03-29 08:24 UTC, npepinpe commented
bors r+

2019-03-29 08:49 UTC, npepinpe commented
bors retry

2019-03-29 09:16 UTC, merged