chore(logstreams): introduce async snapshotting
camunda/camunda pull request #2300
Opened 2019-04-01 13:41 UTC by Zelldon

* created new state machine for the snapshotting (need to document this)
 * snapshot is done independent from the normal stream processing
 * it is ensured that at max 3 valid snapshots are created on runtime - follow up issue should make this configurable
 * need follow up issue to make snapshot time configurable again
 * reprocessing and recovery works the same way

@saig0  lets discuss this tomorrow :) 

closes #2292

2019-04-03 05:50 UTC, Zelldon commented
Changed the PR as discussed, we will now store the latest successful processed event position in RocksDB. This makes it possible to ensure on which position the snapshot was taken and start reprocessing from this point. @saig0 please have a look

2019-04-03 08:17 UTC, saig0 requested changes
I like the idea :+1: Just some comments.

2019-04-03 08:17 UTC, saig0 commented on logstreams/src/test/java/io/zeebe/logstreams/processor/AsyncSnapshotingTest.java
> +    logStreamRule.getClock().addTime(Duration.ofMinutes(1));
Please use the same duration as configured in the director.

2019-04-03 08:17 UTC, saig0 commented on logstreams/src/test/java/io/zeebe/logstreams/processor/AsyncSnapshotingTest.java
> +    waitUntil(() -> asyncSnapshotDirector.lastWrittenEventPosition != INITIAL_POSITION);
Please avoid using the internal state of the director. This test should also work without this check.

2019-04-03 08:19 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/processor/AsyncSnapshotDirector.java
> +    conditionCheckOut.accept(commitCondition);
This removes the registered condition

2019-04-03 08:26 UTC, saig0 commented on logstreams/src/main/java/io/zeebe/logstreams/processor/AsyncSnapshotDirector.java
> +    conditionCheckOut.accept(commitCondition);
Ok. Do we really need to remove the condition? If should only happens when the logstream is closed.

2019-04-03 12:18 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessor.java
> +  }
yes :cry:

2019-04-03 12:18 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java
> +    final long snapshotPosition = streamProcessor.getLastSuccessfulProcessedPositionFromState();
what do you mean exactly?

2019-04-03 12:19 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/processor/StreamProcessorController.java
> +              actor.runOnCompletionBlockingCurrentPhase(
So I will remove it ?

2019-04-03 12:19 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/state/StateSnapshotController.java
> +  public void ensureMaxSnapshotCount(int maxSnapshotCount) throws Exception {
this means what? :sweat_smile:

2019-04-03 12:29 UTC, saig0 commented on logstreams/src/main/java/io/zeebe/logstreams/state/StateSnapshotController.java
> +  public void ensureMaxSnapshotCount(int maxSnapshotCount) throws Exception {
#2303

2019-04-03 12:58 UTC, saig0 approved these changes

2019-04-04 11:56 UTC, Zelldon commented
bors r+

2019-04-04 12:09 UTC, merged