I can delete from logstream
camunda/camunda pull request #2313
Opened 2019-04-05 20:14 UTC by Zelldon

closes #2304

2019-04-07 14:17 UTC, menski commented
I rebased this branch with the latest develop to pull in the cloud CI config.

2019-04-08 07:04 UTC, Zelldon commented
@menski thanks

2019-04-08 07:23 UTC, saig0 requested changes
Just some small things :)

2019-04-08 07:23 UTC, saig0 commented on logstreams/src/test/java/io/zeebe/logstreams/log/LogStreamTest.java
> +    final long fourthPosition = writeEvent(logStream, BufferUtil.wrapArray(largeEvent));
The test setup is similar in all 3 cases. Please extract it.

2019-04-08 07:23 UTC, saig0 commented on logstreams/src/test/java/io/zeebe/logstreams/log/LogStreamTest.java
> +    assertThat(events(logStream).count()).isEqualTo(2);
It is not clear why we delete only 2 of 4 segments and not 3. Please add a comment or change the test case.

2019-04-08 09:54 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/impl/log/fs/FsLogSegments.java
> +  public void removeSegments(int segmentId) {
Your renamings are evil.

2019-04-08 09:56 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/impl/log/fs/FsLogSegments.java
> +  public void removeSegments(int segmentId) {
We have an check in the FsLogStorage, so I will then just ignore it if it is greater?

2019-04-08 12:45 UTC, Zelldon commented
Please see my latest changes

2019-04-08 12:58 UTC, saig0 approved these changes

2019-04-08 13:15 UTC, Zelldon commented
bors r+

2019-04-08 13:29 UTC, merged