chore: Simplify class assignability check
camunda/camunda pull request #23172
Opened 2024-10-08 15:45 UTC by fml2

## Description
A solution for #23329.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #23329

2024-10-10 08:07 UTC, korthout requested changes
Thank you for your contribution @fml2 

❌ At this time, I cannot accept the change. It is not clear why the change is necessary. Please [reference the issue](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#creating-a-pull-request) that this change resolves. If none exists, please [open a new issue](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#starting-on-an-issue). For more information about contributing to this project, please read our [contributing](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md) guide.

2025-04-07 13:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda?pullRequest=23172) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda?pullRequest=23172) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda?pullRequest=23172) it.</sub>

2025-10-24 09:45 UTC, npepinpe commented
Closing as stale.

2025-10-24 09:45 UTC, closed without merging

2025-10-24 15:56 UTC, fml2 commented
:+1 I like the reasoning.

2025-10-24 16:08 UTC, npepinpe commented
If you still think it's relevant we can pick it up, I just saw it hadn't been touched in 1 year 🤷‍♂️

2025-10-24 19:45 UTC, fml2 commented
IMO it hasn't lost anything of its relevance (or non-relevance). The project maintainers decide. But "stale" isn't a good justification. This is my opinion here or in any other PR (regardless of the author).

2025-10-24 20:51 UTC, npepinpe commented
I get where you're coming from. From my side, it's happened quite often that PRs become abandoned, and this is what it looked like to me here, which I hope you can understand. I hope this doesn't deter you from future contributions, or from continuing here if you have a strong motivation for the change.