refactor: Remove dangling references to snapshot checksum
camunda/camunda pull request #23210
Opened 2024-10-09 13:01 UTC by filipecampos

## Description

Remove dangling references to snapshot checksum as it is no longer used.

## Related issues

closes #20760

2024-10-10 07:47 UTC, EuroLew reviewed
Missing `PreDefinedImmutableChecksum` but otherwise looks like it covers everything

2024-10-11 11:21 UTC, EuroLew approved these changes
LGTM

2024-10-11 13:53 UTC, lenaschoenburg requested changes

2024-10-11 17:24 UTC, filipecampos commented on zeebe/atomix/cluster/src/main/java/io/atomix/raft/snapshot/impl/SnapshotChunkImpl.java
> -        .snapshotChecksum(0)
Reverted this change.

2024-10-14 06:40 UTC, lenaschoenburg approved these changes

2024-10-15 17:07 UTC, merged