chore(broker-core): listen to leaderelection primitive disconnect
camunda/camunda pull request #2339
Opened 2019-04-12 11:04 UTC by deepthidevaki

* a node can listen to network disconnection so that it can step down from stream processor leader
* there is now a PartitionLeaderElection service which all services can use to listen to leadership changes.

closes #2325

2019-04-15 12:40 UTC, saig0 requested changes
Looks good. Just some small notes.

BTW: Can we now enable the test case `BrokerLeaderChangeTest#shouldChangeLeaderAfterLeaderDies()`?

2019-04-15 14:11 UTC, deepthidevaki commented
> BTW: Can we now enable the test case `BrokerLeaderChangeTest#shouldChangeLeaderAfterLeaderDies()`?

I guess yes.

2019-04-15 14:14 UTC, deepthidevaki commented
@saig0 I have made the suggested changes. Please have a look.

2019-04-16 05:47 UTC, saig0 requested changes

2019-04-16 05:47 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/clustering/base/partitions/PartitionLeaderElection.java
> +          "Couldn't get current leadership for partition {}. Transitioning to follower. {}",
```suggestion
          "Couldn't get current leadership for partition {}. Transitioning to follower.",
```

The exception doesn't need a parameter in the log statement. Just add it as the last argument.

2019-04-16 05:47 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/clustering/base/partitions/PartitionLeaderElection.java
> +          LOG.error("Couldn't get current leadership for partition {} {}", partitionId, e);
```suggestion
          LOG.error("Couldn't get current leadership for partition {}", partitionId, e);
```

2019-04-16 07:21 UTC, deepthidevaki commented
@saig0 updated.

2019-04-16 07:40 UTC, saig0 approved these changes

2019-04-16 08:17 UTC, deepthidevaki commented
bors r+

2019-04-16 08:33 UTC, merged