build: use reflective equals and hashCode in Optimize
camunda/camunda pull request #23489
Opened 2024-10-14 15:46 UTC by buccarel

## Description

This is a prototype: the implementation is currently complete and the build is green, but it's missing unit tests.

With the de-lombok'ification of the monorepo, the removal of the annotation `@EqualsAndHashCode` generated a lot of code. Such code, not only is big in terms of number of lines, but it's also static (e.g., if we add a variable to a class that implements `hashCode()`, we also need to change the implementation of such method to also include the new variable).

With this prototype, I am using an implementation of equals and hashCode that works reflectively when applied to any class, with any variables in it. It's provided by an apache library and it is my understanding that it doesn't need the "call-super" special case, when used reflectively.

This PR has been generated programmatically with a script that replaces the equals() and hashCode() methods, when hashCode() is present in the class.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

2024-10-16 13:42 UTC, RomanJRW commented on optimize/util/optimize-commons/src/main/java/io/camunda/optimize/util/DynamicEqualsAndHashCode.java
> +    // case 1: at least 1 object is null
this would already be covered by case 2?

2024-10-17 16:50 UTC, matthewBearCamunda requested changes
The code changes look good to me, I think the approach of using the library from apache commons is a cleaner and simpler way to go

Before I give the green approval check, would you be able to test the performance of this change on a large dataset? The use of reflection in both the hash code and equals method makes me think that a test would be worthwhile

2024-10-18 13:56 UTC, matthewBearCamunda approved these changes
Approving! The performance test was helpful, and the performance hit we would take would be acceptable

https://camunda.slack.com/archives/CUZUYDMMG/p1729258751439819?thread_ts=1729082399.343169&cid=CUZUYDMMG

2024-10-19 02:12 UTC, merged

2024-10-23 11:15 UTC, korthout commented on optimize/upgrade/pom.xml
> +    </dependency>
❌ This change broke building with `mvnd` (Maven Daemon)

```
mvnd clean install -Dquickly -Dskip.fe.build -Dspotless.skip
[INFO] Processing build on daemon 60b1894c
[INFO] Scanning for projects...
[ERROR] Some problems were encountered while processing the POMs
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.camunda.optimize:upgrade-optimize:8.7.0-SNAPSHOT (/Users/korthout/gh/camunda/camunda/optimize/upgrade/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.commons:commons-lang3:jar -> version 3.14.0 vs (?) @ line 191, column 5
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

@buccarel Can you revert this change?