don't transition leader/follower until previous one is done
camunda/camunda pull request #2361
Opened 2019-04-17 08:28 UTC by deepthidevaki

closes #2355

2019-04-17 11:08 UTC, ChrisKujawa requested changes
Thanks for fixing this :+1: some small things

2019-04-17 11:08 UTC, Zelldon commented on qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/BrokerLeaderChangeTest.java
> +    assertThat(election.getLeadership().leader().id()).isEqualTo(String.valueOf(2));
The assertion is a bit flaky and also the assertions below

2019-04-17 14:15 UTC, deepthidevaki commented
@zelldon I have updated PR as we discussed. Topology is updated only after leader/follower services are installed. In addition, before transitionFuture in PartitionInstallService was completed when the install is complete, now it also waits for the removals. Also moved all the services for leader into a composite service.

2019-04-23 08:54 UTC, ChrisKujawa approved these changes

2019-04-23 12:52 UTC, deepthidevaki commented
bors r+

2019-04-23 13:40 UTC, deepthidevaki commented
bors retry

2019-04-23 13:57 UTC, merged