chore(logstreams): delete logstream data after snapshot
camunda/camunda pull request #2373
Opened 2019-04-23 11:05 UTC by MiguelPires

closes #2305

2019-04-23 13:01 UTC, saig0 requested changes
We should add a test case to verify that this works all together in the broker with some exporters.

2019-04-24 19:15 UTC, MiguelPires commented
Thanks for the feedback @saig0. I changed the tests and also removed the callback when the exporter service stops

2019-04-25 08:58 UTC, saig0 requested changes
Currently, it can happen that the data deletion is triggered by the exporter stream processor.

```
10:36:23.224 [exporter-snapshot-director] [0.0.0.0:25602-zb-fs-workers-0] INFO  io.zeebe.logstreams.snapshot - Creation of snapshot for exporter took 48 ms.
10:36:23.229 [exporter-snapshot-director] [0.0.0.0:25602-zb-fs-workers-0] INFO  io.zeebe.logstreams - Delete data from logstream until position '4294973080' (address: '4294973336').
10:36:23.232 [exporter-snapshot-director] [0.0.0.0:25602-zb-fs-workers-0] INFO  io.zeebe.logstreams - Deleted 1 segments from log storage (0 to 1).
```

This is not ok because we need to ensure that we have enough snapshots of the workflow stream processor state :sweat_smile: 
This might be fixed when we use just one RocksDB. If there is an easy way to avoid this then we should do it. Otherwise, we need to fix it with the refactoring.

2019-04-25 08:58 UTC, saig0 commented on qa/integration-tests/src/test/java/io/zeebe/broker/it/DataDeleteTest.java
> +    exporterCfg.setClassName(TestExporter.class.getName());
We should use a different exporter. This one is defined in a different test module.

2019-04-25 08:58 UTC, saig0 commented on qa/integration-tests/src/test/java/io/zeebe/broker/it/DataDeleteTest.java
> +    brokerRule.getClock().pinCurrentTime();
I see no reason why we should pin the time.

2019-04-25 11:16 UTC, MiguelPires commented
Hey @saig0, I made another iteration. The solution to prevent data from being deleted after an exporter snapshot is not the most elegant but it should work until the refactor. I added it to issue #2381 so we don't forget to remove it

2019-04-25 11:41 UTC, saig0 approved these changes

2019-04-26 10:17 UTC, MiguelPires commented
bors r+

2019-04-26 10:32 UTC, merged