fix(msgpack): Fix for wrapping values that are at edge of buffer capacity and has zero-length
camunda/camunda pull request #2374
Opened 2019-04-23 12:28 UTC by iamtakingiteasy

Fixes edge-case, when wrapped value offset is equal to buffer capacity, but length is zero, so no error should be thrown.

closes #2371

2019-04-23 15:15 UTC, iamtakingiteasy commented
Also made case when offset is less than buffer's capacity, but length is beyond that to throw the same exception as when it is overflowed directly from the edge.

2019-04-23 15:26 UTC, iamtakingiteasy commented
Forgot probably unnecessary, but conforming to rest of the code (byte) cast in last test.

2019-04-24 11:41 UTC, saig0 requested changes
Thank you for your contribution :+1:

I prepared some minor changes to align with your code base. Please apply the PR https://github.com/iamtakingiteasy/zeebe/pull/1 and squash the two commits into one.

2019-04-24 13:58 UTC, iamtakingiteasy commented
Done.

2019-04-25 05:23 UTC, saig0 approved these changes

2019-04-25 05:23 UTC, saig0 commented
bors r+

2019-04-25 05:46 UTC, saig0 commented
bors retry

2019-04-25 06:04 UTC, saig0 commented
bors r+

2019-04-25 06:19 UTC, merged