chore(broker-core): clean up network configuration
camunda/camunda pull request #2376
Opened 2019-04-23 15:00 UTC by deepthidevaki

closes #1928

2019-04-24 16:19 UTC, miguelpires requested changes

2019-04-24 16:19 UTC, MiguelPires commented on broker-core/src/test/java/io/zeebe/broker/system/ConfigurationTest.java
> +  public void shouldUseClusterNameromEnvironment() {
```suggestion
  public void shouldUseClusterNameFromEnvironment() {
```

2019-04-25 08:29 UTC, miguelpires approved these changes

2019-04-25 14:45 UTC, deepthidevaki commented
bors r+

2019-04-26 07:46 UTC, deepthidevaki commented
bors retry

2019-04-26 08:16 UTC, Zelldon commented
bors r+

2019-04-26 08:39 UTC, merged