Allow cancelling banned instances
camunda/camunda pull request #23849
Opened 2024-10-22 15:04 UTC by berkaycanbc

## Description

After this PR, users will be able to cancel banned instances. Therefore, they will be able to get rid of unnecessarily written timer records.

In addition to automated test cases, following cases are tested manually:

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #14213 
closes #12772

2024-10-23 16:02 UTC, korthout requested changes
Thanks @berkaycanbc 🚀 

@remcowesterhoud and I ended up spending some time together pairing on reviewing this. Thanks @remcowesterhoud 🙌 

👍 We're looking forward to cancel some banned instances after this!

❌ We found some issues with the test cases that require attention. Please have a look.

Additionally, we think there is a need for one more manual test case to ensure that we can cancel already-terminating instances:
- Cancel process instance with service task. Throw exception in the TaskProcessor onTerminate method for the first call. Observe rejection for the first call. Then, send cancellation command again. Expect that the banned process instance is cancelled on the second command.

Lastly, we have a question about this manual test case:

>Create a looping process with 120000 timer instances created. Cancel the process and observe that the cancellation works with huge amount of timers. Will therefore work for banned instances with huge number of timer instances created. (the test setup for the support case)

❓ Did you also ban the instance in this test? Or just assumed that it would work. We should ensure that this works correctly for instances with many timers.

2024-10-24 09:19 UTC, berkaycanbc commented
Thanks @korthout and @remcowesterhoud for the review! 🚀 I will process your comments soon. I can already answer the question:

> ❓ Did you also ban the instance in this test? Or just assumed that it would work. We should ensure that this works correctly for instances with many timers.

No. I just used our dev environment without banning. What we can do is to test the case with banning once we deliver the PR. I think, it is way easier because our automated tests needs a configuration to prevent timeouts etc. There is an affected customer with a similar issue, we can let them know after we test the similar case by ourselves.

2024-10-24 10:24 UTC, berkaycanbc commented on zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/BannedInstanceIT.java
> +  @Rule public final BrokerClassRuleHelper helper = new BrokerClassRuleHelper();
Indeed using `@Rule` is functionless. ZeebeIntegrationExtension already handles to cleanup exporters before each test run. Therefore, no need to differentiate between process ids.

2024-10-24 12:15 UTC, berkaycanbc commented on zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/BannedInstanceIT.java
> +        .isEmpty();
@korthout @remcowesterhoud do you know how to receive the engine clock within JUnit5 integration test class?

2024-10-24 12:38 UTC, berkaycanbc commented on zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/BannedInstanceIT.java
> +        .isNotNull();
> ❌ Please also ensure to limit the record streams to speed up the tests

@korthout Does `limit(1)` speed up a test when using `exists()` query (see my new commits)? Exists call should find the first occurrence and return, right?

2024-10-24 12:58 UTC, korthout commented on zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/BannedInstanceIT.java
> +        .isEmpty();
You can use the actor clock endpoint for this, which is available for ZPT specifically. You'll need to add an actuator. I've created a quick poc here: https://github.com/camunda/camunda/compare/main...korthout-berkay-clock-actuator

2024-10-24 12:58 UTC, berkaycanbc commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java
> +              || intent == ProcessInstanceBatchIntent.TERMINATE;
Using EnumSet is not possible since we have two different enum types here `ProcessInstanceIntent` and `ProcessInstanceBatchIntent`.

2024-10-24 13:28 UTC, korthout commented on zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/BannedInstanceIT.java
> +        .isNotNull();
👍 `exists()` is short-circuiting

2024-10-24 14:34 UTC, berkaycanbc commented on zeebe/qa/integration-tests/src/test/java/io/camunda/zeebe/it/processing/BannedInstanceIT.java
> +        .isEmpty();
@korthout created the related PR https://github.com/camunda/camunda/pull/24018

2024-10-24 16:36 UTC, korthout approved these changes
Thanks @berkaycanbc 🚀 

For speed, I've added my review comments as commits. Please have a look.

2024-10-28 10:37 UTC, korthout commented
@remcowesterhoud With Berkay out of office, do you have some time to review my last commits?

2024-10-28 14:00 UTC, remcowesterhoud approved these changes
LGTM @korthout. Let's get it into the patch 💪

2024-10-28 14:55 UTC, merged

2024-10-28 14:55 UTC, backport-action commented
Created backport PR for `stable/8.3`:
- #24120 with remaining conflicts!

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin backport-23849-to-stable/8.3
git worktree add --checkout .worktree/backport-23849-to-stable/8.3 backport-23849-to-stable/8.3
cd .worktree/backport-23849-to-stable/8.3
git reset --hard HEAD^
git cherry-pick -x 38eb6c234d3b8213af47dc0554d94ffe05359566 13517d85c1e7490a059eb1c560aec85a96843515 be70099845dc772c5dbcb25234b859dfa838ca45 048188a5d6c7798b455c0e2353320ee37175013a ea983c23ba80c17d700e3aadc987f0892727eea9 188cb1ab6152b11d8b8e2d499350953dfa4154bb d8372bcded520c13a47b2423e945ebc94cf51cf7 1129c2063e3e581962ab24ec87abfc7889786e81 d90836a0f9037fa6c530f0a02cd88f2f55fac224 65c6aabe9e8ad92192eda6fb3d48a43776bc5db8 ab81492b4bbe380dba6b6e555499910e3ec3b2fd b4446a1356127c3314616055c1f8391397cb2891 6cd6f6302bc3556deffd61dbbc695a04b30cdf62 acc15f6089acdb0c0ecd1c0ac3ca1553871782eb 64a30303c9f364042a597e1e2bdb378be4c81cd9 baea357beee75c78a53570b603b4773cbcdbd58c ac5de88b70ec43cc65eb49657deb26d142f5e134 02bc85489333a0e9b854fd90e3b33220ca4b3e14
git push --force-with-lease
```

2024-10-28 14:55 UTC, backport-action commented
Created backport PR for `stable/8.4`:
- #24121 with remaining conflicts!

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin backport-23849-to-stable/8.4
git worktree add --checkout .worktree/backport-23849-to-stable/8.4 backport-23849-to-stable/8.4
cd .worktree/backport-23849-to-stable/8.4
git reset --hard HEAD^
git cherry-pick -x 38eb6c234d3b8213af47dc0554d94ffe05359566 13517d85c1e7490a059eb1c560aec85a96843515 be70099845dc772c5dbcb25234b859dfa838ca45 048188a5d6c7798b455c0e2353320ee37175013a ea983c23ba80c17d700e3aadc987f0892727eea9 188cb1ab6152b11d8b8e2d499350953dfa4154bb d8372bcded520c13a47b2423e945ebc94cf51cf7 1129c2063e3e581962ab24ec87abfc7889786e81 d90836a0f9037fa6c530f0a02cd88f2f55fac224 65c6aabe9e8ad92192eda6fb3d48a43776bc5db8 ab81492b4bbe380dba6b6e555499910e3ec3b2fd b4446a1356127c3314616055c1f8391397cb2891 6cd6f6302bc3556deffd61dbbc695a04b30cdf62 acc15f6089acdb0c0ecd1c0ac3ca1553871782eb 64a30303c9f364042a597e1e2bdb378be4c81cd9 baea357beee75c78a53570b603b4773cbcdbd58c ac5de88b70ec43cc65eb49657deb26d142f5e134 02bc85489333a0e9b854fd90e3b33220ca4b3e14
git push --force-with-lease
```

2024-10-28 14:56 UTC, backport-action commented
Created backport PR for `stable/8.6`:
- #24123 with remaining conflicts!

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin backport-23849-to-stable/8.6
git worktree add --checkout .worktree/backport-23849-to-stable/8.6 backport-23849-to-stable/8.6
cd .worktree/backport-23849-to-stable/8.6
git reset --hard HEAD^
git cherry-pick -x 02bc85489333a0e9b854fd90e3b33220ca4b3e14
git push --force-with-lease
```

2024-10-29 09:49 UTC, korthout commented
/backport

2024-10-29 09:49 UTC, backport-action commented
Created backport PR for `stable/8.3`:
- #24156 with remaining conflicts!

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin backport-23849-to-stable/8.3
git worktree add --checkout .worktree/backport-23849-to-stable/8.3 backport-23849-to-stable/8.3
cd .worktree/backport-23849-to-stable/8.3
git reset --hard HEAD^
git cherry-pick -x 38eb6c234d3b8213af47dc0554d94ffe05359566 13517d85c1e7490a059eb1c560aec85a96843515 be70099845dc772c5dbcb25234b859dfa838ca45 048188a5d6c7798b455c0e2353320ee37175013a ea983c23ba80c17d700e3aadc987f0892727eea9 188cb1ab6152b11d8b8e2d499350953dfa4154bb d8372bcded520c13a47b2423e945ebc94cf51cf7 1129c2063e3e581962ab24ec87abfc7889786e81 d90836a0f9037fa6c530f0a02cd88f2f55fac224 65c6aabe9e8ad92192eda6fb3d48a43776bc5db8 ab81492b4bbe380dba6b6e555499910e3ec3b2fd b4446a1356127c3314616055c1f8391397cb2891 6cd6f6302bc3556deffd61dbbc695a04b30cdf62 acc15f6089acdb0c0ecd1c0ac3ca1553871782eb 64a30303c9f364042a597e1e2bdb378be4c81cd9 baea357beee75c78a53570b603b4773cbcdbd58c ac5de88b70ec43cc65eb49657deb26d142f5e134 02bc85489333a0e9b854fd90e3b33220ca4b3e14
git push --force-with-lease
```

2024-10-29 09:49 UTC, backport-action commented
Created backport PR for `stable/8.4`:
- #24157 with remaining conflicts!

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin backport-23849-to-stable/8.4
git worktree add --checkout .worktree/backport-23849-to-stable/8.4 backport-23849-to-stable/8.4
cd .worktree/backport-23849-to-stable/8.4
git reset --hard HEAD^
git cherry-pick -x 38eb6c234d3b8213af47dc0554d94ffe05359566 13517d85c1e7490a059eb1c560aec85a96843515 be70099845dc772c5dbcb25234b859dfa838ca45 048188a5d6c7798b455c0e2353320ee37175013a ea983c23ba80c17d700e3aadc987f0892727eea9 188cb1ab6152b11d8b8e2d499350953dfa4154bb d8372bcded520c13a47b2423e945ebc94cf51cf7 1129c2063e3e581962ab24ec87abfc7889786e81 d90836a0f9037fa6c530f0a02cd88f2f55fac224 65c6aabe9e8ad92192eda6fb3d48a43776bc5db8 ab81492b4bbe380dba6b6e555499910e3ec3b2fd b4446a1356127c3314616055c1f8391397cb2891 6cd6f6302bc3556deffd61dbbc695a04b30cdf62 acc15f6089acdb0c0ecd1c0ac3ca1553871782eb 64a30303c9f364042a597e1e2bdb378be4c81cd9 baea357beee75c78a53570b603b4773cbcdbd58c ac5de88b70ec43cc65eb49657deb26d142f5e134 02bc85489333a0e9b854fd90e3b33220ca4b3e14
git push --force-with-lease
```

2024-10-29 09:49 UTC, backport-action commented
Created backport PR for `stable/8.5`:
- #24158 with remaining conflicts!

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin backport-23849-to-stable/8.5
git worktree add --checkout .worktree/backport-23849-to-stable/8.5 backport-23849-to-stable/8.5
cd .worktree/backport-23849-to-stable/8.5
git reset --hard HEAD^
git cherry-pick -x 02bc85489333a0e9b854fd90e3b33220ca4b3e14
git push --force-with-lease
```

2024-10-29 09:49 UTC, backport-action commented
Backport failed for `stable/8.6`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin stable/8.6
git worktree add -d .worktree/backport-23849-to-stable/8.6 origin/stable/8.6
cd .worktree/backport-23849-to-stable/8.6
git switch --create backport-23849-to-stable/8.6
git cherry-pick -x 38eb6c234d3b8213af47dc0554d94ffe05359566 13517d85c1e7490a059eb1c560aec85a96843515 be70099845dc772c5dbcb25234b859dfa838ca45 048188a5d6c7798b455c0e2353320ee37175013a ea983c23ba80c17d700e3aadc987f0892727eea9 188cb1ab6152b11d8b8e2d499350953dfa4154bb d8372bcded520c13a47b2423e945ebc94cf51cf7 1129c2063e3e581962ab24ec87abfc7889786e81 d90836a0f9037fa6c530f0a02cd88f2f55fac224 65c6aabe9e8ad92192eda6fb3d48a43776bc5db8 ab81492b4bbe380dba6b6e555499910e3ec3b2fd b4446a1356127c3314616055c1f8391397cb2891 6cd6f6302bc3556deffd61dbbc695a04b30cdf62 acc15f6089acdb0c0ecd1c0ac3ca1553871782eb 64a30303c9f364042a597e1e2bdb378be4c81cd9 baea357beee75c78a53570b603b4773cbcdbd58c ac5de88b70ec43cc65eb49657deb26d142f5e134 02bc85489333a0e9b854fd90e3b33220ca4b3e14
```