fix: exclude task-template from being populated and created by tasklist when CamundaExporter is enabled
camunda/camunda pull request #24069
Opened 2024-10-25 09:04 UTC by panagiotisgts

## Description
- Change `tasklist-task` version to 8.5.0
- When `ZEEBE_BROKER_EXPORTERS_CAMUNDA_CLASSNAME=io.camunda.exporter.CamundaExporter`
- - Exclude `tasklist-task` from Tasklist's SchemaManager
- - Exclude UserTask and Form record from being handled by Tasklist's 8.7 Importer

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

2024-10-25 09:15 UTC, Zelldon approved these changes
For the moment it makes sense I guess. In general, we should get rid of the 8.7 importer. What do you think when or how we can delete it? Operate has no 8.7 Importer I believe? 🤔

2024-10-25 09:26 UTC, panagiotisgts commented
> In general, we should get rid of the 8.7 importer. What do you think when or how we can delete it? Operate has no 8.7 Importer I believe?

Operate also has an 8.7 Importer for the time being. When Tasklist FE migrates to V2 APIs most of Tasklist's services and business logic will be removed, along with the 8.7 importer.

2024-10-25 10:19 UTC, Zelldon commented on dist/src/main/resources/application-tasklist.properties
> +camunda.tasklist.exporterClassName=${zeebe.broker.exporters.camunda.className:${zeebe.broker.exporters.camundaExporter.className:${ZEEBE_BROKER_EXPORTERS_CAMUNDA_CLASSNAME:${ZEEBE_BROKER_EXPORTERS_CA
TIL; Did you tested this somehow? :)

2024-10-25 10:31 UTC, Zelldon requested changes
I realized your planned change will not work for SaaS (what we try to fix). As the importer is running in separate container/pod.

Lets just fix the version aa first increment. I try to get the importer disabled in SaaS for now.

2024-10-25 10:40 UTC, panagiotisgts commented
Why wouldn't it? If the config property is present the behavior should be the same. Am I missing something?

2024-10-25 10:41 UTC, Zelldon commented
Each deployment has its own config map. That is the current state at least

2025-01-16 12:14 UTC, panagiotisgts commented
Closing this as is no longer needed

2025-01-16 12:14 UTC, closed without merging