chore(broker): none replication on single broker
camunda/camunda pull request #2408
Opened 2019-04-29 11:08 UTC by Zelldon

closes #2390

2019-04-30 05:14 UTC, saig0 requested changes

2019-04-30 05:14 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/clustering/base/partitions/Partition.java
> +    final boolean isSingleBroker = brokerCfg.getCluster().getClusterSize() == 1;
I guess we should check the replication factor instead. It could be that we have a cluster count > 1 but replication factor == 1.

2019-04-30 05:28 UTC, Zelldon commented
Done.

2019-04-30 06:15 UTC, saig0 approved these changes

2019-04-30 12:36 UTC, Zelldon commented
bors r+

2019-05-01 12:00 UTC, Zelldon commented
Bors r+

2019-05-01 12:16 UTC, merged