chore(logstreams): delete data on followers
camunda/camunda pull request #2409
Opened 2019-04-29 13:55 UTC by MiguelPires

One noteworthy detail is that, from the followers perspective, the situation where no exporter state snapshot is sent by the leader (for instance, because there are no exporters configured) is indistinguishable from the situation where the snapshot is in transit and simply hasn't arrived. In that situation we don't delete data to avoid deleting something that an exporter might need. We don't need to implement a better solution because when we have a unified RocksDb instance, this problem will be solved by default.

closes #2346

2019-05-02 07:52 UTC, saig0 requested changes
Please see the comments. Feel free to discuss it.

2019-05-02 07:52 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/clustering/base/partitions/Partition.java
> +    }
On the follower, we don't respect the configured max snapshot count. After a snapshot is replicated, we delete the data up to the snapshot position. If the max snapshot count is greater than 1 then we should use the position of one of the previous snapshots.  

BTW: it seems that it is also no correct on the leader. Please have a look at `AsyncSnapshotDirectorTest.shouldInvokeDataDeleteCallbackOnMaxSnapshots()` .

2019-05-02 07:52 UTC, saig0 commented on qa/integration-tests/src/test/java/io/zeebe/broker/it/clustering/SnapshotReplicationTest.java
> +    clusteringRule.getClock().pinCurrentTime();
We should not pin the time in integration tests. This can lead to weird problems :sweat_smile:

2019-05-02 13:01 UTC, MiguelPires commented
Thanks @saig0, I made some changes according to your feedback

2019-05-02 18:18 UTC, MiguelPires commented
Fixed failing test. The test was failing because the ```getPositionToRecoverFrom``` was only getting the minimum from the Db, not from the containers. There is no test for this but I think that if the leader has two exporters and only one of them updates the position, the replicated snapshot would cause the follower to use that updated position as the minimum because the non-updated exporter wasn't in the state. I made a small fix but didn't add a test since the test would be more complex and we already have an issue to improve the test coverage.

2019-05-03 07:30 UTC, saig0 requested changes
@MiguelPires, just some small things left.

2019-05-03 07:30 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/exporter/stream/ExporterStreamProcessor.java
> +      }
We should move this function to `onRecovered()`. We already update the state there :)

2019-05-03 07:30 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/exporter/stream/ExporterStreamProcessorState.java
> +    return lowestPosition.get();
To make it more explicitly:

```suggestion
    final LongArrayList positions = new LongArrayList();
    state.visitPositions((exporterId, position) -> positions.addLong(position));
    
    return positions.longStream().min().orElse(-1L);
```

2019-05-03 07:30 UTC, saig0 commented on broker-core/src/main/java/io/zeebe/broker/exporter/stream/ExporterStreamProcessor.java
> +      }
Please add a new test case to `ExporterStreamProcessorTest` to verify that we don't recover from a higher position if one exporter never updates its position. It shouldn't be hard to write this as unit test ;)

Also, we should add a test case in `ExporterStateTest` for the new method `getLowestPosition()`.

2019-05-03 09:37 UTC, MiguelPires commented
Thanks for the feedback, I added the test cases

2019-05-03 09:40 UTC, saig0 approved these changes

2019-05-03 10:24 UTC, MiguelPires commented
bors r+

2019-05-03 10:38 UTC, MiguelPires commented
bors retry

2019-05-03 11:37 UTC, MiguelPires commented
bors r+

2019-05-03 11:52 UTC, merged