feat: Grafana REST metrics row
camunda/camunda pull request #24326
Opened 2024-11-04 15:56 UTC by megglos

## Description

New REST API Row in Zeebe Dashboard and first metric on requests/s.

Meets following acceptance criteria of the initial issue
- [x] A new REST API row is added to the Zeebe Dashboard
- [x] The REST API row contains a REST requests per second (range = 1m) panel split by path

Note: a lot of reformatting happened probably due to a newer Grafana version?

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

relates #17442

2024-11-04 16:05 UTC, npepinpe commented
I can't really review 1k lines of JSON :sweat_smile: Do you have a demo up somewhere I can see? Or some images?

2025-01-08 11:37 UTC, npepinpe commented
Looks like we forgot about this. Any plans to update?

2025-01-08 11:43 UTC, npepinpe requested changes
:x: Lots of changes in here lead me to think that the dashboard was not exported for reuse. For example, removing all the plugin versions and the data source definition at the top?

It would also be best if you export the dashboard with the new row collapsed instead of expanded.

2025-01-08 19:05 UTC, megglos commented
Yeah I didn't find time to look further into this, @tmetzke is this something you can pick up within the REST API work stream again? As @koevskinikola is assigned to identity, I don't think he will have time to continue in this either 😬

2025-01-09 06:54 UTC, tmetzke commented
@megglos, I think we can, yes. Whoever works on it from the API team will need an introduction to how this works, though. I cannot provide that because I don't know myself. Who should that dev reach out to when looking into this?

2025-01-09 16:36 UTC, npepinpe commented
They can reach out to me for now, I'll delegate to someone at that time.

2025-01-22 18:49 UTC, megglos commented
@npepinpe I tend to close this then, as I don't see much reason for anyone to continue work on this PR but actually start a new one.

2025-01-22 18:49 UTC, closed without merging