feat: camunda exporters support tenant add and remove entity events
camunda/camunda pull request #24648
Opened 2024-11-12 15:29 UTC by Oleksiivanov

## Description

- added TenantEntityAddedHandler and tests
- added TenantEntityRemoveHandler and tests
- updated index, entity and related code to join relation

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #24590 and #24591

2024-11-12 16:51 UTC, Ben-Sheppard commented on zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/TenantEntityAddedHandler.java
> +
I'm going to tag the exporter team as they may have better opinions than myself :)

2024-11-29 12:22 UTC, koevskinikola commented
@Oleksiivanov I can start with the PR review here if no one else has started working on it yet.

2024-11-29 12:43 UTC, koevskinikola requested changes
Nice job @Oleksiivanov, just a small change in the create-update handler and we can merge it 🚀

2024-11-29 12:43 UTC, koevskinikola commented on zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/TenantCreateUpdateHandler.java
> +        .setName(value.getName());
❌ We need to add a "parent" join relation here, do define this as the "parent" entity:

```suggestion
    final var joinRelation = TenantIndex.JOIN_RELATION_FACTORY.createParent();
    entity
        .setTenantKey(value.getTenantKey())
        .setTenantId(value.getTenantId())
        .setName(value.getName())
        .setJoin(joinRelation);
```

2024-11-29 12:53 UTC, koevskinikola approved these changes

2024-11-29 13:37 UTC, merged