feat: store metadata of newly created deployments
camunda/camunda pull request #24692
Opened 2024-11-13 16:51 UTC by lenaschoenburg

This creates a new applier for the Deployment/Created event that actually stores the record in the state. The records only contains the resource metadata.

Because we don't want to overwrite deployments, the processor now checks whether a deployment already exists before handling a distributed Deployment/Create command. If it does, we simply write a rejection.
This also means that we no longer re-create the resources needlessly, so that's a small performance win too.

:thought_balloon: I wasn't sure what to do about the old deployment handling where we remove the deployment from the state once fully distributed. This mechanism is no longer used since we switched to generalized command distribution but the code for it is still there, so there's a chance that we can still remove deployments. Could we remove the old processors/appliers now?

closes #24683

2024-11-14 15:33 UTC, remcowesterhoud requested changes
Thanks @lenaschoenburg, very easy to review 👍 One thing needs to change

2024-11-14 15:42 UTC, remcowesterhoud commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/EventAppliers.java
> +    register(DeploymentIntent.CREATED, 2, new DeploymentCreatedV2Applier());
Maybe it's not? But I suggest just adding a V3. It's 2 minutes of work and guarantees it won't cause issues.

2024-11-15 08:34 UTC, lenaschoenburg commented on zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/EventAppliers.java
> +    register(DeploymentIntent.CREATED, 2, new DeploymentCreatedV2Applier());
Indeed, that was easy to change, see 989ac3b

2024-11-15 08:58 UTC, remcowesterhoud approved these changes
🎉

2024-11-15 09:24 UTC, merged