Add group create service
camunda/camunda pull request #24833
Opened 2024-11-19 08:12 UTC by koevskinikola

## Description

Add a group service together with create, find, and get methods.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #24815

2024-11-22 08:33 UTC, nicpuppa requested changes
Thanks for splitting the PR into separate commits 💪 

Please have a look at my comments 🙏

2024-11-22 08:33 UTC, nicpuppa commented on service/src/test/java/io/camunda/service/GroupServiceTest.java
> +  public void shouldEmptyQueryReturnRoles() {
🔧 `shouldEmptyQueryReturnGroupes`

2024-11-22 08:33 UTC, nicpuppa commented on service/src/test/java/io/camunda/service/GroupServiceTest.java
> +public class GroupServiceTest {
❌ You missed to test the group creation

2024-11-22 08:33 UTC, nicpuppa commented on service/src/test/java/io/camunda/service/GroupServiceTest.java
> +  public void shouldReturnSingleVariable() {
❓ I'm not sure what is the scope of the test, can you clarify ?

2024-11-22 08:33 UTC, nicpuppa commented on service/src/test/java/io/camunda/service/GroupServiceTest.java
> +  public void shouldReturnSingleVariableForGet() {
❓ I'm not sure what is the scope of the test, can you clarify ?

2024-11-22 08:39 UTC, nicpuppa commented on service/src/test/java/io/camunda/service/GroupServiceTest.java
> +public class GroupServiceTest {
Ok I saw you adjusted this in the other PR

2024-11-22 08:39 UTC, nicpuppa commented on service/src/test/java/io/camunda/service/GroupServiceTest.java
> +  public void shouldReturnSingleVariable() {
Same as above

2024-11-22 08:40 UTC, nicpuppa commented on service/src/test/java/io/camunda/service/GroupServiceTest.java
> +  public void shouldReturnSingleVariableForGet() {
Same as above

2024-11-26 11:21 UTC, koevskinikola commented
✅ @nicpuppa all the review feedback is applied.

2024-11-26 11:27 UTC, nicpuppa approved these changes

2024-11-26 12:51 UTC, merged