Migrates IO threads to cpu bound
camunda/camunda pull request #2498
Opened 2019-05-21 13:08 UTC by Zelldon

Migrated the IO bounded threads to the CPU bounded scheduler.  With this change we get more CPU time to execute the processing part and avoid unnecessary idling of the IO Threads.

See the attached profiles 
[io-profiling.zip](https://github.com/zeebe-io/zeebe/files/3202630/io-profiling.zip)

closes #2470

2019-05-22 17:05 UTC, menski requested changes
Please rephrase the configuration file section to not contain the `ioThreadCount` anymore, so an user cannot accidentally set this value. Also please remove the hint that the `cpuThreadCount` should not be higher then the CPU cores, as this is not true anymore.

https://github.com/zeebe-io/zeebe/blob/2470-io-bound/dist/src/main/config/zeebe.cfg.toml#L213-L230

Please also change the default value to `0` of the `ActorSchedulerBuilder`. https://github.com/zeebe-io/zeebe/blob/2470-io-bound/util/src/main/java/io/zeebe/util/sched/ActorScheduler.java#L145

Please add an assert to the `ActorExecutor.submitTask` method to make sure that we not accidentally schedule tasks as io bound in the future, without increasing this configuration parameter again.

```
private ActorFuture<Void> submitTask(ActorTask task, boolean collectMetrics, ActorThreadGroup threadGroup) {
      assert threadGroup.numOfThreads > 0;
```
```

2019-05-22 17:05 UTC, menski commented on broker-core/src/main/java/io/zeebe/broker/system/configuration/ThreadsCfg.java
> +  private int ioThreadCount = 0;
Remove this settings completely from the configuration please, as we do not use any io threads anymore.

2019-05-23 06:04 UTC, Zelldon commented
> Also please remove the hint that the cpuThreadCount should not be higher then the CPU cores, as this is not true anymore.

Here I'm not sure, why it makes sense to have more threads then CPU cores?

2019-05-23 06:05 UTC, Zelldon commented
Proposal change would be:

```
# Controls the number of non-blocking CPU threads to be used. WARNING: You
# should never specify a value that is larger than the number of physical cores
# available. Good practice is to leave at least one for the operating
# system (it has to run somewhere). For example, when running Zeebe on a machine
# which has 4 cores, a good value would be 2.
#
# The default value is 2.
#cpuThreadCount = 2
```

2019-05-23 06:45 UTC, menski commented
> Here I'm not sure, why it makes sense to have more threads then CPU cores?

My main point would be that exporters often tend to be written in a sync fashion, like the elastic exporter. And we saw a degraded performance if we didn't increased the thread count to 16 on a 8core machine in our benchmark setup. But we can also discuss this offline, maybe we want to keep IO threads and put the exporters there.

2019-05-23 15:00 UTC, menski commented
We decide to use the IO threads for exporters, as they often export data in a blocking fashion, i.e. waiting for a response from an external system. (#2513)

2019-05-23 15:00 UTC, closed without merging