chore(broker): restore logstream
camunda/camunda pull request #2514
Opened 2019-05-23 15:11 UTC by deepthidevaki

closes #2429

2019-05-24 11:55 UTC, npepinpe requested changes
:+1:

2019-05-24 11:55 UTC, npepinpe commented on logstreams/src/main/java/io/zeebe/logstreams/impl/service/LogStreamService.java
> +  public boolean canProcess() {
Let's add an uglier workaround in the `LogstreamConfig` as we will figure out a proper way to do this in #2484

2019-05-24 14:33 UTC, npepinpe approved these changes

2019-05-24 15:29 UTC, deepthidevaki commented
bors r+

2019-05-27 07:24 UTC, deepthidevaki commented
bors retry

2019-05-27 07:45 UTC, npepinpe commented
bors retry

2019-05-27 07:51 UTC, npepinpe commented
bors r+

2019-05-27 08:11 UTC, npepinpe commented
bors retry

2019-05-27 08:12 UTC, npepinpe commented
bors r+

not sure why bors always ignores my retry :thinking:

2019-05-27 09:23 UTC, npepinpe commented
Merging manually as the builds fail due to different flaky tests.

2019-05-27 09:26 UTC, merged