pg-migrate-variables-fix
camunda/camunda pull request #25415
Opened 2024-11-28 11:18 UTC by panagiotisgts

## Description

Adjust VariableHandler to take into account `MIGRATED` intents that, by definition, do not contain the variable `value` and would otherwise nullify the variable's value fields.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues
Ref: [Slack thread](https://camunda.slack.com/archives/C06F0GLJNFM/p1732721264015329) 
closes #

2024-11-28 11:56 UTC, panagiotisgts commented
:question:  What about user input's that have `"null"` as value?  Since the Intent is not visible while flushing the entity to the ExportWriter we can't discern the cases I think. Got any clue about this? Could this be a valid user scenario?

2024-12-04 14:14 UTC, romansmirnov requested changes
IMO, there should be a separate handler to handle the migrated intent.

2024-12-04 14:53 UTC, panagiotisgts commented
@romansmirnov @ChrisKujawa @mustafadagher Would it make sense to include the Zeebe Record `Intent` in the flush method signature? It would help in other cases as well such as the [UserTaskHandler](https://github.com/camunda/camunda/blob/ea8722d99f7a276969b32bb762c73a93279098e5/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserTaskHandler.java#L139) where essentially we have to check the updated fields twice since we don't know the Intent of the record. 

Thinking out aloud :thought_balloon:

2024-12-05 10:05 UTC, mustafadagher commented on zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/VariableHandler.java
> +        && !record.getIntent().name().equals(VariableIntent.MIGRATED.name());
🔧 let's compare intent objects not names. i.e. `!record.getIntent().equals(VariableIntent.MIGRATED)
🔧 no need to check that the handled value, it's already guaranteed by the other means

2024-12-05 10:05 UTC, mustafadagher commented on zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/MigratedVariableHandler.java
> +  }
🔧 same here

2024-12-05 10:05 UTC, mustafadagher commented on zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/VariableHandlerTest.java
>    @Test
🔧 could be more fluently done with
```java
@ParameterizedTest
  @EnumSource(
      value = VariableIntent.class,
      names = {"MIGRATED"},
      mode = Mode.EXCLUDE)
```

2024-12-05 10:05 UTC, mustafadagher commented on zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/VariableHandlerTest.java
> +  /*  @Test
❓ why keeping a commented test?

2024-12-05 10:05 UTC, mustafadagher commented on zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/MigratedVariableHandlerTest.java
> +  @Test
🔧 similarly, can be more fluently done using

```java
@ParameterizedTest
  @EnumSource(
      value = VariableIntent.class,
      names = {"MIGRATED"},
      mode = Mode.EXCLUDE)
```

2024-12-05 10:27 UTC, panagiotisgts commented on zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/VariableHandlerTest.java
>    @Test
Good thought :+1:

2024-12-05 10:37 UTC, mustafadagher approved these changes
LGTM!

2024-12-09 08:25 UTC, romansmirnov approved these changes
LGTM.

2024-12-09 08:45 UTC, merged