23907 grpc gateway decode token
camunda/camunda pull request #25422
Opened 2024-11-28 12:41 UTC by nicpuppa

## Description

This PR adds a new interceptor to decode the token, get the user claims from the decoded token and set them into the gRPC context. When the request is forwarded to the broker the user claims are set into the Authorization metadata in a token format.
See commits messages for more details

❗ ❓  The token validation is NOT part of this PR. Since is not easy to implement we need to discuss in details about it

## Related issues

closes #23907

2024-11-28 12:43 UTC, nicpuppa commented on zeebe/auth/src/main/java/io/camunda/zeebe/auth/JwtDecoder.java
> +public class JwtDecoder {
💭 This class should replace the identity SDK, once we decide how to verify the token. 
When we will refactor the auth type format we are going to remove the other 2 encode/decode jwt class

2024-11-29 11:23 UTC, Ben-Sheppard commented
> ❗ ❓ The token validation is NOT part of this PR. Since is not easy to implement we need to discuss more in details about it

@nicpuppa should we discuss this on Monday?

2024-11-29 12:08 UTC, nicpuppa commented
Good to me @Ben-Sheppard

2024-12-02 12:10 UTC, koevskinikola requested changes
The code looks good @nicpuppa, nice job!

The only blocker is how we add the `AuthenticationInterceptor` in the `Gateway` class. Let's discuss this before we can merge this PR.

2024-12-02 12:10 UTC, koevskinikola commented on zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/Gateway.java
> +      interceptors.add(new AuthenticationInterceptor());
❓ We still support `AuthMode.NONE`. Do you think it makes sense to only add this interceptor if the `AuthMode` is `Identity`?

This way, the `AuthenticationInterceptor` will always be invoked, even when we want authentication to be disabled. And I think we might want this mode for local test setups.

2024-12-02 12:10 UTC, koevskinikola commented on zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/interceptors/impl/AuthenticationInterceptor.java
💭 I assume you created a completely new class instead of adding this code to the `IdentityInterceptor`, as we will be removing the code there completely soon.

2024-12-02 12:22 UTC, nicpuppa commented on zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/interceptors/impl/AuthenticationInterceptor.java
Yes, this class will be removed here https://github.com/camunda/camunda/pull/24757

2024-12-02 13:43 UTC, koevskinikola commented on zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/Gateway.java
> +      interceptors.add(new AuthenticationInterceptor());
Yes, so the `AuthenticationInterceptor` shouldn't be invoked at all in that case.

2024-12-02 13:50 UTC, koevskinikola commented on zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/interceptors/InterceptorUtil.java
Sorry, I rambled in my comment above.

My point was that we don't have to add the new `USER_CLAIMS` property in the `InterceptorUtil` class.

The goal for the `InterceptorUtil` class was to make it easier for users to implement multi-tenancy when using Zeebe in a standalone setup. If a user still wants to implement something custom, does the `USER_CLAIMS` property help them in this, or in implementing some custom Authorization mechanism?

2024-12-02 13:59 UTC, koevskinikola commented on zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/Gateway.java
> +      interceptors.add(new AuthenticationInterceptor());
👍 Yes it is, and I mixed up the if-blocks in the code there. Sorry for wasting your time 😅

2024-12-02 14:00 UTC, koevskinikola approved these changes
LGTM @nicpuppa 👏

2024-12-03 08:17 UTC, nicpuppa commented on zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/interceptors/InterceptorUtil.java
Should I remove the property from here then ?

2024-12-03 09:34 UTC, koevskinikola commented on zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/interceptors/InterceptorUtil.java
Yup, it would be safer to remove it.

2024-12-03 10:29 UTC, merged