group rest api user endpoints
camunda/camunda pull request #25618
Opened 2024-12-04 15:17 UTC by koevskinikola

## Description

Add Group REST API endpoints for user assign/unassign operations.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #22387

2024-12-04 15:18 UTC, koevskinikola commented
@remcowesterhoud @nicpuppa sorry for chaining so many PRs, I can also merge them in a single, bigger PR, or base them off the first (create group) PR if you prefer that.

2024-12-06 13:06 UTC, remcowesterhoud requested changes
I think I made it through all your PRs 🎉

2024-12-09 11:20 UTC, koevskinikola commented on zeebe/gateway-protocol/src/main/proto/rest-api.yaml
> +        "500":
👍 I'll also add it to the REST API definition, as it's not documented there.

2024-12-09 13:59 UTC, koevskinikola commented
@remcowesterhoud I applied your feedback.

2024-12-10 14:24 UTC, remcowesterhoud approved these changes
Thanks @koevskinikola 👍 

On a side note I just saw in the `GroupAddEntityProcessor` that we don't check for a duplicate assignment yet. I'll have to check the other processors as well, because if we don't do this check we'll run into consistency check error when we assign an entity multiple times

2024-12-11 08:42 UTC, koevskinikola commented
@remcowesterhoud you added a duplicate check, but only on command distribution ([here](https://github.com/camunda/camunda/blob/e1008fc5d88e739c4ed459353fa09c5f0998157e/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/GroupAddEntityProcessor.java#L117-L125)). It's the same in the other Identity-related processors. 

Should I update them to do this check on the initial command processing?

2024-12-11 08:49 UTC, remcowesterhoud commented
> @remcowesterhoud you added a duplicate check, but only on command distribution ([here](https://github.com/camunda/camunda/blob/e1008fc5d88e739c4ed459353fa09c5f0998157e/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/identity/GroupAddEntityProcessor.java#L117-L125)). It's the same in the other Identity-related processors.
> 
> Should I update them to do this check on the initial command processing?

@koevskinikola That's not a duplicate check. Processing a distributed command must be idempotent. There's no guarantee that the second partition only receives this distributed command a single time. We need to be able to handle this by detecting if we already processed this command. That's what this check is for. If we detect we already added this entity we can reject the command, and acknowledge the distribution. This way the first partition is aware that the distribution was successful.

Without this check we'll run into an exception when we process the distirbuted command twice. That means there won't be an acknowledgement and the first partition will infinitely retry this distribution.

> Should I update them to do this check on the initial command processing?

The check should be added to the initial command processing additionally 🙂

2024-12-11 09:00 UTC, merged

2024-12-11 09:03 UTC, koevskinikola commented
@remcowesterhoud I'll apply the check to roles, groups and tenants today.