feat: add custom keystore/truststore config for zeebe client
camunda/camunda pull request #25666
Opened 2024-12-05 17:13 UTC by igpetrov

## Description

feat: add custom keystore/truststore config for zeebe client

There are cases where a user doesn't want to maintain whole SSL infrastructure for the Camunda cluster but also use X509 authorizes.

This code allows configure SSL context only against authorizer HTTP call.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

Related to: https://github.com/camunda/product-hub/issues/2451

2024-12-09 19:49 UTC, igpetrov commented
Hi @npepinpe 

This one is ready for review

2024-12-10 13:23 UTC, npepinpe commented
@nicpuppa - can you take care of the review please? :pray: I don't think we need more than 1 review, and I trust you can do it well ;)

2024-12-10 14:35 UTC, nicpuppa requested changes
Thanks @igpetrov , looks good. Please have a look at my comments.

❓ Do we want to support this new configuration also in the Spring SDK

2024-12-10 14:35 UTC, nicpuppa commented on clients/java/src/main/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsProvider.java
> +  private SSLSocketFactory createSSLContext() {
🔧 Just a little refactor

```suggestion
  private SSLSocketFactory createSSLContext() {
    if (keystorePath == null && truststorePath == null) {
      return SSLContexts.createSystemDefault().getSocketFactory();
    }
    final SSLContextBuilder builder = SSLContexts.custom();
    try {
      if (keystorePath != null) {
        builder.loadKeyMaterial(
            keystorePath,
            keystorePassword == null ? null : keystorePassword.toCharArray(),
            keystoreKeyPassword == null ? new char[0] : keystoreKeyPassword.toCharArray());
      }

      if (truststorePath != null) {
        builder.loadTrustMaterial(
            truststorePath, truststorePassword == null ? null : truststorePassword.toCharArray());
      }

      return builder.build().getSocketFactory();

    } catch (final NoSuchAlgorithmException 
                   | KeyManagementException 
                   | KeyStoreException 
                   | UnrecoverableKeyException 
                   | CertificateException 
                   | IOException e) {
      throw new RuntimeException("Failed to create SSL context", e);
    }
  }
```

2024-12-10 14:35 UTC, nicpuppa commented on clients/java/src/main/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsProviderBuilder.java
> +      keystoreKeyPassword = envKeystorePassword;
❌ 

```suggestion
      keystoreKeyPassword = envKeystoreKeyPassword;
```

2024-12-10 14:48 UTC, igpetrov commented on clients/java/src/main/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsProviderBuilder.java
> +      keystoreKeyPassword = envKeystorePassword;
Ahh, good catch! Fixed

2024-12-10 14:49 UTC, igpetrov commented on clients/java/src/main/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsProvider.java
> +  private SSLSocketFactory createSSLContext() {
Applied your suggestion. Thank you!

2024-12-10 14:51 UTC, igpetrov commented
@nicpuppa thank you for finding time for this review.

> ❓ Do we want to support this new configuration also in the Spring SDK

Probably, yes, but if so, I will do it in a separate PR.

2024-12-10 15:02 UTC, nicpuppa approved these changes

2024-12-10 15:38 UTC, merged