feat: support process migration in RDBMS #24057
camunda/camunda pull request #26257
Opened 2024-12-18 15:20 UTC by stoerti

## Description

Add support for ProcessInstance migration to RDBMS exporter.

## Related issues

closes #24057

2024-12-20 13:36 UTC, p-wunderlich commented on db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/UserTaskWriter.java
> +            Map.of(
Hm, shouldn't we be consistent regarding how we pass data to mybatis? So by using a pojo ...

2024-12-20 13:36 UTC, p-wunderlich commented on qa/integration-tests/src/test/java/io/camunda/it/exporter/ProcessMigrationIT.java
> +    final var steps = new MigrationSteps(testBroker);
It depends now if we want wo work with this JGiven Like structure

2025-02-11 12:57 UTC, p-wunderlich requested changes

2025-02-11 12:57 UTC, p-wunderlich commented on db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/UserTaskWriter.java
> +      final long userTaskKey,
Normally the exporter creates the model, and here we create it in the writer?

2025-02-11 12:57 UTC, p-wunderlich commented on zeebe/exporters/rdbms-exporter/src/main/java/io/camunda/exporter/rdbms/handlers/UserTaskExportHandler.java
> +              value.getProcessInstanceKey(),
We need the ProcessDefinitionKey here, or not?

2025-02-11 12:57 UTC, p-wunderlich commented on qa/integration-tests/src/test/java/io/camunda/it/exporter/ProcessMigrationIT.java
> +  static final BrokerITInvocationProvider PROVIDER = new BrokerITInvocationProvider();
Why not using the Annotation at class level? 

@ExtendWith(BrokerITInvocationProvider.class)

(I think in the future this test will nevertheless be using the new MultiDbTest Annotation)

2025-02-11 12:57 UTC, p-wunderlich commented on zeebe/exporters/rdbms-exporter/src/main/java/io/camunda/exporter/rdbms/handlers/FlowNodeExportHandler.java
> +        .processDefinitionKey(value.getProcessInstanceKey())
ProcessDefinitionKey should be used here

2025-02-11 13:08 UTC, stoerti commented on qa/integration-tests/src/test/java/io/camunda/it/exporter/ProcessMigrationIT.java
> +  static final BrokerITInvocationProvider PROVIDER = new BrokerITInvocationProvider();
So far RDBMS is not activated for MultiDbTest, so I rather keep it on the old and working path

2025-02-11 13:11 UTC, stoerti commented on db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/UserTaskWriter.java
> +      final long userTaskKey,
I didn't wanted to expose the `UserTaskMapper.MigrateToProcessDto` to the exporter. Did the same in `FlowNodeInstanceWriter#finish`

But yeah 5 parameters are a lot.. I could introduce a `*.domain.UserTaskMigrationDbModel`

2025-02-11 13:39 UTC, p-wunderlich commented on db/rdbms/src/main/java/io/camunda/db/rdbms/write/service/UserTaskWriter.java
> +      final long userTaskKey,
Yes I think that would be better

2025-02-11 16:57 UTC, p-wunderlich approved these changes

2025-02-12 06:41 UTC, merged