feat: RPA files REST endpoint
camunda/camunda pull request #26329
Opened 2024-12-20 12:11 UTC by kzraitel

## Description

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

2024-12-20 12:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda?pullRequest=26329) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda?pullRequest=26329) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda?pullRequest=26329) it.</sub>

2024-12-20 12:11 UTC, kzraitel commented
Merge after https://github.com/camunda/camunda/issues/24772

2024-12-20 15:36 UTC, koevskinikola commented
Hey @kzraitel, I changed the PR base from `main` to the `24772-Support-Resource-in-DeploymentCreateProcessor` branch so that I could filter out the relevant changes. The base will be reverted to `main` once #25918 is merged. I can also put it back to `main` if you prefer.

2025-01-08 13:54 UTC, koevskinikola requested changes
The code looks good @kzraitel. However, it would be good to generalize the implementation here as well, so that responses provide generic "resource" metadata, even though we currently only support RPA resources for it.

This makes the endpoint future-proof for further resource type expansions.

2025-01-08 13:54 UTC, koevskinikola commented on zeebe/gateway-protocol/src/main/proto/rest-api.yaml
> +          $ref: "#/components/schemas/DeploymentRpa"
❌ We should generalize this part as well. To ensure that we can easily expand support for other types of resources, we should name this schema (and the `DeploymentRpaNumberKeys`) to `DeploymentResource` and `DeploymentResourceNumberKeys` appropriately.

We will prevent the deployment of other types of resources with the code implemented [here](https://github.com/camunda/camunda/pull/25918/files#diff-1ba96a098bc7b39fc9ef5c0aea87dfd2184a73a79b0f7574f01067d27cbd71bdR83), and through documentation on what types of resources are supported.

If we name this schema `DeploymentRpa` we will have to add new entities for each new resource type we add support for.

2025-01-13 15:38 UTC, koevskinikola approved these changes
Hey @kzraitel, the code looks good. 👍  

I only have some minor feedback related to the REST API docs, but I'm pre-approving this PR, so you can merge it as soon as the REST API docs are fixed.

2025-01-13 15:38 UTC, koevskinikola commented on zeebe/gateway-protocol/src/main/proto/rest-api.yaml
> +          description: The resource name from which this RPA was parsed.
❌ We still have mentions of RPA in this section. We should generalize it to `resource`.

```suggestion
            The resource ID, as parsed during deployment, together with the version forms a
            unique identifier for a specific form.
        version:
          type: integer
          format: int32
          description: The assigned resource version.
        resourceName:
          type: string
          description: The resource name from which this resource was parsed.
```

2025-01-14 13:37 UTC, merged