chore(docs): update message correlation
camunda/camunda pull request #2663
Opened 2019-06-18 22:26 UTC by jwulf

* Update documentation of message correlation

2019-06-19 15:57 UTC, wints commented on docs/src/reference/message-correlation.md
> +Message catch and boundary events in process definitions are linked to message specifications that have a `name` (the message name) and a `correlationKey`. In the case of the message specification, t
This line confuses me a bit, but I'm not sure how I'd change it. Maybe it's because the configuration step in the process definition isn't mentioned?

2019-06-19 15:58 UTC, wints commented on docs/src/reference/message-correlation.md
> +Messages are published by clients with the `name` and the _value to match_ as the `correlationKey`. The value of the correlationKey in a message is matched against the value of the variable named in
"looks for workflow **instances** listening for that message..." might be a bit more clear

2019-06-19 16:01 UTC, wints commented on docs/src/reference/message-correlation.md
> +Messages have a TTL, so boundary events can be triggered in processes that start after the arrival of a message, if the message TTL has not yet expired when the process starts.
I don't follow this line completely. Can it be reworded?

2019-06-19 16:03 UTC, wints commented
Made a few minor comments here–generally, I find the additions helpful but would want @saig0 to give input before we merge.

2019-06-20 08:46 UTC, saig0 requested changes
Thank you for your input :+1: Please see my comments - it's mainly to align with the other documentation.

BTW: I think it would be good to explain that the message correlation is based on subscriptions of the workflow instance. Currently, it is only shown in the image.

2019-06-20 08:46 UTC, saig0 commented on docs/src/reference/message-correlation.md
> +A message is published by the payment service. It has the name `Money collected` and the message correlationKey is set as `0000-123`. The broker will correlate this message with any running workflows
The word "payload" is outdated and should be replaced by "variables".

2019-06-20 08:46 UTC, saig0 commented on docs/src/reference/message-correlation.md
> +A message is published by the payment service. It has the name `Money collected` and the message correlationKey is set as `0000-123`. The broker will correlate this message with any running workflows
> That means that our order workflow instance will receive a copy of the message.

I'm not sure that this should mean.

2019-06-20 08:46 UTC, saig0 commented on docs/src/reference/message-correlation.md
> +In the case of boundary events, a process does not need to be waiting for the message. In the case of a boundary event, the arrival of a correlated message will either cause an interruption to the cu
This doesn't really belong to the message buffering. I think it is already covered by https://docs.zeebe.io/bpmn-workflows/message-events.html.

2019-06-20 08:46 UTC, saig0 commented on docs/src/reference/message-correlation.md
> +> Note that the uniqueness check only looks into the buffer. If a message is discarded from the buffer then a message with the same name, correlation key and id can be published and correlated after
This is a good addition but I still would not recommend setting a long TTL :sweat_smile: 

> If you need 100% guaranteed idempotency over a long period of time, set a long TTL on the message.

2019-07-04 13:50 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 6b847ab667b1666c14c37838656d0fd497452e57
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2019-08-13 07:26 UTC, Zelldon commented
Any plans to merge this PR ?

2019-08-15 17:40 UTC, jwulf commented
I'm going to let this percolate for a few days: https://zeebe.io/blog/2019/08/zeebe-message-correlation/

Then roll it into the docs.

2019-10-28 14:42 UTC, npepinpe commented
:eyes: 

Any updates on this PR?

2019-10-29 05:03 UTC, saig0 commented
I'll have a look at this PR again in the next weeks and try to integrate the improvements.

2019-11-22 10:51 UTC, Zelldon commented
@saig0 any news on this?

2019-11-22 11:06 UTC, saig0 commented
@Zelldon, after finishing the message aggregator topic, I'll update the message documentation and will merge the PR. Please be patient ;)

2019-12-09 14:28 UTC, saig0 commented
Closing this PR now. I updated the message docs and tried to integrate some feedback.

2019-12-09 14:28 UTC, closed without merging