Improve IncidentRecordValue docs
camunda/camunda pull request #2674
Opened 2019-06-19 12:43 UTC by Zelldon

closes #2626

2019-06-19 13:12 UTC, saig0 requested changes

2019-06-19 13:12 UTC, saig0 commented on protocol/src/main/java/io/zeebe/protocol/record/value/IncidentRecordValue.java
> +   *     some cases the returned value is equal to value of {@link #getElementInstanceKey()}.
I'm not sure if this is more confusing than helpful:

> In some cases the returned value...

We should either explain the cases when this happens or remove this hint :sweat_smile:

2019-06-20 06:46 UTC, Zelldon commented
Agree, I changed it

2019-06-20 06:47 UTC, saig0 approved these changes
bors r+

2019-06-20 07:00 UTC, merged