docs(bpmn-workflows): add docs for multi-instance
camunda/camunda pull request #3118
Opened 2019-09-26 13:39 UTC by saig0

## Description

* add multi-instance section to BPMN workflows
* add markers on the coverage overview

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2019-09-27 12:15 UTC, npepinpe requested changes
:rocket: 

I like it; I highlighted a few typos/things that seem grammatically wrong (? I'm not native though so don't blindly trust me :sweat_smile:) but everything was quite clear. Then again I was involved in this, so maybe it might be interesting to get feedback from Deepthi or Miguel who may not know very well multi-instance.

One thing, we add images and the BPMN that was used to generate them; I'm wondering if it might not be interesting to try out embedding `bpmn.js` (is there a read-only mode?) and just render the BPMNs directly. Not to do in this PR but just a thought

2019-09-27 12:15 UTC, npepinpe commented on docs/src/bpmn-workflows/multi-instance/multi-instance.md
> +When the activity is entered, the multi-instance body is activated and one instance for every element of the `inputCollection` is created (sequentially or in parallel). When the all instances are com
```suggestion
When the activity is entered, the multi-instance body is activated and one instance for every element of the `inputCollection` is created (sequentially or in parallel). When all instances are completed, the body is completed and the activity is left.
```

2019-09-27 12:15 UTC, npepinpe commented on docs/src/bpmn-workflows/multi-instance/multi-instance.md
> +In order to access the current element of the `inputCollection` within the instance, the multi-instance activity can define the `inputElement` variable (e.g. `item`). The element is stored as local v
```suggestion
In order to access the current element of the `inputCollection` within the instance, the multi-instance activity can define the `inputElement` variable (e.g. `item`). The element is stored as a local variable of the instance under the given name.
```

2019-09-27 12:15 UTC, npepinpe commented on docs/src/bpmn-workflows/multi-instance/multi-instance.md
> +Every instance has a local variable `loopCounter`. It holds the index in the `inputCollection` of this instance, starting by `1`.
```suggestion
Every instance has a local variable `loopCounter`. It holds the index in the `inputCollection` of this instance, starting with `1`.
```

2019-09-27 13:05 UTC, saig0 commented
@npepinpe , I applied your suggestions ;)

I'll look into the BPMN rendering afterwards :+1:

2019-09-30 07:48 UTC, npepinpe approved these changes

2019-09-30 07:48 UTC, saig0 commented
bors r+

2019-09-30 08:05 UTC, merged