feat(clients/java): get workflow outcome
camunda/camunda pull request #3242
Opened 2019-10-22 14:58 UTC by deepthidevaki

## Description

* create a workflow instance and get the results (set of variables) when the workflow is completed. 

## Related issues

Related to #2896 
closes #3227 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2019-10-25 08:58 UTC, ChrisKujawa requested changes
I think we need some more tests for the variable stuff the rest looks good

2019-10-25 08:58 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/api/command/CreateWorkflowInstanceCommandStep1.java
>  }
```suggestion

}

interface CreateWorkflowInstanceWithResultCommandStep1 extends FinalCommandStep<WorkflowInstanceResult>
{
  // here we could add later more methods
}
```

2019-10-25 08:58 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/api/command/CreateWorkflowInstanceCommandStep1.java
>  }
If you add this interface and return this on withResult() we are able to add more methods without breaking the public api.
It is also more consistent to the other interfaces.

2019-10-25 08:58 UTC, Zelldon commented on clients/java/src/test/java/io/zeebe/client/workflow/CreateWorkflowInstanceWithResultTest.java
> +    final WorkflowInstanceResult response =
The key point are the variables I think we should test them as well. That we are able to receive them from the response as map, as object etc.

2019-10-25 10:49 UTC, Zelldon commented
Could you also please check the sonargate and the failing builds

2019-10-29 08:27 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 91697bb7086acba78f436fafded51afe14e9d816
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci, build**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2019-10-29 13:25 UTC, ChrisKujawa reviewed
Thanks @deepthidevaki i like the new tests. Do you think we need also a tests for not returning variables which are not on root scope? Not sure if it makes sense actually. So for example variables which are only available at sub process level or you have variables but in sub process you hide them and change the values only at sub process level.

2019-10-29 14:06 UTC, deepthidevaki commented
@Zelldon Isn't it more a test for variable scoping? But I will add one.

2019-10-29 14:44 UTC, deepthidevaki commented
@Zelldon  I added the test. Pls have a look.

2019-10-30 07:00 UTC, ChrisKujawa approved these changes
Very good thanks :+1:

2019-10-30 08:13 UTC, deepthidevaki commented
bors r+

2019-10-30 08:37 UTC, merged