feat(broker): specify variables to include in workflow result
camunda/camunda pull request #3253
Opened 2019-10-24 14:06 UTC by deepthidevaki

## Description

* Added another field in grpc message 'CreateWorkflowInstanceWithResultRequest'
* Response will now include only the requested variables

## Related issues

closes #3226 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2019-10-28 08:00 UTC, ChrisKujawa requested changes
Thanks @deepthidevaki can we discuss some things ?

@saig0 had the idea of removing the response record - for the gateway we do not it (since we do not write it to the stream) what do you think?

2019-11-01 08:18 UTC, ChrisKujawa approved these changes

2019-11-01 08:18 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/api/command/CreateWorkflowInstanceCommandStep1.java
> +     * @return the builder for this command. Call {@link #send()} to complete the command and send *
```suggestion
     * @return the builder for this command. Call {@link #send()} to complete the command and send
```

2019-11-01 08:18 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/api/command/CreateWorkflowInstanceCommandStep1.java
> +     * @return the builder for this command. Call {@link #send()} to complete the command and send *
```suggestion
     * @return the builder for this command. Call {@link #send()} to complete the command and send
```

2019-11-01 08:45 UTC, deepthidevaki commented
bors r+

2019-11-01 14:52 UTC, deepthidevaki commented
bors r+

2019-11-01 15:29 UTC, merged