feat(logstreams): add back pressure on log appender
camunda/camunda pull request #3309
Opened 2019-11-04 12:55 UTC by Zelldon

We observed due to high load in atomix disruptive clusters, which are
 mostly caused by high append latencies.
 With introducing a dynamic back pressure into the log storage
 appender, we try to avoid the overloading of atomix.
 It is possible to use either gradient2 or vegas as back pressure
 algorithm.
 In  our benchmarks it shows that vegas, with configured alpha=MAX(3,
 limit * 0.7)
 and beta=MAX(6, limit * 0.95) functions fits our current needs.

 To see all results take a look at zeebe-io/zeebe#3306

2019-11-04 16:37 UTC, deepthidevaki requested changes
Looks good. Some minor comments.

2019-11-04 16:43 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/impl/backpressure/AppendEntryLimiter.java
> +      Loggers.LOGSTREAMS_LOGGER.warn(
Yes you're right. Even if I do not expect that this happens :D

2019-11-04 16:52 UTC, Zelldon commented
Thanks for the review applied your hints.

2019-11-05 07:55 UTC, deepthidevaki approved these changes
:+1:

2019-11-05 10:24 UTC, Zelldon commented
bors r+

2019-11-05 11:03 UTC, npepinpe commented
Seems the build failed but for some reason Jenkins has it as still pending

2019-11-05 11:05 UTC, npepinpe commented
bors retry

2019-11-05 11:07 UTC, Zelldon commented
bors r-

2019-11-05 11:07 UTC, Zelldon commented
bors r+

2019-11-05 14:20 UTC, merged