feat(broker): support message start event subprocess
camunda/camunda pull request #3312
Opened 2019-11-04 16:38 UTC by MiguelPires

## Description

Adds support for message start events subprocesses (1st commit) and improves the test coverage (2nd commit). I'm not closing issue #3247 because variables tests are not included in this PR.

## Related issues

closes #3209 

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2019-11-05 09:01 UTC, saig0 requested changes
:+1: 

Just a few comments.

2019-11-06 08:34 UTC, MiguelPires commented on engine/src/test/java/io/zeebe/engine/processor/workflow/subprocess/EventSubprocessTest.java
> +                  "added 60s to trigger event for workflow instance {}", key);
That was a debugging thing. I missed it during cleanup

2019-11-06 08:51 UTC, MiguelPires commented on engine/src/test/java/io/zeebe/engine/processor/workflow/subprocess/EventSubprocessTest.java
> +                          .exists());
Sure, I agree that seems clearer

2019-11-06 11:01 UTC, MiguelPires commented
Thanks for the feedback @saig0. I've improved the tests based on your comments

2019-11-06 11:49 UTC, MiguelPires commented
This last commit adds a new test to validate that the workflow instance is kept active even if the process task completes.

2019-11-06 11:59 UTC, MiguelPires commented
@saig0 I added a few more test cases to validate that the workflow instance is kept active if the process completes but the event subprocess is pending and to validate that the event subprocess is terminated if the scope is terminated.

2019-11-06 14:09 UTC, saig0 approved these changes
:+1:

2019-11-06 14:09 UTC, saig0 commented on engine/src/test/java/io/zeebe/engine/processor/workflow/subprocess/EventSubprocessTest.java
> +  private long deployAndWaitForJob(BpmnModelInstance model) {
IMO, the relevant part is that the method triggers the event-subprocess.

```suggestion
  private long createInstanceAndTriggerEvent(BpmnModelInstance model) {
```

2019-11-06 14:09 UTC, saig0 commented on engine/src/test/java/io/zeebe/engine/processor/workflow/subprocess/MultipleEventSubprocessTest.java
> +      new RecordingExporterTestWatcher();
`RecordingExporterTestWatcher` is included by the `BrokerClassRuleHelper`.

2019-11-06 14:09 UTC, saig0 commented on engine/src/test/java/io/zeebe/engine/processor/workflow/subprocess/MultipleEventSubprocessTest.java
> +        .await();
`await()` take the first record - no need to set `limit(1)`

2019-11-06 14:22 UTC, MiguelPires commented
bors r+

2019-11-06 14:48 UTC, MiguelPires commented
bors retry

2019-11-06 15:05 UTC, MiguelPires commented
bors r+

2019-11-06 16:09 UTC, MiguelPires commented
bors r+

2019-11-07 16:10 UTC, menski commented
bors r+

2019-11-09 09:44 UTC, MiguelPires commented
bors r+

2019-11-10 09:22 UTC, MiguelPires commented
Bors r+

2019-11-10 09:39 UTC, merged