fix(exporter): allow multiple shards for Elasticsearch indices
camunda/camunda pull request #3330
Opened 2019-11-07 13:03 UTC by sdorokhova

## Description

* use routing = partitionId when indexing records
* set default shard number to 3 for WORKFLOW_INSTANCE adn JOB indices
* disable query caching for all indices

## Related issues

closes #3329

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2019-11-07 16:00 UTC, menski commented
@sdorokhova could you shortly explain to me the reason you think we should disable the query cache? thanks

2019-11-08 07:17 UTC, sdorokhova commented
@menski , my idea was, that we never do one and the same query again when importing data from Operate. But cache population and eviction is quite active, when import is going on, which can occupy ELS resources:
![image](https://user-images.githubusercontent.com/17064290/68457131-d2043200-01ff-11ea-895c-48a2f6c74c08.png)

Though I'm not sure actually, if it really affects the speed of import in some way. If you have doubts, I can perform a separate test for this.

2019-11-08 08:46 UTC, menski requested changes
Thanks for the explanation. As you changed the shards of two indices this the unit tests are currently failing, see https://github.com/zeebe-io/zeebe/blob/3329-els-exporter-shards/exporters/elasticsearch-exporter/src/test/java/io/zeebe/exporter/AbstractElasticsearchExporterIntegrationTestCase.java#L77. Could you adjust the assert that it based on the index name a different shard count checks? Thanks

2019-11-13 15:32 UTC, menski approved these changes
bors r+

2019-11-13 15:47 UTC, menski commented
bors r+

2019-11-13 16:03 UTC, merged