Docs workflow creation
camunda/camunda pull request #3470
Opened 2019-12-03 05:43 UTC by deepthidevaki

## Description

- Added a section describing different ways to create a workflow instance

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2019-12-03 05:43 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: a604f4fef2cfff06b8801be88c750ab647dbc2d7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 69c5c644705566f3a1c49c79d6e44faeb8e807fa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: be860d3cf063079aaafad7117e2b7c3a9ed75985
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2019-12-03 08:26 UTC, saig0 requested changes
Looks good :+1: 

Just a few comments for improvements.

2019-12-03 08:26 UTC, saig0 commented on docs/src/reference/workflow-creation.md
> +## Explicit creation of a workflow instance
```suggestion
## Create Workflow Instance Command
```

Using common terms from the API/clients could help users to understand it faster.

2019-12-03 08:26 UTC, saig0 commented on docs/src/reference/workflow-creation.md
> +A workflow instance can be created by sending a command specifying the process id or the unique key of the workflow.
```suggestion
A workflow instance can be created by sending a command specifying the BPMN process id or the unique key of the workflow.
```

2019-12-03 08:26 UTC, saig0 commented on docs/src/reference/workflow-creation.md
> + The execution of the workflow happens after the response is send.
An image would help to understand it easier/faster.

2019-12-03 08:26 UTC, saig0 commented on docs/src/reference/workflow-creation.md
> +   <summary>Code example</summary>
What do you think about using the Zbctl instead of the Java client? It is more language agnostic and could help non-Java users.

2019-12-03 08:26 UTC, saig0 commented on docs/src/reference/workflow-creation.md
> +The [CreateWorkflowInstanceWithResult](/reference/grpc.html#createworkflowinstancewithresult-rpc) command allows you to “synchronously” execute workflows and receive the results via a set of variable
An image would help to understand it easier/faster.

2019-12-03 08:26 UTC, saig0 commented on docs/src/reference/workflow-creation.md
> +### Asynchronous execution
What do you think about aligning the two headlines? 
* `Asynchronous Execution` vs. `Synchronous Execution` 
* `Create and Execute Asynchronously` vs. `Create and Await Results`

2019-12-03 08:26 UTC, saig0 commented on docs/src/reference/workflow-creation.md
> +The [CreateWorkflowInstanceWithResult](/reference/grpc.html#createworkflowinstancewithresult-rpc) command allows you to “synchronously” execute workflows and receive the results via a set of variable
We should clarify a bit more that "synchronously" means here to not confuse the users.

2019-12-03 08:26 UTC, saig0 commented on docs/src/reference/workflow-creation.md
> +- Grpc timeout: If the grpc deadlines are not configured for long request timeout, the connection may be closed before the workflow is completed.
```suggestion
- gRPC timeout: If the gRPC deadlines are not configured for long request timeout, the connection may be closed before the workflow is completed.
```

2019-12-03 10:58 UTC, deepthidevaki commented
@saig0 Thanks for the comments. I have added two images and replaced java examples with zbctl. Please have a look.

2019-12-04 06:02 UTC, saig0 approved these changes
:+1: 

Just some minor suggestions for the code examples.

2019-12-04 06:02 UTC, saig0 commented on docs/src/reference/workflow-instance-creation.md
> +  "variables": "{}"
I think, in the example, it would make sense to return some variables.
Why should we wait for the result if it contains no variables? :sweat_smile:

2019-12-04 08:43 UTC, MiguelPires commented
Do we want these docs in 0.22-alpha2?

2019-12-04 09:15 UTC, saig0 commented
Docs are not published during the `alpha` release - just for minor releases.

2019-12-20 10:35 UTC, menski approved these changes
Fine from my side. let's incorporate Philipps proposals and then merge.

2020-01-02 10:06 UTC, falko commented
Are there any plans do add docs on how to use this in the Java client? It took me quite a while to figure out the API there, especially because the fluent API does not allow everything in every step.

2020-01-03 07:26 UTC, deepthidevaki commented
> Are there any plans do add docs on how to use this in the Java client? It took me quite a while to figure out the API there, especially because the fluent API does not allow everything in every step. I almost thought that the Java client does not yet support it.

@falko Do you mean docs for create workflow with awaiting results? How about adding an example here https://docs.zeebe.io/java-client-examples/index.html#workflow ?

2020-01-03 08:30 UTC, deepthidevaki commented
bors r+

2020-01-03 09:02 UTC, merged

2020-01-03 10:47 UTC, falko commented
> @falko Do you mean docs for create workflow with awaiting results? How about adding an example here https://docs.zeebe.io/java-client-examples/index.html#workflow ?

Yes, that is what I mean and I also looked there for a Java client example.