chore(upgrade-tests): add basic upgradability test
camunda/camunda pull request #3775
Opened 2020-02-03 13:24 UTC by MiguelPires

## Description

* added a basic upgradability test
* gets the last released version from the pom
* creates a job in the last version, closes the outdated zeebe, starts a current version, completes the job

## Related issues

closes #3743 

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-02-06 13:13 UTC, npepinpe reviewed
Pretty excited to finally have this :+1: just a few comments

2020-02-06 13:13 UTC, npepinpe commented on parent/pom.xml
> +    <version.zeebe-test-container>0.21.0-alpha2</version.zeebe-test-container>
Can you upgrade to the latest release `0.22.1`?

2020-02-06 13:13 UTC, npepinpe commented on upgrade-tests/pom.xml
> +      <version>0.21.0-alpha2</version>
I guess copy and paste leftover?

2020-02-06 13:13 UTC, npepinpe commented on upgrade-tests/pom.xml
> +          <argLine>-Xmx2048m -XX:MaxDirectMemorySize=4g</argLine>
What happens if we remove this?

2020-02-06 13:13 UTC, npepinpe commented on upgrade-tests/src/test/java/io/zeebe/test/UpgradeTest.java
> +            LOG.error(container.getLogs());
Good idea :+1:

2020-02-06 13:13 UTC, npepinpe commented on upgrade-tests/src/test/java/io/zeebe/test/UpgradeTest.java
> +            LOG.error(container.getLogs());
Maybe we can prefix these? e.g.

```
===============================================
Broker logs
===============================================
...
...
...


===============================================
Gateway logs
===============================================
...
...
```

2020-02-06 14:28 UTC, MiguelPires commented
Thanks for the review @npepinpe.

For transparency: This PR won't be merged until it can be updated to the newest zeebe-test-container version. Currently this test is incompatible with the new version due to the fact that it uses a unsupported tag as a version. So this PR will be pending for a bit until we make some changes and re-release zeebe-test-container.

2020-02-08 16:38 UTC, npepinpe requested changes
Some of the tests failed due to some docker issues - we can look into them together

2020-02-10 15:05 UTC, npepinpe approved these changes
:+1: 

I like it, great job!

2020-02-10 15:20 UTC, MiguelPires commented
bors r+

2020-02-10 15:44 UTC, merged