chore(expression-language): improve variable resolving for expression evaluation
camunda/camunda pull request #3897
Opened 2020-02-21 12:58 UTC by saig0

## Description

* add a method to get a single variable value from the variable state
* pass a context for evaluating an expression instead of all variables to only read the required variables
* replace Jackson MessagePack object mapper by manual transformation using Zeebe's MessagePack reader/writer to reduce overhead

## Related issues

closes #3794

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-02-21 13:00 UTC, saig0 commented
It seems that Spotbugs doesn't like nested Scala classes :/

```
[INFO] --- spotbugs-maven-plugin:3.1.12.2:check (default) @ expression-language ---

[INFO] BugInstance size is 2

[INFO] Error size is 0

[INFO] Total bugs: 2

[ERROR] Null pointer dereference of ? in new io.zeebe.el.impl.feel.FeelVariableContext$EvaluationContextWrapper(FeelVariableContext) [io.zeebe.el.impl.feel.FeelVariableContext$EvaluationContextWrapper] Dereferenced at FeelVariableContext.scala:[line 18] NP_ALWAYS_NULL

[ERROR] Null pointer dereference of ? in new io.zeebe.el.impl.feel.MessagePackContext$MessagePackMapVariableProvider(MessagePackContext, DirectBuffer) [io.zeebe.el.impl.feel.MessagePackContext$MessagePackMapVariableProvider] Dereferenced at MessagePackContext.scala:[line 30] NP_ALWAYS_NULL
```

2020-02-25 10:02 UTC, deepthidevaki requested changes
Looks good :+1:. But my review on the scala code is superficial. Is it not possible to have those scala classes in java?

2020-02-25 10:15 UTC, menski commented
@saig0 I would like to challenge that we introduce more scala in the Zeebe code base. Let's talk about it face to face tomorrow.

2020-02-26 12:02 UTC, saig0 commented on expression-language/src/main/java/io/zeebe/el/impl/Loggers.java
> +  public static final Logger LOGGER = new ZbLogger("io.zeebe.expression-language");
The logger is used in `FeelToMessagePackTransformer.scala` and `MessagePackValueMapper.scala`. 
Currently, we create a class like this if we need a logger in a new module. We could also think about having all loggers defined in the `util` module.

2020-02-26 12:04 UTC, saig0 commented on expression-language/src/main/scala/io/zeebe/el/impl/feel/FeelEvaluationResult.scala
> +class FeelEvaluationResult(
Yes. Because it uses Scala types it was easier to write it in Scala than Java.

2020-02-26 12:12 UTC, saig0 commented
I'm open to challenges :crossed_swords: 

I wrote some classes in Scala which interacts directly with the FEEL engine. Since the FEEL engine uses Scala types, it is easier to use them with Scala code. Sure, it is possible to use purely Java code but this will make it not easier to understand the code.

2020-03-05 07:25 UTC, saig0 commented
I opened an issue to provide a Java-friendly context API in the FEEL engine (https://github.com/camunda/feel-scala/issues/115). When this is implemented then we can replace the current Scala code with proper Java code. Until when we will stay with the few Scala classes which are not exposed to other modules.

@deepthidevaki, I added the missing API docs. Please have a second look. Thanks :)

2020-03-05 07:27 UTC, deepthidevaki approved these changes

2020-03-05 08:48 UTC, saig0 commented
bors r+

2020-03-05 09:55 UTC, saig0 commented
bors retry

2020-03-05 10:16 UTC, merged