Introduce new ZeebeIndex
camunda/camunda pull request #3928
Opened 2020-02-26 14:35 UTC by Zelldon

## Description

**NOTE:** The build will fail until https://github.com/zeebe-io/atomix/pull/165 is merged

 In order to improve seek performance and reduce log deletion time,
 we introducing a new ZeebeIndex. This index wraps the Atomix
 SparseJournalIndex and builds an own map of position to index.

 With this index it is easily and in a performant way possible to look
 up an index/address for a given position. This look up is used
 for example on deletion instead of the old seek strategy. This treats
 time against space, which means we need to use more space in memory but
 are fast to find an index/position.

 The ZeebeIndex is on startup injected into the RaftPartition such that
 is filled on leader and follower on appending new entries.

 The underlying data structure needs to be thread safe, since we access
 it on different threads.

Be aware that it is currently just created on Broker startup and injected into the partition before opening them. I plan to refactor the Broker bootstrap and ZeebePartition with https://github.com/zeebe-io/zeebe/issues/3519 and https://github.com/zeebe-io/zeebe/issues/3518 where I then also rewrite this a bit.

### Benchmarks

I run several benchmarks with iteration of this. I will update this description shortly.

## Related issues

closes https://github.com/zeebe-io/zeebe/issues/3918
closes https://github.com/zeebe-io/zeebe/issues/3623

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-02-26 20:29 UTC, npepinpe commented
Haven't had a chance to look but the results look very promising! The only downside I can see is that not compacting now may lead to out of memory issues faster than before, correct? But we can worry about this in a further iteration. Great job! 👍

2020-03-03 17:10 UTC, deepthidevaki requested changes
Thanks @Zelldon. I have some minor comments.

2020-03-05 13:09 UTC, Zelldon commented on broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java
> +            zeebeIndexMapping, atomixRaftPartition.getServer().openReader(-1, Mode.COMMITS));
Actually here I was not 100% sure, since it used a different index as on newReader. Might that @npepinpe knows.

2020-03-05 13:12 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/log/LogStreamReader.java
> +  long lookupAddress(long position);
What do you mean with the current address? Which current? :sweat_smile: It just checks the index.

2020-03-05 13:17 UTC, Zelldon commented
@deepthidevaki adjusted the branch. thanks for the review

2020-03-05 13:23 UTC, npepinpe commented on broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java
> +            zeebeIndexMapping, atomixRaftPartition.getServer().openReader(-1, Mode.COMMITS));
Hm, I guess we could use it, don't see any reason why not - the goal is just that it starts at the beginning.

2020-03-05 13:24 UTC, Zelldon commented on broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java
> +            zeebeIndexMapping, atomixRaftPartition.getServer().openReader(-1, Mode.COMMITS));
newReader uses index zero or 1 and this one -1 :man_shrugging:

2020-03-05 13:25 UTC, npepinpe commented on broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java
> +            zeebeIndexMapping, atomixRaftPartition.getServer().openReader(-1, Mode.COMMITS));
Yeah, doesn't really matter I think, just that it starts at the beginning, as far as I remember. Just try it and see, should be fine

2020-03-05 13:26 UTC, deepthidevaki commented on logstreams/src/main/java/io/zeebe/logstreams/log/LogStreamReader.java
> +  long lookupAddress(long position);
Sorry. I mean it returns an index corresponding to a pos <= given `position`.

2020-03-05 13:27 UTC, Zelldon commented on logstreams/src/main/java/io/zeebe/logstreams/log/LogStreamReader.java
> +  long lookupAddress(long position);
Ok I think I get it :D

2020-03-05 16:33 UTC, deepthidevaki approved these changes

2020-03-05 16:34 UTC, deepthidevaki commented on broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java
> +            zeebeIndexMapping, atomixRaftPartition.getServer().openReader(-1, Mode.COMMITS));
I have approved the PR. You can change to `atomixLogStorage.newReader()` if you think it wouldn't break anything.

2020-03-09 06:08 UTC, Zelldon commented
bors r+

2020-03-09 06:09 UTC, Zelldon commented on broker/src/main/java/io/zeebe/broker/system/partitions/ZeebePartition.java
> +            zeebeIndexMapping, atomixRaftPartition.getServer().openReader(-1, Mode.COMMITS));
We currently need the implementation class in the AtomixRecordSupplier. I will leave it for now.

2020-03-09 06:27 UTC, merged