Respond NOT_FOUND when partition cannot be found
camunda/camunda pull request #3978
Opened 2020-03-04 14:23 UTC by korthout

## Description

When a request from a client refers to an elementInstanceKey that does
not encapsulate a partition (or encapsulates a non-existing partition),
then the gateway now responds with NOT_FOUND.

The gateway simply checks that the partitionId is part of the known partitions of
the topology.

## Related issues

closes #3961

2020-03-04 15:12 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 1313da6c44575b5c89b5f6299fe3f7d514306413
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d6b25dc9d70bdb22ca883cd0bea8bdcbe45fd80e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-03-05 08:16 UTC, deepthidevaki requested changes
:+1: Looks good. One small comment.

2020-03-05 08:16 UTC, deepthidevaki commented on gateway/src/main/java/io/zeebe/gateway/cmd/PartitionNotFoundException.java
> +    super(String.format("Unknown partition '%d'", partitionId));
I suggest to have a more detailed message. Something like `Expected to send request to partition '0', but partition '0' unknown in topology `. https://github.com/zeebe-io/zeebe/wiki/Error-Guidelines

2020-03-05 08:58 UTC, jwulf requested changes

2020-03-05 09:00 UTC, jwulf commented on gateway/src/main/java/io/zeebe/gateway/cmd/PartitionNotFoundException.java
> +    super(String.format("Unknown partition '%d'", partitionId));
If we can think of / or discover other cases where the user sees this error and this text is misleading, we can adjust.

2020-03-05 16:23 UTC, deepthidevaki approved these changes

2020-03-06 10:42 UTC, korthout commented on gateway/src/main/java/io/zeebe/gateway/impl/broker/BrokerClient.java
> +  <T> ActorFuture<BrokerResponse<T>> sendRequest(BrokerRequest<T> request, Duration requestTimeout);
I reverted the removal of this method after discussing it with @npepinpe.

The method now only exists for a single test, but it was easier just to revert the removal of the method than to rewrite the test. A more thorough refactoring of the BrokerClient is needed anyways.

2020-03-06 10:43 UTC, korthout commented on gateway/src/main/java/io/zeebe/gateway/cmd/PartitionNotFoundException.java
> +    super(String.format("Unknown partition '%d'", partitionId));
@jwulf I've applied your comment to the code. Can you take another look?

2020-03-10 13:42 UTC, jwulf approved these changes
Good work!

2020-03-10 14:06 UTC, korthout commented
bors r+

2020-03-10 14:20 UTC, korthout commented
bors r-

2020-03-11 06:53 UTC, korthout commented
bors r+

2020-03-11 07:11 UTC, merged