docs(appendix): Update docs with new info on configuration
camunda/camunda pull request #4025
Opened 2020-03-10 16:53 UTC by pihme

## Description

This pull request updates and expands the documentation with respect to the new configuration options.

Some tests were also added to address some edge cases that arose while writing the documentation.

## Related issues

closes #3968

## Pull Request Checklist

- [ X ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ X ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ X ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-03-11 16:26 UTC, npepinpe requested changes
:+1: 

I like it. In general I only have minor change requests (e.g. typos), let me know if anything is unclear. 

One thing that came to mind is whether or not we should have the legacy configuration in the appendix, or in the operations section under pre 0.23.x configuration?

2020-03-12 09:00 UTC, pihme commented
@jwulf Did you have time to take a look at this?

2020-03-13 02:16 UTC, jwulf commented on docs/src/introduction/install.md
> +docker run --name zeebe -p 26500-26502:2600-26502 camunda/zeebe:latest
I think we need to have the "legacy" configuration in the docs. My assessment is grounded in our statement that 0.20 was production ready - and I know of several users who have in fact gone into production with pre-0.23 brokers. They will need documentation until they are ready to do the work to migrate to a later version in production.

2020-03-13 02:17 UTC, jwulf commented on docs/src/operations/resource-planning.md
> +eventLogSize = [event log size for duration of maxSnapshots * snapshotPeriod]
I heard that we are fixing snapshots at 1? Simple, sane defaults are best.

2020-03-13 07:58 UTC, jwulf requested changes
Great work! A bunch of minor edits and suggestions - probably the largest keeping the legacy configuration as a reference for existing users.

2020-03-13 07:58 UTC, jwulf commented on docs/src/operations/resource-planning.md
>  On the lead broker of a partition, the current running state is kept in memory, and on disk in RocksDB. In our experiments this grows to 2GB under a heavy load of long-running processes. The snapshot
In our experience this grows

2020-03-13 07:58 UTC, jwulf commented on docs/src/operations/setting-up-a-cluster.md
>  It's possible to specify how often Zeebe clients should send keep alive pings. By default, the official Zeebe clients send keep alive pings every 45 seconds. This interval can be configured through t
By default, the official Zeebe clients (Java and Go) send keep alive pings

2020-03-18 14:52 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 566314bacd1a530ad11ed62f64002a00022dae76
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-03-18 14:52 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 566314bacd1a530ad11ed62f64002a00022dae76
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d3a04559f1d562b486923cddbf9c9677a89c110e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-03-18 14:52 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 566314bacd1a530ad11ed62f64002a00022dae76
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d3a04559f1d562b486923cddbf9c9677a89c110e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-03-18 15:00 UTC, pihme commented on docs/src/operations/configuration.md
> +Zeebe uses Spring Boot for its configuration parsing. So all other ways to configure a Spring Boot application should also work.
done

2020-03-18 15:22 UTC, pihme commented on docs/src/operations/resource-planning.md
> +eventLogSize = [event log size for duration of maxSnapshots * snapshotPeriod]
please look at this section again. I already removed the `maxSnapshot` setting in anticipation of @korthout PR. Still I am unsure about the formulas.

2020-03-18 16:01 UTC, pihme commented on docs/src/operations/resource-planning.md
> +> - Do not configure an exporter which does not not advance its record position (such as the Debug Exporter)
done, please look at this section again

2020-03-18 16:04 UTC, pihme commented on docs/src/operations/resource-planning.md
> +- A cluster loses its quorum. In this case events are queued but not processed. Once a quorum is reestablished, events will be replicated and eventually event log segments will be deleted.
I don't know how to describe this well. Maybe this is also not so much a topic for ordinary resource planning, but more a topic for how to deal with cascading failures.

2020-03-18 16:08 UTC, pihme commented on docs/src/appendix/deprecated-features.md
> +__  ___  ___  __   ___  ___     __   __   __        ___  __
Don't know. I also see many cases where Zeebe is written in lowercase. Who would know such a thing?

2020-03-18 16:10 UTC, pihme commented on docs/src/appendix/environment-variables.md
> +  - `ZEEBE_LOG_LEVEL`: Sets the log level of the Zeebe Logger (default: `info`).
Would like to keep this. Will work for broker + gateway, afaik

2020-03-18 16:12 UTC, pihme commented on docs/src/operations/configuration.md
> +To verify that the configuration was applied, start the application and look at the applications log.
Again, would like to keep it this way. It pertains to Broker and Gateway alike.

2020-03-18 16:12 UTC, pihme commented on docs/src/operations/configuration.md
> +If the configuration could be read, the application will log out the effective configuration during startup:
same reason

2020-03-18 16:13 UTC, pihme commented on docs/src/operations/configuration.md
> +In some cases of invalid configuration the application will fail to start with a warning that explains which configuration setting could not be read.
same reason

2020-03-18 16:17 UTC, pihme commented on docs/src/operations/resource-planning.md
> +The event log for each partition is segmented. By default, the segment size is 512MB. This can be changed in the [configuration](/appendix/broker-config-template.md) with the setting `zeebe.broker.da
Removed the second sentence. Please look at it again whether it is better now

2020-03-18 16:17 UTC, pihme commented on docs/src/operations/resource-planning.md
>  On the lead broker of a partition, the current running state is kept in memory, and on disk in RocksDB. In our experiments this grows to 2GB under a heavy load of long-running processes. The snapshot
yeah, that was what I meant to type :-)

2020-03-18 16:26 UTC, pihme commented
Went through your comments. Incorporated most. Some questions from my side, and some pushback on some points. Please have a look at it again

2020-03-18 16:51 UTC, npepinpe commented on docs/src/operations/resource-planning.md
> +eventLogSize = [event log size for duration of maxSnapshots * snapshotPeriod]
looks good to me :+1:

2020-03-18 16:54 UTC, npepinpe commented on docs/src/operations/resource-planning.md
> +- A cluster loses its quorum. In this case events are queued but not processed. Once a quorum is reestablished, events will be replicated and eventually event log segments will be deleted.
Let's leave it as is for now then

2020-03-18 16:54 UTC, npepinpe approved these changes
Looks good to me :+1:

2020-03-23 12:11 UTC, jwulf requested changes

2020-03-23 12:11 UTC, jwulf commented on docs/src/appendix/deprecated-features.md
> +__  ___  ___  __   ___  ___     __   __   __        ___  __
At the moment it says ZEEBEE with four e's

2020-03-23 12:11 UTC, jwulf commented on docs/src/operations/configuration.md
> +To verify that the configuration was applied, start the application and look at the applications log.
In that case, maybe:

"To verify that the configuration was applied, start Zeebe and look at the log"

2020-03-23 12:11 UTC, jwulf commented on docs/src/operations/configuration.md
> +If the configuration could be read, the application will log out the effective configuration during startup:
In that case, maybe: "Zeebe will log out..."

The reasoning being, that "application" is not a term that we have used to refer to Zeebe previously. Usually we say "the broker".

2020-03-23 12:11 UTC, jwulf commented on docs/src/operations/configuration.md
> +In some cases of invalid configuration the application will fail to start with a warning that explains which configuration setting could not be read.
In some cases of invalid configuration Zeebe will fail to start

2020-03-23 13:36 UTC, pihme commented on docs/src/appendix/deprecated-features.md
> +__  ___  ___  __   ___  ___     __   __   __        ___  __
There is a dedicated issue for this (which sparked some discussion regarding font) #4111

2020-03-23 13:39 UTC, pihme commented on docs/src/operations/configuration.md
> +
I will bring this up with Sebastian or in the team meeting, and create a new issue for this, Here I would like to close it for now, so I can merge the canges

2020-03-23 13:50 UTC, pihme commented
Please have a good look at the documentation again. I had some merge conflicts due to the changes by Nico regarding the removal of the `maxSnapshots` setting.

2020-03-23 15:28 UTC, jwulf approved these changes
YOLO

2020-03-23 16:33 UTC, npepinpe approved these changes
LGTM - only small thing is the 0.25.0 mention, we can already drop support in 0.24.0. Anyway not a blocker, just correct it and merge, no need for another review as far as I can tell :+1:

2020-03-23 16:33 UTC, npepinpe commented on docs/src/appendix/deprecated-features.md
> +- Legacy environment variables - deprecated in 0.23.0-alpha2, to be removed in 0.25.0
```suggestion
- Legacy environment variables - deprecated in 0.23.0-alpha2, to be removed in 0.24.0
```

As far as I know, we support two minor versions, so when we are on 0.24.x, we will be supporting 0.23.x and 0.24.x - so at that point we can already remove legacy configuration support. Correct me if I'm wrong @menski

2020-03-25 08:31 UTC, pihme commented
bors r+

2020-03-25 08:47 UTC, merged

2020-03-25 08:48 UTC, pihme commented
bors retry