chore(logstreams): fixes race condition on LogStream#close()
camunda/camunda pull request #4057
Opened 2020-03-16 12:42 UTC by npepinpe

## Description

- fixes a race condition where the test writes to the dispatcher and closes the LogStream without waiting for the written event to have been persisted on disk
- adds a helper method in LogStreamRule to await a given commit position
- removes some unused methods

## Related issues

closes #4046 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-03-16 13:11 UTC, npepinpe commented
Ah, I introduced another race condition - if the position is already committed, it won't be notified, so it times out if it's too fast now :see_no_evil:

2020-03-16 14:56 UTC, miguelpires requested changes
I'm still getting the timeout you mentioned

2020-03-16 14:57 UTC, npepinpe commented
:+1: 

Is it easy to reproduce? I let it run for ~100 times but it's pretty fast so I could let it run longer.

2020-03-16 15:12 UTC, MiguelPires commented
Yes, I got it after less than 60 runs (13 seconds)

2020-03-17 08:54 UTC, npepinpe commented
My bad, I guess I tried being too clever and actually overriding `setPositionListener` breaks other things :sweat_smile: 

I updated the PR and let it run for quite a while and it looks fine now.

2020-03-17 08:59 UTC, miguelpires approved these changes
:+1:

2020-03-17 09:00 UTC, npepinpe commented
bors r+

2020-03-17 09:17 UTC, merged