chore(ci): collect test results immediately
camunda/camunda pull request #4353
Opened 2020-04-22 16:14 UTC by pihme

## Description

Currently test results are only collected after all test stages completed. The one exception to this is the Go tests which are collected immediately. This should be expanded to the other test stages as well.

## Related issues

closes #4348

## Pull Request Checklist

- [ X ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ X ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ X ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-04-22 17:22 UTC, menski requested changes
I think this does not work as expected as we now publishing the same test results multiple times. See for example https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/4348-collect-test-results-immediately/5/tests where the same test is reported 3 times as failed.

Reason is that all stages as far as I remember the same workspace share, i.e. they will all post the same junit result files. No matter if the test was related to the stage or not.

2020-04-23 06:54 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: f945f84e601ca5fc99ac5dfabf76b5e20478fd0c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-04-23 06:57 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: f945f84e601ca5fc99ac5dfabf76b5e20478fd0c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-04-23 07:06 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: a057da9d566f0dbf03eb4635f44ff1a93971b9a4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-04-23 07:29 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: a057da9d566f0dbf03eb4635f44ff1a93971b9a4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-04-23 07:57 UTC, pihme commented
Good catch! I was wondering about this.

I now made some changes to remedy this: https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/4348-collect-test-results-immediately/11/tests

You still see one test being reported twice, because it is also run twice (once for Java 8 and once for Java 11). I think this is ok, because the test might have different results in different Java versions.

The one thing I am still unhappy about is that the suffix is defined in two places (in shell script and Jenkins file). If you have an idea how to improve this, I am all ears.

2020-04-27 12:04 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: a057da9d566f0dbf03eb4635f44ff1a93971b9a4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-04-27 12:06 UTC, menski commented
> You still see one test being reported twice, because it is also run twice (once for Java 8 and once for Java 11). I think this is ok, because the test might have different results in different Java versions.

This is expected from my side and should stay like this.

> The one thing I am still unhappy about is that the suffix is defined in two places (in shell script and Jenkins file). If you have an idea how to improve this, I am all ears.

My proposal is to use an env var to set this suffix, see https://github.com/zeebe-io/zeebe/pull/4353/commits/f75b7be3eaa088ddce218f1795a391538675b289 how I could imagine it. Basically in the Jenkinsfile we set the env var `SUREFIRE_REPORT_NAME_SUFFIX` per stage. And then use it in the maven surefire configuration and the Jenkinsfile post archive task. WDYT? Feel free to remove/adjust my commit.

2020-04-27 12:07 UTC, menski approved these changes
I will approve this PR as it solves the problem. But feel free to further discuss the topic from my last comment.

2020-04-27 12:37 UTC, pihme commented
Looks good to me. 

I tested what will happen when I run tests locally and the environment variable is not defined. Works just fine.

2020-04-27 12:42 UTC, pihme commented
bors r+

2020-04-27 13:04 UTC, merged