docs(bpmn-workflows): clarify variable visibility of multi-instance
camunda/camunda pull request #4389
Opened 2020-04-27 13:15 UTC by saig0

## Description

* extend variable mapping section of multi-instance page

## Related issues

closes #4362

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-04-27 15:23 UTC, korthout requested changes
It's a good addition, but I would add something about potential race conditions when using non-local variables in parallel multi instance activities. (At least, I think there might be, so correct me if I'm wrong).

2020-04-27 15:23 UTC, korthout commented on docs/src/bpmn-workflows/multi-instance/multi-instance.md
> +The input mappings can be used to create new local variables in the scope of an instance. These variables are only visible within the instance. It is a way to restrict the **visibility** of variables
```suggestion
The input mappings can be used to create new local variables in the scope of an instance. These variables are only visible within the instance. It is a way to restrict the **visibility** of variables. By default, new variables (e.g. provided by a job worker) are created in the scope of the workflow instance and are visible to all instances (i.e. instances of the multi instance activity) as well as outside of the multi-instance activity. If the variable is defined as local variable, then it is not propagated to a parent or the workflow instance scope. This is especially important for parallel multi instance activities, as race conditions may occur when variables are shared among the instances (i.e. non-local variables).
```

2020-04-28 04:47 UTC, saig0 commented
That is a good hint :+1:  Please have a second look.

2020-04-28 06:57 UTC, korthout approved these changes
LGTM

2020-04-28 11:19 UTC, saig0 commented
bors r+

2020-04-28 11:37 UTC, merged