chore(gateway): add flag to enable/disable long polling
camunda/camunda pull request #4660
Opened 2020-06-03 14:16 UTC by korthout

## Description

Adds a config flag `gateway.cluster.longPollingEnabled` (or environment variable `ZEEBE_GATEWAY_CLUSTER_LONGPOLLINGENABLED`) to switch on/off long polling for available jobs.

## Related issues

closes #4415

## WIP

[x] add config flag
[x] test config flag
[x] use config to enable/disable long polling
[ ] test that: given long polling disabled, when requesting to activate jobs and no jobs available, then response is instantly closed; i.e. requests are not blocked (this test assumes long polling is already sufficiently tested)

2020-06-08 13:12 UTC, korthout commented
@deepthidevaki I was unable to verify in a test that the request is responded immediately for non-long polling and not immediately for long polling, because I didn't want to make any tests time dependant. Perhaps you have an idea on how to improve this.

2020-06-10 08:23 UTC, deepthidevaki requested changes
LGTM. Some minor comments. 
For testing with no long polling how about adding it to qa/integration? As a reference `io.zeebe.broker.it.client.command#shouldWaitUntilJobsAvailable`

2020-06-12 15:32 UTC, korthout commented
@deepthidevaki Can you have another look? I will resolve the conflicts after the changes are generally approved.

2020-06-15 07:14 UTC, deepthidevaki approved these changes
:+1: Thanks. Please take a look at LGTM warnings before you merge.

2020-06-15 12:45 UTC, korthout commented
bors r+

2020-06-15 13:16 UTC, korthout commented
bors retry

2020-06-15 13:45 UTC, merged