4396 long polling blocked bug - target 0.23.0
camunda/camunda pull request #4681
Opened 2020-06-08 14:35 UTC by pihme

## Description

This PR proposes a fix to the long polling blocked bug. I don't expect it be approved right away. Instead I hope for some critical comments and engaging discussion.

Please read the issue and the analysis therein to understand what was fixed.

Talking about the fixes:
- for the backpressure the `ActivateJobsHandler` now tracks whether some brokers returned a resource exhausted error and if so, it tells the polling handler about it. I think this change is solid, albeit not very elegant.
- for the time window where the long polling handler did not know that a request is currently running: Here the main idea is to register any active request right away. I think the approach is solid, but the implementation is somewhat lacking. It is quite big for a simple bugfix, and rather small for a major refactoring. Also, besides the intended change in behavior there are some unintended side effects. Like scheduling of long polling requests will change slightly in order. And the number of how often the Broker is queried also changes. The existing code had some downsides, in my opinion, so I took some liberty in deviating from the existing implementation. Having said that, it is hard to know which specific behavior was intended and which was arbitrary. 

Happy to discuss the details and answer any questions. Just want to create the review early given that it is a critical bug and I did the best I could.

## Related issues

closes #4396

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-06-08 15:07 UTC, menski commented
Looping in @deepthidevaki as she was the main author of the original feature. Maybe she has some insides to share.

2020-06-09 08:19 UTC, ChrisKujawa requested changes
Thanks @pihme I just had a look code wise and found some issues we can discuss.

Do you think it makes sense to maybe refactor a bit more the current LongPollingHandler, because it was a bit hard to understand to review it. Or should we do it in a separate issue?

Cool that you found a way to test it. Do you think we can somehow simplify the test ? Does this test fail without your changes?

How you fixed the issue with the missed notification during checking the brokers? Is this because you just retry on onComplete?

2020-06-09 08:19 UTC, Zelldon commented on gateway/src/main/java/io/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java
> +      actor.submit(() -> handlePendingRequests(request.getType()));
So we just continue with sending requests?

2020-06-11 07:08 UTC, deepthidevaki reviewed
I like the solution for handling backpressure. For the second case, I think the idea is good. However the current implementation prevents concurrent activate job requests to be send to the brokers. This will impact the overall job activation latency in normal execution when there are plenty of jobs available.

2020-06-11 07:08 UTC, deepthidevaki commented on gateway/src/main/java/io/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java
> +    if (state.getActiveRequest() == null) {
Isn't this again preventing concurrent requests?

2020-06-11 14:13 UTC, pihme commented on gateway/src/main/java/io/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java
> +          if (state.getActiveRequest() == null
You are so right. I focused so much on the edge case that I forgot the main case.

2020-06-12 14:09 UTC, pihme commented
## Baseline
![grafik](https://user-images.githubusercontent.com/14032870/84511525-f01a9f00-acc6-11ea-8f5b-b45ffadc7451.png)

## Change
![grafik](https://user-images.githubusercontent.com/14032870/84511548-f9a40700-acc6-11ea-847e-1ee21ce5fea4.png)

Not sure what to make of the two benchmarks. They are in the same ballpark. Also note that the changed benchmark ran for longer, whereas I took a screenshot of the baseline right when it started to dip in throughput.

2020-06-16 06:52 UTC, deepthidevaki approved these changes
LGTM. It would be also interesting to run a benchmark with low load - create only a few instances per sec - and verify workflow processing latency.

2020-06-22 08:19 UTC, pihme commented
@menski Do you want to participate in this reivew?

2020-06-22 09:08 UTC, menski commented
@pihme I don't have time right now to focus on that so please don't wait for me

2020-06-25 15:05 UTC, pihme commented
I ran several benchmarks. High throughput, low throughput, settings that were close to menskis setup when he observed the bug, settings that were tailored in an attempt to provoke the bug. 

All I can say is that the software still runs with the changes and performance is within general fluctuation.

I was not able to reproduce the bug or show any significant improvement by the change. I do believe that the benchmarks currently are too blunt a tool to make these precise observations.

2020-06-25 15:35 UTC, pihme commented on gateway/src/main/java/io/zeebe/gateway/impl/job/ActivateJobsHandler.java
> +        false,
See #4824

2020-06-25 15:37 UTC, pihme commented
@npepinpe I cannot access the details for the security/snyk tests. 

Could you have a look at it and let me know what I need to know or whether I can ignore it?

2020-06-25 15:42 UTC, npepinpe commented
It complains about the log4j2 dependency having problems. If you rebase it should be fixed as develop has the updated version, but you can also ignore it.

2020-06-25 15:43 UTC, pihme commented
@npepinpe I am on 0.23 not develop, should this be fixed there as well?

2020-06-25 15:44 UTC, npepinpe commented
Oh right, yeah we should back port it. I can open an issue for it, or we can do it here? It's updating log4j2 to 2.13.3.

2020-06-25 15:46 UTC, pihme commented
I can do it with this PR

2020-06-26 08:38 UTC, ChrisKujawa approved these changes
:+1:

2020-06-26 10:28 UTC, pihme commented
bors r+

2020-06-26 10:39 UTC, pihme commented
bors retry

2020-06-26 10:54 UTC, pihme commented
bors retry

2020-06-26 11:09 UTC, pihme commented
bors retry

2020-06-26 11:24 UTC, pihme commented
bors retry

2020-06-26 11:43 UTC, pihme commented
bors retry

2020-06-26 11:59 UTC, pihme commented
bors retry

2020-06-26 12:14 UTC, pihme commented
bors retry

2020-06-26 12:48 UTC, pihme commented
bors retry

2020-06-26 13:16 UTC, pihme commented
bors retry

2020-06-26 13:44 UTC, pihme commented
bors retry

2020-06-26 13:58 UTC, pihme commented
bors retry

2020-06-26 14:21 UTC, npepinpe commented
If you're sure you can merge it yourself, looks like you've hit a particularly bad patch of flaky tests :S

2020-06-26 14:26 UTC, pihme commented
bors retry

2020-06-26 14:40 UTC, pihme commented
bors retry

2020-06-29 08:44 UTC, merged

2020-06-29 08:45 UTC, pihme commented
Merged manually due to unstable 0.23 branch