fix(engine): catch error event on multi-instance activity
camunda/camunda pull request #4751
Opened 2020-06-16 13:16 UTC by saig0

## Description

* be aware of multi-instance activities when looking for an error catch event
* add new helper method to resolve the element based on a given BPMN element type to handle multi-instance activities

## Related issues

closes #4601 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

2020-06-17 11:19 UTC, korthout requested changes
Fix looks good, but I have a small comment

2020-06-17 11:19 UTC, korthout commented on engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java
> +  private ExecutableFlowElement getParentWorkflowScope(
I understand that the `getElementById` now needs an elementType, but this should always be `CALL_ACTIVITY` for this method. I also think that the return type can be specified to ExecutableCallActivity, as other elements should not be provided by this method.

2020-06-17 11:19 UTC, korthout commented on engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java
> +    final var elementType = callActivityContext.getBpmnElementType();
So I would change this to:
```suggestion
    final var elementType = BpmnElementType.CALL_ACTIVITY;
```

2020-06-17 11:33 UTC, saig0 commented on engine/src/main/java/io/zeebe/engine/nwe/behavior/BpmnStateTransitionBehavior.java
> +    final var elementType = callActivityContext.getBpmnElementType();
:+1:

2020-06-17 11:38 UTC, saig0 commented
@korthout, please have a second look. I applied your hints :wink:

2020-06-18 10:07 UTC, korthout approved these changes
LGTM 👍

2020-06-18 13:42 UTC, saig0 commented
bors r+

2020-06-18 14:04 UTC, merged