Improve test stability
camunda/camunda pull request #4962
Opened 2020-07-14 09:35 UTC by saig0

## Description

* the test `HealthMonitoringTest.java` is currently unstable on `0.23` 
* the stability of the test has been improved already on `develop` and `0.24`
* backport the changes from `develop` to `0.23` to improve the stability of the branch

## Related issues

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release annoncement

2020-07-14 09:56 UTC, Zelldon commented
@saig0 do you have an reference of the previous PR which removed the other test? Would like to understand that.

2020-07-14 11:06 UTC, saig0 commented
@Zelldon, the test case was removed by #4635.

2020-07-14 12:10 UTC, Zelldon commented
@saig0 actually this test was moved into new class https://github.com/zeebe-io/zeebe/pull/4635/files#diff-4e11261a358cd52aaa3b68056dbabc64

2020-07-15 06:34 UTC, ChrisKujawa requested changes
Could you please do the same as on the reference PR and add the other test as replacement or is this not possible?

2020-07-15 09:35 UTC, saig0 commented
:see_no_evil: I'll try.

2020-07-15 12:20 UTC, saig0 commented
@Zelldon, I added the missing test class :sweat_smile:

2020-07-17 10:18 UTC, ChrisKujawa approved these changes

2020-07-20 07:20 UTC, saig0 commented
bors r+

2020-07-20 08:30 UTC, saig0 commented
bors r+

2020-07-20 09:09 UTC, saig0 commented
bors r+

2020-07-20 11:05 UTC, saig0 commented
bors r+

2020-07-20 11:43 UTC, merged