Clean up poms
camunda/camunda pull request #4998
Opened 2020-07-17 14:00 UTC by Zelldon

## Description

 *  fix scm deprecation errors
 * remove duplicate dependencies

## Related issues

related to https://github.com/zeebe-io/zeebe/issues/2165

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

2020-07-17 14:29 UTC, npepinpe requested changes
Thanks for this! Only one suggestion, I would enforce not having duplicate dependencies. wdyt?

2020-07-17 14:29 UTC, npepinpe commented on parent/pom.xml
>              </execution>
```suggestion
            </execution>
             <execution>
              <id>enforce-unique-dependencies</id>
              <goals>
                <goal>enforce</goal>
              </goals>
              <configuration>
                <rules>
                  <banDuplicatePomDependencyVersions/>
                </rules>
              </configuration>
            </execution>
```

2020-07-17 14:35 UTC, Zelldon commented
Lets do it👍

2020-07-18 12:15 UTC, Zelldon commented
Bors r+

2020-07-18 13:08 UTC, npepinpe approved these changes
Sorry i thought I had approved it

2020-07-18 13:41 UTC, Zelldon commented
Me2😬

Bors r+

2020-07-18 15:16 UTC, npepinpe commented
bors retry

2020-07-18 15:39 UTC, merged