chore(atomix): use compatible serializers
camunda/camunda pull request #5042
Opened 2020-07-23 15:25 UTC by MiguelPires

## Description

This PR changes the serializer we use in Atomix from the FieldSerializer to the VersionFieldSerializer. This will allow us to make backwards compatible changes to the serialized classes in the future. In order to provide a way for users to upgrade, the serializer used for storage tries to deserialize first with the VersionFieldSerializer and, if that fails then it uses the old one.

I have tested this manually but I haven't started a benchmark yet since the grafana dashboard is broken. I opened a PR to fix it and, when it's merged I'll start a benchmark.

## Related issues

closes #5038

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatible with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [x] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

2020-07-23 15:59 UTC, pihme requested changes
I am missing tests for `FallbackNamespace`. Maybe a unit test based on mocks to make sure the right namespace is called for deserialization, and an integration test which deserializes an old and a new message successfully?

2020-07-28 09:33 UTC, MiguelPires commented
Thanks for the feedback @pihme. I added the tests you mentioned. Let me know if there's anything else that can be improved

2020-07-29 06:38 UTC, MiguelPires commented on atomix/cluster/src/main/java/io/atomix/raft/partition/impl/RaftNamespaces.java
> +    RAFT_STORAGE = new FallbackNamespace(legacy, compatible);
Simply backporting this wouldn't work but we can adjust it slightly to make a two-step upgrade work. Besides allowing brokers to deserialize both versions (which one is the fallback is irrelevant I think), they would still serialize in the "old" format (i.e., non-compatible). This way, when upgrading from 0.24.x to 0.24.x+1, the 0.24.x brokers could read 0.24.x+1 messages and the rolling upgrade would work. After that the 0.24.x+1 brokers would be able to accept 0.25 brokers into the cluster, even though these work serialize in the new compatible format.

2020-07-29 06:51 UTC, MiguelPires commented on atomix/utils/src/main/java/io/atomix/utils/serializer/FallbackNamespace.java
> +  private final Namespace legacy;
`default` is a Java keyword. Maybe one can be just `namespace` and the other `fallback`/`fallbackNamespace`, does that work for you?

2020-07-29 07:05 UTC, pihme commented on atomix/utils/src/main/java/io/atomix/utils/serializer/FallbackNamespace.java
> +  private final Namespace legacy;
Sure

2020-07-29 07:06 UTC, pihme commented on atomix/cluster/src/main/java/io/atomix/raft/partition/impl/RaftNamespaces.java
> +    RAFT_STORAGE = new FallbackNamespace(legacy, compatible);
Sounds good

2020-07-29 07:12 UTC, pihme approved these changes
Looks good to me. Elegant solution.

2020-07-29 07:12 UTC, pihme commented
Will be interesting to see the effect on performance in the benchmarks.

2020-07-29 07:13 UTC, pihme commented
Did you get a chance to talk to Steve about the importance of rolling upgrades?

2020-07-29 07:18 UTC, MiguelPires commented
I spoke to menski and Tim but not Steve actually, since he was in BPMN training. I have a meeting scheduled for today to discuss next steps. At least this is a partial solution that we can build on to provide rolling upgrades. I'll can start a benchmark now before merging

2020-08-03 08:15 UTC, MiguelPires commented
The benchmark is still running after several days and its throughput is similar to the baseline, so I think this can be merged

2020-08-03 08:16 UTC, MiguelPires commented
bors r+

2020-08-03 08:50 UTC, merged