benchmarks: add duration limit to starter
camunda/camunda pull request #5243
Opened 2020-08-26 12:29 UTC by falko

## Description

Add an optional limit of the test duration.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backward compatible with previous versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criteria of the issue
* [ ] New tests are written to ensure backward compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-08-26 12:33 UTC, falko commented
@pihme it currently still uses `System.exit`. Ideally, we change that to something more graceful as discussed today

2020-08-26 12:55 UTC, pihme commented
@Zelldon don't want to make any changes here without your consent

2020-08-27 12:23 UTC, Zelldon requested changes, later dismissed
Like it, but could we not directly also implement the todo?

2020-08-27 12:23 UTC, Zelldon commented on benchmarks/project/src/main/java/io/zeebe/Starter.java
> +            // TODO can one use scheduledFuture.cancel(false) to gracefully
Who is the one ? :sweat_smile:

2020-08-27 12:23 UTC, Zelldon commented on benchmarks/project/src/main/java/io/zeebe/Starter.java
> +            // TODO can one use scheduledFuture.cancel(false) to gracefully
So what you want to do is canceling the timer, stopping the execution service. Await all remaining responses and then exit right?

2020-09-03 12:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zeebe-io/zeebe?pullRequest=5243) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/zeebe-io/zeebe?pullRequest=5243) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: falko<br/>:x: pihme<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zeebe-io/zeebe?pullRequest=5243) it.</sub>

2020-10-08 07:05 UTC, Zelldon approved these changes
Thanks guys :+1:

2020-10-08 07:05 UTC, Zelldon commented
bors r+

2020-10-08 07:30 UTC, merged