Add flag to disable disk usage watermarks
camunda/camunda pull request #5260
Opened 2020-08-28 14:42 UTC by menski

## Description

On disabling watermarks for disk usage the watermarks are set to 1, meaning the whole disk space can be used.

## Related issues

closes #5214 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-08-31 12:15 UTC, deepthidevaki reviewed
When it is disabled, diskSpaceMonitor is still running. But since the threshold is 1.0 it doesn't react to disk full, is that the idea? Should we 'not start' diskSpaceMonitor when it is disabled?

2020-08-31 12:15 UTC, deepthidevaki commented on broker/src/main/java/io/zeebe/broker/system/configuration/DataCfg.java
> +  private boolean diskUsageWatermarkEnabled = DEFAULT_DISK_USAGE_WATERMARK_ENABLED;
I recommend to name it `diskUsageMonitoringEnabled`.

2020-08-31 15:18 UTC, menski commented
I renamed the property and skipped the scheduling of the disk space monitor actor. I wasn't feeling confident to also skip the creation of the disk space monitor as it is also used in another startup step.

2020-09-01 07:43 UTC, deepthidevaki requested changes
Thanks. Can you also add the new config param to `broker.yaml.template` and `broker.standalone.template`

2020-09-01 07:43 UTC, deepthidevaki commented on broker/src/main/java/io/zeebe/broker/Broker.java
>      diskSpaceUsageListeners.forEach(l -> diskSpaceUsageMonitor.addDiskUsageListener(l));
We can also skip this step when monitoring is disabled.

2020-09-01 08:56 UTC, menski commented
I rebased the branch after merging #5259, I updated the config and the documentation. Let me know if anything is left.

2020-09-01 09:09 UTC, deepthidevaki approved these changes
:tada:

2020-09-01 09:12 UTC, menski commented
bors r+

2020-09-01 09:36 UTC, merged