chore(benchmarks): add docs for changing log levels dynamically
camunda/camunda pull request #5309
Opened 2020-09-07 09:01 UTC by deepthidevaki

## Description

Add docs on how to change log levels dynamically.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-09-07 09:47 UTC, pihme requested changes
This looks all good and well. 

However, I think we should also mention it in the Zeebe documentation in the Operations Chapter

Maybe the best place with the current content would be to add this also to operations/configuration.md/Logging

2020-09-10 07:04 UTC, deepthidevaki commented
Thanks @pihme . Docs are now added to the main documentation. Please have a look.

2020-09-10 07:40 UTC, pihme approved these changes
Some editorial changes

2020-09-10 07:40 UTC, pihme commented on docs/src/operations/configuration.md
> +Zeebe brokers expose a [Spring Boot Actuators web endpoints](https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#loggers)
```suggestion
Zeebe brokers expose a [Spring Boot Actuators web endpoint](https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#loggers)
```

2020-09-10 07:40 UTC, pihme commented on docs/src/operations/configuration.md
> +To change the log level of a broker make a `POST` request to the `/actuator/loggers/{logger.name}` endpoint as shown in the example below.
```suggestion
To change the log level of a logger make a `POST` request to the `/actuator/loggers/{logger.name}` endpoint as shown in the example below.
```

2020-09-10 14:41 UTC, deepthidevaki commented
bors r+

2020-09-10 16:09 UTC, merged