feat(clients/go, clients/java): Add message key to the response of publish message
camunda/camunda pull request #5343
Opened 2020-09-12 19:52 UTC by aivinog1

## Description

1. Add the key to the response of the publish message method in the protobuf file.
2. Add the key to the response in the gateway
3. Add a new class of response in java client
4. Some little tests.

## Related issues

closes #4794

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-09-16 11:21 UTC, saig0 commented
@aivinog1 thank you for your contribution :cookie: I'll look at it soon.

2020-09-17 06:39 UTC, saig0 requested changes
Looks good :cake: 

Just a few minor comments :)

2020-09-17 06:42 UTC, saig0 commented
@MiguelPires the Go build failed with these changes. It seems to be a problem with the Go backward compatibility check.

<details>
  <summary>Go Build Output</summary>
  <p>

```
[2020-09-17T06:03:06.069Z] + .ci/scripts/distribution/build-go.sh

[2020-09-17T06:03:06.069Z] + set -o pipefail

[2020-09-17T06:03:06.069Z] + export CGO_ENABLED=0

[2020-09-17T06:03:06.069Z] + CGO_ENABLED=0

[2020-09-17T06:03:06.069Z] + ORG_DIR=/go/src/github.com/zeebe-io

[2020-09-17T06:03:06.069Z] + mkdir -p /go/src/github.com/zeebe-io

[2020-09-17T06:03:06.069Z] + ln -s /home/jenkins/agent/workspace/_key-to-publish-message-response /go/src/github.com/zeebe-io/zeebe

[2020-09-17T06:03:06.069Z] + cd /go/src/github.com/zeebe-io/zeebe/clients/go

[2020-09-17T06:03:06.069Z] + PREFIX=github.com/zeebe-io/zeebe/clients/go

[2020-09-17T06:03:06.069Z] + EXCLUDE=

[2020-09-17T06:03:06.069Z] + for file in {internal,cmd/zbctl/internal}/*

[2020-09-17T06:03:06.069Z] + EXCLUDE=' --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/containersuite'

[2020-09-17T06:03:06.069Z] + for file in {internal,cmd/zbctl/internal}/*

[2020-09-17T06:03:06.069Z] + EXCLUDE=' --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/containersuite --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/embedded'

[2020-09-17T06:03:06.069Z] + for file in {internal,cmd/zbctl/internal}/*

[2020-09-17T06:03:06.069Z] + EXCLUDE=' --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/containersuite --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/embedded --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/mock_pb'

[2020-09-17T06:03:06.069Z] + for file in {internal,cmd/zbctl/internal}/*

[2020-09-17T06:03:06.069Z] + EXCLUDE=' --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/containersuite --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/embedded --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/mock_pb --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/utils'

[2020-09-17T06:03:06.069Z] + for file in {internal,cmd/zbctl/internal}/*

[2020-09-17T06:03:06.069Z] + EXCLUDE=' --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/containersuite --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/embedded --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/mock_pb --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/utils --exclude-package github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands'

[2020-09-17T06:03:06.069Z] + /usr/bin/gocompat compare --go1compat --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/containersuite --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/embedded --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/mock_pb --exclude-package github.com/zeebe-io/zeebe/clients/go/internal/utils --exclude-package github.com/zeebe-io/zeebe/clients/go/cmd/zbctl/internal/commands ./...

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".DeployWorkflowRequest.XXX_NoUnkeyedLiteral FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".DeployWorkflowRequest.XXX_unrecognized FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".DeployWorkflowRequest.XXX_sizecache FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".DeployWorkflowRequest.XXX_Unmarshal MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".DeployWorkflowRequest.XXX_Marshal MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".DeployWorkflowRequest.XXX_Merge MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".DeployWorkflowRequest.XXX_Size MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".DeployWorkflowRequest.XXX_DiscardUnknown MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".NewGatewayClient SignatureChanged

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".Partition.XXX_NoUnkeyedLiteral FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".Partition.XXX_unrecognized FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".Partition.XXX_sizecache FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".Partition.XXX_Unmarshal MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".Partition.XXX_Marshal MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".Partition.XXX_Merge MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".Partition.XXX_Size MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".Partition.XXX_DiscardUnknown MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_NoUnkeyedLiteral FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_unrecognized FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_sizecache FieldDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_Unmarshal MethodDeleted

[2020-09-17T06:03:32.680Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_Marshal MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_Merge MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_Size MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_DiscardUnknown MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_NoUnkeyedLiteral FieldDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_unrecognized FieldDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_sizecache FieldDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_Unmarshal MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_Marshal MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_Merge MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_Size MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_DiscardUnknown MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ActivateJobsRequest.XXX_NoUnkeyedLiteral FieldDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ActivateJobsRequest.XXX_unrecognized FieldDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ActivateJobsRequest.XXX_sizecache FieldDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ActivateJobsRequest.XXX_Unmarshal MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ActivateJobsRequest.XXX_Marshal MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ActivateJobsRequest.XXX_Merge MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ActivateJobsRequest.XXX_Size MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ActivateJobsRequest.XXX_DiscardUnknown MethodDeleted

[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".PublishMessageRequest.XXX_NoUnkeyedLiteral FieldDeleted

[2020-09-17T06:03:32.681Z] "githu [...]

2020-09-17 06:46 UTC, saig0 commented on gateway-protocol/src/main/proto/gateway.proto
> +  int64 key = 1;
Looking at https://github.com/zeebe-io/zeebe/wiki/Protocol-Backwards-Compatibility#protobuf.

Okay. We don't need the optional but the default value should still make sense.

2020-09-18 06:03 UTC, saig0 commented
Sounds odd for me :thinking: The PR just adds a new field in the response of the publish message command. 
Please guide @aivinog1 to fix the issue. Thank you :moon_cake:

2020-09-18 06:15 UTC, aivinog1 commented
@MiguelPires @saig0 Maybe I should generate go files using the same version of `protoc-gen-go` that used by you and we should update the README of `gateway-protocol-impl` to the usage of the generator with approved version? If there will a need to choose another version (maybe the latest or something else) we will update the README.

2020-09-18 06:41 UTC, aivinog1 commented
@saig0 I've amended changes that you requested to the latest commit :)

2020-09-18 07:01 UTC, aivinog1 commented on gateway-protocol/src/main/proto/gateway.proto
> +  int64 key = 1;
@saig0 I'm trying to compile with the code that you provided and I see this:
```
[INFO] Compiling 1 proto file(s) to /Users/a.i.vinogradov/IdeaProjects/zeebe/gateway-protocol-impl/target/generated-sources/protobuf/java
[ERROR] PROTOC FAILED: gateway.proto:230:37: Explicit default values are not allowed in proto3.

[ERROR] /Users/a.i.vinogradov/IdeaProjects/zeebe/gateway-protocol-impl/target/proto/gateway.proto [0:0]: gateway.proto:230:37: Explicit default values are not allowed in proto3.
```

Start looking into docs: https://developers.google.com/protocol-buffers/docs/proto3#default I see that default values are already used (for example, for numeric values it is zero). So, can you provide a solution you like:
1. Use dirty workarounds, like https://stackoverflow.com/a/55402302/11112760 to make it returns -1 by default.
2. Use the default value that proto3 provides.

2020-09-18 07:29 UTC, aivinog1 commented on gateway-protocol/src/main/proto/gateway.proto
> +  int64 key = 1;
Now I just add a comment about the new field :)

2020-09-22 12:46 UTC, MiguelPires commented
@aivinog1 sorry for the delay. I just opened a PR to fix the code generation and updated the generated protobuf code as well. When that PR is merged, the build should be fixed. I'll look into it when it's merged and see if any issues persist

2020-09-23 13:43 UTC, MiguelPires commented
@saig0 @aivinog1 I rebased on develop and the build is passing https://github.com/zeebe-io/zeebe/tree/aivinog1-4794-add-key-to-publish-message-response :+1:

2020-09-28 04:59 UTC, aivinog1 commented
@saig0 Hi! I've rebased the current branch to the current develop branch and fix all your review comments :)

2020-09-28 11:46 UTC, saig0 requested changes
Thank you @aivinog1 for your engagement :candy: 

I looked at the changes again. These are the remaining points before we can merge the PR: 

* Zbctl: print the message key from the response `clients/go/cmd/zbctl/internal/commands/publishMessage.go`
* Java client tests: adjust the test case and verify the message key in the response: `clients/java/src/test/java/io/zeebe/client/workflow/PublishMessageTest.java`
* QA Integration tests: add a new test case and verify the message key in the response: `qa/integration-tests/src/test/java/io/zeebe/broker/it/client/command/MessageCorrelationTest.java`
* Documentation: update the gRPC section: `docs/src/reference/grpc.md`

2020-09-28 11:46 UTC, saig0 commented on clients/java/src/main/java/io/zeebe/client/api/response/PublishMessageResponse.java
> +  long messageKey();
Align the method name with the other responses. 

```suggestion
  long getMessageKey();
```

2020-09-29 06:45 UTC, aivinog1 commented
@saig0 Hi, I've fixed all your comments :)

2020-09-29 12:45 UTC, saig0 requested changes
Thanks @aivinog1 :doughnut: 

Just a few minor improvements for the tests. Then it's done :rocket:

2020-09-29 12:45 UTC, saig0 commented on clients/java/src/test/java/io/zeebe/client/workflow/PublishMessageTest.java
> +    assertThat(response.getMessageKey()).isZero();
Let's check that we return the correct key. 

First, we need to instrument the gateway:
```
    // given
    final long messageKey = 123L;
    gatewayService.onPublishMessageRequest(messageKey);
```

When we can check the response:
```suggestion
    assertThat(response.getMessageKey()).isEqualTo(messageKey);
```

In `io.zeebe.client.util.RecordingGatewayService`, we need to add the new method to control the response:

```
  public void onPublishMessageRequest(final long key) {
    addRequestHandler(
        PublishMessageRequest.class,
        request -> PublishMessageResponse.newBuilder().setKey(key).build());
  }
```

2020-09-29 12:49 UTC, aivinog1 commented
@saig0 Thanks for such a comprehend review, I found a lot of interesting stuff about the project while fixing it :)

2020-09-29 13:25 UTC, aivinog1 commented
@saig0 All your review comments are fixed now :)

2020-09-30 03:40 UTC, saig0 approved these changes
@aivinog1 nice job :tada: 
Thank you for your contribution and your patience :+1:

2020-09-30 03:40 UTC, saig0 commented
bors r+

2020-09-30 04:07 UTC, merged

2020-09-30 17:43 UTC, Zelldon commented
Awesome thanks @aivinog1