feat(clients/java): Add gatewayAddress method & deprecate brokerContactPoint method
camunda/camunda pull request #5345
Opened 2020-09-14 09:46 UTC by aivinog1

## Description

I create the `gatewayAddress` method in the client builder, configuration, and deprecate the `brokerContactPoint` method.
**Note**: To keep PR small I've decided to move part with switching to the new method in internal parts of the project (inner logic, tests) to another PR.

## Related issues
#2973 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-09-15 09:26 UTC, aivinog1 commented
@npepinpe Hi! I've inspected the analysis report from SonarCloud and I have a question: what version should I use in the `java.lang.Deprecated#since`? I'm thinking about `0.25.0-SNAPSHOT` or `0.25.0-alpha2`, for example, but I'm not sure about it :)

2020-09-15 10:48 UTC, npepinpe requested changes
Thanks @aivinog1!

One small thing about the deprecation, normally with Java 9+ we can simply add a since param to the annotation, but in this case (as it's Java 8) we can't - can we add that in the Javadoc though? Inform users that it's deprecated since 0.25.0, and will be removed in 0.26.0.

Additionally, can you update the documentation and the usages of `brokerContactPoint` everywhere, since we're going to deprecate it?

2020-09-15 11:30 UTC, aivinog1 commented
@npepinpe I've amended all changes that you request in my commit, can you check it again, please? :)

2020-09-15 15:19 UTC, npepinpe requested changes
Hey @aivinog1, thanks for the quick turn around! I'm sorry, I think I wasn't clear in my last review :sweat_smile: 

Since we're on Java 8 for the client and we can't use `@Deprecated(since = )`, it's important to have the Javadoc annotation `@deprecated` and to add since when, but we also still need the `@Deprecated` annotation on the properties/methods. You can see SonarCloud complaining about it (do you have access to it? If not tell me and I can try to figure out something).

Also, if you could please update the Zeebe code where `brokerContactPoint` is used - there's the samples, but also in our own tests wherever we create the clients. If we don't, we'll end up ourselves with deprecation warnings :slightly_smiling_face: I would also be OK with doing that in a follow up issue - you can create a new maintenance issue for this, and then do the migration in a separate PR, but we should do that as soon as possible to not forget.

Let me know if anything's unclear, or just chime in on Slack :+1:

2020-09-18 07:50 UTC, aivinog1 commented
@npepinpe As we discuss in Slack, I return `@Deprecated` and looking forward to create a draft PR with internal usage of `brokerContactPoint` updated.

2020-09-21 14:41 UTC, npepinpe approved these changes
:+1:

2020-09-21 14:41 UTC, npepinpe commented
bors r+

2020-09-21 15:45 UTC, merged