chore(engine): update last processed position after reprocessing
camunda/camunda pull request #5348
Opened 2020-09-15 07:14 UTC by deepthidevaki

## Description

When the broker is out of disk space, stream processor is paused immediately after reprocessing. Then the last processed position was not updated. As a result, no snapshots are taken because `AsyncSnapshotDirector` assumes there is nothing processed, even though new snapshots can be taken because exporter position has changed. So the logs are not compacted and the brokers cannot recover from out of disk space.
In this PR, we initialize streamprocessor's `lastProcessedPosition` to the last reprocessed position. Then we can take new snapshots even if nothing new has been processed.

## Related issues

closes #5329

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-09-16 07:16 UTC, saig0 requested changes
Looks good :cookie: 
Just a few minor comments.

2020-09-16 07:16 UTC, saig0 commented on engine/src/test/java/io/zeebe/engine/processing/streamprocessor/StreamProcessorReprocessingTest.java
> +    streamProcessorRule.closeStreamProcessor();
This part of the test is a bit hard to read. Please try to improve it. For example, by adding a new line :)

2020-09-17 09:48 UTC, deepthidevaki commented on engine/src/main/java/io/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java
> +    }
I created a new method for starting the processing. I think we should not update the metrics. If we update it, it gives the wrong information that something is processed even though we have only reprocessed it. So I removed the metrics update.

2020-09-17 09:51 UTC, deepthidevaki commented on engine/src/test/java/io/zeebe/engine/processing/streamprocessor/StreamProcessorReprocessingTest.java
> +  public void shouldUpdateLastProcessedPositionAfterReprocessing() throws Exception {
As we discussed already we can't write a deterministic test because we cannot ensure that streamprocessor is paused after reprocessing.

2020-09-17 11:22 UTC, saig0 approved these changes
Thanks :cake:

2020-09-17 12:32 UTC, deepthidevaki commented
bors r+

2020-09-17 12:56 UTC, merged