2973 remove usage broker contact point
camunda/camunda pull request #5373
Opened 2020-09-18 08:13 UTC by aivinog1

## Description

Remove internal usages of `brokerContactPoint` from #5345 

## Related issues

closes #2973

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [X] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-09-23 12:04 UTC, npepinpe requested changes
Thanks again for your contribution!

Two points:

1. In `ZeebeClientTest`, the following tests are redundant now: `shouldBrokerContactPointReturnTheSameAsGatewayAddress` and `shouldGatewayAddressReturnsTheSameAsBrokerContactPoint`. They test setting the gatewayAddress and reading it :slightly_smiling_face: I would like to keep a test to ensure that setting the `brokerContactPoint` still sets the `gatewayAddress`, but the other one can be removed. We can remove that test in 0.26.
1. Just for future reference (no need to do anything now), if possible we'll usually do one commit per module. So instead of `chore(broker, gateway)` we'd do two commits, `chore(broker)` and `chore(gateway)`. That said, sometimes you need changes in two modules otherwise the build breaks, and we also like if every commits builds. So in this PR, for example, it should've been possible to do one commit per module. But it's also fine, just for next time :slightly_smiling_face:

2020-09-28 05:25 UTC, aivinog1 commented
@npepinpe Hi, I've fixed all your review comments :)

2020-09-30 10:14 UTC, npepinpe approved these changes
Thanks! Looks good :+1:

2020-09-30 10:15 UTC, npepinpe commented
bors r+

2020-09-30 12:33 UTC, aivinog1 commented
@npepinpe Can you post the build error please? :)

2020-09-30 14:33 UTC, npepinpe commented
Could you revert the changes in `benchmarks/project`? This is a project outside of the Zeebe root project, so it pulls in Zeebe via maven and uses the latest version - so it has no access to things not yet released :slightly_smiling_face:

2020-10-01 09:22 UTC, aivinog1 commented
@npepinpe Hi, I've removed usage of new API in the benchmarks :) Do we need a separate issue to remove the usage of deprecated methods in the benchmarks after the new release will come?

2020-10-01 10:15 UTC, aivinog1 commented
bors r+

2020-10-01 10:25 UTC, npepinpe commented
No, that's alright, it will be part of updating the Zeebe version task! Thanks!

2020-10-01 10:25 UTC, npepinpe commented
bors r+

2020-10-01 11:00 UTC, aivinog1 commented
@npepinpe Can you say why the last build is failed, please? :)

2020-10-01 11:07 UTC, npepinpe commented
Some tests were marked as flaky, but they had nothing to do with your changes so it's simply unfortunate. Nothing to worry about :+1:

2020-10-01 11:07 UTC, npepinpe commented
bors retry

2020-10-01 11:32 UTC, merged