Admin api for brokers
camunda/camunda pull request #5408
Opened 2020-09-23 15:12 UTC by deepthidevaki

## Description

Expose an interface to trigger following functions externally
 * trigger snapshots on all partitions
 * pause processing on all partitions
 * resume processing on all partitions
 * prepare for upgrade - which internally pause processing and trigger snapshots
 * query status of partitions

The endpoint can be enable/disabled by configuration.

## Related issues

closes #5405

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-09-28 06:46 UTC, saig0 requested changes
Really nice! :cake: 

Just a few minor comments.

Please mention the new endpoints in the release announcement.

2020-09-29 08:39 UTC, deepthidevaki commented on broker/src/main/java/io/zeebe/broker/system/management/PartitionStatus.java
> +  private final Phase streamProcessorPhase;
You are right. I can include them back.

2020-09-29 08:40 UTC, deepthidevaki commented on broker/src/main/java/io/zeebe/broker/system/management/BrokerAdminServiceImpl.java
> +                    () -> getFollowerPartitionStatus(partition, partitionStatus)));
Would it be ok if we return a `PartitionStatus` with all null values as an error response?

2020-09-29 08:43 UTC, saig0 commented on broker/src/main/java/io/zeebe/broker/system/management/BrokerAdminServiceImpl.java
> +                    () -> getFollowerPartitionStatus(partition, partitionStatus)));
Yes. It would be an option. Or, just throwing an exception that would lead to status code `500`.

2020-09-29 15:16 UTC, deepthidevaki commented
@saig0 I have applied your comments and moved the endpoints to actuators. Please have a look.

2020-09-30 05:00 UTC, saig0 approved these changes
Thanks @deepthidevaki :cookie: 

I've two optional suggestions regarding the endpoint.

2020-09-30 08:00 UTC, deepthidevaki commented
I renamed the argument and the endpoint.

2020-09-30 08:00 UTC, deepthidevaki commented
bors r+

2020-09-30 08:25 UTC, merged