Lower log level to WARN
camunda/camunda pull request #5448
Opened 2020-09-30 18:36 UTC by haardikdharma10

## Description

Lowered the log level of AtomixServerTransport#sendResponse on leader change, from error to warn as discussed with @npepinpe on issue #5396 

## Related issues

#5396

2020-09-30 18:36 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: c0795f5d3dd175946793a3c9d213ba8d4c000387
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-09-30 18:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zeebe-io/zeebe?pullRequest=5448) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zeebe-io/zeebe?pullRequest=5448) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zeebe-io/zeebe?pullRequest=5448) it.</sub>

2020-10-01 01:29 UTC, jwulf reviewed
LGTM

2020-10-01 01:29 UTC, jwulf commented
Thanks for the PR @haardikdharma10!

2020-10-01 01:32 UTC, jwulf requested changes
You'll need to amend the commit message, following these guidelines: https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines

2020-10-01 07:45 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: c0795f5d3dd175946793a3c9d213ba8d4c000387
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-10-01 07:46 UTC, haardikdharma10 commented
Hi @npepinpe, done! sorry about the messed up commits:/

2020-10-05 06:29 UTC, Zelldon commented
Hey @haardikdharma10 thanks for your contribution :tada: 

The scope for the commit message is normally the maven module name (or first folder name), so here it would be transport. 

I suggest you change the commit message to:

```
chore(transport): lowered log level to warn
```

After that you need to squash your commits. You can take a look at this guide/doc https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

If you have done this we can merge your PR.

Thanks
Chris

2020-10-05 11:41 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: c0795f5d3dd175946793a3c9d213ba8d4c000387
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-10-05 11:43 UTC, haardikdharma10 commented
Hey @Zelldon, Thanks for the suggestion. I have done the needful and also squashed the commits. Let me know if this looks good.

Thanks
Haardik.

2020-10-06 07:20 UTC, Zelldon commented
Hey @haardikdharma10 thanks the last commit message looks good, but still there are several commits which need to be squashed. 


Greets
Chris

2020-10-06 08:53 UTC, haardikdharma10 commented
Hi @Zelldon, I guess I figured it out. Hope it's fine now. Thanks for all your help 😉

2020-10-06 08:55 UTC, Zelldon approved these changes
Awesome thanks @haardikdharma10 

bors r+

2020-10-06 08:55 UTC, Zelldon commented
bors r+

2020-10-06 08:56 UTC, Zelldon commented
@jwulf please accept the PR :)

2020-10-06 08:56 UTC, haardikdharma10 commented
> @jwulf please accept the PR :)

Maybe the checks are still in progress?

2020-10-07 08:22 UTC, jwulf approved these changes

2020-10-07 08:22 UTC, jwulf commented
bors r+

2020-10-07 08:31 UTC, Zelldon commented
bors r+

2020-10-07 10:48 UTC, merged