fix(broker): Connection Timeouts Logged at Debug Level for Gateway Lo…
camunda/camunda pull request #5467
Opened 2020-10-02 22:53 UTC by sccalabr

…gger

## Description

The log level was lowered from error to debug for connection time out exceptions.

## Related issues

closes #5397

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-10-05 21:41 UTC, jwulf commented
Thanks for the contribution @sccalabr. Looks like you nailed the commit message - well done. I've requested a review from @npepinpe.

2020-10-07 10:46 UTC, Zelldon requested changes
Hey @sccalabr thanks for your contribution :tada: 

I discussed that with @npepinpe and we would like to have the logging level as warn instead of debug could you please change that then we can merge it.

Greets
Chris

2020-10-07 10:46 UTC, Zelldon commented on gateway/src/main/java/io/zeebe/gateway/EndpointManager.java
> +      Loggers.GATEWAY_LOGGER.debug(
```suggestion
      Loggers.GATEWAY_LOGGER.warn(
```

2020-10-09 04:32 UTC, sccalabr commented on gateway/src/main/java/io/zeebe/gateway/EndpointManager.java
> +      Loggers.GATEWAY_LOGGER.debug(
Done :)

2020-10-13 06:48 UTC, Zelldon requested changes
Hey @sccalabr 

thanks for the change. Sorry I missed it on the first review you commit message need to be changed as well.

**TL;DR**

Current:
```
fix(broker): Connection Timeouts Logged at Debug Level for Gateway Lo… …
…gger
```

Ideally it would be:
```
chore(gateway): log timeouts as warn
```

**Description:**

Your PR is not really a bug fix, which means we should use `fix` as type here. We use `chore` for these kind of changes.
The scope should normally be the maven module, which was under change the most. In your PR it is `gateway` not `broker`.
The message of your commit is to long, which means it will be shorten by github. Ideally it contains only 72 characters take a look at this guide for more information https://www.robertcooper.me/git-commit-messages#subject-line-less-than-or-equal-to-72-characters-in-length

In general you can also read our Contribution guidelines for more information
https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines

Greets
Chris

2020-10-21 08:21 UTC, Zelldon commented
Hey @sccalabr 

thanks for applying my review hints!
Unfortunately there are some merge conflicts. Could you please rebase to develop so we can merge your PR. If you need help with that let me know.

Greets
Chris

2020-10-24 06:00 UTC, sccalabr commented
Let me know if I did it right.

2020-10-28 09:04 UTC, Zelldon commented
@sccalabr the issue is that we moved most of the stuff into a new class called `GrpcErrorMapper` I think you need to make your changes there.

2020-10-31 17:02 UTC, sccalabr commented
Would I just add the logging statement or something else

2020-10-31 18:00 UTC, closed without merging

2020-10-31 18:02 UTC, sccalabr commented
Looks like I somehow closed it? Not sure how to reopen