Improve OauthCredentialProvide in Go Client
camunda/camunda pull request #5630
Opened 2020-10-19 13:53 UTC by zeromberto

## Description
The OAuthCredentialProvider checks the validity of the tokens before injecting them in the http headers. If the token is invalid it tries to refresh the token. 

Furthermore, the cache is not repopulated every time a cached token is requested but only once on provider creation. This reduces disk read operations as the information is in memory anyways.

## Related issues

closes #5625 

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-11-04 10:36 UTC, npepinpe reviewed
Hey @zeromberto, thanks for the contribution! iirc, the reason the cache was repopulated every time was in case multiple clients are accessing the same cache. This adds increase disk operations, but reduces the number of authentication calls (which is rate limited in Camunda Cloud). I think the assumption was that normally we only would do this if the token is expired, so this shouldn't be a frequent operation anyway. 

Let me know what you think :+1:

2020-11-04 10:40 UTC, zeromberto commented
Hi @npepinpe, okay I understand. In this case I revert the change which moves the cache refreshment to the constructor.

2020-11-04 10:55 UTC, npepinpe requested changes
One small thing, could we add a test to `oauthCredentialsProvider_test.go`? We already have a test which checks that if there is a cached token we use it, and if there isn't we fetch a new one. Could we add one which checks if we do have one, but it is expired, we are fetching a new one as well? You can look at the following for inspiration:

https://github.com/zeebe-io/zeebe/blob/4494f1da3e65232935d19a1a7eadad6ac61c0696/clients/go/pkg/zbc/oauthCredentialsProvider_test.go#L403-L464

Do ask questions if anything is unclear :+1:

2020-11-05 19:27 UTC, npepinpe commented
Sorry for the slow update, I've pushed your branch so our CI can build it - if all is good we can approve it :+1:

2020-11-05 19:42 UTC, npepinpe approved these changes
Looks good :+1:

2020-11-05 20:00 UTC, npepinpe commented
The build is red, but the failing tests are known, unrelated flakes, so don't worry about it. Could you please rebase and squash your commits? Then we can merge.

2020-11-06 11:44 UTC, zeromberto commented
Hey @npepinpe, I rebased and squashed my work.

2020-11-06 16:51 UTC, npepinpe commented
bors r+

2020-11-06 16:51 UTC, npepinpe commented
Thanks a lot @zeromberto :tada:

2020-11-06 18:06 UTC, npepinpe commented
bors retry

2020-11-06 18:07 UTC, npepinpe commented
Side note for @MiguelPires: please backport this to 0.25 and 0.24 when this is merged :+1:

2020-11-06 18:44 UTC, merged