Support list es nodes
camunda/camunda pull request #5636
Opened 2020-10-19 18:56 UTC by jooble

## Description

Allows use list urls in exporters` configuration

## Related issues

closes #5635 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-10-19 18:56 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 9063229fcf934f4f50995915f31e38bb1ae93778
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

2020-10-19 18:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zeebe-io/zeebe?pullRequest=5636) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zeebe-io/zeebe?pullRequest=5636) before we can accept your contribution.<br/><hr/>**dzhezlov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zeebe-io/zeebe?pullRequest=5636) it.</sub>

2020-12-29 10:53 UTC, liljaylj commented
LGTM. Is it going to be merged?

2021-01-09 15:55 UTC, npepinpe requested changes
Thanks for your contribution, and sorry for the slow review - this fell through the cracks, then the holidays were on us. I understand if you've moved on, let us know if we should take it over and finish it for you :+1: 

Regarding the tests added in `ElasticsearchClientTest` - this class is misnamed, as these are integration tests, whereas the tests added are simple unit tests. Please rename it `ElasticsearchClientIT`, and create a new `ElasticsearchClientTest` which then includes only your two tests (and in the future, tests which just check the client is well constructed, or at least do not rely on a real Elasticsearch node).

2021-01-09 15:55 UTC, npepinpe commented on exporters/elasticsearch-exporter/src/test/java/io/zeebe/exporter/ElasticsearchClientTest.java
> +  public void shouldUseLegacyUrlIfExist() {
As you can see from the other tests in the file, we tend to use a format of

```java
@Test
public void shouldTestSomething() {
  // given
  // add all the setup here, i.e. variable declaration, object instantiation, etc.
  
  // when
  // add the behaviour you want to test: for example, here, creating the client is the behaviour under test.
  
  // then
  // add your assertions here - in this case, something like the following:
  assertThat(client.client.getNodes().stream().map(Node::getHost)).containsExactly(elastic.getRestHttpHosts()[0]);
}
```

I would also argue a test with no assertions (just checking that an exception is thrown) is typically a code smell - what if we stop resolving the host at initialization and start doing so lazily? Then the test breaks. We should aim for explicit asserts as much as possible.

2021-01-09 15:55 UTC, npepinpe commented on exporters/elasticsearch-exporter/src/test/java/io/zeebe/exporter/ElasticsearchClientTest.java
> +    configuration.url = "http://localhost:8080";
We can use `elastic.getHttpHosts()[0].toString()`

2021-01-09 15:55 UTC, npepinpe commented on exporters/elasticsearch-exporter/src/test/java/io/zeebe/exporter/ElasticsearchClientTest.java
> +    configuration.urls = List.of("bad url");
There's no need to expect an exception here - we can simply create a list of fake URLs, e.g.

```java
configuration.urls = List.of("http://localhost:8080", "http://localhost:8081");
```

And assert the following:

```java
assertThat(client.client.getNodes().stream().map(Node::getHost).map(HttpHost::toString))
        .containsExactlyInAnyOrderElementsOf(configuration.urls);
```

2021-02-03 21:07 UTC, liljaylj commented
@jooble , found a problem - it is not possible to set `urls` using environment variable `ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URLS`.

my proposal is to set urls using comma-separated host list, then split, trim and map and convert to `HttpHost[]`

2021-03-02 12:46 UTC, npepinpe commented
Superseded by https://github.com/zeebe-io/zeebe/pull/6467

2021-03-02 12:46 UTC, closed without merging