[Backport 0.24] Introduce new update test build agent
camunda/camunda pull request #5917
Opened 2020-11-25 13:26 UTC by npepinpe

## Description

This PR backports #5908 to 0.24. I cherry picked those from #5916 so the conflicts were minimal.

## Related issues

related to #5873 
backports #5908 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-11-25 15:16 UTC, npepinpe commented
Same, build failure is a flaky test.

2020-11-25 15:20 UTC, korthout approved these changes
LGTM 🍪

2020-11-25 15:21 UTC, npepinpe commented
bors r+

2020-11-25 16:51 UTC, npepinpe commented
bors retry

2020-11-25 17:23 UTC, npepinpe commented
Hm, it runs into flaky tests and I can't tell if 0.24 was flaky before or if it's this PR. I have a feeling reducing the resources may not have been a good idea? :thinking:

2020-11-25 17:23 UTC, npepinpe commented
bors retry

2020-11-26 16:16 UTC, korthout requested changes
Please apply the same changes as in https://github.com/zeebe-io/zeebe/pull/5916

2020-11-27 10:41 UTC, npepinpe commented
Superseded by https://github.com/zeebe-io/zeebe/pull/5927

2020-11-27 10:41 UTC, closed without merging