[Backport stable/0.24] Backport CI improvements
camunda/camunda pull request #5961
Opened 2020-12-03 15:12 UTC by npepinpe

## Description

This PR backports several CI improvements to the 0.24 branch. As we will be maintaining it for the next 3 months, having a more stable CI on this branch is equally important. The PR backports the following changes:

- templated podSpecs, allowing us to use the non-preemptible nodes for bors
- improved control over the Maven/Surefire/Failsafe parallelism
- fixes an error when using a separate IT agent where `./target` may not be there when appending to `FlakyTests.txt`
- synchronizes the CI files with develop so further backports can easily be made

## Related issues

related to #5937 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2020-12-03 15:12 UTC, npepinpe commented
I realize that we're going to phase 0.24, and most likely we won't have much more to do there. But there's always a chance we have a critical bug, or need to do something, so I'd like to keep the CI up to date and as stable as possible, plus avoid later conflicts if we need to backport more CI stuff.

2020-12-03 16:41 UTC, korthout commented
@npepinpe It seems the pipeline detected a failure here.

2020-12-03 16:48 UTC, korthout reviewed
Looking at the changes I don't see anything jump out at me. So I'm curious about why the build actually failed. Was it unrelated to the changes?

2020-12-03 17:29 UTC, npepinpe commented
I think I know the issue - I fixed it in different PR which I haven't merged yet, https://github.com/zeebe-io/zeebe/pull/5912

See: https://github.com/zeebe-io/zeebe/blob/fd39466b36b10f2aade8aa57abf9644ea7e09fbc/update-tests/src/test/java/io/zeebe/test/SnapshotTest.java#L55-L57

2020-12-03 17:30 UTC, npepinpe commented
This is actually an issue currently on develop as well, but that PR is currently 99% done, so hopefully merged tomorrow? :+1:

2020-12-03 17:54 UTC, korthout commented
@npepinpe Do you think we can merge this before then? Perhaps retry the build?

2020-12-04 07:56 UTC, npepinpe commented
By the way, that flaky test is already flaky on stable/0.24, so I'm pretty sure it's independent of this PR.

2020-12-04 09:34 UTC, korthout requested changes
@npepinpe The build still fails with an error (not flaky) and that failure does not happen on stable/0.24. Can you please have another look at it?

2020-12-07 13:45 UTC, korthout approved these changes
Much better, thanks! LGTM 🍭

2020-12-07 13:46 UTC, npepinpe commented
bors r+

2020-12-07 14:14 UTC, merged