5763 java jobclient
camunda/camunda pull request #6048
Opened 2021-01-02 21:42 UTC by cobre420

## Description

client should accept the job to send complete command

## Related issues

#5763

closes #5763

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-01-02 21:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zeebe-io/zeebe?pullRequest=6048) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zeebe-io/zeebe?pullRequest=6048) before we can accept your contribution.<br/><hr/>**jiri.dostal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zeebe-io/zeebe?pullRequest=6048) it.</sub>

2021-01-06 08:16 UTC, Zelldon requested changes
Hey @cobre420 

thank you very much for your contribution! We appreciate your efforts :) 
Please sign our CLA otherwise I can't merge your PR. I added some comments and request to change before we can merge this. In general it looks good, but I think it makes more sense to just delegate to the other method which accepts an job key see below.

Thanks again and greets
Chris

2021-01-06 08:16 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/api/worker/JobClient.java
> +   * long job = ..;
```suggestion
   * ActivatedJob job = ..;
```

2021-01-06 08:16 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/api/worker/JobClient.java
> +   * long job = ..;
```suggestion
   * ActivatedJob job = ..;
```

2021-01-06 08:16 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/api/worker/JobClient.java
> +   * long job = ...;
```suggestion
   * ActivatedJob job = ...;
```

2021-01-06 08:16 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/api/worker/JobClient.java
> +   * activity and continue the flow.
```suggestion
   * <p>The job is linked to a workflow instance and this command will complete the related
   * activity and continue the flow.
```

2021-01-06 08:16 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/impl/ZeebeClientImpl.java
> +    return jobClient.newCompleteCommand(job);
I had expect that we just delegate here to jobkey. Like job.getKey(). Then the other methods are not necessary.

2021-01-06 08:16 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/impl/ZeebeClientImpl.java
> +    return jobClient.newFailCommand(job);
Same here

2021-01-06 08:16 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/impl/ZeebeClientImpl.java
> +    return jobClient.newThrowErrorCommand(job);
And here

2021-01-06 08:16 UTC, Zelldon commented on clients/java/src/main/java/io/zeebe/client/impl/worker/JobClientImpl.java
> +    return new CompleteJobCommandImpl(
As I wrote earlier I think this is not necessary. Either we delegate in ZeebeClient directly to the method which accepts the jobkey or we do it here and just call newCompletecommand(jobKey)

2021-01-19 15:43 UTC, npepinpe commented
Hi @cobre420, do you think you will have time to work on this? Please let us know within the next two weeks, otherwise we will take the PR over.

2021-02-01 12:46 UTC, npepinpe commented
@Zelldon, please take this over - either apply the changes, or if we think this is too much work, then approach me and let's see what we want to do.

2021-02-01 12:49 UTC, Zelldon commented
@npepinpe the cla is not signed

2021-02-11 21:59 UTC, closed without merging