fix(clients/go): log failure to reopen stream
camunda/camunda pull request #6211
Opened 2021-01-27 11:29 UTC by MiguelPires

## Description

This PR fixes the error handling when remaking a stream (after its auth token expired). If there's no error, we are erroneously logging `Failed to reopen job polling stream: <nil>` and stopping that iteration early. If there is an error, we try to get jobs. The fix is just inverting the condition.

## Related issues

closes ##6210

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-01-27 17:13 UTC, npepinpe requested changes
:sweat_smile:  good catch!

Can we test this?

2021-01-28 09:43 UTC, MiguelPires commented
I tried for a bit yesterday but it's not very easy, and eventually I ran out of time. I managed to observe the panic at some point but it was very flaky. This is because the job poller runs on its own thread and there's a lot of preconditions required for the error:
- The job stream must be opened successfully first
- The token must expire while streaming jobs
- The token must be successfully refreshed and the stream is retried
- The job stream fails to be remade for some reason

Since it was just a one character change and at some point I could see that it was fixed, I just opened it. Do you want me to try to  write a test for longer? Also, this is probably a sign that I should refactor the job poller to be more testable

2021-01-28 13:24 UTC, npepinpe commented
> Also, this difficulty is probably a sign that I should refactor the job poller to be more testable

Let's do that when we add back off then.

2021-01-28 13:24 UTC, npepinpe approved these changes
bors r+

2021-01-28 15:05 UTC, MiguelPires commented
bors retry

2021-01-28 15:30 UTC, merged