Separate mutable and immutable states
camunda/camunda pull request #6233
Opened 2021-01-29 10:24 UTC by saig0

## Description

* extract mutable and immutable interfaces of the states
* flatten the hierarchy of states
* move methods to the responsible states

## Related issues

closes #6170

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-02-01 12:25 UTC, korthout requested changes
These changes make me very happy. The naming convention feels really good. 

In the immutable variants I did have to think for some time about 2 methods that change internal state of the class, but not the actual state the class provides access to. Considering they don't actually change db state, its fine to keep them in the immutable interface.

I did find a method that should not be in an immutable interface (see comment) and I have a small naming suggestion.

Great work on this.

2021-02-01 12:25 UTC, korthout commented on engine/src/main/java/io/zeebe/engine/state/mutable/MutableWorkflowState.java
> +  int getNextWorkflowVersion(String bpmnProcessId);
Let's rename this to `nextWorkflowVersion` to make it more clear that this is not a getter without a side-effect

2021-02-01 14:02 UTC, saig0 commented on engine/src/main/java/io/zeebe/engine/state/immutable/EventScopeInstanceState.java
> +  EventTrigger pollEventTrigger(long eventScopeKey);
Good catch :+1:

2021-02-01 14:17 UTC, saig0 commented
@korthout thanks for the fast review. I applied your hints. Please have a look :)

2021-02-01 15:31 UTC, korthout approved these changes
Thanks for the fast changes. LGTM 🥇

2021-02-02 04:36 UTC, saig0 commented
bors

2021-02-02 09:00 UTC, saig0 commented
bors r+

2021-02-02 09:22 UTC, merged