Seek to asqn with in committed index
camunda/camunda pull request #6691
Opened 2021-03-30 08:00 UTC by deepthidevaki

## Description

* JournalReader seekToAsqn accepts an upperbound index to seek to so that readers with mode COMMITS can bound the seek to the committed index. 
* Update RaftLogReader to use the new api
* Use seekToAsqn to find the last applicationEntry for entry validation in LeaderRole

## Related issues

closes #6343

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-03-31 08:30 UTC, MiguelPires requested changes
Looks good, just a few minor details

2021-03-31 08:30 UTC, MiguelPires commented on journal/src/test/java/io/zeebe/journal/file/JournalReaderTest.java
> +    final var fifthIndex = journal.append(data).index();
```suggestion
    journal.append(data).index();
```
fifthIndex is never used since you use `Long.MAX_VALUE` for the last seek

2021-03-31 08:30 UTC, MiguelPires commented on journal/src/main/java/io/zeebe/journal/JournalReader.java
> +   * @param indexUpperBound
I think we can either add a description for the parameters or remove them if you think it's clear enough

2021-03-31 08:30 UTC, MiguelPires commented on journal/src/main/java/io/zeebe/journal/file/JournalIndex.java
> +   * @param indexUpperBound
Same, we can add a description or remove them

2021-03-31 08:59 UTC, deepthidevaki commented
Thanks @MiguelPires I have applied your comments.

2021-03-31 10:03 UTC, MiguelPires approved these changes
Thanks! :+1:

2021-03-31 10:11 UTC, deepthidevaki commented
bors r+

2021-04-01 07:22 UTC, deepthidevaki commented
bors r+

2021-04-01 07:46 UTC, merged