Support Elasticsearch 7
camunda/camunda pull request #6736
Opened 2021-04-06 18:38 UTC by menski

## Description

This change updates the used Elasticsearch version to 7.

## Related issues

closes #3445 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-04-06 18:39 UTC, menski commented
I didn't do anything to verify if we are backwards compatible, i.e. if we can still run with the new client against an old version. We should discuss if we want such test, which I think is easy to achieve, but didn't wanted to invest time before discussed.

2021-04-06 19:34 UTC, npepinpe commented
I think this is something we can do post release, as adding support for 6.x shouldn't be breaking backwards compat again. I'm not sure what the value is for our users to be honest, I imagine someone on the product team has better insight there.

2021-04-06 19:38 UTC, npepinpe requested changes
Please update the `benchmarks/setup/default` Elastic image as well. Have you tried a benchmark? Will the default curator version work with Elastic 7?

2021-04-07 13:49 UTC, menski commented
I will take care of it, it's not that urgent

2021-04-12 19:16 UTC, menski commented
I updated the benchmark ES version, and started a benchmark [`menski-elastic-7`](http://34.77.165.228/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=menski-elastic-7&var-pod=All&var-partition=All)

2021-04-13 12:06 UTC, npepinpe approved these changes
bors r+

:tada:

2021-04-13 13:13 UTC, merged