feat(broker,gateway): Fix the start process to enable readiness probes.
camunda/camunda pull request #6945
Opened 2021-05-03 14:58 UTC by aivinog1

## Description

So, the `READINESS_STATE` was not published because:
1. It should be published there: `org.springframework.boot.context.event.EventPublishingRunListener#running`
2. But, a broker is `org.springframework.boot.CommandLineRunner` with an infinitive latch
3. In the `org.springframework.boot.SpringApplication#run(java.lang.String...)` we have this order:
3.1. App started
3.2. Calling `org.springframework.boot.SpringApplicationRunListeners#started`
3.3. In one listener this means that the app is in `LivenessState.CORRECT` state (org.springframework.boot.context.event.EventPublishingRunListener#started)
3.4. So, liveness became ok.
3.5. App running (i.e. `org.springframework.boot.CommandLineRunner` is executed)
3.6. Calling `org.springframework.boot.SpringApplicationRunListeners#running`
3.7. In one listener this means that the app is in `org.springframework.boot.availability.ReadinessState#ACCEPTING_TRAFFIC` state
3.8. So, readiness became ok.

I decided to remove sync calls and add some shutdown hooks instead of them.

Because of the current implementation, we are stuck in the 3.5 and don't go down the list.

## Related issues

closes #6413

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-05-07 09:16 UTC, deepthidevaki commented
Thanks @aivinog1 for your contribution. I will review this PR next week.

2021-05-12 07:23 UTC, deepthidevaki requested changes
Thanks @aivinog1. Looks good to me. What is missing is a test that verifies the fix. We have a test for health endpoints for the broker `BrokerMonitoringEndpointTest`. You can add a similar one for the gateway. Use testcontainers `io.zeebe.containers.cluster.ZeebeCluster` to create a cluster with one gateway and one broker. The test should verify that the health probes on the gateway returns success. Let me know if you have any questions.

Since this is a bug fix for the gateway, the commit message should be `fix(gateway):...`.

2021-05-14 07:52 UTC, aivinog1 commented
Hi @deepthidevaki! I have a question about `io.zeebe.containers.cluster.ZeebeCluster`. Is it true that it uses not a test image tag (`current-test`), but a current image tag (`1.0.0` in the last version of the library)? So, if I understand correctly this test will always fall because of my changes not in the `1.0.0` version. So I see these options:
1. Expand and rename the `io.camunda.zeebe.broker.it.gateway.GatewayLivenessProbeIntegrationTest` to `io.camunda.zeebe.broker.it.gateway.GatewayHealthProbeIntegrationTest` (add to this test some readiness stuff)
2. Add issues to the Zeebe Testcontainers project (ability to set image tag, monitoring envs, etc) and fix them.

We can use both of the options (they are not exclusive), WDYT?

2021-05-14 14:18 UTC, deepthidevaki commented
> Hi @deepthidevaki! I have a question about `io.zeebe.containers.cluster.ZeebeCluster`. Is it true that it uses not a test image tag (`current-test`), but a current image tag (`1.0.0` in the last version of the library)? So, if I understand correctly this test will always fall because of my changes not in the `1.0.0` version. So I see these options:

In another test tests that use `ZeebeCluster` the image is set explicitly https://github.com/camunda-cloud/zeebe/blob/6580431a3ba32915a28f2562b1e0a8c828a8ba77/qa/integration-tests/src/test/java/io/camunda/zeebe/broker/it/network/AdvertisedAddressTest.java#L129
But, I agree it would be better to specify it in the builder.

>     1. Expand and rename the `io.camunda.zeebe.broker.it.gateway.GatewayLivenessProbeIntegrationTest` to `io.camunda.zeebe.broker.it.gateway.GatewayHealthProbeIntegrationTest` (add to this test some readiness stuff)

Yes. That is actually a perfect place to put this test. Go for it. :+1:

2021-08-04 11:58 UTC, npepinpe commented
Is there any update on this?

2021-08-04 12:02 UTC, aivinog1 commented
@npepinpe Hey, I want to continue work on this after https://github.com/camunda-community-hub/zeebe-test-container/issues/150. Because it is not convenient to work with the Zeebe testcontainer with the current API. I think I'll look closely at this after 19th August :)

2022-01-03 14:48 UTC, aivinog1 commented
Closed as duplicate #8506

2022-01-03 14:48 UTC, closed without merging