Replace exceptions related to event subscriptions with either
camunda/camunda pull request #7554
Opened 2021-07-27 14:43 UTC by korthout

## Description

This replaces the subscribe to message and timer events logic with functional style using the Either type.

To achieve that, this PR uses the previously added `Either.collect()` to collect multiple calculations that can fail, and adds a new `peek(Consumer<R> action)` method to Either to perform the different subscription actions while also making it possible to return either a failure or the all events that we subscribed to.

It's likely best to review this on a commit by commit basis. However, please keep in mind that not all changes made in the first commits are kept in the final result.

## Related issues

relates #4323

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-07-27 14:45 UTC, korthout commented
@saig0 Please have a look, and let me know if you see ways to improve this further. In addition, if you want to me extract the Either.peek to a separate pull request, please let me know.

2021-07-29 13:06 UTC, saig0 requested changes
I like the new style :+1: Thanks @korthout :cake: 

I just have some minor comments. Please have a look.

2021-07-30 09:32 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/processing/common/CatchEventBehavior.java
> +        .peek(results -> subscribeToTimerEvents(context, sideEffects, commandWriter, results))
That's an interesting point. I guess the confusion during yesterday's show and tell was partially due to the peek and could've been avoided this way. 

I do feel it takes the power of chaining away, which feels very useful in the java world where side-effects are everywhere. Another idea is to change the Either.ifRight signature to what peek actually is. This allows something like the following.

```suggestion
        .ifRight(results -> subscribeToMessageEvents(context, sideEffects, results))
        .ifRight(results -> subscribeToTimerEvents(context, sideEffects, commandWriter, results))
```

 To be fair, probably it's best not allow this chaining altogether and make side effects more visible by having to either place it in the end of a chain, or separate it like in your example. I'll remove the `peek` for now

2021-07-30 12:14 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/processing/common/ExpressionProcessor.java
> +                                scopeKey)))
@saig0 Note that this is the only place where we deviate from the standard typecheck failure message. If we align the messages this entire mapLeft is unnecessary. WDYT?

2021-07-30 12:17 UTC, korthout commented
@saig0 I've played around a bit more after your comments. I've added a collectorFoldingLeft Collector in an effort to reduce the required logic, removed the peek method to highlight the side effects and reduced the return value mapping logic to the bare minimum.

Please have another look.

2021-07-30 12:48 UTC, saig0 commented on engine/src/main/java/io/camunda/zeebe/engine/processing/common/ExpressionProcessor.java
> +                                scopeKey)))
Yes, I see your point. I would like to be consistent too.

The advantage of this message is that it says what is wrong. For example, if the incident is created for a task with multiple boundary events. 

We could change the standard type check and add a context to it (e.g. `... while evaluating the correlation key`).

2021-07-30 12:52 UTC, saig0 commented on engine/src/main/java/io/camunda/zeebe/engine/processing/common/CatchEventBehavior.java
> +        .peek(results -> subscribeToTimerEvents(context, sideEffects, commandWriter, results))
> probably it's best not allow this chaining altogether and make side effects more visible by having to either place it in the end of a chain

I agree. 

Allow to chain `ifRight()` would also differ from the Java API of `Optional#ifPresent()` and the semantics of terminal stream operations.

2021-07-30 13:02 UTC, saig0 approved these changes
Looks good :+1:

2021-07-30 13:37 UTC, korthout commented on engine/src/main/java/io/camunda/zeebe/engine/processing/common/ExpressionProcessor.java
> +                                scopeKey)))
Interesting. I'll just open an issue for that idea. I'll extract the special code in a separate method for now

2021-07-30 13:43 UTC, korthout commented
bors merge

2021-07-30 13:43 UTC, korthout commented
bors cancel

2021-07-30 13:49 UTC, korthout commented
bors merge

2021-07-30 14:19 UTC, korthout commented
bors retry

2021-07-30 14:41 UTC, merged