Add configurable fixed partitioning scheme
camunda/camunda pull request #7685
Opened 2021-08-23 13:10 UTC by npepinpe

## Description

This PR introduces a new configurable partitioning scheme which lets users manually distribute partitions across a static set of nodes. Additionally, if priority election is used, it lets users assign priorities to these nodes as well.

A valid configuration consists of:

- All partitions with IDs between 1 and `partitionsCount` are configured explicitly
- All partitions configure exactly `replicationFactor` nodes
- All nodes configured for a partition have a valid node ID, i.e. between 0 and `clusterSize - 1`.
- If priority election is enabled, then all priorities configured for a partition are different

If any of these conditions are not met, then the broker will fail to start. Note that if priority election is enabled, the target priority for a partition will be whatever was the highest configured priority.

## Related issues

closes #6266 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-08-23 13:34 UTC, npepinpe commented
@deepthidevaki - I initially had a very lightweight model for the distributor, where it would just take in a map of maps, and figure out the distribution. You can see this [commit](https://github.com/camunda-cloud/zeebe/commit/3d360cf3d6f61041a8d8c221c102078b214caee3) where I added a more explicit intermediate model. I like this more, but it's definitely more verbose. The main reason why I like this approach more:

- It's more explicit in terms of what are the map keys and values, what they mean, etc., then using some basic types like `Integer` or `String`.
- The builder hides some complexity of what you're putting in and where
- It gives us a bit more flexibility in terms of changing the user facing configuration later I think as it's more decoupled

To be honest though, the builder already decouples things enough that we could do away with the `FixedPartitionDistribution` for example and just pass back a `Map<PartitionId, Map<MemberId, Integer>>` - however the nested map is unclear what the integer is, and it's not very extensible (though, you know, YAGNI and all...). We could compromise and just have the builder and nothing else.

Let me know what you think.

2021-08-24 13:12 UTC, deepthidevaki requested changes
Thanks @npepinpe . Just have some minor comments.

The distribution builder looks good. But I think the `FixedPartitionDistributor` is unnecessary. It is just a wrapper around the map. You can remove it, but keep other abstractions.

2021-08-24 13:12 UTC, deepthidevaki commented on dist/src/main/config/broker.standalone.yaml.template
> +        # can have unintended consequences. Finally, the highest configured priority will become the
Also, I think we don't allow it to have same priority anymore. It fails the validation.

2021-08-24 13:12 UTC, deepthidevaki commented on broker/src/main/java/io/camunda/zeebe/broker/partitioning/RaftPartitionGroupFactory.java
> +        distributionBuilder.assignMember(
The builder is nice :+1:

2021-08-24 13:16 UTC, npepinpe commented on broker/src/main/java/io/camunda/zeebe/broker/partitioning/distribution/FixedPartitionDistribution.java
> +final class FixedPartitionDistribution {
In the initial approach, the map has a type: `Map<PartitionId, Map<MemberId, Integer>>`. Is this what you mean? Or do you refer to the wrapped map, `Map<PartitionId, Set<FixedDistributionMember>>`?

2021-08-24 13:21 UTC, npepinpe commented
I applied your review hints, let me know what you think :+1:

2021-08-24 14:31 UTC, deepthidevaki approved these changes
:+1:

2021-08-24 14:35 UTC, npepinpe commented
bors merge

2021-08-24 15:06 UTC, npepinpe commented
bors retry

2021-08-24 15:28 UTC, merged