Add feature flag for new bootstrap/transition behavior
camunda/camunda pull request #7739
Opened 2021-08-31 15:23 UTC by pihme

## Description

- Adds a feature flag to switch between existing and new logic to bootstrap and transition partition
- Adds alternative implementation for partition transition
- Adds additional steps for partition bootstrap and shutdown
- extends `PartitionTransitionStep` interface as discussed

Review hints:
I am going to write tests for the new transition behavior class. But this will be a separate PR.

The one thing that maybe is unfamiliar is `ConcurrencyControl`. This was added recently for cases in which you need an `ActorControl` to schedule stuff but you don't want to pass that actor control object around. It also comes in handy when you want to test actor-style code without spinning up an actor scheduler. 

## Related issues

closes #7733

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-09-01 13:28 UTC, deepthidevaki requested changes
I think there is some confusion on the semantics of `prepareForTransition`.  I had a different idea on how it will be used. Let me know if you would like to discuss it.

2021-09-01 13:28 UTC, deepthidevaki commented on broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionFactory.java
> +  public static final boolean FEATURE_TOGGLE_USE_NEW_CODE = false;
Let's add a short comment here so that others reading the code doesn't get confused.

2021-09-01 16:12 UTC, pihme commented on broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java
> +    steps.forEach(step -> step.prepareForTransition(role));
Yes, let's discuss this in more detail. I did have a different idea.

2021-09-01 16:15 UTC, pihme commented on broker/pom.xml
> +    <dependency>
`TestConcurrencyControl` is defined in the test sources of utils project.

2021-09-02 13:03 UTC, pihme commented
@deepthidevaki Please also have a look at the log output (e.g. from the unit test). I hope it makes sense. Especially the bit about clean up of the old transition for the new transition was a bit confusing, in my mind. Would be interesting how you see it and whether you have any idea which information you want to see.

2021-09-06 06:43 UTC, deepthidevaki approved these changes
Thanks @pihme.

2021-09-06 06:43 UTC, deepthidevaki commented on broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java
> +    steps.forEach(step -> step.onNewRaftRole(role));
I'm not sure if this should be called after `currentTransition.cancel()`. We can leave it here and revisit it when we have some concrete examples of how this method will be implemented.

2021-09-06 06:43 UTC, deepthidevaki commented on broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java
> +      new StartupProcess<PartitionStartupContext>(LOG, List.of());
FYI. In a parallel PR, I have introduced new startup steps. It might introduce merge conflicts.

2021-09-06 07:37 UTC, pihme commented
bors r+

2021-09-06 08:03 UTC, pihme commented
bors retry

2021-09-06 08:23 UTC, merged