Fix intermittent role transitions
camunda/camunda pull request #7887
Opened 2021-09-21 16:37 UTC by pihme

## Description

This PR keeps track of the latest term for which a transition was requested. If the current transition is below the latest term, it is effectively never started.

## Related issues

closes #7873

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-09-21 16:38 UTC, pihme commented
Sorry for the review spamming, but I would appreciate a couple more eyes on this. Especially with respect to what the expected behavior is and whether there are other edge cases that need to be considered.

2021-09-21 16:39 UTC, pihme commented
FYI: the log output in the scenario described will look like this:

```
18:13:46.818 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 1 requested.
18:13:46.834 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 1 starting
18:13:46.835 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 1 - executing WaitingTransitionStep
18:13:46.837 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to CANDIDATE on term 2 requested.
18:13:46.837 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 3 requested.
18:13:46.838 [] [main] INFO  io.camunda.zeebe.broker.system - Skipping transition to CANDIDATE on term 2 because it is superseded by term 3.
18:13:46.843 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 3 requested while another transition is still running
18:13:46.843 [] [main] INFO  io.camunda.zeebe.broker.system - Received cancel signal for transition to FOLLOWER on term 1
18:13:46.844 [] [Thread-0] INFO  io.camunda.zeebe.broker.system - Transition to FOLLOWER on term 1 completed
18:13:46.846 [] [main] INFO  io.camunda.zeebe.broker.system - Cleanup of transition to FOLLOWER on term 1 starting (in preparation for new transition to LEADER)
18:13:46.846 [] [main] INFO  io.camunda.zeebe.broker.system - Cleanup of transition to FOLLOWER on term 1 - executing WaitingTransitionStep
18:13:46.847 [] [main] INFO  io.camunda.zeebe.broker.system - Cleanup of transition to FOLLOWER on term 1 completed
18:13:46.847 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 3 starting
18:13:46.847 [] [main] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 3 - executing WaitingTransitionStep
18:13:46.848 [] [Thread-1] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 3 completed
```

2021-09-21 16:54 UTC, pihme commented
What would you think about this log?
```
18:13:46.818 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 1->FOLLOWER requested.
18:13:46.834 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 1->FOLLOWER starting
18:13:46.835 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 1->FOLLOWER - executing WaitingTransitionStep
18:13:46.837 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 2->CANDIDATE requested.
18:13:46.837 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 3->LEADER requested.
18:13:46.838 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 2->CANDIDATE skipped because it is superseded by 3->LEADER
18:13:46.843 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 3->LEADER requested while another transition 1->FOLLOWER is still running
18:13:46.843 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 1->FOLLOWER Received cancel signal
18:13:46.844 [] [Thread-0] INFO  io.camunda.zeebe.broker.system - Transition 1->FOLLOWER completed
18:13:46.846 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 1->FOLLOWER Cleanup starting (in preparation for new transition 3->LEADER)
18:13:46.846 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 1->FOLLOWER Cleanup - executing WaitingTransitionStep
18:13:46.847 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 1->FOLLOWER Cleanup completed
18:13:46.847 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 3->LEADER starting
18:13:46.847 [] [main] INFO  io.camunda.zeebe.broker.system - Transition 3->LEADER - executing WaitingTransitionStep
18:13:46.848 [] [Thread-1] INFO  io.camunda.zeebe.broker.system - Transition 3->LEADER completed
```

Better? Worse?

2021-09-22 06:38 UTC, deepthidevaki requested changes
Thanks @pihme for looking at this issue so fast. 

I only skimmed through it. Ordering transitions based on term would not work. Term is guaranteed to increase only when transitioning from Follower to CANDIDATE.  From Leader to follower, the term can remain unchanged depending on why the leader has to step down. We also have Follower -> Inactive -> Follower transitions in which the term is not changed.

2021-09-22 06:54 UTC, pihme commented
Closed because of Deepthis objection; another solution needs to be found

2021-09-22 06:54 UTC, closed without merging

2021-09-22 06:57 UTC, Zelldon commented
Just as a comment. The previous solution was safe because it directly replaces the future before enqueue more work, this allows to enqueue always on the next future etc. We could do it similar as before see here https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionImpl.java#L84

2021-09-22 07:10 UTC, deepthidevaki commented
> Just as a comment. The previous solution was safe because it directly replaces the future before enqueue more work, this allows to enqueue always on the next future etc. We could do it similar as before see here https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionImpl.java#L84

This would work. But it does not allow us to skip enqueued transitions when there is already a new transition. If we cannot find a a safe solution that works with skip, we can do it this way.

2021-09-22 07:14 UTC, Zelldon commented
I would prefer this and then we have time to find a good approach in regards to skipping transitions, if this is really necessary.

2021-09-22 08:26 UTC, pihme commented
I thought the goal was to make the transitions as fast as possible? If this is the case, then the fastest transition is one which skips unnecessary work. I really don't understand what we are trying to achieve here.

2021-09-22 08:45 UTC, deepthidevaki commented
> I thought the goal was to make the transitions as fast as possible? If this is the case, then the fastest transition is one which skips unnecessary work. I really don't understand what we are trying to achieve here.

IMO we should definitely skip enqueued transitions. But for a quick fix before the release it might be faster to fix it without the skip, and we should add skipping back.

2021-09-22 08:49 UTC, pihme commented
For the release I would propose to switch the feature flag back to the old code. I would not feel comfortable with any quick fix at this point. I don't think the new transition logic has approval by you guys (Deepthi, Chris, Nicolas), so I would rather not deliver it to customers.

2021-09-22 08:52 UTC, Zelldon commented
This would also mean that we have not the benefit of the building state on followers feature. I think we can fix it now and later bugs via patch releases. If we now disable the transition this would mean that this feature will be avail in 3 months with 1.3, which I personally dislike.

2021-09-22 09:03 UTC, pihme commented
Aren't we also building state on followers with the old transition mechanism?

2021-09-22 11:45 UTC, Zelldon commented
Yes but we will not benefit of the fast transition from Follower to Leader, which was the goal of that topic, since we then still copy the snapshot to runtime, start from the last snapshot etc. @deepthidevaki mentioned that she implemented this logic only for the new transition behavior.