7531 delete corrupted snapshots
camunda/camunda pull request #7931
Opened 2021-10-05 10:18 UTC by oleschoenburg

## Description

Previously we only deleted corrupt snapshots in the case of a missing checksum file. Now, if there is a valid snapshot, we delete everything else in the snapshot directory.
This ensures that we don't accumulate corrupted snapshots. It also replaces the logic that deleted older, valid snapshots.

## Related issues

closes #7531

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-10-05 13:14 UTC, deepthidevaki requested changes
:rocket: awesome!

I have only some minor comments. Please see below.
In addition, it would be good to add one more test to verify the corrupted snapshots are not deleted if there is no other valid snapshot. What do you think?

2021-10-05 13:14 UTC, deepthidevaki commented on snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java
> +      LOGGER.debug("Deleting snapshots other than {}", latestPersistedSnapshot);
```suggestion
      LOGGER.debug("Deleting snapshots other than {}", latestPersistedSnapshot.getId());
```

2021-10-05 13:14 UTC, deepthidevaki commented on snapshot/src/test/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStoreTest.java
> +    assertThat(snapshotStore.getLatestSnapshot()).hasValue(newerSnapshot);
For completeness, I would also suggest to verify that the valid snapshot is not deleted.
```
    assertThat(newerSnapshot.getDirectory()).exists();
    assertThat(newerSnapshot.getChecksumFile()).exists();
```

2021-10-06 07:50 UTC, oleschoenburg commented
@deepthidevaki Thanks for the review! I agree with you and added an additional test case that confirms that a corrupt snapshot is not deleted if there is no valid snapshot available.

2021-10-06 07:56 UTC, deepthidevaki approved these changes
Great! :tada:

2021-10-06 08:34 UTC, merged