refactor(broker): re-enable new transition logic
camunda/camunda pull request #8121
Opened 2021-11-02 09:18 UTC by pihme

## Description
Re-enables new transition logic in `stable/1.2`

Please cast your vote of confidence.

@npepinpe I included you not so much for a review, but more to intervene in case you have other ideas, like switching the feature flag on the testbench first, canary rollout to trial users or things like that.

## Related issues

closes #8044

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-11-02 13:00 UTC, Zelldon approved these changes

2021-11-02 13:35 UTC, deepthidevaki approved these changes

2021-11-02 16:52 UTC, npepinpe requested changes
Normally this would only be released next month, however I can easily imagine it slipping through if we had to build a spontaneous patch release.

I don't see the big rush in releasing this for 1.2 at the moment. If the team feels very confident, I believe you and we can do that. But right now, I think it's safer to deal with potentially forgetting to enable it in the next patch release (with the safe guard that we can enable it via environment variables later in the cloud), then releasing it when we need to release something else next week and finding more transition issues.

I would propose instead:

- keep it off by default
- do a out-of-cadence patch release
- enable it in dev and int via environment variables
- if all is well, we set it as true by default for the next patch release on Dec 1

Note: we can still enable it by default in prod before that if we see a need via env vars. Also, if you think that we don't need a month but one week of load testing should uncover most issues, then we can still do another patch release in between to set it by default. If you (and I mean the group here) think that we already did enough testing (but I think we have a patch since only a few days, and it took a while last time for the issues to appear?), then please mention it here.

I also have a question, do we have some ideas on how to test now (can be manual) the stability of the new transition logic to avoid "testing-in-prod-itis" :smile: ?

2021-11-03 13:32 UTC, pihme commented
> I also have a question, do we have some ideas on how to test now (can be manual) the stability of the new transition logic to avoid "testing-in-prod-itis" smile ?

We do have a property based test for the new partition logic and ran it exhaustively with chains of up to 5 consecutive transitions.

2021-12-16 17:02 UTC, npepinpe commented
I would propose keeping it off for 1.2.x for now, and as it's the default in 1.3, users will have access to a version with it, and we can recommend them to turn it on for 1.2 if they need it. Feel free to challenge this of course.

2021-12-16 17:02 UTC, closed without merging