Add temporary variable migration
camunda/camunda pull request #8254
Opened 2021-11-23 09:19 UTC by remcowesterhoud

## Description

With the removal of temporary variables in #6982  we need a migration in order to map existing temporary variables to event triggers. 
Without this migration it would be possible for a broker to have temporary variables in the store, get updated to the latest version and lose access to the variables.

## Related issues

closes #8114 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-11-24 10:28 UTC, saig0 requested changes
@remcowesterhoud thank you :cookie: It looks good :+1: But we should increase the test coverage.

Please have a look at my comments.

2021-11-24 10:28 UTC, saig0 commented on engine/src/main/java/io/camunda/zeebe/engine/state/migration/DbMigrationState.java
> +          final long eventScopeKey = -1L;
:x: We should rename the variable to `eventKey` because it is used as the argument for the event key.

2021-11-24 10:28 UTC, saig0 commented on engine/src/test/java/io/camunda/zeebe/engine/state/migration/to_1_3/TemporaryVariableMigrationTest.java
> +public class TemporaryVariableMigrationTest {
:x: Additionally, we should verify that we migrate the data correctly. Currently, we verify only that the temp variables are removed after the migration.

Have a look at the examples here: [io.camunda.zeebe.engine.state.migration.to_1_1.DbMigrationStateTest](https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/test/java/io/camunda/zeebe/engine/state/migration/to_1_1/DbMigrationStateTest.java).

2021-11-25 15:54 UTC, remcowesterhoud commented
Thanks for your review @saig0! I've processes your feedback

2021-11-26 14:00 UTC, saig0 approved these changes
@remcowesterhoud thanks :cookie: Looks good :+1: 

After scanning the code from version `1.2`, I think we don't handle one case in the migration: 
* an event subprocess is triggered by a message 
* the event subprocess is `activated` 
* the start event is not `activating` yet
* at this point, there should be temp variables on the scope of the event subprocess
* as a result, the migration will create an event trigger for the event subprocess
* but the event trigger of the event subprocess is not used because it assumes that the event trigger is created for the start event

Please double-check this case. If it is an issue then we should solve it but it can be in a follow-up PR :rocket:

2021-11-29 13:57 UTC, remcowesterhoud commented
@saig0 Thanks! About the case you mention here.

_but the event trigger of the event subprocess is not used because it assumes that the event trigger is created for the start event_
I don't think this is correct. I agree that when we run the migration the event trigger is created for the event sub process. However, in this case once the start event gets activated it will move the variables of that event trigger to a new event trigger with the scope of the start event. This happens in the `ProcessInstanceElementActivatingApplier`:
```java
if (currentElementType == BpmnElementType.START_EVENT
        && flowScopeElementType == BpmnElementType.EVENT_SUB_PROCESS) {
      final EventTrigger flowScopeEventTrigger =
          eventScopeInstanceState.peekEventTrigger(flowScopeInstance.getParentKey());
      moveVariablesToNewEventScope(
          flowScopeEventTrigger, flowScopeInstance.getParentKey(), elementInstanceKey);
}
```

Please let me know if you agree!

2021-11-30 14:34 UTC, remcowesterhoud commented
bors merge

2021-11-30 15:05 UTC, remcowesterhoud commented
bors retry

2021-11-30 15:27 UTC, merged

2021-12-06 05:45 UTC, saig0 commented
@remcowesterhoud regarding:

> but the event trigger of the event subprocess is not used because it assumes that the event trigger is created for the start event
I don't think this is correct. I agree that when we run the migration the event trigger is created for the event sub process. However, in this case once the start event gets activated it will move the variables of that event trigger to a new event trigger with the scope of the start event. This happens in the ProcessInstanceElementActivatingApplier:

```
if (currentElementType == BpmnElementType.START_EVENT
        && flowScopeElementType == BpmnElementType.EVENT_SUB_PROCESS) {
      final EventTrigger flowScopeEventTrigger =
          eventScopeInstanceState.peekEventTrigger(flowScopeInstance.getParentKey());
      moveVariablesToNewEventScope(
          flowScopeEventTrigger, flowScopeInstance.getParentKey(), elementInstanceKey);
}
```

No, I don't agree :sweat_smile: Please have a close look where the event trigger is read from: `eventScopeInstanceState.peekEventTrigger(flowScopeInstance.getParentKey())`.

It reads the trigger from the parent of the flow scope. 
* flow scope = event subprocess
* parent of the event subprocess = process instance

So, it doesn't read the event trigger from the event subprocess. Correct?