fix(polling/state): prevent duplicates in repeatable requests list
camunda/camunda pull request #8392
Opened 2021-12-14 17:17 UTC by romansmirnov

## Description

## Related issues

relates #8310
closes #8390

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

2021-12-14 20:14 UTC, romansmirnov commented
I know, I know... using `HashSet` without implementing `hashCode()` and `equals()` in `LongPollingActivateJobsRequest` 😄 But none of the existing given properties (each on its own and all together) helps to identify a request clearly. For example, a replicated worker shares the same configuration which would result in multiple separate requests with the same request property values. So that, the requests could not be distinguished anymore as they would be considered as equal.

Possible Solutions:
1. Continue using `HashSet` but introduce a unique identifier for each incoming request per job type. The ID could be used to implement `equals()` and `hashCode()`.
2. Keep the type `LinkedList` but check if the request is already contained by the list
```
activeRequests.forEach((r) -> {
  if (!activeRequestsToBeRepeated.contains(r)) {
    activeRequestsToBeRepeated.add(r);
  }
});
```
3. Accept the duplicates as they all will be removed when the request times out (but the request might be executed multiple times unnecessarily)
4. ...

2021-12-16 16:16 UTC, romansmirnov commented
Dear Reviewer,

Please consider the following:

* Introduce a `requestId` property in `LongPollingActivateJobsRequest` which allows to clearly identify a request. Additionally, that allows to implement `#hashCode()` and `#equals()` accordingly. Otherwise, the existing properties do not allow to differentiate them properly.
* The `requestId` is not persisted, meaning, after a Gateway restart the `requestId` starts again with `1`.

Also, the PR might be in conflict with the PR #8389 when merging it.

2021-12-17 13:25 UTC, romansmirnov commented on gateway/src/test/java/io/camunda/zeebe/gateway/api/job/LongPollingActivateJobsTest.java
> +    final var allRequestsSubmittedLatch = new CountDownLatch(1);
Dear Reviewer, just FYI: I consciously decided to use the `CountDownLatch` to ensure that all requests are submitted to the actor initially. As an alternative, I considered using the `ControlledActorScheduler` but the test was too flaky with the controlled scheduler. With the latch, the test is reliable.

2021-12-20 11:14 UTC, oleschoenburg requested changes
:x:  I think introducing a request id is not necessary because we can just rely on identity to check for duplicates in `activeRequestsToBeRepeated`. We create new instances of `LongPollingActivateJobsRequest` only once. 

That means `activeRequestsToBeRepeated` could be: 
```
private final Set<LongPollingActivateJobsRequest> activeRequestsToBeRepeated =
      Collections.newSetFromMap(new IdentityHashMap<>());
```
Unless we want to use the request id for more than just checking duplicates I think we should not introduce it here and instead rely on object identity. 

WDYT?

2021-12-20 13:31 UTC, npepinpe commented
Regarding identity, what you say sounds reasonable - as long as we only create requests once and each instance is meant to be unique, it should be OK to simply use the default `equals`. I can't really speak on his intentions and reasoning, but I can imagine two reasons why Roman would've implemented a custom one however (which would require an ID as otherwise there's no way to guarantee we can distinguish requests):

1. What if that constraint changes? It's not a specific constraint of the class that it must be instantiated only once per request, so it's not too crazy to think someone might not respect it.
1. What if later on, someone thinks: "hey, what if we aggregated similar requests that share the same properties/subset to reduce load on the broker? we could implement a custom equals/hashCode and put that in a set so they're automatically deduplicated per job type". This may break the current expectations of uniqueness, and maybe it wouldn't be immediately obvious what happened, or easy to diagnose.

That's just OTOH though - my proposal would be to accept with the ID, and open a follow up to discuss it with Roman when he's back - there's no rush here, and removing the ID or taking a different approach in the long run is easy to do. Let me know what you think :+1:

2021-12-20 15:13 UTC, oleschoenburg approved these changes
I rebased to resolve conflicts with the other gateway/long-polling related PRs.

bors r+

2021-12-20 16:43 UTC, merged