chore(ci): use prod Vault
camunda/camunda pull request #9302
Opened 2022-05-05 14:48 UTC by cmur2

## Description

This PR is needed to ensure that workflows using GHA self-hosted runners still work (the Nexus caching part of it; workaround could also be disabling that temporarily) after configuring `camunda/zeebe` to use self-hosted runners from the `prod` environment (currently `stage` but INFRA-3257 includes steps to promote it).

## Related issues

Related to INFRA-3257

2022-05-05 14:56 UTC, oleschoenburg approved these changes
We also use vault in the deploy workflow: https://github.com/camunda/zeebe/blob/22c1222e4a412587973b46f46e7f8dc14f273e82/.github/workflows/deploy.yml#L21-L31

Here we use `secrets.VAULT_ADDR`. I think we should align them both. Either update both of the to just the plain url or use the secret in both places and update that once it's ready.

Other than that this looks fine to me of course :+1:

2022-05-05 15:12 UTC, lenaschoenburg requested changes
I guess I shouldn't have approved that already. I think it's important to fix the issue above first.

2022-05-05 19:30 UTC, cmur2 commented
> We also use vault in the deploy workflow:
> 
> https://github.com/camunda/zeebe/blob/22c1222e4a412587973b46f46e7f8dc14f273e82/.github/workflows/deploy.yml#L21-L31
> 
> Here we use `secrets.VAULT_ADDR`. I think we should align them both. Either update both of the to just the plain url or use the secret in both places and update that once it's ready.

In my PR here it is crucial to use the plain value and I did this on purpose since afaik accessing `${{ secrets.XYZ }}` will prevent the workflow to run correctly for outside contributors. I assumed this capability is important for your so I built the Nexus CI caching feature accordingly. This feature is only needed on self-hosted runners.

The `deploy.yml` workflow does not use self-hosted runners, uses a different way to authenticate to Vault (via approle instead of K8s SA) and does (must) not need to be run by outside contributors. The action secrets `VAULT_ADDR`, `VAULT_ROLE_ID` and `VAULT_SECRET_ID` are managed by Infra team automation in this (and other) repository to allow successful connection to Vault via approle auth.

@oleschoenburg I think there is no way we could align them and I also think we should not due to the different use cases and requirements.

2022-05-05 19:41 UTC, cmur2 commented
I could add an explanatory comment to the workflow touched in this PR to explain the difference from the usual practice of relying on `secrets.VAULT_ADDR`?

2022-05-06 07:41 UTC, oleschoenburg approved these changes
Thanks @cmur2 for the detailed explanations, these were all things I haven't thought of :+1:

2022-05-09 07:20 UTC, cmur2 commented
bors +r

2022-05-09 07:20 UTC, cmur2 commented
bors r+

2022-05-09 07:46 UTC, merged