Java client accepts topologies with `DEAD` partitions
camunda/camunda pull request #9410
Opened 2022-05-18 16:28 UTC by oleschoenburg

## Description

The Java client now accepts partitions that are `DEAD` instead of throwing an exception. I've also added a test that generates randomized topology responses and ensures that they are accepted by the Java client.

closes #9387

2022-05-18 16:34 UTC, oleschoenburg commented
@saig0 Since you reacted to the original issue, are you interested in reviewing this? :wink:

2022-05-19 06:29 UTC, oleschoenburg commented
Hm, looks like I can't get Junit 5 to work for the java-client module :thinking: 
```
[2022-05-19T06:14:48.670Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M6:test (default-test) on project zeebe-client-java: 
[2022-05-19T06:14:48.670Z] [ERROR] 
[2022-05-19T06:14:48.670Z] [ERROR] Please refer to /home/jenkins/agent/workspace/9387-java-client-dead-partitions/clients/java/target/surefire-reports for the individual test results.
[2022-05-19T06:14:48.670Z] [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[2022-05-19T06:14:48.670Z] [ERROR] There was an error in the forked process
[2022-05-19T06:14:48.670Z] [ERROR] TestEngine with ID 'junit-jupiter' failed to discover tests
[2022-05-19T06:14:48.670Z] [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[2022-05-19T06:14:48.670Z] [ERROR] TestEngine with ID 'junit-jupiter' failed to discover tests
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:699)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1332)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1165)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:929)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
[2022-05-19T06:14:48.670Z] [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
[2022-05-19T06:14:48.671Z] [ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2022-05-19T06:14:48.671Z] [ERROR] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2022-05-19T06:14:48.671Z] [ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2022-05-19T06:14:48.671Z] [ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-05-19T06:14:48.671Z] [ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-05-19T06:14:48.671Z] [ERROR] 	at java.lang.Thread.run(Thread.java:750)
```

2022-05-20 12:01 UTC, saig0 requested changes
@oleschoenburg thank you for providing a fix :+1: 

I have suggestion about the test. Please have a look.

2022-05-20 12:01 UTC, saig0 commented on clients/java/pom.xml
> +    </dependency>
:x: The versions of the dependencies are not compatible.

```
Dependency convergence error for org.jeasy:easy-random-core:jar:4.3.0:test paths to dependency are:
Failed while enforcing releasability. See above detailed error message.
+-io.camunda:zeebe-client-java:jar:8.1.0-SNAPSHOT
  +-org.jeasy:easy-random-core:jar:4.3.0:test
and
+-io.camunda:zeebe-client-java:jar:8.1.0-SNAPSHOT
  +-io.github.murdos:easy-random-protobuf:jar:0.4.0:test
    +-org.jeasy:easy-random-core:jar:5.0.0:test

Warning:  Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
```

2022-05-20 12:06 UTC, oleschoenburg commented on clients/java/src/test/java/io/camunda/zeebe/client/impl/response/TopologyImplTest.java
> +  }
Yeah that makes sense to me :+1: The nice thing about this randomized test would have been that it doesn't just test the handling of the health enum but the entire topology response.

2022-05-23 03:20 UTC, saig0 approved these changes
@oleschoenburg LGTM :+1:

2022-05-23 03:24 UTC, saig0 commented
bors merge

2022-05-23 03:54 UTC, merged

2022-05-23 03:55 UTC, backport-action commented
Must have admin rights to Repository.

2022-05-23 03:55 UTC, backport-action commented
Must have admin rights to Repository.

2022-05-23 04:08 UTC, saig0 commented
@korthout something is wrong with the backport action :sweat_smile: can you have a look?

2022-05-23 07:58 UTC, korthout commented
Thanks for letting me know. It seems to be related to the request review feature. To request reviews, the @backport-action user must have admin rights to this repo, which it doesn't have. I'll open a bug for it. 

As a workaround in zeebe, until a fix is available, we could give the backport-action user admin rights to the repo. For example, by adding it to the [Zeebe team](https://github.com/orgs/camunda/teams/zeebe/members). However, I don't think we should because the account is not controlled by Camunda, and therefore less secured. Luckily it seems to open PRs correctly.

I think the only solution is to disable the feature or make enabling it configurable. However, that will require a new release.

2022-05-23 08:43 UTC, korthout commented
A new version is released https://github.com/zeebe-io/backport-action/releases/tag/v0.0.8

2022-05-23 08:44 UTC, backport-action commented
Git push to origin failed for stable/1.3 with exitcode 1

2022-05-23 08:44 UTC, backport-action commented
Git push to origin failed for stable/8.0 with exitcode 1

2022-05-23 08:47 UTC, korthout commented
Haha wow, it picked up the url as a backport comment. You can ignore these last 2 comments.