Fix QA Testbench GHA
camunda/camunda pull request #9530
Opened 2022-06-09 14:11 UTC by Zelldon

## Description

![workflow](https://user-images.githubusercontent.com/2758593/172867787-3ffa57b7-a6b0-4528-a70f-27df8809b163.png)

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-06-09 19:13 UTC, Zelldon commented
![qa](https://user-images.githubusercontent.com/2758593/172926015-c25a5fc0-da7c-41ed-ac34-4bcac3715c70.png)

:muscle:

2022-06-09 20:51 UTC, Zelldon commented
Tested as well with `stable/8.0` to verify different branch name formats
![success](https://user-images.githubusercontent.com/2758593/172941812-d4dabe81-4dd4-419b-8055-9678e68012d3.png)


Success messages are sent to slack as well. 
![successmsg](https://user-images.githubusercontent.com/2758593/172941876-b6ae197d-a3ed-4446-8746-3da1a89a978c.png)

This is discussable of course. My thought was this would help to avoid checking testbench whether a QA run was executed or not as medic.

2022-06-10 07:05 UTC, oleschoenburg requested changes
Nice, I only have one blocker because I think the slack notification won't work if QA times out. Other than that it looks good! :+1:

2022-06-10 07:05 UTC, oleschoenburg commented on .github/workflows/qa-testbench.yaml
>      name: Send slack notification on build failure
:upside_down_face: The name and description isn't accurate anymore, we always send a slack notification.

2022-06-10 07:08 UTC, Zelldon commented on .github/workflows/qa-testbench.yaml
> +              "text": ":alarm: QA run on `${{ env.BRANCH_NAME }}` with generation template `${{ env.GENERATION_TEMPLATE }}` failed! :alarm:\n ${{ env.BUILD_URL }}",
Because we schedule the github action and then these values are empty, which is why we have to set some defaults above.

2022-06-10 07:09 UTC, Zelldon commented on .github/workflows/qa-testbench.yaml
> +    timeout-minutes: 45
We can try out. I could decrease it to 5 min and run it ? Or we add the cancel to the slack notification. How would it change if we move it to  `Run Testbench QA` ?

2022-06-10 07:09 UTC, oleschoenburg commented on .github/workflows/qa-testbench.yaml
> +              "text": ":alarm: QA run on `${{ env.BRANCH_NAME }}` with generation template `${{ env.GENERATION_TEMPLATE }}` failed! :alarm:\n ${{ env.BUILD_URL }}",
Ah, right! Thanks :+1:

2022-06-10 07:12 UTC, oleschoenburg commented on .github/workflows/qa-testbench.yaml
> +    timeout-minutes: 45
Okay, let's try it :+1: I guess the difference is that other steps could potentially time out too but that's something we don't control in other workflows too.

2022-06-10 07:14 UTC, oleschoenburg commented on .github/workflows/qa-testbench.yaml
> +    timeout-minutes: 45
forget what I said. The entire qa job is cancelled, but the slack notification is a different job so timeout should work :facepalm:

2022-06-10 07:14 UTC, oleschoenburg approved these changes

2022-06-10 07:26 UTC, Zelldon commented on .github/workflows/qa-testbench.yaml
> +    timeout-minutes: 45
That what I thought as well :D

2022-06-10 07:28 UTC, Zelldon commented
bors r+

2022-06-10 07:43 UTC, merged