`TypedStreamWriter` that writes to buffer
camunda/camunda pull request #9840
Opened 2022-07-19 09:24 UTC by pihme

## Description

- Implements `TypedStreamWriter` that writes to buffer
- Implements processing result builder to use the buffered stream writer
- does not add tests. I started it, but it would take too much time. Hope I can revisit it after my holidays. For now there is just a follow up issue: https://github.com/camunda/zeebe/issues/9838

## Related issues

closes #9780 

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-07-19 14:12 UTC, npepinpe requested changes
:+1: 

Looks good, I like the linear structure much more than the builder approach (since we anyway require all fields to be filled out).

- :x: One concern I have is related to the `canWriteAdditionalEvent` method. The functionality here is that there are processors where we want to handle, during processing, if writing an additional event will cause the write to fail downstream (e.g. job batch activation). Before, we were (indirectly) querying the dispatcher directly, but now we're back to using the `maxFragmentSize`. `maxFragmentSize` is unfortunately not the actual limit, since the dispatcher will frame entries as we add them. So if you have one entry, the real max fragment size for this writer would be `maxFragmentSize - frameLength`. But if you have multiple entries, it's `maxFragmentSize - (entryCount * frameLength)`. Actually, it's a little less than that, as we then align the size of the batches as well, which may cause them to require more memory than expected. So the real `maxFragmentSize` is more of a function of the number of entries and the total length of the batch. Anyway, all this to say, I think this currently breaks pre-existing functionality. We're now reverting to the implementation that it was before we fixed #5525 (relevant PR is #8799). Possibly we would be re-opening #5525 here. One problem is we never managed to write a good integration/regression test for #5525, so I don't know if we'd catch it now.

2022-07-19 14:12 UTC, npepinpe commented on engine/src/main/java/io/camunda/zeebe/streamprocessor/BufferedProcessingResultBuilder.java
> +      throw new RuntimeException("Missing value type mapping for record: " + value.getClass());
```suggestion
      throw new IllegalArgumentException("Missing value type mapping for record: " + value.getClass());
```

2022-07-19 14:28 UTC, pihme commented
> * Anyway, all this to say, I think this currently breaks pre-existing functionality

I fear the same. I don't really see how we can avoid this, tbh. Do you have any idea how to solve this problem? (e.g. secure upper bounds; more precise calculations; try to write it regardless of capacity, then handle the error if and when it arises)

Without an approach, I am afraid this is a blocker for this development strain for now.

2022-07-19 14:33 UTC, npepinpe commented
Well, in a perfect world, we wouldn't have any limitation associated with the dispatcher/follow up records. That's a much bigger scope, however. Maybe if instead of passing a static length we passed a function to compute it? It's definitely hacky without some major refactoring, but the current solution is already somewhat hacky.

2022-07-20 08:50 UTC, pihme commented on engine/src/main/java/io/camunda/zeebe/streamprocessor/BufferedProcessingResultBuilder.java
> +    if (!(value instanceof BufferWriter)) {
No idea. Kept it as it was. Will add a todo, though

2022-07-20 09:27 UTC, npepinpe requested changes

2022-07-20 09:27 UTC, npepinpe commented on engine/src/main/java/io/camunda/zeebe/streamprocessor/BufferedStreamWriter.java
> +    return length < capacityCalculator.apply(recordBufferOffset);
:x: I expect the current function to map down to `Dispatcher#canClaimFragmentBatch(int recordCount, int batchLength)` at the end, so it should be a `BiFunction<Integer, Integer, Integer>`, I think.

2022-07-20 09:36 UTC, npepinpe approved these changes

2022-07-20 09:36 UTC, npepinpe commented on engine/src/main/java/io/camunda/zeebe/streamprocessor/BufferedStreamWriter.java
> +  BufferedStreamWriter(final BinaryOperator<Integer> capacityCalculator) {
:+1: TIL about the `BinaryOperator` (though I shouldn't be surprised after the `UnaryOperator` :smile:)

2022-07-20 10:41 UTC, pihme commented
bors merge

2022-07-20 10:45 UTC, pihme commented
bors merge

2022-07-20 10:46 UTC, oleschoenburg commented
@pihme test failures are legitimate, check out https://github.com/camunda/zeebe/runs/7427420911?check_suite_focus=true

2022-07-20 10:56 UTC, pihme commented
> @pihme test failures are legitimate, check out https://github.com/camunda/zeebe/runs/7427420911?check_suite_focus=true

Thanks. I feel the heat is getting me

2022-07-20 11:08 UTC, oleschoenburg commented
e8fb77b7792d5fd96501df765440b60fce119f65 (latest commit on this branch here) builds for me but when I rebase this branch on main it fails:
```
io.camunda.zeebe.streamprocessor.BufferedProcessingResultBuilder is not abstract and does not override abstract method resetPostCommitTasks() in io.camunda.zeebe.engine.api.ProcessingResultBuilder
```

2022-07-20 11:14 UTC, pihme commented
bors merge

2022-07-20 11:27 UTC, merged