Create engine outside
camunda/camunda pull request #9989
Opened 2022-08-04 10:44 UTC by Zelldon

## Description

Create the engine outside of the StreamProcessor, which should allow to also inject other RecordProcessors.
Furthermore we can fill the Engine with the needed TypedRecordProcessorFactory, which means we no longer need that in our builders and contexts.

I hope this helps you in make further progress @deepthidevaki 

## Related issues

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

2022-08-04 15:08 UTC, deepthidevaki requested changes
:rocket: Exactly what I wanted :smile:  Just some minor comment.

2022-08-04 15:12 UTC, Zelldon commented on engine/src/main/java/io/camunda/zeebe/engine/RecordProcessorContext.java
> +public final class RecordProcessorContext {
I don't see that as blocker since we are not done yet but sure can do tomorrow.

2022-08-05 11:56 UTC, Zelldon commented
@deepthidevaki I moved the implementation and introduced a new interface. Could you review again? Maybe you trust me next time :grin: so I can just go ahead and merge after the changes :)

2022-08-05 12:17 UTC, deepthidevaki commented
> @deepthidevaki I moved the implementation and introduced a new interface. Could you review again? Maybe you trust me next time grin so I can just go ahead and merge after the changes :)

:confused: I didn't know that we now approve and request changes at the same time.

2022-08-05 12:18 UTC, deepthidevaki approved these changes
Thanks.

2022-08-05 12:24 UTC, Zelldon commented
Since this was only something minor I thought so :) https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md#reviewing-a-pull-request

2022-08-05 13:21 UTC, Zelldon commented
bors r+

2022-08-05 14:34 UTC, merged